### ISSUE TITLE
Trainees complete Slack profile data

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#1]

**Comment by ClaireBickley** [comment]
@SallyMcGrath can you give a bit more info/context on this ticket, please?
Are we just trying to get trainees to fill in more info on their Slack profiles?

**Comment by SallyMcGrath** [comment]
@ClaireBickley I've got no idea. It was on the board as a draft and I merely converted it to a ticket when I created your repo.

**Comment by ClaireBickley** [comment]
aha OK its been assigned to me and I've no idea what it is 🙃 I'll investigate

**Comment by ClaireBickley** [comment]
@gbencci can you give more context on this please? Is the goal just to get trainees to fill in their profile?

**Comment by gbencci** [comment]
Hi Claire, yes, that's right. We need to ensure the regions get their trainees to fill their profile data, as it's becoming really hard to identify who's who. Ideally the volunteers would also do it, but trainees are the top priority

**Comment by gbencci** [comment]
@ClaireBickley this ticket has been opened for a while. Can we close this this ticket and reopen it when we are able to work on it? Now that we'll deactivate lots of people, the next phase would be to get the whole community to complete their profile data. This would need to involve all communities, probably partially in-class. It doesn't matter when, as long as it's on your list.
