### ISSUE TITLE
Data Talent 2023 - 14/03/2023

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/CYF-Staff-Tickets#100]
Data Talent at the Hilton Hotel in Glasgow

Primarily a recruitment event focused on MSc students who are graduating or have recently graduated from relevant courses in AI and data at Scottish Universities.

Meeting with the Data Lab to discuss what interests CYF most and how we can get involved in one or more events or a potential partnership and what this involves etc.

**Comment by MarianaVazquezCYF** [comment]
Thanks Caro! how can I support you on this? @caromelendezl
