### ISSUE TITLE
Oversight of New London Volunteers

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1008]
### Background

New London volunteers and trainees who have been absent have been tasked with organising the portfolio module. 

There are some risks here. New volunteers have no experience of flipped classroom or what has already been done; they have yet to learn where existing resources are or what has been done already. Trainees organising the class are not following the portfolio module day plan (not a risk if we are happy to abandon it?).

There is a risk of us falling into bad habits here. 
- We do not want lectures 
- We do not want people spending hours making resources that already exist
- We do not want sources of conflicting advice 
- We do not want everything organised over DMs again

### Acceptance criteria

- [x] Meet with new volunteers and do some training on flipped classroom/ how we work - Halden/ Mitch?
- [x] Introduce volunteers to the workshops folder, PD syllabus etc
- [x] Put new volunteers in contact with volunteers who run good flipped workshops before what a good CYF workshop looks like

### Owner

@halden

### Stakeholder

@SallyMcGrath  @mitch

### Approver

@halden

**Comment by Dedekind561** [comment]
@haldenb Hey there, could you clarify what you mean by "running classes". As far as I'm aware, I thought classes weren't running in London - it's just Portfolio? Unless I've missed something.

**Comment by haldenb** [comment]
Yeah it is portfolio module, I have edited this a little for clarity

**Comment by haldenb** [comment]
More info here https://codeyourfuture.slack.com/archives/G6H0HAY10/p1714648268610719
