### ISSUE TITLE
GL6 Networking event

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1012]
**Background**
Glasgow 6 our 6th cohort in Glasgow who graduated in November 2023. Currently, we have 16 unemployed graduates but from those 17, 6 are working on portfolios, 6 are course completer and they active, 1 is inactive, 2 are persuading further education and 2 are asylum seekers and (meaning that they can't work until they have their refugee status) and 2 are doing further education.

**Goal of the event**
Create a networking event with at least one hiring company and at least 12 glasgow 6 graduates.

**Format of the event**
-We could have a speed networking, for this event you could ask 3 volunteers from the company or 3 different companies etc. Check one example of this event on this [link](https://docs.google.com/document/d/1e1LIJC83bKEUjucuXb2lEpC4w8vJdhX6BgxK2GDy-ew/edit?usp=sharing)
-We could have an insight session with a company
-We could have an inspiring talk by a company
-We could have a round table discussion with our grads and at least one member of a companies etc
-You are free to explore more options of networking events!

**Dates:**
-It should happen the week of the 1st of June Propossal- Friday 31 May- Consider the date according to the venue. This event has to happen on a work day in order to enable the participation of guest companies

**Considerations:**
The costs of trains for grads in the region are covered.
The cost of volunteers is not covered

**Venue**

- [Frank Duffy](https://www.linkedin.com/in/frank-duffy-4b287122/?originalSubdomain=uk), the founder and director of [Code Division.](https://codedivision.co.uk/) has told us that we could do an event together and he could have a space to host an event (this could be an idea) if you choose this option, please let us know to make an into email to frank. 

- Another option could be at Barclays Labs (we have done events there before) however, please coordinate with a staff member to secure a date.

**Budget:**
Your budget for this event is XXXXXX (TO BE CONFIRMED)

Raise any questions you have or unclear information, as well as any steps taken on this ticket, so we have a history of what was done

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , you need to create your tickets for this using the CYF-Events repo, not our staff one :)
