### ISSUE TITLE
Answer Dept 

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1035]
### Background

[Dept](https://www.deptagency.com/en-gb/)

They went to our presentation at DEVWorld :sparkles:and they want to help. They’re asking the top things we need at the moment. This is what we shared:
In this respect, I want to share some options that currently have the most impact at CYF:

a) Diverse hiring --> hiring CYF grads. If that's not the case, connect/introduce us to clients who can be potential hiring partners.
b) Help us bring more senior tech leaders to our community --> professionals in those positions can be a source of inspiration, encouragement and advice. 
c) Volunteering focused on tech solutions --> volunteers to work on one sprint on a CYF Product
d) Fundraising --> helping CYF Community to raise funds that help us to pay for expenses such as childcare, meals and transport to our trainees. 

This is what they're asking. 

Especially around option C we have some questions. For example:

- Which tech stack is being used for CYF products?
- Is a sprint two weeks? And 40 hours per week?
- Can this work be done remotely?
- What kind of work can we expect?
- What kind of people will we be collaborating with?

For option B we’re mostly interested in what will be expected from the senior tech leaders and what the time investment is.

### Acceptance criteria

- [ ] @kfklein15 to share info on option C
- [ ] @alecmccrindle to share info on option B
- [ ] @lilianabermudes to share the details with them

### Owner

@liliana

### Stakeholder

@kfk @alec

### Approver

@liliana

**Comment by alecmccrindle** [comment]
Hi @lilianabermudes - the simple answer on Tech Leaders it is best they [join a networking event](https://docs.google.com/spreadsheets/d/12ePQr1-ndMuKRfrk0zfnmEaaqhycmaBS6YoJlx6vArI/edit#gid=190210108) as 
 speaker or come hang out and speak at a portfolio Saturday, probably in London for the time being.

**Comment by lilianabermudes** [comment]
Thank you, Alec! 

Karen, I'll cc you about the Product part, so you reply directly to them when you can :)
