### ISSUE TITLE
Referals tab in the global trainee

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#104]

**Comment by MarianaVazquezCYF** [comment]
Hey @gbencci , @alecmccrindle and I, would like to have a tab in the global trainees where we can see where our trainees are coming from! 
DWP has asked us to share some successful stories and the only way we can see this is to ask to the proms or look manually! , in addition, this will help us to know whats the tendency among our graduates who get a job in tech and where they are coming from :)
 Can you please help us to add a tab? and I can add the Data of London 8 , and ask Halden and Dara to add the data for London 9, 10 glasgow 6, and add this question in the PCF for WM5 and NW6 ccing @lilianabermudes

**Comment by gbencci** [comment]
hi @MarianaVazquezCYF it's done. It's in column J
