### ISSUE TITLE
Draft Glasgow Statement

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#1043]
Add information to [this document](https://docs.google.com/document/d/1AAWqSwRoAjddH3Z0mL6WB-ZXA74v-eol-A6chH0nqXU/edit)

- [x] Find information from Slack about events
- [x] Find information from tracker about SD numbers 
- [x] Find information from tracker about Launch Project numbers 
- [x] Finalise draft and add to doc

**Comment by MattCFry** [comment]
Hey Dara :) what's this ticket about?
