### ISSUE TITLE
DLP Trainee Testimonials - Review

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#1054]
### Background

[Context Thread](https://codeyourfuture.slack.com/archives/C029341FPH6/p1714052215958699)

DLP has attempted to provide trainee stories/testimonials previously. It was not a huge success, so it is worth reviewing, retroing and drafting something to attempt with Sheffield DLP.

The goal is not to destroy and replace. This is an iteration attempt.

### Acceptance criteria

- [x] Review the DLP "[Questions & email](https://docs.google.com/document/d/1i81XEPtecwdvZwb3rQx1wA6Ydgng5XRXHtlCcFGrJ0Q/edit)" doc
- [x] Gather thoughts 
- [x] Construct feedback and thoughts for a new iteration.

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@mattcfry

**Comment by MattCFry** [comment]
My thoughts on the current version:

I understand the desire for a well-rounded question pool to build this grand narrative for the DLP. In my opinion, the DLP is a more shorter course, we need to be more susinct with our questioning. I fear you may struggle to get sufficient answers for some of the questions as people only have three weeks of experience with the DLP. You could unintentionally scare off people from submitting answers.

Some of the questions were heavily detail-oriented and needed to address the core desired outcomes of the DLP. These outcomes are increased confidence with day-to-day digital skills and the ability to participate in the digital age. We need to focus on these parts and blow up our impact reporting.

**Comment by MattCFry** [comment]
I've made an initial draft of the changes I will make. It won't be my final iteration. I will do some research and reflection, then come back to this. 

Maybe we could also consider some lower stress options of surveying? At this point in the course, people may be more comfortable with Google Forms.

**Comment by MattCFry** [comment]
@AmyCYF I will close this ticket; however, could you please give your initial thoughts on the questions I've left and my feedback? Thanks!

**Comment by AmyCYF** [comment]
Happy to change the format to an online form - think that is a great idea. 

The questions were designed to be done in an interview style, agree that if these were in a form they would be intimidating. 

I read through your draft and it looks like a good starting point. I think would be a great thing to put together for the Sheffield cohort and trial it with those participants? Does that seem like a reasonable deadline? Would be good to then share this journey and results in the Team demos meeting.

**Comment by MattCFry** [comment]
I like the interview format. I think we should still give them the option and see how that goes. 

I'm up for sharing in the demo. I think I will choose next time instead of today to get a bit deeper into my journey :)

Thanks for input
