### ISSUE TITLE
Review onboarding document

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1059]
### Background

It's been a year since we implemented the onboarding process + quiz.

We need to review and see if we need to add new information: what new volunteers should know?

### Acceptance criteria

- [x]  Halden to review it and leave comments: https://docs.google.com/presentation/d/1B-fgMuZ3wSHFdCnzXrtF0qxvQc07QkcL3OJr0RGC4og/edit#slide=id.g189a0cf129a_1_0
- [x] Alec to review Halden's review :)

### Owner

Halden

### Stakeholder

Alec

### Approver

Alec

**Comment by alecmccrindle** [comment]
I've done my review. Made changes and left a few comments for you @lilianabermudes. Thanks.

**Comment by lilianabermudes** [comment]
Some comments:

- Alec, can add some words to the video for the culture slide 3? It would be great to highlight some of the sentences. They're so good!
- It's fine to leave the Slack bit - some people will do it. However, they have to get that instruction later again
- Let's use this same doc for alumni willing to volunteer, so I removed the "volunteers only". Well, essentially, it's correct, as this is for everyone who is looking to volunteer only (now including alumni) :D
