### ISSUE TITLE
Coco trainings

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#106]

**Comment by MarianaVazquezCYF** [comment]
- [ ] Alec to work in a document about how to take a picture
- [ ] Alec to work in a document about how to write a story / post
- [ ] Alec to work in a document where we can have design templates 
- [ ] Mariana to work in a document about how we create events
- [ ] Mariana to work in a document about how we recognise volunteers and send them to our trainees
- [ ] Mariana to work in a document about how we create community building activities

**Comment by SallyMcGrath** [comment]
@alecmccrindle this ticket is not assigned to a planner. Is it Done? Please close it if it's done. Leaving hundreds of tickets open makes a huge mess for everyone else to wade through.
