### ISSUE TITLE
Refugee Festivals in all the regions and create content

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1068]
- [ ] Finding volunteers who would like to lead on this, extra will be if its a refugee or asylum seeker 
- [ ] Make that the next monthly meetings, could have this topic covered:
- Glasgow - Mariana
- WM - Do this on the networking demo day June 7th 
- London - Alec help 
- NW - Help !!! 

- [ ] Create content refugee week

**Comment by kfklein15** [comment]
We will probably only do Glasgow -  job fair.
Think about a weekly communication or twice a week during the refugee week with examples/stories - new story @MarianaVazquezCYF

**Comment by alecmccrindle** [comment]
Glasgow event is due and so are refugee posts. Closing ticket.
