### ISSUE TITLE
Demo days

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#107]

**Comment by MarianaVazquezCYF** [comment]
**What do WM and Manchester need from outreach and community?** 

- @AliciaE08 do you already have a guest list of companies and a place? how can and the cocos help you? ((we will bring the team to take pictures and video)) 

- @martaesn/ @ElizabethlawalCYF do you already have a guest list of companies and a place? how can we help you? (we will bring the team to take pictures and video)

-  In terms of community I would like to try to rent a van from Scotland to Manchester and invite Scotland to attend and the same with WM and London! (Obviously, I will need to see the budget) and @ClaireBickley  in terms of insurance and safety, is it possible to do this? ccing @gbencci for ideas!

**Comment by ClaireBickley** [comment]
Hi Mariana, can you get an idea of numbers please? That will help determine the vehicle size we need. For example, are you thinking 7 people or 25? Maybe hiring a coach could work - it would come with a driver and be fully insured.

**Comment by gbencci** [comment]
From my experience I would start with:
- Define the size you want (you can have two options)
- Making a request for coaches on the specific date and get quotes for it
- Make sure you are not the only one organising, but that volunteers are part of the planning and logistics. The community should get excited about doing it

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , can I please be invited to Birmingham and Manchester one? Thank you! :)

**Comment by alecmccrindle** [comment]
- [ ] @alecmccrindle to find a photographer

**Comment by gbencci** [comment]
Can we close this ticket?

**Comment by gbencci** [comment]
@MarianaVazquezCYF can we close this ticket?
