### ISSUE TITLE
Niyo Fest 3 -5 october - fill our speaker information

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1070]
what:  SPEAKER at Niyo Fest, a global tech event in Birmingham with an expected attendance of 10k+ aimed at providing an immersive experience to all attendees.
where: Birmingham
when: 3- 5 October 
who: Find speaker and fill out this form : https://airtable.com/apprI3ScFigkYoizW/shrpV9eskR1j0yZhM

**Comment by kfklein15** [comment]
This changed to a panel and has to be a staff member (senior). Mariana what the panel is about.

**Comment by kfklein15** [comment]
Mariana needs to follow-up, since there has been no reply.
