### ISSUE TITLE
actions for Lead Dev London June 11 and 12

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1074]
- [x] Post linkedin 
- [x] Post newsletter
- [x] Assign tickets 
- [x] Logistics banner 
Your 10% discount code to share with your network: CODE-YOUR-FUTURE
x5 LeadDev London complimentary tickets can be claimed [here](https://ti.to/whiteoctober/leaddev-london-2024/with/sdu-bbpktva).
x5 LeadingEng London complimentary tickets can be claimed [here](https://ti.to/whiteoctober/leadingeng-london-2024/with/bwt6iegr2ok). Please note delegates must meet the [manager of manager eligibility criteria](https://leaddev.com/sites/default/files/2023-04/LeadingEng%20Eligibility%20Criteria%20%28LE%29.pdf) to attend (senior engineering leaders only - Head, Director, VP, CTO).
See social media card attached on the email 
See marketing copy attached on the email

**Comment by kfklein15** [comment]
Create a separate ticket for speaker: @alecmccrindle

**Comment by MarianaVazquezCYF** [comment]
we just need a linkedin post and we can close this ticket! any ideas @alecmccrindle ?

**Comment by alecmccrindle** [comment]
Linkedin post done @MarianaVazquezCYF - we can close it!
