### ISSUE TITLE
Luan's story

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1089]
- [x] Write story
- [ ] Add images
- [ ] Add social media summaries too

**Comment by alecmccrindle** [comment]
[Story is here](https://docs.google.com/document/d/1kD2wSzseanaAXiLeJJUX66R0J8h89C5vnTHAKdoz-l0/edit)

**Comment by kfklein15** [comment]
Raise another ticket for promotion.
