### ISSUE TITLE
Have all the media in one place!

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#109]

**Comment by MarianaVazquezCYF** [comment]
Hey @alecmccrindle where do we normally have all our media? do we have a folder? should we always create the folders for all the regions? :D

**Comment by kfklein15** [comment]
What about the FP Lon 8 that built an MVP of a portal with our media?

**Comment by MarianaVazquezCYF** [comment]
yeees, but this also can be covered by an album no? I dont remember how was that FP D:

**Comment by SallyMcGrath** [comment]
https://docs.google.com/document/d/1_aYRVzw1DJE1K5EadBzZqqh00ZlA4uaXw7izzLJkAIo/edit

**Comment by alecmccrindle** [comment]
We have most photos on [Google Photos
](https://docs.google.com/document/d/1CoMqKEd73BwPgJHUuuF5FE6UiAxgLHe-Q4MmM1aeKoQ/edit).

Most finished videos are are [YouTube](https://www.youtube.com/@codeyourfutureyoutube/videos). 

There are a couple of videos on Vimeo where we don't want ads. 

There is around 90GB and growing of raw video we use to make videos - with three different people.  

All of our articles are in the Drive and posted on the website.

Good to chat about access in the coming weeks: for example, photos taken by other folks may be nice to use, but these photos are not in Google Photos. How should we deal with that? Do we need permissions on our photos?, etc. Should we think about YT vs Vimeo for videos?
