### ISSUE TITLE
WMCA Adult Learning Awards

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#11]
https://www.wmca.org.uk/news/nominations-now-open-for-adult-learning-awards/

Hi All,

Nominations are now open for a new award ceremony aimed at celebrating achievements and innovation in adult learning in the West Midlands.

The first ever West Midlands Adult Learning Awards will look to highlight individuals, providers and employers who have made a positive difference in education such as creating an engaging method of teaching, an exciting atmosphere to learn in or overcoming barriers to succeed as a student.

People have until Friday 24 February 2023 to submit learners or organisations for nomination and those shortlisted will be invited to the official awards ceremony later this year.

More details can be found here: - [Nominations now open for Adult Learning Awards (wmca.org.uk)](https://www.wmca.org.uk/news/nominations-now-open-for-adult-learning-awards/)

 

Or,

To nominate, please visit one of the following pages:

[Individual nominations](https://forms.office.com/e/kegJJQg5Uh)
[Tutor nominations](https://forms.office.com/e/zjEJHjpQkR)
[Employer nominations](https://forms.office.com/e/kUWDsWBrdA) 
[Provider nominations](https://forms.office.com/e/bZygcJBZYW)

 

For further queries on the awards, please email: westmidawards@learningandwork.org.uk

**Comment by ElizabethlawalCYF** [comment]
I am going to suggest that the trainees in the WM nominate themselves and then we have a voting system between now and mid feb.

It will also be great for the trainees to nominate a volunteer so I'll get this up an running.

I am wondering if we wanted to nominate capgemini for the employer awards.

**Comment by gbencci** [comment]
We are already in contact with Capgemini about this. We'll apply together in the employer section @MarianaVazquezCYF is in charge of the selection

**Comment by MarianaVazquezCYF** [comment]
**In which area within the West Midlands does the learning take place?** 
Please select all that apply. 

Birmingham

Coventry

Dudley

Sandwell

Solihull

Walsall

Wolverhampton

@ElizabethlawalCYF do you know if we are in all of those areas?

**Comment by gbencci** [comment]
Email thread between Mariana and Capgemini: 
https://mail.google.com/mail/u/0/#inbox/FMfcgzGrcFhSNJPlRZgdlSghrlWxhvrQ

**Comment by ElizabethlawalCYF** [comment]
We are in Birmingham @MarianaVazquezCYF but we have trainees from all of those areas
