### ISSUE TITLE
London 10 catching up group

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1102]
### Background

3 trainees did not make it to the London Launch projects.

This group has been studying and catching up since (against Sally's advice, sorry, Sally!)

Could they join Launch projects with NW/ WM if they are ready? - how will we know? Pair programming?

### Acceptance criteria

- [x] @haldenb has a catch-up with trainees and volunteers about the progress of the group. 
- [ ] Group does pair programming to asses readiness for Launch Projects 
- [ ] This situation is resolved. Either they Launch projects, or they stop studying with CYF and we signpost them somewhere else. They can always volunteer.

### Owner

@halden

### Stakeholder

@halden @karen @mitch @sally

### Approver

@halden

**Comment by kfklein15** [comment]
Hi Halden, I cannot see a way of measuring these people to get them onto Launch tbh and we have enough on our plates right now, so we won't be looking into this for a while.

I also would love to understand why we did something against the Programme's advice. This is important so we can avoid repeating this in the future.

**Comment by haldenb** [comment]
I wonder if they knew it was against the programme teams advice?

**Comment by kfklein15** [comment]
Who talked to them about it and agreed this course of action?

**Comment by SallyMcGrath** [comment]
I'm going to  close this
