### ISSUE TITLE
Create Google Form to collect DLP Trainee Testimonials

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#1103]
### Background

Following #1057 

[Context Thread](https://codeyourfuture.slack.com/archives/C029341FPH6/p1714052215958699)

DLP has attempted to provide trainee stories/testimonials previously. It was not a huge success, so it is worth reviewing, retroing and drafting something to attempt with Sheffield DLP.

The goal is not to destroy and replace. This is an iteration attempt.

### Acceptance criteria

- [x] Create Google form to collect testimonials

### Owner

@mattcfry

### Stakeholder

-

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Hi @AmyCYF. With the face-to-face interviews, would you like to go about arranging them? 

We could link them to a calendly or Google meeting schedule. You could also arrange via email or WhatsApp, but that could get complicated.

**Comment by AmyCYF** [comment]
It would need to be coordinated, as I would need to work out travel time etc. I think if they want a F2F then I will reach out to them to coordinate via email/WhatsApp, depending on their preferred medium of comms.

**Comment by MattCFry** [comment]
Would you ever want to do them online?

**Comment by AmyCYF** [comment]
Potentially, but I would need to gauge how comfortable the trainee was with using the tool.

**Comment by MattCFry** [comment]
Okay. I will get them to reroute to whatsapp and email

**Comment by MattCFry** [comment]
https://docs.google.com/forms/d/1mltcKTKapdRO2WjGRtgn5FSPQtY9xaysTf5bmc2gg0E/edit
