### ISSUE TITLE
ZA monthly meeting venue

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1113]
## Background
Want to find a venue for monthly meetings. CodeBridge is a great start. Maybe we try find a free one too?

## Acceptance criteria

- [x] Shaun to email CodeBridge for costs. 
- [x] Alec to do some research for other venues and chat to Shaun about it.

### Owner
@alecmccrindle 

### Stakeholder
@ShaunCYFSA 

### Approver
@alecmccrindle

**Comment by ShaunCYFSA** [comment]
Sent an email to [Code Bridge](community@openup.org.za) on 02/05/2024. to enquire about venue costs.

**Comment by ShaunCYFSA** [comment]
CodeBridge has closed down.
Searching for alternative venues. Parow and Bellville Library are booked for most of the proposed dates.
Will speak to Mustadafin.

**Comment by alecmccrindle** [comment]
Shame about CodeBridge - I found these incubators, companies that host meetups and other spaces

- https://www.injini.africa/
- https://www.savant.co.za/contact/
- https://www.grindstonexl.com/
- Neighbourhood coworking space
- https://www.allangray.co.za/gallery/

**Comment by alecmccrindle** [comment]
Mustadafin confirmed for 6 July. Closing this ticket, new one should be opened by Shaun for the invite.
