### ISSUE TITLE
Add to the Global Trainees data

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#112]

**Comment by MarianaVazquezCYF** [comment]
@ClaireBickley 
Hello Claire, can we please add the following to the Global Trainees document? :D 

- If a trainee supports dependents
- Where the trainee heard about CYF 

Can we please also add this info to the Personal Circumstances Form? @ElizabethlawalCYF or @lilianabermudes ? :D

**Comment by ClaireBickley** [comment]
Hi Mariana, can we have a super quick call about this please? Just want to understand where is best to put this info.
Please pop something in my calendar

**Comment by lilianabermudes** [comment]
Hi @MarianaVazquezCYF and @ClaireBickley some general comments:

- The dependents question is on Rainbird
- We also ask the trainees where did they hear about CYF when they register, so it's on the dashboard

Not saying we shouldn't add this to the form, but we just need to think about how many times we're asking for the same info throughout the journey. Not ideal.

**Comment by MarianaVazquezCYF** [comment]
I agree! but otherwise the proms will need to add that info manually, instead of just copy paste the info from the personal circumstances form

**Comment by gbencci** [comment]
can we take a final decision on this?

**Comment by ClaireBickley** [comment]
Personally, I think we can put this on hold for now - the Personal Circumstances form is being reviewed and in time I really want to look at condensing Global Trainees into more useful information. We can pull information from different sources to suit the needs of different teams.
