### ISSUE TITLE
Marketing materials for WM4 Networking event

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1124]
context: https://codeyourfuture.slack.com/archives/C070SS37RAM/p1715075064985289

**Comment by alecmccrindle** [comment]
[Deck done](https://docs.google.com/presentation/d/1Lh0c5vC3cY2O2kCFIhShPeFKXjcKuUo_wfRRcDbSPnE/edit#slide=id.g2b4fc47e262_1_98)

In the current format, feedback was 

- Will this be sent and who is this being sent to? Just the companies?
- The format is long for a speed networking event. Is every session valuable for the companies in attendance?
- Inspiring talk at the beginning - can we make that a CYF grad? Easier to arrange and hopefully reminds people why they are there.
