### ISSUE TITLE
Open Scotland Channels

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#113]
[Related discussion on Slack](https://codeyourfuture.slack.com/archives/C029341FPH6/p1677079703522539?thread_ts=1675775089.416739&cid=C029341FPH6)

**Comment by ClaireBickley** [comment]
@emcglackenr1 I opened a few channels, were there any others?

**Comment by emcglackenr1** [comment]
Yes. Our in-class volunteer and our buddy channels. I have suggested we open in-class, but based on discussions with @caromelendezl this is currently on hold.

**Comment by emcglackenr1** [comment]
This channel is also closed: #gla6-ldn10-edu-volunteers

Since it is crossregional, I feel this shouldn't be an issue to open.

**Comment by ClaireBickley** [comment]
cool, please add me to any channels that need opening and I'll sort it :)

**Comment by emcglackenr1** [comment]
Yes this can be closed.
