### ISSUE TITLE
Follow up Centrica - British Gas corporate volunteer event

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1134]
I need to have a meeting with Lili and review the price and sen it over

- [x] Send risk assesment
- [x] Proposal dates

**Comment by kfklein15** [comment]
Info was sent, @MarianaVazquezCYF needs to follow-up on it.

**Comment by MarianaVazquezCYF** [comment]
They have come back to me, they need an update of the following:

- [ ]  Update centrica requirmenets for corporate volunteering - Mail with so many screenshot attached 

- [ ]  Propose 2events
- [ ]  Update venue
