### ISSUE TITLE
[Anderson] Design template for when speakers comes to our events

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#1135]
## Background
@MarianaVazquezCYF to complete

### Approver

**Comment by andersonuk** [comment]
Hi @MarianaVazquezCYF , here are a couple of templates we can use for this occasion.

- Variations with illustration, a single speaker and up to 4 speakers.

Can you both give your feedback, please?
@alecmccrindle 

- [ ] After Marianas' feedback make a ticket to convert it to Canva

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/f685193a-5987-4e3a-8b4e-6852d35c535e)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/747fba58-5794-47dc-9d52-47235b89f32a)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/0850151b-80df-4603-921f-6ba4edfff833)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/46d0f313-da07-4cbd-b8a5-12bf984fca36)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/a17e982b-44b8-4f82-a904-79a66f1e36e3)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/d0e2822a-5b39-48d2-bf07-8ca49fe19595)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/6fd70162-90a8-48fe-885c-54861a4c6a37)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/87ee2847-d841-4609-8c26-cb61d6032dae)

>  
 __

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/04498eb3-488c-41f6-bed8-246f07054c8e)
