### ISSUE TITLE
Evergreen Introduction to DLP Template - Referral Partner

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#1145]
### Background

We require a template email for referral partner outreach, which is not linked to a specific cohort.

I needs to engage the interests of the orgs, have them want to work with us and set up a meeting so we can secure the partnership

### Acceptance criteria

Create the template, ensuring it covers the following...
- [x] Introduction to DLP
- [x] Goal/mission of DLP
- [x] Value and impact to org community
- [x] Action to book a meeting with Amy
- [x] Has the evergreen file attached

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Amy calendly - https://calendly.com/amy-mead/30min?month=2024-05

**Comment by MattCFry** [comment]
[Similar Example](https://docs.google.com/document/d/1bTM_HfIb5b8tEUPpUmr_X7UCShozmTwDpIN-7XJhvdw/edit)

**Comment by MattCFry** [comment]
https://docs.google.com/document/d/1bTM_HfIb5b8tEUPpUmr_X7UCShozmTwDpIN-7XJhvdw/edit#heading=h.qz7nf5oobj

**Comment by AmyCYF** [comment]
Thanks @MattCFry - reviewed and added feedback.
