### ISSUE TITLE
Hotels for DLP Marketing Material - Organisation

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#1147]
### Background
We will need break down the list of hotels into areas and divide the distribution to the hotels within that team

### Acceptance criteria
- [ ] go through list of hotels and organise them by location

###  Owner
@MattCFry 

### Stakeholder
@AmyCYF 

### Approver
@MattCFry

**Comment by kfklein15** [comment]
@AmyCYF , another one, not sure if I bring it in to my backlog?
