### ISSUE TITLE
Hotels for DLP Marketing Material - Research

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#1155]
### Background

The DLP needs a renewed effort to source and attract participants for the London courses, including the Capgemini Holborn cohorts.

Similar to Sheffield Outreach, we need to do prepping, outreach and planning

### Acceptance criteria

- [ ] Research LDN hotels which house refugees/ Asylum Seekers and add them to the [LDN DLP Outreach tab](https://docs.google.com/spreadsheets/d/1TkJKSYTsIHT_psNdIm0ML8UiwHEJBzUSpzVia61MV9I/edit#gid=2024157036). Aim for 30

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Old list - https://docs.google.com/spreadsheets/d/1lHqgYqZ2m0co6yFGkdSImRBUdH3Glolf4Njx9cvn3KY/edit#gid=0

**Comment by kfklein15** [comment]
@AmyCYF , is this something I should pick up?

**Comment by AmyCYF** [comment]
I will set up a time with you to chat about this. Its got a few variables

**Comment by kfklein15** [comment]
Closing this since the world (CYF) has changed
