### ISSUE TITLE
Capgemini Report via CYF Next

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#117]
Story about [Capgemini report - Version 1](https://github.com/CodeYourFuture/cyf-next/issues/46)

**Comment by kfklein15** [comment]
@ClaireBickley , for you to review :D

**Comment by ClaireBickley** [comment]
closing this as Capgemini are having a think about what data they actually want, I think they already capture what they need so let's re-visit this at a later date?
