### ISSUE TITLE
Summit accommodation - Travelodge Stockport quote 

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1173]

**Comment by alecmccrindle** [comment]
[I called travel lodge, these are their Stockport rates](https://docs.google.com/document/d/1LY8gLZ6-JAkOq3D_mnV7g6Scouo-xPTZ5JVC3JKuBTc/edit?usp=sharing) @MarianaVazquezCYF
