### ISSUE TITLE
DLP - Flyer

### ISSUE THREAD

**Issue by andersonuk** [CodeYourFuture/CYF-Staff-Tickets#1193]
## Background
We're making a flyer for the DLP programme that may include ITD. 

## Acceptance criteria

- [x] Printable PDF flyer

### Owner
@andersonuk 

### Stakeholder
@AmyCYF @alecmccrindle 

### Approver
@AmyCYF

**Comment by alecmccrindle** [comment]
@andersonuk asked @AmyCYF if both DLP and ITD should be on the flyer. 

@AmyCYF - we've added Anderson to our board, can you respond here in the ticket?

**Comment by AmyCYF** [comment]
@andersonuk yes both should be on the flyer. It would need to be a digital version we can share with potential partners.

**Comment by andersonuk** [comment]
https://docs.google.com/document/d/1Gy6HzrxdjoTRGxc6syB9cFPDo_oeQRFyqvH2FbzS2LU/edit

**Comment by alecmccrindle** [comment]
[Sketches](https://www.figma.com/file/0niiYqGBfCUxfizyKbgJnV/CYF-Marketing-material?type=design&node-id=6847%3A2&mode=design&t=peWUz80YTKU9h0e1-1) for you @andersonuk

**Comment by AmyCYF** [comment]
It's looking good @andersonuk. 
My feedback would be:
DLP:

1. Under 'Duration' can we also include '15 hours'
2. Under 'Cost' the minimum is incorrect. It is meant to be £3000, not £3500.
3. Space is not included in any of the costs, not just outside of London, Manchester etc. I think we can also change the wording to 'Venue'.
4. Transportation costs **for trainers** are not included outside of London, Manchester etc

I have updated the wording on the [shared doc](https://docs.google.com/document/d/1Gy6HzrxdjoTRGxc6syB9cFPDo_oeQRFyqvH2FbzS2LU/edit) to reflect the changes in points 3 & 4.

ITD:

1. I think we need to include the following information: 'Designed to welcome 100+ registrations.' as without this the cost section does not make sense. I have [updated the doc](https://docs.google.com/document/d/1Gy6HzrxdjoTRGxc6syB9cFPDo_oeQRFyqvH2FbzS2LU/edit) to show the wording change in the intro paragraph.
2. change second point under 'Cost' to be 'named locations' so it is consistent with point 3. I have [updated the doc](https://docs.google.com/document/d/1Gy6HzrxdjoTRGxc6syB9cFPDo_oeQRFyqvH2FbzS2LU/edit) to show the wording change

**Comment by andersonuk** [comment]
Thank you for the feedback @AmyCYF!

1 - Could you please check this version?
2 - Related to the photos as I mentioned before they are placeholders. Do you have other images we could use?


![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/b9681804-bada-4679-a743-b88027da0671)

**Comment by AmyCYF** [comment]
Hi @andersonuk 
My feedback would be:
General:

- the copy font is quite small and difficult to read
- Unfortunately, I do not have any DLP images that are the quality we would need for this, that have the trainees consent to use.

DLP:

- Under 'Duration' can we also include '15 hours total'. Seeing it in situ makes me realise it could be interpreted as 15 hour per session.
- The venue section  should just say: 'Venue costs not included'
- The transportation section should say 'Transportation costs for trainers are not included outside of London, Manchester, Birmingham and Glasgow' 

Please could you chat to @alecmccrindle regarding the following feedback we spoke about in person:

- moving the logo
- using a cartoon image from the DLP branding
- Made changes to the prices based on a conversation with German today, they are [updated on this doc](https://docs.google.com/document/d/1Gy6HzrxdjoTRGxc6syB9cFPDo_oeQRFyqvH2FbzS2LU/edit)

**Comment by andersonuk** [comment]
Good morning, @AmyCYF

I needed to change the layout to better accommodate the content.

Can you please revise it again?  If you prefer, we can schedule a call today so I can finish it.


Thank you 



![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/edd1d3a6-9a55-4f76-bddb-aeaf116b7194)

**Comment by AmyCYF** [comment]
@andersonuk I added a comment on the google doc with the copy which would need to be changed on the design.

**Comment by andersonuk** [comment]
> [@andersonuk](https://github.com/andersonuk) I added a comment on the google doc with the copy which would need to be changed on the design.



![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/61c9a25c-9bac-461e-992a-a73b85087070)
[programmes_cost.pdf](https://github.com/CodeYourFuture/CYF-Staff-Tickets/files/15500918/programmes_cost.pdf)



@AmyCYF I did the change and convert it to PDF format. Let me know if is that all.

Thank you!

**Comment by AmyCYF** [comment]
Thanks @andersonuk. Is there a file I can access where I can make minor copy tweaks? It feels more efficient than going back and forth. :)

**Comment by andersonuk** [comment]
> Thanks [@andersonuk](https://github.com/andersonuk). Is there a file I can access where I can make minor copy tweaks? It feels more efficient than going back and forth. :)

I did invite you to edit the Figma file by this e-mail: amy.mead@codeyourfuture.io

You can edit the text and don't worry if the layout gets messed, I have a copy and I can fix it when you finish.

**Comment by AmyCYF** [comment]
Thanks @andersonuk - I am done. If you could fix the spacing on the ITD Duration section (it went misaligned when I deleted text) then I can send to German for final approval

**Comment by andersonuk** [comment]
> Thanks @andersonuk - I am done. If you could fix the spacing on the ITD Duration section (it went misaligned when I deleted text) then I can send to German for final approval

Done! @AmyCYF 
![approved_programmes_cost](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/86576314/7948854b-0e68-4278-bbae-6265c4d31334)
[approved_programmes_cost.pdf](https://github.com/user-attachments/files/15592562/approved_programmes_cost.pdf)

**Comment by AmyCYF** [comment]
@gbencci please could you take a quick look at these designs and confirm you are happy for me to send this to Scottish Army? I am happy on my side.

**Comment by gbencci** [comment]
sorry for the delay. Please go for it
