### ISSUE TITLE
Product page - build image gallery

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1195]
## Background
We are building a product page on wordpress. We have a wireframe and now we have to build and test the page in Wordpress, element by element.

[Wireframe is here.](https://www.figma.com/board/hyFA2QAPgs6Cr6bRSU4UyJ/products?node-id=0%3A1&t=jtQ7ytPwKACfn23G-1)

## Acceptance criteria
Build and test image gallery

### Owner
@andersonuk 

### Stakeholder
@kfklein15 

### Approver
@alecmccrindle

**Comment by andersonuk** [comment]
@alecmccrindle 
Maybe this task can be merged to the #1194 task as gallery and slider were made together.
