### ISSUE TITLE
Product page - check navigation on mobile and desktop

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1196]
## Background
We are building a product page on wordpress. We have a wireframe and now we have to build and test the page in Wordpress, element by element.

[Wireframe is here.](https://www.figma.com/board/hyFA2QAPgs6Cr6bRSU4UyJ/products?node-id=0%3A1&t=jtQ7ytPwKACfn23G-1)

## Acceptance criteria
Ensure navigation works on mobile and desktop

### Owner
@andersonuk 

### Stakeholder
@kfklein15 

### Approver
@alecmccrindle

**Comment by andersonuk** [comment]
@alecmccrindle 
- The question about this task was related if the Tab navigation would work well on mobile. I think it does but we can disscuss it in a meeting.

**Comment by alecmccrindle** [comment]
Working for mobile and desktop. Next step is to make design.
