### ISSUE TITLE
Product page content

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1198]
## Background
We are building a product page on wordpress. We are building and test the page in Wordpress.

[Wireframe is here.](https://www.figma.com/board/hyFA2QAPgs6Cr6bRSU4UyJ/products?node-id=0%3A1&t=jtQ7ytPwKACfn23G-1)

## Acceptance criteria

- [x] Choose one product and create content for that product in the showcase
- [x] Make tickets for the other product content

### Owner
@kfklein15  

### Stakeholder
@andersonuk 

### Approver
@kfklein15

**Comment by andersonuk** [comment]
@alecmccrindle 
We have a first draft from Karen. These are the first products we will start off:

**Introduction to Digital**
**Volunteer Form**
**Dashboard**

**Comment by alecmccrindle** [comment]
Note to share content from Google doc for @alecmccrindle to review. 
We should make the following ticket:

- [x] Screenshots from the products

**Comment by andersonuk** [comment]
> Note to share content from Google doc for [@alecmccrindle](https://github.com/alecmccrindle) to review. We should make the following ticket:
> 
> * [ ]  Screenshots from the products

@alecmccrindle 
[I added the doc on Google Drive](https://docs.google.com/document/d/1mXtqv3o8lU71VVg4RgBC3msc0R23QmwPEqP8DQ4vDyk/edit?usp=sharing)
