### ISSUE TITLE
DDS - competitive research

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1202]
## Background
One of the ways we can help our course completers get jobs is by helping them with their portfolios. 
This ticket is to do competitive research to see how our competitors showcase their trainees work.  

## Acceptance criteria

- [x] CYF competitors (@alecmccrindle)
- [ ] Add research into Figjam board @andersonuk)
- [ ] Make ticket for further action (@andersonuk)

### Owner
@andersonuk 

### Stakeholder
@alecmccrindle and @kfklein15 

### Approver
@alecmccrindle

**Comment by alecmccrindle** [comment]
Need to do the research before Anderson can continue

**Comment by alecmccrindle** [comment]
Hi @andersonuk - this is a good list of 'competitors' for CYF. 

Free

- Code First Girls
- School of Code
- 01 Founders
- HackYourFuture
- WeThinkCode
- Laboratoria

Paid

- Le Wagon
- Makers
- North Coders

**Comment by alecmccrindle** [comment]
Hi @andersonuk - can you share an update on this research? Thanks

**Comment by SallyMcGrath** [comment]
closed as stale
