### ISSUE TITLE
Donate items from CYF storage

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#1204]
**Background**
Discussed items in CYF Scotland storage in my handover document. This refers to the items[ listed here](https://docs.google.com/spreadsheets/d/1If9wrGPQtnGyIuo3nqw_EIpi93jDxXXbMI0DRq0rvoc/edit#gid=1463586366)
Completion Criteria 
- [x] Arrange with Frank a time I can stop by with a volunteer (was blocked for a while due to various conferences he was attending)
- [x] Contact Refuweegee about items to confirm they will take them
- [x] Donate items to Refuweegee - suits, kitchen items
- [x] Donate to Clutha Trust / Code Division - food and drink (tea, coffee, etc)
- [x] Donate to charity shop that take electronics - other items - see spreadsheet

**Comment by kfklein15** [comment]
@emcglackenr1 , has this been done?

**Comment by emcglackenr1** [comment]
Yes was just coming online to complete this :)
