### ISSUE TITLE
Move London office 

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1206]
### Background

We are moving to Holborn :D When do we get keys?

### Acceptance criteria

[ ] - Buy Moving Boxes
[ ] - Get everything packed up
[ ] - Move to new office (do we need a van?) Stuff from Cititec - Stuff from storage (do we need to cancel the storage?)
[ ] - Buy stuff for Coffee? Cafatiere etc 
[ ] - Organise a moving-in party (for the next after-class social?)

### Owner

@halden

### Stakeholder

@halden

### Approver

@halden

**Comment by alecmccrindle** [comment]
Close this ticket?
