### ISSUE TITLE
Grant Proposal for Family Trust

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#122]
@kfklein15 , we'll try to apply for the small grant (15k) to support Product development. German's suggestions were around fund  dashboard 2.0 and the other products (the new classroom one)

Do you have any other/different ideas?

**Comment by kfklein15** [comment]
Nope, these would be the ones. Do you need my help and with what by when? I am on holiday next week :)

**Comment by lilianabermudes** [comment]
Good - it would be great if you could only outline how the 15k could be spent. And then, I build the proposal

**Comment by kfklein15** [comment]
Created a budget [here](https://docs.google.com/spreadsheets/d/1DxrCSqzfohiT5bY2ArJoMIfjbVxk_iTyFNER33VV07g/edit?usp=sharing). Worth checking if I am not paying too little or too many people :D

**Comment by lilianabermudes** [comment]
Thank you @kfklein15

**Comment by lilianabermudes** [comment]
@kfklein15, German has added his numbers proposal to the same spreadsheet so you can compare. I will wait to get your opinion before we actually send the proposal. To be discussed next week.

**Comment by kfklein15** [comment]
I'm happy with German's suggestion, @lilianabermudes  :)

**Comment by lilianabermudes** [comment]
- @kfklein15 do you have a good answer for these questions they're asking? 👯 

- The proposal is to employ 4 graduates and 1 senior developer for 3 months - how long would you usually employ people for? Is 3 months the usual length of time?
- What happens to any graduates who don't manage to find a job in tech at the end of the 3-month contract?

**Comment by kfklein15** [comment]
@lilianabermudes 

- In the proposal, we said it would 2.5 months (50 days). We usually hire people for 3 months, yes, but the budget wouldn't cover that
- They will be jobless looking for a job. They could continue volunteering for us to keep their coding experience up and running AND work with the employability team to search for jobs. And we might have by then other grants or needs and be able to offer them a second contract, but we cannot promise that.

**Comment by kfklein15** [comment]
@lilianabermudes @gbencci , I have mapped some of the projects we need and we could use the Maigot trust's money to do. What are your thoughts about these? Any I missed? Which one is your favourite? 

https://docs.google.com/spreadsheets/d/1Ki1vllTJS7mcYdrc7gcdmQppHxOSqtlzkNrurKwENIU/edit#gid=0
