### ISSUE TITLE
Review design research from weekend in London

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1221]
[Notes from Alec's phone](https://docs.google.com/document/d/1LLD_KGAXg5Y3xBm8nic1gKwJaTlqEjaAoHzclb1JwhU/edit)

**Comment by andersonuk** [comment]
@alecmccrindle 
Hi Alec, follow the [Figma link to the research](https://www.figma.com/board/kKDWutyhAScMyj0nn6NJua/Graduates%2C-Alummini%2C-Volunteers-Research?node-id=0-1&t=plS5JGCrtgzUUNOm-1)
