### ISSUE TITLE
Order chairs and tables Summit 

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1225]
- [ ] Find providers for food 
- [ ] Order decoration 
- [x] message luke about logistics, coffee etc 
- [x] Order chairs and tables 
- [x] Order catering - coffee / tea / water jars
- [ ] order microphone
- [ ] Order plates, cuttery, napkins, cups , markers, name tags

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , are we doing train or bus? I remember you saying buses are cheaper?

**Comment by MarianaVazquezCYF** [comment]
we are doing train!
