### ISSUE TITLE
Open source proposal for anita.org

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#123]
We received this message:

As part of my role at [AnitaB.org](http://anitab.org/) I'm leading our initiatives for this years' GHC Open Source Day. Currently we're looking for open source projects to partner with for a full-day of open source events at our Grace Hopper Celebration Open Source Day (OSD) event this! We are reaching out to you because of your extensive involvement in the tech community and focus on DEI in the hopes that you can help us broaden our search.
This event is an exciting opportunity for attendees to learn & become open source contributors. Trained mentors provide guidance to make contributions to listed projects. Projects that participate in the event not only gain visibility and same-day contributions, but also benefit by widening their pool of future contributors. We are looking specifically for open source projects that have female or non-binary maintainers and focus on solving real world problems inclusive of experiences from around the world.
If you are aware of or have any open source projects within your community, whom you think are a great fit for this opportunity, please feel free to share the following information:
Learn more --- https://ghc.anitab.org/programs-and-awards/open-source-day/
Submit a proposal --- https://ghc.anitab.org/become-a-speaker/

**Comment by lilianabermudes** [comment]
- @kfklein15 it seems it can apply to[ this project.](https://app.sessionboard.com/submit/grace-hopper-celebration-2023/f9ed4ea9-3e3e-4936-a112-c4f4af24dbfc) what do you think?

- @MarianaVazquezCYF would you like to see if this is a good space for us to join as speakers or what are the requirements? https://ghc.anitab.org/programs-and-awards/open-source-day/

**Comment by lilianabermudes** [comment]
@kfklein15 should we work on this together? :-) Let's involve Mariana too

**Comment by kfklein15** [comment]
Yes, please, @lilianabermudes , because I know very little about this amazing portal Sally et all crated :)

**Comment by MarianaVazquezCYF** [comment]
Hello, so I have checked and we can be
1. Speakers https://ghc.anitab.org/become-a-speaker/  deadline: 26 April 
2.  Submit our open source project for a hackathon , do we want that? https://app.sessionboard.com/submit/grace-hopper-celebration-2023/f9ed4ea9-3e3e-4936-a112-c4f4af24dbfc deadline: 26 April 
3. Submit a workshop proposal https://app.sessionboard.com/submit/grace-hopper-celebration-2023/d7692142-015a-42b4-b806-c769c50340e9 https://app.sessionboard.com/submit/grace-hopper-celebration-2023/d7692142-015a-42b4-b806-c769c50340e9. Do you want to lead a workshop @SallyMcGrath ? (I think you love doing workshops :D )

**Comment by MarianaVazquezCYF** [comment]
Timeline
Thursday, February 23 – Call for Participation (CFP) Opens
Tuesday, March 7, 3:00 p.m. Eastern Time – Info session and Q&A (Recording to come soon.)
Wednesday, April 19, 12:00 p.m. Eastern Time – Info session and Q&A ([Register Here](https://membership.anitab.org/events/EventDetails.aspx?id=1729106)!)
Wednesday, April 26, 8:00 p.m. Eastern Time – CFP Closes
June – Proposal Status Notifications sent
July – Guides and Resources
August – Orientation and Training
September 26-29 – GHC 23!

(I have registered for the Q/A)

**Comment by kfklein15** [comment]
@SallyMcGrath could also be a speaker about Open Source :D

**Comment by SallyMcGrath** [comment]
Just a note to say there's actually a Product Management Track and it might be interesting for Karen to do a talk on CYF Products: developing products with so many juniors, training PMs at the same time, infra, final projects -- it's a wild job really -- I think it would be really interesting to people and might get us some vols? @kfklein15

**Comment by lilianabermudes** [comment]
@kfklein15 & @MarianaVazquezCYF, can you work together on this? The deadline to apply is this week - it should be simple.

They really want us to join - the lady messaged me again :)

**Comment by kfklein15** [comment]
@MarianaVazquezCYF @SallyMcGrath , I put something together in this [document](https://docs.google.com/document/d/1oCXhi7FdYyRzyuAg3m-Ory9JmqZ4SVJBQkBwSDeZnu0/edit?usp=sharing). The yellow bits are what I am suggesting.
Feedback welcome.

**Comment by MarianaVazquezCYF** [comment]
Amazing Karen! you already did everything for your talk! therefore, I will submit that one and the one of the open source :)

**Comment by kfklein15** [comment]
Thanks, @MarianaVazquezCYF . Let me know once you know if we actually have to do it, so I can prep the presentation itself :D

**Comment by MarianaVazquezCYF** [comment]
The proposals have been submitted! In June we will know if we were selected!

**Comment by lilianabermudes** [comment]
HI @MarianaVazquezCYF that's the answer I got from my contact: Hey Liliana, Thats great to hear! I just double checked to make sure it was received and Im not sure that I see it. Can you confirm the project/workshop name?

**Comment by MarianaVazquezCYF** [comment]
![Screenshot 2023-05-01 at 10 00 06](https://user-images.githubusercontent.com/91734869/235432240-446622ea-d946-4bb6-a911-4ef05b1fb630.png)


In my portal says: pending; however, there is no button to edit them and I received the confirmation emails that the proposals were submitted! Can you please ask them Lili?


Sessions: 

- Empowering social impact with volunteer led Product Management

- Immersive engineer program in a volunteer run charity

**Comment by lilianabermudes** [comment]
Done (just asked :)
