### ISSUE TITLE
Interview 2 x alumni about design in their day to day

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1233]

**Comment by alecmccrindle** [comment]
Shayan

Design info wasn't really needed for Shayan
He built his portfolio in this first month at CYF
There is a design team at his job
Weekly meeting with the designers
Designers show designs for new features - ask devs if it's feasible
All design work is coming through designers - they share the components 
[There is a good storybook and documentation - full of patterns and components! ](https://britishgas.design/)
Devs are speak daily to designers during standup. If there are any issues, designers can change the design with the devs. Working together. 
Designers ask him for design ideas! 

Thoughts:
CSS is important for understanding system design - brain should think like a designer.
Good to practice on design system / components. Make sure the work is clear and tidy. Introduce the idea of a design system. 
If they want to design by themselves, they can practice on a design system.

Ideas for CYF cirriculum - introduce the idea of what a design system is. Maybe practice something with it.

**Comment by alecmccrindle** [comment]
**What did you learn about design at CYF?**
Didn't learn anything about UXUI, just front end

**What did you learn about design in your job.**
Ali learned about storybooks at his job. It helps him work better. 
Designers design in Figma, import in the storybook then show them to designers. 
This can be made into components.

Didn't make a portfolio. Just shared Github and the final project. 

**Ali's ideas and suggestions:**

- Ali wished that there was a small module about working with Figma, it would have been helpful.
- Ali also suggests that the grads research and implement interesting solutions and problems and share them online - eg. Ali found a technique to hide code and shared it on his Linked / Medium. 
- Maybe some education about website architecture - so that you can make suggestions to help with things like data leaks, security, etc. Avoid duplicate work. Which component is best to start with - home page, etc. How components interact with each other.   
- If designers want a higher chance to get hired, they could learn something like DeckGL. Working with live data is popular - like on a map.

**Comment by andersonuk** [comment]
> ding system design - brain should think like a designer.
> Good to practice on design s

Hi @alecmccrindle, Is Shayan an Alumini? from each cohort, please?
