### ISSUE TITLE
Write outline for potential speaker slot at EATP Conference

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#124]
I have a connection that works as organiser for:
https://www.eatpconference.eu.com/

She asks us to choose 2 topics to present at the conference in Vienna. 
Sally, I think this could be a good chance for you to speak (if you want). 

We can choose a topic that covers our experience of training the people we work with. It can also touch a bit on our experience around testing them.

One paragraph per topic is enough. I'll send it to Giulia Bianchi.

**Comment by SallyMcGrath** [comment]
Topic: Candidate: Understanding the new expectations of candidates towards assessment. This may include matters to address a shift in their value of testing, issues relating to digital poverty, equity in assessment, and access.

_Tearing up the Certificates: The Measure Is Not The Target_

How we work to liberate our learners from collecting endless pieces of paper and instead focus them on building their own, individual, marketable skills: 

- We cancelled grading... and our outcomes improved.
- We give our leaners the solutions and teach them how to review themselves.
- Our graduation criteria: You have to really build it, and you have to show us.
- How this fails and what to do next.

Topic: Transforming: All aspects of transforming the assessment process, from paper to digital, centre to remote, microcredentials, and more.

_Where we're at: Harvesting activity from learner interactions_

- Identifying signals in assessment - finding proxies
- Setting milestones and pulling data - good APIs drive design decisions
- Strict on the entry and exit, super relaxed about the routes
- Staying loose and keeping it light - our learners should be able to build their own tracking systems

**Comment by gbencci** [comment]
Yes, too much work to write a paper. Much better to be invited to talk without having to write a paper
