### ISSUE TITLE
Arrange interview with hiring manager

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#1240]
Speak to Barny about this

**Comment by alecmccrindle** [comment]
I did one interview myself. Someone who has hired from universities and bootcamps, front and back end and full stack. 

"A bad portfolios is noticeable. 
Good design is nice but doesn't have to be too good. 
Sometime a dev may need to do some basic design - in figma or coded - making it look okay, using components, is good. Knowing how to source design elements is a good start. Eg. How to use a design system to make components.
Engineers who have wider skills are good - + product or data or UXUI or visual design, etc.…
Dev who knows about design can take some pressure off main designers 
Unblock yourself - you don’t have to queue for designers - but some places will still make you queue!
Stand out  - aesthetic effect 
Suggests we check out data - who got hired at CYF what do those portfolios tell you. We could also send same persons CV to various places and check results (don't think this will work).
Having some UXUI sense helps take pressure off yourself
Idea: pair designer with dev at CYF for portfolios too?"

**Comment by alecmccrindle** [comment]
This interview is done, Anderson has a ticket for the other interview.
