### ISSUE TITLE
Values and Principles rewriting

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#125]

**Comment by lilianabermudes** [comment]
- @gbencci @alecmccrindle I couldn't wait anymore on the external contact who said he would do it. I had a go for the second time with chat GPT (only the values, the principles look good)

Would you like to have a look at pages 5 and 6, please?

**Comment by alecmccrindle** [comment]
I added a further edit it using Hemmingway and Grammerly (and a couple of small suggestions myself, removing repeats. 

You can see those versions from page 6.

**Comment by lilianabermudes** [comment]
I like your version, Alec! Let's wait for German to see what he says, then.
