### ISSUE TITLE
DDS - arrange interview with hiring manager

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1260]

**Comment by andersonuk** [comment]
@alecmccrindle 
Already sent an invitation and waiting for confirmation.

**Comment by andersonuk** [comment]
> [@alecmccrindle](https://github.com/alecmccrindle) Already sent an invitation and waiting for confirmation.

I already sent an e-mail to you @alecmccrindle and @Barny-6 that I need to find another Hiring Manager to make an interview as the person Barny suggested is not able to participate any more.

**Comment by Barny-6** [comment]
Hey Anderson, could you try posting in CYF-Volunteers asking if anyone is or knows someone who is a hiring manager?

**Comment by alecmccrindle** [comment]
[Link to the other interview with hiring manager](https://github.com/orgs/CodeYourFuture/projects/55/views/25?pane=issue&itemId=63554899)

**Comment by andersonuk** [comment]
@alecmccrindle I sent a message for a Hiring Manager referred from Parul.
Waiting for his response
https://www.linkedin.com/in/josh-wingate-b7b159195/

**Comment by SallyMcGrath** [comment]
this looks blocked

**Comment by alecmccrindle** [comment]
Anderson has left so this ticket is closed.
