### ISSUE TITLE
DLP Manchester Outreach - First round

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#1265]
27th June - course starts
Outreach: must start asap
Most sign-ups are 2 weeks before the course starts

**Acceptance criteria**
- Find organisations/charities
- Send e-mails to them to share the DLP - specific email with the cohort

**Comment by kfklein15** [comment]
@AmyCYF , FYI this is the ticket for Manchester outreach. Can you add any comments/files on here, please?

**Comment by AmyCYF** [comment]
[Manchester DLP Flyer.pdf](https://github.com/user-attachments/files/15592861/Manchester.DLP.Flyer.pdf)
![Manchester DLP Flyer](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/133657703/7061e298-a5c0-48f9-8b27-545cbc3aa5d5)
