### ISSUE TITLE
Have one PD Syllabus representative per region [Lara]

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#127]
London - Irene, Alfonso, Erika
NM - Jiwei
WM - Matt
Glasgow - Roger and Jack
South Africa - Lizelle

**Comment by SallyMcGrath** [comment]
@kfklein15 I'm cleaning up the tickets. This ticket isn't assigned to a planner or person. Should it be closed?
