### ISSUE TITLE
Separate Meetups for Glasgow and West Midlands?

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1273]
**Background**
The paid version of Meetup has only 3 meetups

**acceptance criteria**
- investigate options
- understand cost

**Comment by MarianaVazquezCYF** [comment]
I will pass this to sprint 17 or 18 as we have more urgent priorities for this sprint

**Comment by alecmccrindle** [comment]
Met, this is not needed right now.
