### ISSUE TITLE
Define a Design System for CYF Products

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#128]
**Background**
We have many design systems at CYF.
[Slack thread ](https://codeyourfuture.slack.com/archives/C04LXPM69B6/p1679927964060839)about this
[CYF UI](https://github.com/CodeYourFuture/cyf-ui)
[TWilo example Design System](https://www.figma.com/community/file/1207476064127503112)

**Acceptance criteria**
- Work should be fit for UI/UX and Developers to use
- Define which one should be the unique Design System (if possible) or at least unique per product
- Define the process to implement/use the Design System

**Comment by kfklein15** [comment]
Jo Change looking into it. She will organise a meeting with me and Jon.

**Comment by kfklein15** [comment]
Research done by Jo Chang and Mandy is in **this dcument.**
I shared it with @SallyMcGrath , since she believes this would not be helpful, so we need to understand what the gaps are and decide what's best for us.

**Comment by SallyMcGrath** [comment]
To be clear, I don't object to the concept of design systems. I object to mediocre design systems. The options proposed are worse than the code we have in Rainbird so it's not an improvement. They are slower and less accessible. Rainbird is definitely not perfect and needs lots of work; that work shouldn't make it worse.

**Comment by SallyMcGrath** [comment]
Is this in progress, or blocked?

**Comment by alecmccrindle** [comment]
The designers are presenting their previous research this Thursday, so technically in progress/review?

**Comment by kfklein15** [comment]
@alecmccrindle , how is this doing? Any final decision on it?

**Comment by alecmccrindle** [comment]
Hi @kfklein15, The Deloitte-funded project aimed to find a design system. I think that outcome — a design system — seems secondary to using design (and perhaps design volunteers) to help grads with their portfolios.  

The output of that project may still be advances in our design system. I'm adding this comment to update you. Given that this was in review, should we discuss new tickets related to design systems in later sprint plannings?

**Comment by kfklein15** [comment]
Design system for Products is not the same as for their portfolio.
It think we should close this ticket and see if this actually one days becomes a priority.
