### ISSUE TITLE
DLP (Manchester)- Social Media Post

### ISSUE THREAD

**Issue by andersonuk** [CodeYourFuture/CYF-Staff-Tickets#1294]

**Comment by andersonuk** [comment]
## Background
Make a Social Media Post.

## Acceptance criteria
Copy:
https://docs.google.com/document/d/14neZlYmCd6O0Cs_Ns_lvdbxNB_XbH3ce8ILU3b-9tIo/edit


### Owner

### Stakeholder
@AmyCYF 

### Approver
@alecmccrindle

**Comment by andersonuk** [comment]
@AmyCYF, @alecmccrindle 
[The design file is on Canva here](https://www.canva.com/design/DAGIfQFjPoY/JoWgGdI27mp-zPB5ys7s7Q/edit?utm_content=DAGIfQFjPoY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Please, let me know if it will attend the demand, thank you!

**Comment by AmyCYF** [comment]
Perfect! Thank you Anderson!
