### ISSUE TITLE
DLP Outreach Roles - Hackney

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1297]
### Background

Hackney Volunteer Centre can advertise some DLP roles :D

### Acceptance criteria

 fill this out https://docs.google.com/document/d/10XDTXNj1JSANvWim6wQozRKUq-or5TxG/edit 
 
 Send it to louis@vchackney.org 

### Owner

@halden

### Stakeholder

@halden Amy

### Approver

Amy

**Comment by SallyMcGrath** [comment]
@AmyCYF is this blocked?

**Comment by AmyCYF** [comment]
I don't think so. Once for @lilianabermudes / @MarianaVazquezCYF to pursue if they are interested?
