### ISSUE TITLE
CYF Guidelines for Offices use

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#130]
- After the meeting with Cititec, let's create a general draft to be used in your regions
- After we have the draft, let's share it with the PROMs

**Comment by lilianabermudes** [comment]
Hi @ClaireBickley, I'm reviewing my tickets. Have we progressed with this? I don't think we created a general template for office use, but now that we have the Cititec one do you think we can use that as a base?

**Comment by ClaireBickley** [comment]
I wrote a starter document but I think realistically we should be led by the venues - we should be asking them of their expectations and passing it on to the community. I don't think we need our own doc but we should be sending something to community members based on what the venue gives us.

**Comment by lilianabermudes** [comment]
- Cool, let's close this ticket then and work on an ad-hoc basis with the venues.
