### ISSUE TITLE
Keep onboarding documents up to date

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1304]
### Background

Ensure the Welcome Event presentation is up to date, reflecting any changes to the model and programme [NEW Welcome to CYF - for volunteers (WIP)](https://docs.google.com/presentation/d/1rawXCCKbTj7t0Em48X1vxw3PxSYsVLYwAxDqsOgHsVU/edit#slide=id.g141ca3155bf_0_11)

Ensure the onboarding quiz is up to date and reflects any changes https://docs.google.com/forms/d/1dB6bezcJl0Gz_5HPm-WnHikTuupLbRrchsvssqPIHJY/edit#settings 

### Acceptance criteria

Updated once per quater

### Owner

@halden

### Stakeholder

@halden @lili

### Approver

@halden

**Comment by SallyMcGrath** [comment]
@lilianabermudes I'm closing all these tickets presuming you will define a higher level one
