### ISSUE TITLE
Review of PC form

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#132]
- can we review the PC form?
--> With Rainbird, do we need it at all? (I know it was helpful when Rainbird was down)
--> if we need a version, maybe we need to update it (remove unnecessary questions)

**Comment by lilianabermudes** [comment]
- https://docs.google.com/forms/d/1cduSAlHe6wJ2eXVQMPceYl1wnY5aCJ4pOd5-UuXjjcc/edit

**Comment by SallyMcGrath** [comment]
I think we need to update it

Also I made this the other day (Rainbird wasn't down, but it seemed down) https://docs.google.com/forms/d/e/1FAIpQLSe3hzEgI2EWJJCXuxBY-5Djm7Rw6P3UeEwSxwe1LlQ1_Qiy_Q/viewform

It was actually pretty useful to get the clarity.

**Comment by kfklein15** [comment]
[Meetings notes](https://docs.google.com/document/d/1Ql3mxQSRYXm9S_fnY_9d57VOlqlYIfma-L1xNedjHco/edit#)

**Comment by kfklein15** [comment]
[Mapping of data sets](https://docs.google.com/spreadsheets/d/1Ts6ZCkLbkobRfupEGG2eapFOKYT-TFGbW7BjrN3qH2E/edit#gid=0) from different systems (Rainbird, ITD, PC and what WMCA needs).

Next steps is to re-engineer the data needed by WMCA and origins, updates, etc. If anyone has other suggestions, let me know.

**Comment by SallyMcGrath** [comment]
I have a ton of thoughts on this as you know, Karen! :) Bang it on the agenda for Programme Team
