### ISSUE TITLE
Create video to Combine Community Safety training with volunteer experience

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#133]

**Comment by alecmccrindle** [comment]
Hi @lilianabermudes - any actions needed here?

**Comment by lilianabermudes** [comment]
Hi @alecmccrindle let's go through this together tomorrow :)

**Comment by lilianabermudes** [comment]
@alecmccrindle, what would be a reasonable deadline for this?

**Comment by alecmccrindle** [comment]
Maybe end of the week?

**Comment by lilianabermudes** [comment]
@alecmccrindle can we have a look at it?
