### ISSUE TITLE
Actions for Centra hackathon

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1332]
## Background
CYF needs to find cloud-based problems can be addressed by a one-day hackathon with 10-20 Centra cloud devs with 10-15 CYF trainees.

Date for cloud-based Centra + CYF hackathon is Friday 12th July
The deadline to share the challenges with Centrica is EOP Thursday, the 4th July. 

If we don't have any challenges, Centrica will find its own problems to solve and bring the CYF trainees along.
Note: Centrica asked for an AWS environment to be set up. There is a cost, so we need to keep that down. I have let 
[@Pedro](https://codeyourfuture.slack.com/team/U3XTPVDS7)
 know.

## Acceptance criteria

- [x] Share brief in devops
- [x] Ensure the AWS environment brief is shared by EOP Thursday
- [x] Share info with Centrica
- [x] Any further tickets made

### Owner
@alecmccrindle 

### Stakeholder
@MarianaVazquezCYF @lilianabermudes 

### Approvers
@pedroguima

**Comment by kfklein15** [comment]
**Suggestions** 
Backups of our products
Separate DevOps access per product
Visualise how many times pods are down (or monitoring in general)

Write a briefing (format tbc OR use Twilio)
Share on DevOps channel and with Alec

**Comment by kfklein15** [comment]
First Draft

**Project: Motoring systems for the CodeYourFuture Infrastructure
Background**
At CYF we have multiple products that are being maintained by volunteers. We also have a high turnover of volunteers that stay for 3-6 months and then leave. From a reliability perspective, it would be great if we had an easy monitoring system that could help us identifying if anything is working well, not so well, broken.

**Requirements**

- Use a monitoring system or a combination of them (i.e. Grafana, Prometheus, etc)
- The monitoring system should not incur in any cost (if cost is a must have, how can it be the least possible)
- Monitoring should include infrastructure, back-ups, e-mails (AWS and student e-mail system), etc.
- Monitoring should show:
      - the status of each task    
      - average
      - last updated

**Comment by lilianabermudes** [comment]
Nice!

@MarianaVazquezCYF  Do we have a registration list for trainees? We need to keep promoting it, and asking people to register :-)
