### ISSUE TITLE
ZA Old Mutual LI post

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1363]
[Final edit here. 
](https://docs.google.com/document/d/1w2VzaOFFu4SnrBr5p7CaSEsmtGaqsbJFanEUK8haEeU/edit#heading=h.iz7wih1284ko)

Need to post it next.

**Comment by ShaunCYFSA** [comment]
Hi @alecmccrindle ,

Do we re-open this ticket? 
OM requested a mock-up of the post for review before sign-off.
