### ISSUE TITLE
Winter Seminar owners

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1390]
[Follow up to ensure decisions are being made](https://docs.google.com/document/d/11Tk7IQWeuTFoS2YVLndH0zAdbEYFsyPBzcaVzlV3tHE/edit#heading=h.89g5zms45pfj)

**Comment by SallyMcGrath** [comment]
No progress for 3 months, blocked

**Comment by alecmccrindle** [comment]
**Progress update**

- Date and venue decided
- 2 rounds of invites sent
- Accommodation decided

Closing this ticket.
