### ISSUE TITLE
Review Complaints Policy

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1394]
### Background

Our current draft was reviewed by J&A. We need to review their changes and ask them questions.

- [Our DRAFT.](https://docs.google.com/document/d/1RkpVuzsf72OUQHdySC1IMrs9tDfg_6kKmEmR_o_3h40/edit#heading=h.f1sjudcjf0en)

- [Their VERSION ](https://docs.google.com/document/d/1c7VndDe3WVVrnBU7AFKCi-49ZUetLzqM/edit)(new).

### Acceptance criteria

- [ ] Alec to do some research 
- [x] Alec to review it
- [x] Alec to ask questions/make comments
- [x] Lili and Alec to return our to them

### Owner

Alec

### Stakeholder

Joy/ Atyia

### Approver

Liliana

**Comment by lilianabermudes** [comment]
@alecmccrindle what was the research you were going to do here? This is the first point of the acceptance criteria.

**Comment by alecmccrindle** [comment]
Reviewed - @lilianabermudes you're next :)

**Comment by cynthimicallef101** [comment]
@alecmccrindle is this complete?

**Comment by lilianabermudes** [comment]
Sent it to Joy 27/11
