### ISSUE TITLE
Review Safeguarding Policy

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1395]
### Background

J&A reviewed our draft. Now we need to review their suggestion and make comments and ask questions.

-[ Our DRAFT](https://docs.google.com/document/d/1RkpVuzsf72OUQHdySC1IMrs9tDfg_6kKmEmR_o_3h40/edit#heading=h.f1sjudcjf0en)

- [Their version (NEW)](https://docs.google.com/document/d/18rF6zM81uNrhGfmlu2QGqCg1kcZ4ypy2/edit)

### Acceptance criteria

- [x] Alec to review it and make comments/ask questions
- [x] Alec and Lili to return it to J&A

### Owner

Alec

### Stakeholder

Joy/Atyia

### Approver

Lili

**Comment by alecmccrindle** [comment]
Made my review @lilianabermudes

**Comment by lilianabermudes** [comment]
I sent the documents with our comments to J& A on July, 29th - we need to wait for them.

**Comment by lilianabermudes** [comment]
@alecmccrindle Joy returned the doc with comments: https://docs.google.com/document/d/18rF6zM81uNrhGfmlu2QGqCg1kcZ4ypy2/edit

**Comment by SallyMcGrath** [comment]
No progress for 3 months, blocked

**Comment by alecmccrindle** [comment]
Reviewed. I can confirm all changes made in the last round were based on the most recent comments from Joy. 

Link to the [Safeguarding policy](https://codeyourfuture.io/about/safeguarding/).

Closing for now.
