### ISSUE TITLE
Cohort founders

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1404]
Bring 5 people to become volunteer leaders - (1 of them should be a grad) in London and Sheffield - Mariana

Engage 3 people to continue as volunteer leaders (1 of them should be a grad) in London and Sheffield - Halden

https://docs.google.com/document/d/1S6wKJAPLnq8-x8u0WyB0kVCSt6ZfOmwhEzueSc_9Zc0/edit

**Comment by haldenb** [comment]
had first meeting with Rob and Emily, they are good to go, yet to onboard Abdi, Ellie and Gayle

**Comment by MarianaVazquezCYF** [comment]
Hello Halden, this is a milestone not a ticket, because cohort founders is a huge project! I already have my tickets regardless sheffield and London, therefore I will unassigned this ticket to me! Xx :D

**Comment by MarianaVazquezCYF** [comment]
I have created the cohort founders milestone, I would suggest separating this ticket into:

1. 1st meeting with candidates LDN - Halden - and that's done
2. 2nd meeting new candidates LDN - Halden - in progress
3. Engaging activity with candidate - LDN - Halden - backlog 

and everything should be in the milestone: Cohort Founder LDN ( I have also created one for Sheffield)
