### ISSUE TITLE
DLP community building/ volunteer experience

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1428]
### Background

DLP struggle with community, brings some good vibes and engagement.

### Acceptance criteria

- [ ] Engagement: Foster a sense of community among current volunteers through regular check-ins, updates, and engagement activities.

- [ ] Feedback: Collect and relay feedback from volunteers to the Programme Manager to improve the volunteer experience and programme effectiveness.

### Owner

@halden

### Stakeholder

@halden

### Approver

@halden

**Comment by haldenb** [comment]
@AmyCYF This is taken straight from my job description. I was thinking of booking some calls with volunteers to find out what the DLP volunteer experience is like next week and start working on this?

**Comment by AmyCYF** [comment]
Go for it.
