### ISSUE TITLE
Update corporate volunteering options

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#144]

**Comment by lilianabermudes** [comment]
For the meeting Barny and I are going to join on Tuesday, let's have this deck updated: https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.g16a3027db60_0_124


But :) to update it, we only update info on the [spreadsheet](https://docs.google.com/spreadsheets/d/1VMJ3gFIG9HgqCMpOJ3uPlzbt3vkMJ7rHDJLZBHc0QPQ/edit#gid=1590110171)

I tagged you both. Let's focus on PD coursework review and career mentors ROels that can be done during the week

**Comment by Barny-6** [comment]
Have updated spreadsheet. Will book meeting with Karen to discuss CVs

**Comment by kfklein15** [comment]
Is this still pending? :)

**Comment by lilianabermudes** [comment]
Nope - closing it now :)
