### ISSUE TITLE
Risk X Emergency training - CYF team

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#145]

**Comment by lilianabermudes** [comment]
HI, @SallyMcGrath [drafted the presentation](https://docs.google.com/presentation/d/171epgtNLBtUu1nMkNTPDHZZepj12UyQWixwwqml-xkM/edit#slide=id.g2433cb0310f_0_22) for Tuesday. Please add, or change anything you need. It's better hat you lead it :)

@gbencci tagging you as you won't be around next week. Any comments?

@kfklein15 FYI! Please share any thoughts too, if any

**Comment by gbencci** [comment]
cool, left some comments.. if was more like ideas to make it interactive

**Comment by gbencci** [comment]
@lilianabermudes are we good to close this ticket?
