### ISSUE TITLE
Sort b-roll for volunteer

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1456]
## Background
We have a video volunteer. He needs b-roll. Need to go through all the new stuff, and maybe choose some of the older stuff. 

## Acceptance criteria

- [x] Check cards 
- [x] Check old stuff
- [x] Share over Wetransfer or other means

### Owner
@alecmccrindle 

### Stakeholder
@alecmccrindle 

### Approver
@alecmccrindle

**Comment by alecmccrindle** [comment]
Asked Ralph for the key interview material and if ZA can use old Ryno interview.

**Comment by SallyMcGrath** [comment]
No progress for 3 months, moving to blocked

**Comment by alecmccrindle** [comment]
Completed.
