### ISSUE TITLE
Holborn proposal

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#1469]
### Background

We need to write a propsal to the landlords at holborn to use the office between 10-5 from September

### Acceptance criteria

Must include 

- impact 
- Assign 'key holders' - those responsible -
- Share Risk Assessment
- A to do list before leaving

### Owner

@halden

### Stakeholder

@halden @amy 

### Approver

German

**Comment by AmyCYF** [comment]
@haldenb this looks good. 

Shall we divide and conquer? I can write impact and to do list?

**Comment by haldenb** [comment]
https://docs.google.com/document/d/1N3Jx5wYM7YTIx5q1fn4weKcfyJArXNQdtwqkcC31bEc/edit

Amazing lets do it here - This is impact for DLP and ITD, let me know and I can add some on ITD impact if you would like :)

**Comment by AmyCYF** [comment]
waiting for feedback from @gbencci 
https://docs.google.com/document/d/1N3Jx5wYM7YTIx5q1fn4weKcfyJArXNQdtwqkcC31bEc/edit#heading=h.8ls25keeubwv
