### ISSUE TITLE
Apply for Grant - Community Fund

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#148]
- @gbencci and @lilianabermudes to have a look

https://www.tnlcommunityfund.org.uk/funding/programmes/bringing-people-together#section-3

**Comment by gbencci** [comment]
Ideas:
- Cover 5 regions in the UK and within it 12 hubs
- Access to 90% of people living below poverty line in the UK
- Digital Literacy program and ITD across (bonu is SDC)

**Comment by lilianabermudes** [comment]
- @gbencci, this is closed to new applications ?! :( 
https://www.tnlcommunityfund.org.uk/funding/programmes/bringing-people-together#section-3

**Comment by gbencci** [comment]
We have these ones instead:
https://www.tnlcommunityfund.org.uk/funding/programmes/the-uk-fund

https://www.tnlcommunityfund.org.uk/funding/programmes/people-and-places-large-grants

https://www.tnlcommunityfund.org.uk/funding/programmes/people-and-communities

**Comment by lilianabermudes** [comment]
@gbencci for this one https://www.tnlcommunityfund.org.uk/funding/programmes/the-uk-fund#section-1 we need:
1. to attend the webinar (I registered, so I'm on the waiting list)
2. Only after we send an email can we book an individual chat
3. If they like us, they will send the application form

**Comment by kfklein15** [comment]
This was done, right, @lilianabermudes ?
