### ISSUE TITLE
ITD FAQ v2 update

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1480]
### Background

Need to expand more on new course details in website. 

- [Use this risks doc](https://docs.google.com/spreadsheets/d/1ahh2Izd8IRTccV5Eij2keLEeQBs1YCbnsOrZ1Yf5Ooc/edit?gid=0#gid=0).
- [And new course goals](https://docs.google.com/document/d/1a-27M-O8gxE8F-FGAtGhLlkahkrYgnUxnURaJ8oSoow/edit#heading=h.hqgd5pmuceql). 

### Acceptance criteria

- [ ] Update FAQ
- [ ] Share with team
- [ ] Finalise website

### Owner

alecmccrindle

### Stakeholder

alecmccrindle

### Approver

alecmccrindle

**Comment by SallyMcGrath** [comment]
@alecmccrindle is this done? It seems urgent as the course is opening for the second time in 2 weeks

**Comment by alecmccrindle** [comment]
This was done. Do you think you could [review the FAQ](https://codeyourfuture.io/become-a-student/)? Thanks.

**Comment by SallyMcGrath** [comment]
> This was done. Do you think you could [review the FAQ](https://codeyourfuture.io/become-a-student/)? Thanks.

If it's done can you close the ticket?
