### ISSUE TITLE
Course update v02 on website

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1481]
### Background

[V01 done](https://codeyourfuture.io/become-a-student/). 
Now need to add details and improve copy and design for for courses on website. 

[Use this doc](https://docs.google.com/document/d/1a-27M-O8gxE8F-FGAtGhLlkahkrYgnUxnURaJ8oSoow/edit#heading=h.hqgd5pmuceql).

### Acceptance criteria

- [ ] Write new copy
- [ ] Add it to website
- [ ] Share and update

### Owner

alecmccrindle

### Stakeholder

alecmccrindle

### Approver

alecmccrindle

**Comment by SallyMcGrath** [comment]
@alecmccrindle is this done? It seems quite urgent for the website to be updated

**Comment by alecmccrindle** [comment]
This was done so closing the ticket. I am doing another review and update atm based on the new closing dates (26th or 28th).
