### ISSUE TITLE
Make new ITD video

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1484]
## Background
Need to update [this 2020 video](https://vimeo.com/638708847) with this [new script](https://drive.google.com/file/d/1rdT5-pH0Hd0Bk1aKE1viqCVQ3KtVBH0u/view?usp=sharing) (and new video content?).

## Acceptance criteria

- [x] Check b-roll for relevant content
- [x] Make new video in AI tool / Canva
- [x] Share ticket

### Owner
@alecmccrindle 

### Stakeholder
@alecmccrindle 

### Approver
@alecmccrindle

**Comment by SallyMcGrath** [comment]
What is the progress of this, @alecmccrindle . What is the expected delivery date?

**Comment by alecmccrindle** [comment]
Completed.
