### ISSUE TITLE
Community health meetings

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#1487]
## Background
[Need to measure communities using this doc](https://docs.google.com/spreadsheets/d/1ycUYjkc1E68yS0tILouPL5Nf_KTxEBLgAoqiV_jvi50/edit?gid=558327456#gid=558327456). 

London already done. [Notes here](https://codeyourfuture.slack.com/archives/C074N1XJFA4/p1722433756779339). 

## Acceptance criteria

Arrange meetings with:

- [x] Glasgow with KFK
- [x] NW (with Sally?)
- [x] WM with Azin
- [x] ZA with Shaun

### Owner
@alecmccrindle 

### Stakeholder
@MarianaVazquezCYF 

### Approver
@alecmccrindle

**Comment by SallyMcGrath** [comment]
Nothing can realistically be in progress for three months

moving this to backlog

**Comment by alecmccrindle** [comment]
Completed.
