### ISSUE TITLE
Define what's a successful case for CYF

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#149]
- Alec, Claire, g and I discussed if we should consider people who found a job (but did not graduate with us) as part of our positive stats/outcome
- This is our proposal: [https://docs.google.com/document/d/1hCvQ0RKbuT-gplUFKONH6lNR8Jn6-606EZOvaoxIEHM/edit](url)

- What are your thoughts @Barny-6 @SallyMcGrath @kfklein15?

**Comment by Barny-6** [comment]
Added a comment :)

**Comment by kfklein15** [comment]
Looks good to me.

**Comment by lilianabermudes** [comment]
- @ClaireBickley @gbencci @alecmccrindle can each one of you please review it and add your comments? The team shared their thoughts

**Comment by gbencci** [comment]
@ClaireBickley it works when you copy/paste the link
https://docs.google.com/document/d/1hCvQ0RKbuT-gplUFKONH6lNR8Jn6-606EZOvaoxIEHM/edit?pli=1

**Comment by gbencci** [comment]
left some comments.

**Comment by lilianabermudes** [comment]
@gbencci - I also made some comments.

Who makes this decision? Probably us and @ClaireBickley, as it's related to reporting.

**Comment by kfklein15** [comment]
Has this been done?

**Comment by lilianabermudes** [comment]
We've made some progress and then stalled. @ClaireBickley, this is a good one for our Ops Board

**Comment by gbencci** [comment]
sorry, this was my fault, apologies. I made a suggestion to align it according to what we are trying to do in the Program. Graduate people only when they get jobs.

**Comment by ClaireBickley** [comment]
are there any actions from this @lilianabermudes? Can we close this? Let me know if any updates to Global Trainees are needed.

**Comment by lilianabermudes** [comment]
Hi Claire, I'm closing it as it's graduation = employment. And reporting dates will be discussed on the new ticket
