### ISSUE TITLE
Present New Welcome Session to the team

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1494]
### Background

We've reworked the content of the welcome session.Now we need to present it to team, next weekly meeting.

### Acceptance criteria

- [ ] Present it to the team
- [ ] Get feedback
- [ ] Incorporate feedback on the same day

### Owner

Halden

### Stakeholder

Team

### Approver

Liliana

**Comment by haldenb** [comment]
Awesome shall I present this on Tuesday?

**Comment by lilianabermudes** [comment]
Yes!
