### ISSUE TITLE
CF Training

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#150]
Hi @barny and @kfklein15

What are your thoughts about CYF trying to get a fee from CF for the activity they will do with us? Last week we added slide 12 last week [https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.g18142190d61_2_1](url)

The goals get companies to pay something to host activities with CYF 

Let me know your thoughts! Thank you

**Comment by kfklein15** [comment]
I like the idea, @lilianabermudes, and happy to try it, but will let @Barny-6 give us his overview too.

**Comment by Barny-6** [comment]
Absolutely, a fee would be great!  @lilianabermudes that link doesn't work for me (: It might be hard to get a fee considering they're already committed, any thoughts on how we approach that?

**Comment by kfklein15** [comment]
Pilot done for WM5/NW6 online and LDN 8/9 in person. 
The material is good, but needs to be flipped and adapted to fit our hourly slot or 4h CW/prep.

**Comment by kfklein15** [comment]
Yes, should finalise this week with the final handover/meeting.
