### ISSUE TITLE
Tech Leader Talk - The Failures That Brought Me Here with Andrew Hilel - IHX Engineering Lead - Spotify - promote event

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#1507]

**Comment by MarianaVazquezCYF** [comment]
Date: Wednesday, September 25th 5:30 to 6:30 pm
Audience: CYF graduates  + CYF intro to digital applicants - Approx 20-40 attendees
Format: Online 
Name of the event: Tech Leader Talk - The Failures That Brought Me Here with Andrew Hilel - IHX Engineering Lead - Spotify
Agenda: 
Your background and journey in tech
A story of a big failure and what you learnt from it - for reference, we want to replicate the format of[ Fuck Up nights](https://en.fuckupnights.com/) and create a culture around resilience 
Advice for CYF graduates and intro to digital applicants on career development and skill building
Respond to Q/A

**Comment by SallyMcGrath** [comment]
done
