### ISSUE TITLE
New London Space - Business Rates

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1510]
### Background

From German:

When you have a chance can you find out if we could get the full business rate relief if we move office to Brixton?

You would need to contact Lambeth council and maybe fill a couple of forms online.

If you can let us know by next week that would be great.

This is lower priority than any task you get from Lili, so let me know if you can't do it and I'll work on it. 

Thanks,

### Acceptance criteria

We will need to move out from the London office in Holborn in December, but we might have a good lead a for space in Brixton.

### Owner

Cynthia

### Stakeholder

Liliana

### Approver

German

**Comment by cynthimicallef101** [comment]
Two applications required to be submitted:
1. Mandatory Relief 80%: Print forms attach email with lease to email: businessrates@lambeth.gov.uk. The inspector will need to visit the building to confirm it is being used for charitable purposes. 
2. Discretionary Relief 20%: This application goes off to a different panel. 20% lease will need to be paid first. If application is successful, CYF will get a refund. 
3. Email sent to businessrates@lambeth.gov.uk to enquire about criteria for discretionary relief.

Both applications are saved in the Ops folder: 
https://drive.google.com/drive/folders/1qBQf8ynsFk4P03LnlS6op-WiuqdXVnJM)

**Comment by lilianabermudes** [comment]
Thank you!

Do we need any info from us at this stage?

**Comment by cynthimicallef101** [comment]
At this stage no. German said we won't apply just yet. He wants to get all the information on how to get the discretionary 20% relief first. I am waiting for a reply....but the email I sent will be passed to someone else first. The discretionary relief application does indicate what they are looking for to grant the 20% relief.

**Comment by cynthimicallef101** [comment]
21.10.24 Sent an email requesting a reply from Lambeth council regarding criteria required for CYF to be eligible for the 20% discretionary business rates relief.

**Comment by cynthimicallef101** [comment]
Ben Wintour of Integrate Spaces confirmed - It is one unit with one assessment and the only charity that applies for business rates and relief is Trees for Cities as they are the Lease holder. Issued closed.
