### ISSUE TITLE
Identify users who should keep CYF addrees

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1520]
### Background

There're 79 people with an active CYF email address.

Can everyone please go through this list and help identify the ones we should keep and the ones we should suspend, please?

(https://docs.google.com/spreadsheets/d/1_0Kl3k1F267UTUQ20NEYgzkkIClKtseufniWwZyYSA4/edit?gid=1617052362#gid=1617052362)

### Acceptance criteria

- [ ] All users should have been identified and labeled. 

### Owner

Lili

### Stakeholder

CYF Management 

### Approver

Lili

**Comment by AmyCYF** [comment]
Done

**Comment by kfklein15** [comment]
Reviewed it.
Added names of who some volunteer work with - so people can also easily filter it

**Comment by alecmccrindle** [comment]
Reviewed from me. Design volunteers quiet atm. If they don't restart I'll remove them in a month or so.

**Comment by MarianaVazquezCYF** [comment]
reviewed it!
