### ISSUE TITLE
Discuss Trainees Expenses

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1522]
- Karen has been approving expenses but this is something Ops can do.
- Let's chat about it

**Comment by cynthimicallef101** [comment]
I think I figured the approval process out. I need to:
1. Sort out different forms for London and NW. 
2. Get help from Leanda, which is the right form.

**Comment by SallyMcGrath** [comment]
Is this handed over @cynthimicallef101 ?
