### ISSUE TITLE
Check Motorola Grant

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1523]
### Background

We still have some money from the grant to spend until 2024.

We need to confirm if it's okay to use some of it to hire a North West grad for a project, as the contract is broad. 

### Acceptance criteria

- [ ] Review the contract
- [ ] Confirm where the money can be spent (we know it's to cover NW and Sheffield activities)

### Owner

Cynthia

### Stakeholder

Lili

### Approver

Lili

**Comment by cynthimicallef101** [comment]
I cannot locate the 2023 Motorola contract. I have the 2024 one, but not the 2023 contract. Thank you

**Comment by cynthimicallef101** [comment]
@lilianabermudes The "Authorized Purpose" as stated in the 2023 contract is very general. It does not even state NW and Sheffield. 

**Here is the wording:**

In awarding this grant, it is our understanding that the funds will be used for the following purpose (the
“Authorized Purpose”). I would say yes, a grad can be employed to use the remaining 2023 funds. 

CodeYourFuture (CYF) is a volunteer-led coding school that provides training and support to
secure jobs in the tech sector for socially excluded adults (18+) including but not limited to
refugees, asylum seekers, single parents with low income, people with mental or physical
disabilities, ex-offenders, homeless and long-term unemployed people. CodeYourFuture is
currently working with over 180 trainees across the UK. 70% of CodeYourFuture graduates find
employment in the tech industry within 6 months of course completion.
