### ISSUE TITLE
Check Data Protection fee - direct debit due to be collected ICO:00017796718

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1524]
### Background

We received an email at ops@ about Data protection fee.

The message says it's going to be a direct debit. Just need to update Leanda. (not sure where/how the debit was set up)

### Acceptance criteria

- [x] Communicate to Finance
- [x] Any further action

### Owner

Cynthia

### Stakeholder

Leanda

### Approver

Cynthia

**Comment by cynthimicallef101** [comment]
Already forwarded the email to Leanda and finance. I don't think there is any further action. I looked into it, we pay £40 per year and that's still valid.
