### ISSUE TITLE
Create central management for venues

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1526]
### Background

Hi Cynthia,

This is something small, but key. We need to organise the information and management of the use of spaces across CYF.

My suggestion would be to create one document (spreadsheet maybe) with all the information about the spaces we use in each region: rules of use, fobs/keys, times, insurance, contacts, etc. 

### Acceptance criteria

- [x] Create doc
- [x] Identify the key info we need
- [x] Share it the Ops channel

### Owner

Cynthia

### Stakeholder

German

### Approver

Liliana

**Comment by cynthimicallef101** [comment]
Venues Used by Code Your Future spreadshseet Created. 

https://docs.google.com/spreadsheets/d/1KME3B9O4hlvIob9wgZoKGkouiyTu7moqxyIeN_-dwQw/edit?gid=251747869#gid=251747869

**Comment by cynthimicallef101** [comment]
Document created. In use and shared with the team, viewing only by Internal Staff.
