### ISSUE TITLE
Register as a supplier with Centrica Global Procurement

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1528]
On emails

**Comment by cynthimicallef101** [comment]
Meeting with Centrica moved to Tuesday 15th October. Ariba system was not working last week, we have to do it together.

**Comment by cynthimicallef101** [comment]
A meeting with Centrica on Tuesday 15th Oct proved unsucessful again. There are issues the Ariba system with accepting Code Your Future and they cannot figure out why. Issue raised with Ariba. Kim at Centrica will get back to me.

**Comment by cynthimicallef101** [comment]
Created account with Ariba. 
2 questionnaires to complete: 1. Supplier Registration Questionnaire 2. Procurement Risk Questionnaire

**Comment by cynthimicallef101** [comment]
Questionnaires submitted.
