### ISSUE TITLE
Send Proposal to Cisco

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#153]
Hi @haldenb @MarianaVazquezCYF , I suggest you work together on a draft email to send to Sean tomorrow. Split the asks into short bullet points.

Please consider the corporate volunteering offer https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.g18142190d61_2_1

I can review it when you finish :)

**Comment by MarianaVazquezCYF** [comment]
Hello, we didnt prepare any email ... 

I am a little bit lost here, 

**what would be the exact next step?** @lilianabermudes 

a) Tell him in the email that we have programs of corporate responsibility and that we could create a program specific for cisco and organise a call with him or with the personnel responsible for social responsibility.

b) ask him, if there were people who were interested in volunteering from CISCO and organise a call with the people who are interested in volunteering? or promote again our volunteer opportunities? 

c) Tell him that in the tuesday call, we can explore a full package combining recruitment, branding and corporate volunteering? 

Do you know if you have a template email that we could use for your previous calls?

**Comment by lilianabermudes** [comment]
The idea is that you and/or Halden work together on drafting an email to send to Sean based on what you presented in the call. You asked for support with four areas, so could you try to create bullet points describing each one, telling him the options to get involved. 

Then, he will need to discuss it with his team, and if needed, we can book a second call.

Try to write a draft (not long :), and  I'm happy to review it.

**Comment by lilianabermudes** [comment]
Reviewed! :)
