### ISSUE TITLE
Invite CYF refugees to TENT Mentorship

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1536]
### Background

Every year, we partner with TENT to offer mentorship opportunities to our community.

We received the updated info about the programme, so it's time to share it with the community.

### Acceptance criteria

- [x] Draft email/comms to be sent to alumni, grads
- [x] Review it 
- [x] Send it by email, weekly newsletter and Slack post

### Owner

Azin

### Stakeholder

Karen

### Approver

Lili

**Comment by AzinYad** [comment]
I have post a thread on slack #cyf-announcement about Tent Mentorship Program
Also I add it on this week Newsletter :
https://docs.google.com/email-layouts/d/1dfdjAhus5eW92fLteUHgzzg7yaOWXdDq_sgXcURnKpg/edit

I don’t  think we need to resend this again by email, what do you think @lilianabermudes?

**Comment by lilianabermudes** [comment]
Thank you, Azin.

No, not need to follow-up anytime soon.
