### ISSUE TITLE
Final review JD - regional role

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#154]
- This draft has been reviewed by the consultants [https://docs.google.com/document/d/1D1-YEUom1zPJmfKsQYDLxxiMv3ho84xX/edit](url)
- Karen & Sally can you just have a quick look? In parallel, they are also doing a final review. 
- We should have it open until the end of this month

**Comment by kfklein15** [comment]
Looks good. I am unsure about this phrase: "Experience in managing teams, including recruiting, training, and providing ongoing support".  Which team will they be managing? And why do they have to have recruitment experience? Just didn't seem to be something clear in the description.

**Comment by lilianabermudes** [comment]
Thank you, Karen. I believe they added that thinking on volunteers. Let me think if there's a way of putting it
