### ISSUE TITLE
Review copy to be added to volunteers materials

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#155]
Hi both @german and @alec - I need you both to give your individual review on this :)

I would like to add something like this [https://docs.google.com/document/d/1Nsi9vwupnX94hOvymM-YfXDoWahXiJXe8DLlcPKpqtA/edit](url) to volunteers materials [website -to be discussed with Alec -, Welcome Presentation and onboarding doc]

Do you think it sounds too negative, too harsh, too scary?

**Comment by gbencci** [comment]
I don't think it's scary at all. It's realistic and honest

**Comment by kfklein15** [comment]
Has this been done?
