### ISSUE TITLE
List of Employability requirements for PD syllabus

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#16]
Create Emp. requirements doc for what graduates need before graduation on PD side

**Comment by ElizabethlawalCYF** [comment]
- Communication Skills 
- Problem Solving
- Time Management 
- Teamwork Skills 
- Confidence
- English Language 

Here the soft skills we are assessing

**Comment by kfklein15** [comment]
@Barny-6 @ElizabethlawalCYF , I am working with Lara to do an interview with 5 grads and 5 volunteers about the necessary soft skills. Once this has been done and we have the results with you, I'll share them here too. 

The idea of to have the main pillars and then sub-categories - which hopefully will include all the above mentioned by youboth.

**Comment by gbencci** [comment]
@Barny-6 can we close this ticket or is there anything pending?
