### ISSUE TITLE
Password Manager Research

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#160]

**Comment by ClaireBickley** [comment]
we have a trial of Nordpass - looking for people to test it with me

**Comment by kfklein15** [comment]
@Dedekind561 also did a trail with 1Password. Might be worth checking with him.

**Comment by ClaireBickley** [comment]
yes, we liked it but they are V expensive, Nordpass are cheaper, but still not cheap
still interested in other options that don't cost 😆

**Comment by SallyMcGrath** [comment]
Is this in progress? It's 3 months past due
