### ISSUE TITLE
Add laptop loan copy to ITD

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#167]
Need to update ITD with new laptop policy before we reopen the next cohort. 

Can be updated when we find the new Grasshopper.

**Comment by gbencci** [comment]
@alecmccrindle could you please close this ticket if completed? Here since July

**Comment by alecmccrindle** [comment]
Yeah done, thanks. Will check other old global tickets now.
