### ISSUE TITLE
Update the personal circumstances form

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#168]
The [PC form](https://docs.google.com/forms/d/1cduSAlHe6wJ2eXVQMPceYl1wnY5aCJ4pOd5-UuXjjcc/edit) hasn't been updated for many years. We need to make sure that:

- Is up-to-date with current regulation
- It asks the right questions
- Agree whether we should connect it with Rainbird
- When should it be sent (before the end of ITD?)
- Make it easy to copy the information to Global Trainees

**Comment by gbencci** [comment]
@ClaireBickley @lilianabermudes could you please add any other links or relevant information to get the ticket ready?

**Comment by ClaireBickley** [comment]
this is the barriers to access form Nirmeet has created https://docs.google.com/forms/d/e/1FAIpQLScoDOmdwqnkrbUsJ6nesgT30K516-axFj2HVFfMAeDDJSoGfA/viewform

**Comment by ClaireBickley** [comment]
current PC form https://docs.google.com/forms/d/1CCx9W-VgKBh3h3scEMcPFv43IuJwkhdATCq-MZo8i1U/edit?usp=sharing_eil_m&ts=64b6b83d&urp=gmail_link

**Comment by gbencci** [comment]
We had a previous ticket with the same ask:
- [Meeting notes](https://docs.google.com/document/d/1Ql3mxQSRYXm9S_fnY_9d57VOlqlYIfma-L1xNedjHco/edit#heading=h.tg4poflu888a)
-

**Comment by SallyMcGrath** [comment]
I will take this forward as part of the new Programme Team.

**Comment by SallyMcGrath** [comment]
Note, this will be released for testing tomorrow
