### ISSUE TITLE
Maigot Trust - Product Grant use

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#170]
**Background**
We have been given a grant of £15,000 to invest in product development.
Ticket #122 is the application one
Money must be spent within 2023.

[Map of the possible products](https://docs.google.com/spreadsheets/d/1Ki1vllTJS7mcYdrc7gcdmQppHxOSqtlzkNrurKwENIU/edit#gid=0) to be worked one, their benefits and high level t-shirt size estimation

**Possible issue**
- Lack of Tech Lead (or not enough money to hire one)

**Comment by kfklein15** [comment]
@SallyMcGrath , could you please go through the [mapping](https://docs.google.com/spreadsheets/d/1Ki1vllTJS7mcYdrc7gcdmQppHxOSqtlzkNrurKwENIU/edit#gid=0) I did and give me your opinion on which one you believe we should prioritise. We can arrange a call if needed.

**Comment by SallyMcGrath** [comment]
Done and comments left on doc

**Comment by kfklein15** [comment]
We'll go with the offboarding. Waiting for the final blessings of the [wider team.](https://codeyourfuture.slack.com/archives/CB8NTK7PW/p1690296711542409)

If anyone knows of a tech lead and suggestions of devs we could/should hire would be great.
