### ISSUE TITLE
CYF External events and conferences

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#171]
Ross our social media intern is working on this document: https://docs.google.com/spreadsheets/d/1Q_bEzgPr_o6y224NCMSWxp8jzFPVIr3hkz1Xpy03Yp0/edit#gid=0 with the conferences in Europe that talk about diversity! He is writing the submission, and the responses of the submissions are here: https://docs.google.com/document/d/1zft_yK8G4g-YIESIlc9OIStdgw23AJoTa8FsIMvjtiU/edit

**Comment by SallyMcGrath** [comment]
@MarianaVazquezCYF s this ticket is done please Close it by pressing the Close button. The button is purple.
