### ISSUE TITLE
CYF Internal meet ups

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#172]
London Meet up: helpes: Sami, Aladin, Alvaro and Hinde
Meet ups will be the first Thursday of every month! we have the agenda for the next months: 

Agenda of topics:
Thursday 3 August: Soft Opening
Thursday 7 September: My ups moment!
Thursday 5 October (I will not be here, so we need a host): Black history month- Black Excellence in tech (btw should we change this name)
Thursday 2 November: Lessons of diversity from CYF
Thursday 7 December: Winter Social

To do: 

- [ ] Find a venue to host events
- [ ] Find a food sponsor

**Comment by MarianaVazquezCYF** [comment]
Manchester: 

- [ ] Find the team that wants to help with these meet ups 
- [ ] Define agenda of events
- [ ] Find a food sponsor

**Comment by MarianaVazquezCYF** [comment]
Glasgow : 

- [ ] Find the team that wants to help with these meet ups

- [ ] Define agenda of events
- [ ] Define the space and food sponsor! 
- [ ] Define with @caromelendezl what things we need to do

**Comment by MarianaVazquezCYF** [comment]
Birmingham: 

- [ ]  Find the team that wants to help with these meet ups

- [ ] Define agenda of events

- [ ] Define the space and food sponsor!

**Comment by SallyMcGrath** [comment]
@MarianaVazquezCYF is this ticket done? Please Close it.

**Comment by MarianaVazquezCYF** [comment]
Definitely not done! just in NW.,, but I will close it and add a new one with different regions
