### ISSUE TITLE
CYF Summit

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#175]

**Comment by MarianaVazquezCYF** [comment]
Hello @gbencci and @lilianabermudes maybe on Monday we can talk in person (instead of tuesday online) to talk more about this: 
So far, my questions will be: 

- [ ] Is this a summit for this year or next year? (if its this year, what will be the main difference between the one at the beginning of the year and the one at the end? ) 
- [ ] What's the objective of this summit? I would say that if is a continuation of the things we talked at the beginning of the year, maybe we need to speak again on: flip classroom, the mission of CYF, employment and the challenges of this year? I also remember we talked about Cloud and Products, but not sure if we had a call to action in the past, more than asking for volunteers 
- [ ] Do we have a satisfaction survey of the pasts summits? 
- [ ] In the past, did you work with volunteers? Or who were the people organising it? 
 -[ ] Place, dates etc (no worries, I can handle this)

**Comment by lilianabermudes** [comment]
Hi Mariana, 

Some thoughts, but we can chat on Monday about this:

- It should happen this year. In my opinion, we should use this time to focus on community building and strengthen the bond among regions. I wouldn't create too many activities to collect insights that we will not do anything with;
- We don't have a satisfaction survey from the past years.

**Comment by gbencci** [comment]
In the past at least half of the organisation was done by volunteers. The main contribution from the team was to find transportation and accommodation (half of the job). The rest was done by volunteers

**Comment by SallyMcGrath** [comment]
What is the status of this ticket? Is it done? Blocked?

**Comment by MarianaVazquezCYF** [comment]
We changed this priority to the cyf job fair! However, this will be for 2024! I will add a new deadline to discuss this during Q1

**Comment by gbencci** [comment]
@MarianaVazquezCYF @alecmccrindle can you please close this ticket and open a new one when you have a proposal on what we are doing? Thanks

**Comment by alecmccrindle** [comment]
Hi @gbencci - thanks for the follow up. 

We have a [new ticket here](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/727) - to set a date and share ideas of the format for discussion. 

I'm closing this ticket as requested.
