### ISSUE TITLE
Guide to launch a class

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#185]
@SallyMcGrath 

These are the three docs we have about launching a new cohort: 

[When to launch ITD](https://docs.google.com/document/d/1KuWZUrL8C7sqyPq5VDiS1TplkFjbF9RHzJrM-0sHOGU/edit#heading=h.kdxzky7gbqs6)
[Understanding Scale at CYF](https://docs.google.com/document/d/1uFl8IadzispLdnlEQ8BOONVGBtDO1U51Izg6Y28M8Ug/edit)
[How we want to launch new groups](https://docs.google.com/document/d/1hztjwbf3Q6_yd8f_wsAamSlvPa4_aDbFFIGj8yU3uJY/edit)

Do you think this can be one guide?

**Comment by kfklein15** [comment]
Hi @SallyMcGrath , can you please comment on why this is blocked? Thanks

**Comment by SallyMcGrath** [comment]
Capacity -- too many other more urgent things have come up -- it cannot make it up the todo list. We already have so many of these guides and they are all failures, so this is not as simple as it seems from this description.

Of course I could just write yet another guide for everyone to ignore, but I think there is probably a better solution. However, I don't have capacity at the moment as I have a huge crunch in both SDC and CYF+

**Comment by gbencci** [comment]
I think with the docs we have it's enough to know how to launch a class, so I would consider this done for now until we identify a problem we have. I would consider this done as a first product
