### ISSUE TITLE
Update - Grad-TechProjects -

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#189]
Karen, this week when doing something else for LDN, I found our a couple of grads in the Global Trainees as "Grad-Tech Projects" who are not in tech projects (like this grad from LDN6). 

I'd suggest you if you could filter all regions to see if we have more people in that situation, that should have the status updated.

**Comment by kfklein15** [comment]
Requested access.

**Comment by kfklein15** [comment]
We saw this was an error. I am closing this.
