### ISSUE TITLE
Capg Data - Column for Contract Year

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#19]
Capg want to have this information on the spreadsheet

- [x] Add contract year column
- [x] Fill in data
@ClaireBickley suggested that I ask @gbencci to confirm the dates for this, because she is unsure when their contract year runs ( is it Jan-December etc. ? )

- [x] Ask Germán
- [ ] Update

**Comment by ClaireBickley** [comment]
this is the doc https://docs.google.com/spreadsheets/d/1SvbchlAL4-N1OkzwjDLBfQjB3rA2ctn1FUyt75fhBns/edit#gid=287767925

**Comment by ClaireBickley** [comment]
@gbencci I think this is the ticket where your input was needed
@emcglackenr1 do you still have any questions for G?

**Comment by emcglackenr1** [comment]
Hi Claire, 
Yes I do. 
If you could have a look over them when you get a chance @gbencci that would be great. We were unsure when the Capg contract dates run.

**Comment by gbencci** [comment]
I replied on this in the spreadsheet, but just to make sure it's covered. The years were already reviewed by Capgemini, so if they are happy with it, then it's fine. The years are a mutual agreement on both orgs

**Comment by ClaireBickley** [comment]
yep this is sorted, thanks
