### ISSUE TITLE
Find Final Project coordination volunteers

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#190]
**Background**
We have decided to implement a new Final Project process #141 . However, to make this happen, we need committed volunteers that can run it.

**What we need**
- At least 1 Project Coordinator - [role](https://docs.google.com/document/d/1zlXJjXvlFYJhRGdsxiuMxOOsnWRL1zkloVBWFbEHJtY/edit)
- At least 1 Outreach person with product/tech background - [role](https://docs.google.com/document/d/1GQm1Ct_RZyenQHaobTjycM81XCX9DXRLrDiIB8-JOZ0/edit)

**What I need help with**
- Communication strategy/materials to promote these roles and find volunteers

**When do we want this done?**
We would like to communicate the new Final Project process by end of September, already with dates for the next one.

**Comment by kfklein15** [comment]
@lilianabermudes , FYI I raised this ticket

@alecmccrindle @MarianaVazquezCYF , I need you :)

**Comment by MarianaVazquezCYF** [comment]
oh perfect! communicating end of september, with the objective to recruit those volunteers right? and if so, when would they start?

**Comment by MarianaVazquezCYF** [comment]
ok, so this is the plan: 

1. During the demo day in London, 2 of September, we will run an info session about final projects volunteers, this is the event: https://www.eventbrite.co.uk/e/final-project-outreach-and-coordination-volunteers-for-code-your-future-tickets-698326743087?aff=oddtdtcreator
2. I will promote this event in our different groups on LinkedIn, slack workspaces, etc!

**Comment by lilianabermudes** [comment]
Hi, just double checking: is this the role we also have open on LinkedIn? :-)

If so, has anyone applied through LinkedIn? Just wanting to know if LinkedIn works for this kind of role 

Thanks!

**Comment by kfklein15** [comment]
I think we might have 1 person to coordinate. We still need one for the outreach side, which should be ideally with a product management background or wanting to learn that bit.

**Comment by lilianabermudes** [comment]
Hi @kfklein15, just an idea. It's possible to promote volunteer jobs at Charity Jobs

**Comment by MarianaVazquezCYF** [comment]
what happened with Aine? and Balaji? (I know Balaji wanted to help more in tech) but he said he wanted to help in everything that we need!

**Comment by kfklein15** [comment]
Balaji is pure tech, I don't think he would enjoy an organisational role tbh. And I could use him better as a tech lead. But he never did the test...

Aine I will talk to this week. Which means I still need 1 person, IF she is the right one and understood the role

**Comment by kfklein15** [comment]
Found them.
