### ISSUE TITLE
Fundraising: Research

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#192]
- [x] Competitive
- [ ] Chart (baseline)

**Comment by MarianaVazquezCYF** [comment]
https://docs.google.com/document/d/1PIOrsOqZ9-ajzpHZF2BL9BVVcatp6YdnfR6a7UOvnCw/edit

**Comment by alecmccrindle** [comment]
[Competitive doc with analysis](https://docs.google.com/document/d/19u5qCpWjlMVPZrjHSvagsFgA4GfatLeIpgSomHhtaK0/edit#heading=h.wphzbodgazhw)
