### ISSUE TITLE
Fundraising: timeline

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#193]
- [x] Write fundraising brief - 9th August
- [x] Brief creative agency - 9th August
- [x] v01 Research - 19th August >
- [x] Brief consultancy - 21st August
- [ ] Internal launch annoucement post - 25th August
- [ ] Share internal strategy doc - 25th August
- [ ] Update donation page - 29th August
- [ ] External launch annoucement post - 29th August
- [ ] v01 content schedule and creation - ongoing - include annual report post / how we make money
- [ ] Idea generation and planning with creative agency - week of the 27th August
- [ ] Update timeline
- [ ] Test, learn and iterate 
- [ ] Idea generation and planning with consultancy - week of 26th Sep
- [ ] Have a party or two

**Comment by SallyMcGrath** [comment]
@alecmccrindle Let's spend 10 minutes understanding how to set tickets on a timeline next week? I think it would really benefit you.
