### ISSUE TITLE
Fundraising: community annoucement

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#194]
- [x] Write it - [here](https://docs.google.com/document/d/1TwzfFQweIoU6Fg2youwZZ--lhZOq9MBAvxFJMIFc_8s/edit)
- [x] Update it
- [x] Write v2 (due to Townhall change)
- [x] Post it

**Comment by alecmccrindle** [comment]
```[tasklist]
### My tasks
- [ ] Draft task 1
- [ ] Draft task 2
```

**Comment by SallyMcGrath** [comment]
Is this in progress, @alecmccrindle?

**Comment by alecmccrindle** [comment]
I've marked it as done, but I need to keep doing it for the next month or two.
