### ISSUE TITLE
Flyer for CYF+

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#199]

**Comment by MarianaVazquezCYF** [comment]
@alecmccrindle I also saw this is not in the website in the category of study! I think it should be there, what do you think?

**Comment by alecmccrindle** [comment]
Hi @MarianaVazquezCYF - not sure we are telling trainees about it. We could do a blog post, for example?

**Comment by SallyMcGrath** [comment]
This has been in progress for a month. Suggest it's not progressing. I've moved it back to ready.

**Comment by alecmccrindle** [comment]
@gbencci - you need any help on this?
