### ISSUE TITLE
Founders Strategy

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#206]
- [x] Campaign ideas (see below)
- [ ] Minimum numbers
- [ ] When do they come in (how many trainees do we need?)
- [ ] Very basic role description? eg. vs ComEx and existing volunteers

**Comment by alecmccrindle** [comment]
[V01 messaging and campaign ideas](https://docs.google.com/document/d/1ZkF5dZxqECqZyvs-WXNfuhuO4kuVZsASQdsaYj6uLQw/edit)

**Comment by alecmccrindle** [comment]
Need a timeline next? @MarianaVazquezCYF

**Comment by MarianaVazquezCYF** [comment]
- [ ] - [ ] Clarify founders role and timelines [Alec McCrindle](mailto:alec@codeyourfuture.io) and [Mariana Vázquez](mailto:marianavazquez@codeyourfuture.io)
- [ ] - [ ] Video and stories from other cohort founders [Alec McCrindle](mailto:alec@codeyourfuture.io) 
- [ ] Update the founder page to start XXXX class campaign. [Alec McCrindle](mailto:alec@codeyourfuture.io)
- [ ] Update google ad messaging - start a class campaign? [Alec McCrindle](mailto:alec@codeyourfuture.io)
- [ ] Run WOM campaign - see below [Mariana Vázquez](mailto:marianavazquez@codeyourfuture.io)
- [ ] Recruit through events*.[Mariana Vázquez](mailto:marianavazquez@codeyourfuture.io) and [Alec McCrindle](mailto:alec@codeyourfuture.io)

**Recruiting through events**
- [ ] Tech for Good meetups - through these events and partners.
- [ ] Any community event before a new cohort starts can be used to recruit. Eg. Demo day, Final Projects.
- [ ] Fundraising events and content can be used to attract new volunteers.
