### ISSUE TITLE
Shortlist of new org name

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#21]
- Second brainstorm with the team + Liliana, Alec and German to narrow down options

**Comment by lilianabermudes** [comment]
@gbencci @alecmccrindle we need to define the next steps

**Comment by gbencci** [comment]
Our latest work here: https://docs.google.com/presentation/d/18nzHu_Z_7kvkFnQQSvotWB6zXEiSMuZEZDrGBHVPfKQ/edit#slide=id.g206547c2a5c_0_6

**Comment by gbencci** [comment]
We need to decide whether we have a shortlist to choose from

**Comment by lilianabermudes** [comment]
Links are save for future discussions
