### ISSUE TITLE
Job Fair

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#212]
https://docs.google.com/document/d/1NFwCC5pT32l7LW17HPhd3GKzAW_x0UlpSs5I_pPgjLw/edit

- 
- [x] Find venues, check this link https://docs.google.com/spreadsheets/d/1ByGe1XfKSbg9i6-qU-Fn25HKsdD_Lq4g0KyeqSuYj-o/edit#gid=0

Find dates for:

- [ ] London 9 - 18 octubre 

- [x] NOW!!! PDF Brochure to send to all our attendees and share in social media
- [x] About CYF
- [x] Who we work with
- [x] How we work with organisations
- [x] Partner stories
- [x] How to get involved in the job fair
- [x] Link to the projects of current cohort
- [x] Would like to participate? Contact us at xxxx
- [x] Invite companies to attend the event, Goal 6 companies present in the job fair. 
- [ ] Invite LND9 and Alumni (Mariana) - Investigate who is not from Capgemini (30% is the goal of attendance)
- [x] Waiting for Capgemini to reply / decide a venue

**Comment by MarianaVazquezCYF** [comment]
still in progress but this is the presentation/brochure! https://docs.google.com/presentation/d/1im1nkHVEhIVGoH20ShkBG_1Mk3_NqP5Um0u8IlIeGv8/edit#slide=id.g26df2751f71_0_160

**Comment by MarianaVazquezCYF** [comment]
we are waiting for Capgemini to reply!

**Comment by MarianaVazquezCYF** [comment]
open tech talent diverse day, take this example: https://www.eventbrite.co.uk/e/codeclan-festival-of-talent-open-day-tickets-680955234437?aff=ebdsoporgprofile

**Comment by MarianaVazquezCYF** [comment]
Write template mail for companies

**Comment by SallyMcGrath** [comment]
Is this in progress, or blocked?

**Comment by MarianaVazquezCYF** [comment]
@SallyMcGrath its in progress !

**Comment by SallyMcGrath** [comment]
Is this in progress? 😉
