### ISSUE TITLE
Scotland ITD Outreach

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#214]
- [x] Meeting between @caromelendezl, @MarianaVazquezCYF and Dara-Emma
- [x] Ensure we have the mailchimp vs dashboard conversions
- [ ] Plan to recruit applicants

**Comment by MarianaVazquezCYF** [comment]
https://docs.google.com/document/d/1vwKuyAslQwWH4DOtfqa20baFili0cupor3LRES6XPgI/edit

**Comment by caromelendezl** [comment]
Waiting on meeting @Barny-6 is having about employability and next steps etc on Tuesday29/08
