### ISSUE TITLE
Draft report for COFRA Foundation

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#221]
- Copy and Paste it https://docs.google.com/document/d/1Ucz375vaiqYy6N-7nPgheMu1IK12OFp4tEBMCwWLHTU/edit
- Add LDN9 and LDN10 activities

**Comment by SallyMcGrath** [comment]
This ticket does not seem to have all the information it needs to be worked on.

Refine using the fields on the right hand side:

https://github.com/orgs/CodeYourFuture/projects/142/views/1?pane=issue&itemId=44298533

**Comment by haldenb** [comment]
I completed this. I will close the ticket now.
