### ISSUE TITLE
Oversee Slack Clean-up

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#229]
- Ensure it's been updated

**Comment by ClaireBickley** [comment]
emails sent to everyone on slack - deadline 13th Nov

**Comment by kfklein15** [comment]
Hasn't this been done, and now it is a recurrent task - so should be our calendars instead of a ticket on the board?

**Comment by ClaireBickley** [comment]
nope this is still ongoing, down to the last 190 people that need sorting through (sounds like a lot but this is a small number considering what we've worked through already) should be complete within the next week.

**Comment by ClaireBickley** [comment]
there are 2 people left we are querying. Tracking in the [Slack clean up](https://docs.google.com/spreadsheets/d/1l2hDiOcWtrGunnYIADkmehTPU_xWwwHinhoVDPP1shI/edit#gid=1073508752) spreadsheet tab "Final tab"
relevant people have been tagged directly in the doc

to close this ticket
- [x] each person on that tab needs to either be deactivated or complete the onboarding steps
