### ISSUE TITLE
Cohort Founders Birmingham

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#240]
- [x] Make an event /open class
- [x] Share the event using the communication strategy mentioned here https://docs.google.com/document/d/1LNwJjaXWt57oScBvp7_eELK1MEV965p379E63LAtazw/edit
- [x] Share message in the Meet up page 
- [ ] Follow up with attendees

**Comment by kfklein15** [comment]
Is this for new cohort founders? If yes, can we make it clear on the title - for example cohort founders for WM6.
