### ISSUE TITLE
Volunteers for Scotland

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#241]

**Comment by caromelendezl** [comment]
STAND BY: Waiting on meeting @Barny-6 is having about employability and next steps etc on Tuesday29/08

**Comment by MarianaVazquezCYF** [comment]
This changed from cohort founder to general volunteers that can help us with the projects of our trainees https://www.eventbrite.co.uk/e/we-need-tech-leads-and-pm-for-the-final-projects-of-our-trainees-tickets-708456110297?aff=oddtdtcreator this is the event! I will start with the promotion
