### ISSUE TITLE
Halden do your deactivations :P

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#249]

**Comment by lilianabermudes** [comment]
https://codeyourfuture.slack.com/archives/C055YKVBLT1/p1689580801182479

**Comment by SallyMcGrath** [comment]
I'm moving old tickets out of in progress and setting a limit

**Comment by kfklein15** [comment]
Is this a recurrent task? If yes, maybe it should be a block on your calendar, not a ticket?
