### ISSUE TITLE
List of potential companies for Capgemini to review (Job fair)

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/CYF-Staff-Tickets#261]
Potential Companies:

- Morgan Stanley
- BJSS
- xDesign
- Canon (Medical Research)
- DXW  
- ClearChannel
- Oxa
- UKTV
- IBM
- Clearscore
- Costa Coffee
- Salesforce
- Avaloq
- Alfa System

**Comment by caromelendezl** [comment]
@MarianaVazquezCYF put potential companies on the Preview above. We are having active conversations with them

**Comment by MarianaVazquezCYF** [comment]
amazing thanks Caro, let me send an email to Sally!
