### ISSUE TITLE
Community Satisfaction form REVIEW

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#264]
Mariana, can you please add this to your list? :D 

- Please have a look at the questions on this form and propose which ones should stay or should go. Consider how this information would be useful for your work regarding community experience.

https://docs.google.com/forms/d/1qnpazOmBxW9FtdmJAv9yOa6gEg0a5wLIidd7lIq_F1o/edit

- We last shared this with the community last year.

- It's better we have something useful that actually works

I suggest we have a new form by the end of September so we can share it with the community twice this year (end of September and end of December).

**Comment by MarianaVazquezCYF** [comment]
Hello @lilianabermudes Lili, sorry for seeing this just now! whats the objective of this survey?
a)Measure engagement, measure satisfaction ? 
b)Measure how well prepared they were before stating their volunteer role (we almost have the answer for that?) 
C)Investigate if they have feedback? what we will do with that feedback?

**Comment by lilianabermudes** [comment]
Hi Mariana,

I believe this should focus on community satisfaction = community experience = how happy our volunteers are about their volunteering experience.

Of course, we can use the same form to ask for thoughts/feedback. 

My suggestion: Write a proposal (if you think the questions are good, keep them) and share it with Alec - he has lots of experience with user experience.

**Comment by alecmccrindle** [comment]
- 3. Remove 'I’ve been around for awhile' and 'I’m an old face'. Don't add much, old face is an outdated expression. 
- 4. Change title to 'Which team do you support? Then just a list the teams.
- 5: do you want to find out the most positive experience or generally the things that the community find positives? For example, you could write what is the most positive thing about CYF? Or, do we want a list of specific experiences? Can you add a question about to rank the positivity? 
- 7. Ask for 1 thing that CYF can improve and ask for an example or what outcome the proposed change might look like.
- 9. We ask if people needed more info but don't ask what the information could be. Should we ask what info / experience is missing?
- 8 and 11 seem very similar?
- 14. What do we do with that question? Maybe ask them about their plans for the next 3 months?
- 16. Can be a slider. If they do recommend CYF, can we ask them what type of people they recommend to us?

**Extras**

- Maybe one open ended question at the end - anything you want to share?
- Do we want people who rate us highly to leave reviews for us somewhere? Google Maps maybe?

**Comment by MarianaVazquezCYF** [comment]
@lilianabermudes do you have a preference of when to ask people to answer the community satisfaction form? I am proposing sending it in October (thinking that Glasgow 6, London 10 and London 9) will finished! and sending the second one in March (6 months after) let me know!

**Comment by lilianabermudes** [comment]
It sounds reasonable to me. When you and the team have this ready, please share the link to the form with Claire + your calendar proposal to send the survey to the community. You can add this as a ticket to the Global Team board and tag her :)

**Comment by MarianaVazquezCYF** [comment]
@alecmccrindle alec, I think you were reviewing the form on this ticket, but the proposal was the one in the channel haha, is this one: https://docs.google.com/forms/d/143SjZ0RzdMytIwhm9KLSiOAwxV_KsjJR-ImBmiVD9r0/edit

I added your comments! These are mine: 
3. How long have you been with CYF? I want to have this info, because I want to know if their experience change with their time! I agree that if people have been with us for more than 1 year, then we could agree that they enjoy this community, however I want to check if this change! 
*** I am not sure if we should have questions 8 and 9, what would we do with that info?

**Comment by SallyMcGrath** [comment]
This ticket is both Done! and Backlog.

Is it Done? Close it by pressing the Close button.
