### ISSUE TITLE
Feedback from venue partners [Partnerships]

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#266]
- Lego
- Fourth
- Sansbury
- Slaom
- Guardian
- Zoopla

**Comment by lilianabermudes** [comment]
- Contacts are here: https://docs.google.com/spreadsheets/d/135bCMy_IX_VQR7USmLrszbCzFCRswjSEo3aq7L0PI-I/edit#gid=0

**Comment by SallyMcGrath** [comment]
stale
