### ISSUE TITLE
Messaging for Fundraising

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#276]
- [x] Use ideas from the [Miro Board](https://miro.com/welcomeonboard/U1psZkpiVVZOM1NnOVhTeVhNT2FsZmZKczNnOFRZTkhoOVY0VnZ5ZnZKa25ORzZ1bVVUa2N6WVBXSUU4cUxoc3wzMDc0NDU3MzQ3MzM3MTQ2NzI5fDI=?share_link_id=47277824654)
- [ ] Brainstorm new ideas

**Comment by alecmccrindle** [comment]
[Messaging doc here](https://docs.google.com/spreadsheets/d/1KEDPgpDhTlxZXrGuUXINt3Juwnq5MUWOHbJzVENWXrI/edit#gid=0)

**Comment by SallyMcGrath** [comment]
This ticket doesn't look Ready to me. It doesn't have all the information it needs to be worked on. Let's talk about this next week briefly. 

I think a little bit more work could help everyone use these boards more effectively.
