### ISSUE TITLE
Sheffield Chapter

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#279]

**Comment by MarianaVazquezCYF** [comment]
- [ ] Find volunteers
- [ ] Message applicants ITD
- [ ] Find space for the class 
- [ ] Submit funding
- [ ] Re connect with the volunteers
- [ ] Write the description of the chapter

**Comment by MarianaVazquezCYF** [comment]
[Sheffield Chapter (1).docx](https://github.com/CodeYourFuture/CYF-Staff-Tickets/files/12585464/Sheffield.Chapter.1.docx)

**Comment by SallyMcGrath** [comment]
@MarianaVazquezCYF I think this should be a milestone on the programme teams board. In the New Year, please attend a Prom planning session and we'll go over it.

**Comment by MarianaVazquezCYF** [comment]
Perfect!

**Comment by MarianaVazquezCYF** [comment]
**Btw, I have noticed that on October 25! I sent the following email with the ITD instructions! These instructions are correct right?** 

_Hello team, I hope you are well!

I am contacting you because we will start the Sheffield Chapter soon and I want to know if you are still interested in taking the course! 

If you are interested, please let me know as soon as possible! (this week) 

What to do next?

1. You need to sign up again for your Intro To Digital account
2. Grashoper its not longer available, therefore instead of grasshopper, please follow the next steps: 

 Programming Hub was created to help people get into coding in a fun and easy way. You can do the Programming Hub courses on your smartphone, or using a laptop or desktop computer.
Device: MEDIA
Instructions:
Instructions
Create an account on [Programming Hub](https://programminghub.io/) or download it from your smartphone app store
Complete the course named Fundamentals
Complete the course named IT Basics
Take screenshots of your completed course index pages and upload them
Fundamentals can take around 4 hours and IT Basics can take around 3 hours to complete for someone who has never coded before.
IMPORTANT:
These courses are free. You do not need to sign up to a pro account. Do not pay for Programming Hub.
You only need to complete Fundamentals and IT Basics to progress to the next step. (But you can do as many courses as you like!)
We don't need certificates; you need to take the course for yourself, not for us. Certificates are not the point of Code Your Future; learning real skills are.
Once you have completed both Fundamentals and IT Basics:
Take a screenshot of each completed course page with your phone or computer. ([How to take a screenshot](https://www.cnet.com/tech/mobile/how-to-take-a-screenshot-on-any-phone-android-iphone-11-samsung-galaxy-motorola/).)
Upload your screenshots using the upload button below
A member of the CYF community will ask you what the most interesting thing you learned from the courses was. While you wait for someone to ask you this, you can go on to the next step.

3. Continue with the rest of the steps on ITD, if you need help, please let me know! 

Thank you so much!_

**Comment by kfklein15** [comment]
Closing this since it has all been done. Milestone created.
