### ISSUE TITLE
Product Delivery Path/Track

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#29]
**Background**
Faye is working with two Capgemini volunteers on a new Product Delivery Path Track

**Acceptance criteria**
* Syllabus must follow our [standards](https://docs.google.com/document/d/1xJSTOCWAm4nOvDR8lppG9EKHVbiUR8-A4nt9iI_tLLs/edit)

**Comment by kfklein15** [comment]
Documents shared by Faye to be read
[review the document](https://docs.google.com/document/d/1LN0XbWvgiQYSIAhlqrm57GgvzFI2s9GYlZgKevlg41w/edit?usp=sharing)
and [this document](https://docs.google.com/spreadsheets/d/1y1chIXOEN-PfoKhGI_ILqTYPJD97NE_MXtV1t61zE5w/edit?usp=sharing)

**Comment by kfklein15** [comment]
@SallyMcGrath , do we have other pages like these for our tracks?
https://module-cloud.codeyourfuture.io/overview/welcome-to-devops 

And why are they not linked from the Syllabus? (At least I couldn't find it)

**Comment by SallyMcGrath** [comment]
The devops one exists because I sat down with Pedro and typed it up for him. ;) 

There's a gitbook template https://github.com/CodeYourFuture/Track-Template and a bunch of stubs in gitbooks. If volunteers take them forward they will exist.

**Comment by kfklein15** [comment]
All of this is being communicated on #product-delivery-track channel on Slack.
