### ISSUE TITLE
Dashboard Data Recording

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#30]
**Background**
We do not have a mapping of the data we collect right now. This must be done for all data stories via products, but this is the first exercise. This data should have clear justification, as per GDP

**Acceptance criteria**
* Unique spreadsheet with this mapping ([created](https://docs.google.com/spreadsheets/d/1HK59jdS6uccr02ppUIrdx4fo3tyVeRTKWQnqqM1Zzis/edit#gid=2061664423))
* Defining categories for each data
* Describing the justification/how the data is used
* Describing the impact on the user

**Comment by kfklein15** [comment]
To Dos
- Build a high-level Diagram of all data points (Rainbird, ITD, Personal Circumstances form, FP, Volunteer, Mailchimp, Other forms? etc), so we can visualise the impact.
- Mailchimp: check the data on it?

**Comment by kfklein15** [comment]
@gbencci and @alecmccrindle , I have added an overview tab to our [Recording document](https://docs.google.com/spreadsheets/d/1HK59jdS6uccr02ppUIrdx4fo3tyVeRTKWQnqqM1Zzis/edit#gid=303830669) with the systems/forms I have mapped, so we can have an overview, as discussed a couple of weeks ago.

What do yo think should be our next steps?

My view was going to do the first exercise of re-discussing one of these forms and define the reasons we need that data (which is what I suggested with Applicants). If this is it, should I take a first stab adding reasons and you can review it? Do you prefer starting with a different form/system?

**Comment by kfklein15** [comment]
Is this something we still need to do? @ClaireBickley , not sure if you had seen this before, but just wondering since this has been on my long list for very long now and I am not sure 1) If it's still needed and 2) what should we doing. 
If you want we can have a chat about it :)

**Comment by ClaireBickley** [comment]
I haven't seen this before - I think it's probably worth doing but let's redefine it a bit as we're capturing different info now with the new Personal Circumstances form. This isn't something I'll be able to look at until next year I'm afraid.

**Comment by kfklein15** [comment]
I'll keep it open and we can talk in January/February.

**Comment by kfklein15** [comment]
This isn't at all in my priority list, so would suggest closing it for now.
