### ISSUE TITLE
Closure to LDN9

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#303]
Make linked in post to celebrate the end of SDC and to get excited about Portfolio module 

Thank Leads (Aman, Sam, Andy Tracy - anyone else?)

**Comment by SallyMcGrath** [comment]
@haldenb 

Does this ticket have everything it needs to be worked on? What information would this ticket need to progress?

Look at the fields on the right hand side of this view

https://github.com/orgs/CodeYourFuture/projects/142/views/1?pane=issue&itemId=44298525
