### ISSUE TITLE
Review Regional Goals

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#305]
Hi all,

Can you please review [only] your area in the regions' goals for Q4?

https://docs.google.com/document/d/1UEiHsdU1rZQvcK2LzPJizek0tbCNDCwR_lrPpxK456Y/edit

**Comment by MarianaVazquezCYF** [comment]
@alecmccrindle I added some ideas! 
@SallyMcGrath I have one goal to start the Sheffield chapter in Q4, is this part of community experience or program ?

**Comment by SallyMcGrath** [comment]
Program I guess?
