### ISSUE TITLE
CYF video next steps

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#308]

**Comment by alecmccrindle** [comment]
- [x] Confirm who's going to make it (agency / Alec?)
- [x] Decide who to interview
- [x] Start planning shoot

**Comment by SallyMcGrath** [comment]
Is this urgent? It's a month past the due date

**Comment by SallyMcGrath** [comment]
@alecmccrindle I would really appreciate it if you would from time to time respond to me on GitHub. 90% of my comments to you are unanswered like this.

**Comment by alecmccrindle** [comment]
Apologies for failing to answer, we stopped using Github and I didn't remove all of our replicated tickets in global. Will try avoid in future.
