### ISSUE TITLE
Create Regional PD Training Resources

### ISSUE THREAD

**Issue by ElizabethlawalCYF** [CodeYourFuture/CYF-Staff-Tickets#32]
- Resources for feedback 
- Outline assessment criteria using milestone tracker 
- Guidance for coursework review

**Comment by ElizabethlawalCYF** [comment]
1) Milestone Tracker - https://docs.google.com/forms/d/e/1FAIpQLSc4GxNj3mXY82DzXGZIk_cbtjc3VkvDvZ_4NwaXcOF2BBniJQ/viewform 

2) Coursework review guidance (example only) 
https://docs.google.com/presentation/d/1IDIsgiTD99bmkq03D09cuBKhGUUr1hBDI51_IIZJIzs/edit#slide=id.g1f74406e27e_0_67


3) https://docs.google.com/presentation/d/13tnDQh3Q4piNsUFX_H-9IiaQNP6F1pjExF3pDJ4nRh8/edit#slide=id.g14cc37fc86d_0_157

**Comment by kfklein15** [comment]
Let's make sure we are aligning this to the overall Strategy review.
