### ISSUE TITLE
Resources for proms to offer trainees

### ISSUE THREAD

**Issue by ElizabethlawalCYF** [CodeYourFuture/CYF-Staff-Tickets#33]
**Background:**
- Trainees have mentioned facing challenges with organisation, time management and structure. Here are some tools to offer trainees in the short term.

[Focusmate]((https://www.focusmate.com/) )– working with someone quietly on zoom. A number of ADHD people have ADHD UK  that having someone there to help hold them to account is effective for them.

[Otter.ai] [–]((https://otter.ai/) ) app providing real-time transcription of your meeting. Useful for notes and useful for scrolling back to catch up if your focus moves out of the meeting for a period.

[Llama List – ](https://llamalife.co/)
a different structure to working through work lists.

**Comment by emcglackenr1** [comment]
- [ ] Added to resource doc for trainees in GLA6
