### ISSUE TITLE
Assigning trainees who scored B1 - B2 to Udemy in GLA and London

### ISSUE THREAD

**Issue by ElizabethlawalCYF** [CodeYourFuture/CYF-Staff-Tickets#34]
**Background:**

Trainees scored who scored between B1 - B2 will need extra support to improve their English, they are the most likely to struggle on the course because of this reason. So we will need to assign them to the Udemy Professional English Track https://codeyourfuture.udemy.com/learning-paths/3079064/

**Comment by ElizabethlawalCYF** [comment]
Can you make sure that your trainees are on UDEMY, and list their names below so we can get them set up.

We will also need to inform their buddies (once they are set up that they are struggling with their English so they will need to assess this during their weekly meetings).

**Comment by ElizabethlawalCYF** [comment]
**Here's some copy if you need it.**

We have identified that your English skills will be one of the main areas that you will need to focus on during your time at CodeYourFuture. We have created some resources to assist you on this journey on Udemy and we will be monitoring how your English progresses throughout the course. 

We will be checking in on your English level at the end of JS3 so you have some time to focus on this. 

Please make use of Udemy track, and participate in the classes and resources provided. We encourage you to practice your English as much as possible, whether it be through speaking, writing, or reading.

We are here to support you and will work with you to help you reach your language goal and your buddy will also check in with you to see how you progress.


What are your thoughts on setting up a joint channel for your trainees? @emcglackenr1 @haldenb @caromelendezl

**Comment by emcglackenr1** [comment]
Do you mean a separate joint channel for those with English issues?
Halden and myself set up a help channel for both the cohort but it's more homework help and such

**Comment by ElizabethlawalCYF** [comment]
Yes - As the cohorts are starting at the same time, it makes sense to share resources and to create a global support group for the trainees who need extra support in their English

**Comment by emcglackenr1** [comment]
**Waiting for trainee emails** [Slack Post](https://codeyourfuture.slack.com/archives/C044M02QTM5/p1675344513671579)

**Comment by emcglackenr1** [comment]
Added the trainees who have CYF emails so far
