### ISSUE TITLE
Project decisions: BigBloom and Tech for Good

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#345]

**Comment by kfklein15** [comment]
**BigBloom**
- 

JP Morgan
- Dashboard problem
-

**Comment by kfklein15** [comment]
@gbencci @SallyMcGrath  I have updated the [briefing for BigBloom](https://docs.google.com/document/d/11aESoQO_QgScQMpZba_9yukHbtq7ecUPT4-BZYYmJFI/edit#heading=h.bqh9jfjqcchl) with all our possible tickets. 

If you are both happy with it we can close this ticket, since I will work on the JP Morgan stuff later - this ticket was only to decide on the projects :)

**Comment by SallyMcGrath** [comment]
I'm happy with the descriptions. I have edited the document. This looks done to me!
