### ISSUE TITLE
Create WOWto for community safety training

### ISSUE THREAD

**Issue by ElizabethlawalCYF** [CodeYourFuture/CYF-Staff-Tickets#35]

**Comment by ElizabethlawalCYF** [comment]
https://docs.google.com/presentation/d/10DA_Z3mglS4XHPNygTNmJP1s9lXT6y6joM-94-d9pC8/edit#slide=id.g1398ccd695a_0_680 

These are the current slides we use

**Comment by ClaireBickley** [comment]
I've just done a loom on how we store data for Lili if it helps.
