### ISSUE TITLE
1 pager of Expenses Receipt [examples]

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#360]
Hi Claire,
I was just talking to Sally; she mentioned this would be super helpful to have. Trainees are frequently lost about what's an acceptable receipt and what we can not accept. Is this something you or Leanda could help with?

**Comment by ClaireBickley** [comment]
Hi Lili, I started this before I went on holiday, Sally has seen it. I asked the programme managers to add to it.
https://docs.google.com/document/d/18B7l-JR0tNCK9j-AZDicpwikB6rKyRWBeVXf08K8Xms/edit
