### ISSUE TITLE
Key messaging for fundraising

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#370]
- [x] Use ideas from the [Miro Board](https://miro.com/welcomeonboard/U1psZkpiVVZOM1NnOVhTeVhNT2FsZmZKczNnOFRZTkhoOVY0VnZ5ZnZKa25ORzZ1bVVUa2N6WVBXSUU4cUxoc3wzMDc0NDU3MzQ3MzM3MTQ2NzI5fDI=?share_link_id=47277824654)
- [x] Brainstorm new ideas for GiveAsYourLearn - [document is here](https://docs.google.com/document/d/1JEEdBL2FRBJ7WUUqpRpfH0W9MNRFRikS5CjdgDQq3kY/edit).
- [ ] Messaging docs for Tech Confessions, Portfolio Saturdays and Women in Tech brunch

**Comment by caromelendezl** [comment]
What's this key message related to? Fundraising?

**Comment by alecmccrindle** [comment]
Hi @caromelendezl - yes, see the links. I've updated the board
