### ISSUE TITLE
Invitations to Job Fair in London (LDN9)

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/CYF-Staff-Tickets#383]
Companies invited by @caromelendezl and by @MarianaVazquezCYF

**Comment by caromelendezl** [comment]
@MarianaVazquezCYF, here are the invitations I've sent. I'll add a tick to the ones that responded and the next steps next to each

- [ ] Alfa Systems
- [ ] Arnold Clark UK
- [ ] Avaloq
- [ ] Binance
- [ ] BJSS
- [ ] Bloomberg
- [ ] Bumble
- [ ] Carwow
- [ ] Cisco App Dynamics
- [ ] ClearChannel
- [ ] Clearscore
- [ ] Costa Coffee
- [ ] Dataminr
- [ ] Dell
- [ ] Deloitte
- [ ] DXW
- [ ] Equality Group
- [ ] EY
- [ ] Fatbeehive
- [ ] Financial Times
- [ ] Freshworks
- [ ] Fujitsu
- [ ] Gymshark
- [ ] IBM
- [ ] Kingfisher
- [ ] Kooth
- [ ] Low Carbon
- [ ] LUSH
- [ ] Maersk
- [ ] Metryx Studios
- [ ] Monzo
- [ ] MVF Global
- [ ] MyTutor
- [ ] Oxa
- [ ] Pleo
- [ ] PwC
- [ ] Robiquity
- [ ] SII Group
- [ ] Softserve
- [ ] SopraSteria
- [ ] Stripe
- [ ] Substrakt
- [ ] Ticketmaster
- [ ] TKMaxx
- [ ] Tunstall
- [ ] Tyrrell Systems
- [ ] UKTV (a BBC Company)
- [ ] Version 1
- [ ] VISA
- [ ] Yoti

**Comment by MarianaVazquezCYF** [comment]
https://jobs.codingblackfemales.com/?_gl=1%2A1tcivbr%2A_ga%2AMTE2MjY0ODg3Ni4xNjk4MTQyMDA3%2A_ga_BCMS13RZ7R%2AMTY5ODE0MjAwNy4xLjAuMTY5ODE0MjAwNy42MC4wLjA

BP UK
Lloyds
Capital One
Compare the Market 
Imperial College London
Polific 
Reach Industries

**Comment by MarianaVazquezCYF** [comment]
Companies with more than 3 roles (entry positions) on Linkedin! Could you find the contacts @caromelendezl ? Thank you so much!

- [ ] - [ ]Kraken - Octopus Energy Group. LOTS of roles! 
- [ ] - Rockstar Games 
- [ ] -  Builder.ai
- [ ] - Open Cosmos
- [ ] - BBC

-

**Comment by kfklein15** [comment]
My ex-boss works on [Elexon](https://www.linkedin.com/company/elexon/) nowadays. Do you have "standard" info that I can send to him to see if he can help us?

**Comment by SallyMcGrath** [comment]
Have you invited 

- [ ] Salesforce - funders
- [ ] Slack - funding, hiring, volunteering
- [ ] Udemy - free. products, volunteering
- [ ] Lego - space
- [ ] Fourth - space
- [ ] Evidenced - free products
- [ ] Rainbird - free products, pro bono
- [ ] Crushing Digital - free products - in process of agreeing relationship
- [ ] JP Morgan - hiring, volunteering
- [ ] Thoughtworks - hiring
- [ ] Infinity Works - laptops
- [ ] Workday - funding

They have all supported us in the part or are major ongoing supporters

**Comment by SallyMcGrath** [comment]
BBC has hired from us
Krakenflex have talked to us many times - Barny has the contact

**Comment by MarianaVazquezCYF** [comment]
- Thoughtworks @lilianabermudes could you please invite them?
- Infinity works - I will invite them
- Workday - I will invite them
- JP Morgan - @caromelendezl / @gbencci 
- BBC - @gbencci can you please invite them? 
- Krakenflex @Barny-6 can you please invite them?

**Comment by lilianabermudes** [comment]
My superficial contact with Thoughtworks happened in 2021, and did not progress :/

**Comment by kfklein15** [comment]
Sent it to a friend who is a Lead Dev at Thoughtworks.

**Comment by MarianaVazquezCYF** [comment]
awww team, what we would do without you! thank you so much for sending those emails! so far we have confirmed:

- clear channel
- cisco
- lush
- capgemini
- cititec
- Evidenced (no jobs, but a workshop)
- hopefully slack!
- and hopefully more more!!

**Comment by SallyMcGrath** [comment]
We have a grad at VISA, don't we?

**Comment by SallyMcGrath** [comment]
Is this done? Can you close the ticket?

**Comment by MarianaVazquezCYF** [comment]
@gbencci  @lilianabermudes  @Barny-6 I wanted to follow up on the list of companies Caro previously invited to the job fair. As you can see in HubSpot, less than 10% of invited companies actually attended the last event.

Do either of you have close contacts at any of these organizations that could help secure their attendance? 

If there are companies you feel particularly confident reaching out to, I'd love for you to personally invite them to be part of our upcoming event. Just please write them down on this document to follow up with the invites: https://docs.google.com/spreadsheets/d/1THxEqrJw-OaJZK6Q919cGPRmFtFNx2VgLhZY_Hy0NfA/edit#gid=0

Thanks!!
