### ISSUE TITLE
Annual Report - design

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#390]
We have completed and submitted the [annual report for 2022](https://docs.google.com/document/d/1DrXmoJo_XbLQrzL70iG-BTsj8IuLsVTmhsgtHJ0wr9U/edit) to the charity commission in Scotland and England.

We now need a designed version for sharing on our website and externally. Often, grant applications ask for a copy of our latest annual report, it will be good to use the designed version for this.

We have hired a designer that we have used previously, Mihaela, for this project.

Criteria for success
- [x] choose and hire designer
- [x] send annual report (clean version) to designer
- [x] send pictures
- [x] review and feedback on any drafts
- [x] approve final design

**Comment by ClaireBickley** [comment]
shared with designers, small task

**Comment by ClaireBickley** [comment]
@alecmccrindle I've added some further info to this ticket, please update when here when pictures have been sent

**Comment by alecmccrindle** [comment]
I am a blocker. End of the week hopefully.

**Comment by ClaireBickley** [comment]
@kfklein15 this isn't completed - Alec commented yesterday that he should have this sorted by the end of the week

I think it's on multiple boards which is leading to confusion! I'll try and move it to Ops board

**Comment by kfklein15** [comment]
It's showing as completed on the Community board :) That's why I closed it.

**Comment by kfklein15** [comment]
@alecmccrindle , this is showing as in progress, but it doesn't have an iteration. Should it be in this current iteration?
