### ISSUE TITLE
sort out expenses

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#392]
Missing receipts - need finding and organising

Halden:
- Match existing receipts with expenses

**Comment by haldenb** [comment]
Blocked, I need to find receipts.

Next steps:
- speak to Leanda about risk of not having expenses done on card.

**Comment by SallyMcGrath** [comment]
@haldenb I'm moving this ticket because you haven't touched it since our call.

I really need you to prioritise this problem now. Let me know how I can support you to move this ticket forward.

**Comment by haldenb** [comment]
I have messaged Leanda asking what to do about this will update the ticket when I get a response

**Comment by SallyMcGrath** [comment]
Still no response from @LeandaCYF ?

**Comment by LeandaCYF** [comment]
Hi @SallyMcGrath , I have given Halden a response to the message he sent me
