### ISSUE TITLE
project support with Papier

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#394]

**Comment by haldenb** [comment]
Waiting for Papier to design the project

**Comment by haldenb** [comment]
Papier to run 2 sessions with trainees to build a full stack project with Papier volunteers.

**Comment by SallyMcGrath** [comment]
How could this project be handed over to trainees and volunteers @haldenb

**Comment by haldenb** [comment]
Baz has met with them once. I will see how much ownership he can take. Great idea :)
