### ISSUE TITLE
Slides covering Community Safety

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#397]

**Comment by ClaireBickley** [comment]
https://docs.google.com/presentation/d/10DA_Z3mglS4XHPNygTNmJP1s9lXT6y6joM-94-d9pC8/edit#slide=id.g1398ccd695a_0_0
to review

**Comment by lilianabermudes** [comment]
@ClaireBickley so let's try to implement this as an automated process for anyone joining CYF. They must read it and confirm they have done so.

**Comment by ClaireBickley** [comment]
@alecmccrindle I think we can close this?
