### ISSUE TITLE
Research companies that could provide space

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#405]

**Comment by haldenb** [comment]
https://docs.google.com/spreadsheets/d/135bCMy_IX_VQR7USmLrszbCzFCRswjSEo3aq7L0PI-I/edit#gid=0

**Comment by SallyMcGrath** [comment]
This ticket isn't ready.

It doesn't have a priority. It doesn't have a size. It isn't assigned to a time box. Th goals are not defined. There's no way to know how this ticket could be completed.

Back to the backlog. (if you'd like to meet again today to go through this let me know.)

**Comment by MarianaVazquezCYF** [comment]
I will close this ticket as @gbencci will be working on this!
