### ISSUE TITLE
Define the agenda for the L10 Job Fair

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#407]
**Background**
The venue has been booked for 22/3/2024 Capgemini Holborn 4th floor

**Acceptance criteria**
- [x] Set Agenda for the day, [reusing the London 9 of 2023](https://docs.google.com/document/d/14kq1KoR4XbYMtQkl566xAo-T3sL5vsCudOOiVE0eM8Q/edit)
- [ ] Approve agenda with Alec and Lili
- [ ] Approve agenda with German

**Owner**
@haldenb 

**Stakeholder**
@alecmccrindle @lilianabermudes 

**Approve**
@gbencci

**Comment by haldenb** [comment]
Book Venue
Get Companies
Set Agenda 
Order Pizza

**Comment by SallyMcGrath** [comment]
@gbencci this ticket is In Review. Can it progress to Done?

**Comment by haldenb** [comment]
@gbencci @lilianabermudes @alecmccrindle this ticket is In Review. Can it progress to Done?

**Comment by kfklein15** [comment]
This will be worked on by @MarianaVazquezCYF this sprint. 
Lili and German, we'll need your input on it once she lets you know.
