### ISSUE TITLE
Contact Current Venues Contacts - To Secure Space for Saturday Classes

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#409]
Contact people and locations we already know to try solidify a location. See [this spreadsheet in **Venues tab** ](https://docs.google.com/spreadsheets/d/1viMBflIQGuFArzN8Ug7GxSFRMZ_p4CkPn2tMbezkhfQ/edit) for details on each

These organisations already know us and our requirements. We have used them in the past, and would just be setting up a more regular booking. If they do ask for requirements, see [this ticket for details](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/414)

**Venues Contacted:**
Tick when no more actions needed at this time.

Mitchell Library - 
- [x] Email: contacted by Dara via email, no response yet. 
- [x] Conduct phonecall or visit might have faster results

Woodside Library 
- [x] Email: contacted by Dara via email, no response yet. 
- [x] Conduct phonecall or visit might have faster results

Barclays Eagle Labs 

- [x] Email: Contacted by @caromelendezl 

Strathclyde University 

- [x] Email: Dara in touch with them about setting up space for several upcoming dates, awaiting confirmation.

**Comment by emcglackenr1** [comment]
@SallyMcGrath - there is no deadline for this, should it still be high since it should be done asap?

**Comment by emcglackenr1** [comment]
There already is a deadline

**Comment by SallyMcGrath** [comment]
I feel like a bit more info is needed on this ticket. 

1. What is the space for?
1. How many people?

I understand you have made this massive spreadsheet and linked that. It's vast and feels pretty overwhelming though. It looks honestly like a massive undertaking.

I haven't found organising the Portfolios module to be a massive task myself, so there's something happening between this description

https://curriculum.codeyourfuture.io/portfolio/prep/

and this spreadsheet you have made that would be good to understand.

**Comment by emcglackenr1** [comment]
The only relevant part of the spreadsheet to this issue the tab Venues, which is why I mentioned the tab when I linked it. 

We have a list of requirements to send to potential venues, but this issue in particular is for me to contact the organisations we are already in touch with. So, they have our specifications already.

A separate issue could be made for contacting new venues and include the requirements.

**Comment by SallyMcGrath** [comment]
Is it like 20 people probably?

**Comment by emcglackenr1** [comment]
I've put the requirements in [another ticket,](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/414) because these organisations already know us and our requirements. We have used them in the past, and would just be setting up a more regular booking.
