### ISSUE TITLE
Finalise CoC Document - Trustees

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#413]
@gbencci can you please do a final review and add edit if needed?

Let's try to send it on Tuesday?

https://docs.google.com/document/d/1Kxc6qh51INrycGAnQQC0BiIBTjf0IONQ72R9A28EoSI/edit

**Comment by gbencci** [comment]
Thank you colega, sorry that I haven't reviewed this. Once Alec and Claire are happy wit this, then we can send over, as they have the details much clearer than me.

**Comment by gbencci** [comment]
Hi! I think this is complete, right? Can we close it? Thanks!
