### ISSUE TITLE
Implement / Set Up New Way to Organise Venue Space

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#414]
Summary:
The idea is to make a new, simpler system where anyone can contact organisations, see how progress is, how appropriate venues are etc. From a PROM meeting, a venue specific spreadsheet was suggested by Amy. 
Therefore, this is the system I have gone with. 
The information is currently spread in a few places, so it must be compiled. This can then be handed over to volunteers to support with. 
Some contact details can't necessarily be made public. 
**Some tasks in this issue were completed in Sprint 10, then it was put into backlog because it wasn't urgent.**

Previous related steps

Budget
- [x] Request Information on Budget
- [x] Follow up 1

Admin
- [x] Create new spreadsheet in a reasonable/usable format -[ created](https://docs.google.com/spreadsheets/d/1GomrRyANHU35VFZy1akYEfRt4OI2XGoC5zplrM7Kwh0/edit#gid=0)

**Acceptance Criteria** 
- [x] Budget Follow up 2 - Budget guidance has now been clarified and added to spreadsheet
- [x] Create staff document with individual company contact details that shouldn't be widely shared. Link to spreadsheet - [Completed document](https://docs.google.com/document/d/1akdUgERGsHxnVASamiC5pKFzs-tjtW_3WtuXCnhGFEg/edit)
- [x] Compile information into Spreadsheet (currently spread over [Portfolio Spreadsheet](https://docs.google.com/spreadsheets/d/1viMBflIQGuFArzN8Ug7GxSFRMZ_p4CkPn2tMbezkhfQ/edit#gid=1663620905), Old [Volunteer Collab Doc](https://docs.google.com/document/d/1vZ7apL9_nCFVsJuf4tyKWi5Az7Os1YOkI9oMnJutzkQ/edit), and potentially [Caro's handover document](https://docs.google.com/document/d/1HcVoBIDml-wcc8eExJVaaRG7Si-D2AmE3fY-v_KtPNU/edit#heading=h.6qvtk49hhh2g) - This was only mostly completed, as it is a larger job than expected, and not all of the information is that urgent to add to the documents. Issue #584  was created to add the rest of the info later 

- [x] Share more complete [spreadsheet](https://docs.google.com/spreadsheets/d/1GomrRyANHU35VFZy1akYEfRt4OI2XGoC5zplrM7Kwh0/edit#gid=0) with volunteers 
- [x] Pin to appropriate channels

**Template for Asking about Venues** 

Template for making contact: [in this document ](https://docs.google.com/document/d/1HxTmA_g99MhyTUDf7L74HDEzCeLF7gsFRVQtQufc3yk/edit)

**Space Booking Requirements:**

- Classes start at 10 am and finish at 4:30 pm, so we would ideally need the space from around 9:00 or 09:30 am to set up until 5:00 pm to clean up.
- Tables and chairs for a classroom setting (around 30 people per session)
- Wifi for all students. A microphone and a projector are a plus.
- We can bring our food and drinks for the day. Somewhere to place refreshments in the room would be ideal!
- Facilities to make for coffee, tea, etc, a microwave is a plus. We can organise this if it's not available!
- Plates, cutlery, glasses, but we will understand if this is not possible and we can bring disposable ones.
- We set up the classroom ourselves and clean the entire space before leaving so there is no need to worry about this. It will look like nothing happened and ready for Sunday!
- Private space for community members to use for prayer/reflection

**Comment by emcglackenr1** [comment]
Changed from high to medium priority because we seem to have a reliable space in Strathclyde until at least March. Even when we don't have a booked space, the campus has a large amount of suitable co-working spaces. So, it is only less suitable when there is a demo or lecture.

**Comment by emcglackenr1** [comment]
Priority changed to low because there is now a space for every class until 25th May. Except the 23rd of March for GLA classes. Will make a new issue for finding a venue for that class and link here

**Comment by emcglackenr1** [comment]
Some updates to these documents are not urgent, as most of the key information is now already on the spreadsheet and document. Created new issue to add more information at a later date #584

**Comment by SallyMcGrath** [comment]
Can this ticket progress to In Review or even Done, then @emcglackenr1 ? 🙏
