### ISSUE TITLE
Expenses app: evaluate Xero

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#416]
**Background**
Expenses for trainees are a repetitive process and somewhat time-consuming. We already use Xero as our finance team, so we want to understand if we should use that and set it in place. 

**Acceptance criteria**

- [ ] Has someone looked into this?
- [ ] Which type of account do we have for Xero?
- [ ] Who is our account manager so we can discuss discount/free?
- [ ] Approve cost

**Comment by ClaireBickley** [comment]
Just had a quick chat with Leanda about this, some thoughts:
- we are looking at expenses, but there is lots of groundwork to be done first which is underway
- Xero isn't the only option, we should consider others, doing this research will be time consuming
- using a tool like xero won't solve some of the issues we're facing with trainee expenses (e.g. no bank account, DLP trainees struggling with the online format)

This is on the radar for finance but a deep dive won't be possible before January.

**Comment by kfklein15** [comment]
I believe this isn't going to need my input. Do you want me to keep this open or just remove myself, @ClaireBickley ?

**Comment by ClaireBickley** [comment]
I think we can close this - it can be part of the bigger expenses revamp and we'll look at a few options. Thanks Karen!
