### ISSUE TITLE
Duolingo: testing their English test

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#417]
**Background**
We have a partnership with Duolingo who will be giving us 500 codes per year for English tests
We will use them as follows:
- Open test ([practice test](https://englishtest.duolingo.com/quick)): to be done during ITD
- Paid test: to be used during Fundamentals

We got 5 codes to test the Duolingo English test so that we can test them.

- [ ] 5 codes: 1 will be done by Karen, and the other 4 should be used by trainees and graduates
- [ ] Define documentation to be used when doing the test (this influences the validity of the test for university purposes, for example)

Open other tickets later:
- [ ] Create the process with Duolingo to receive codes
- [ ] Create internal process (ITD / Fundamentals)

**Comment by gbencci** [comment]
Hi Karen, 
Yes, of course, I think it's good you do one.

For trainees, I think it would be good if two are non-native English speakers and the other two are people that we have identified they struggle with their English, so we get a sample

**Comment by kfklein15** [comment]
I have done the test.
Screenshots have been saved [here](https://drive.google.com/file/d/1jGckz1kr6XikdCelfjtoy4rRMNdkBmRr/view?usp=drive_link).

**Key notes**
- Must download the Duolingo Desktop app before doing the test. The app has to have access to read your screen, record screen and microphone.
- Must have ID/passport in hand
- Must be in a silent location by yourself
-

**Comment by kfklein15** [comment]
**Ali Nuri's feedback**
In my view, this test is not very strong.
The listing part played short sentences and I should repeat them, it was better to have longer sentences or small discussions and I should write or record my understanding of the discussions.
The speaking part was fine it was talking about the topic but if you are lucky you get an easy topic otherwise hard one.
Practice conversation
It has a part where you should select the answer for the conversation. In my view, it’s better to answer by myself not selecting an item.
It has the part where you have a record of yourself but it was a short sentence and a simple. They should combine it with short long and mixed sentences to record.
The miss-letters part wasn’t good because when I practised, sometimes it gave me an easy note and sometimes a hard one. It shouldn’t be like this if I am Lucky the easy one comes up and I get more score. They should mix it(easy and hard).
The writing part was not too bad the problem was, that most people did not use the computer for writing and needed the speed to write and find the key on the keyboard.
The reading and compensation were good as I said it should mix it (hard and easy) because sometimes something easy comes and sometimes something hard.
Selecting the best option for each missing word wasn’t good because when I practised, sometimes it gave me easy words and sometimes hard words. It shouldn’t be like this if I am Lucky the easy one comes up and I get more score. They should mix it(easy and hard).
