### ISSUE TITLE
Average Salary on Global data

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#418]
Create an automatic calculation for the average UK and SA salaries of CYF grads in employment

**Comment by gbencci** [comment]
Hi @Barny-6 I have done this. Please check that it's what you need. It's on row B50

**Comment by Barny-6** [comment]
That's perfect, thanks G! Does the total average include Cape Town? It's lower than I thought?

**Comment by gbencci** [comment]
Cape Town has only 4 salaries in their list, so that's all you get. I had to do some extra maneuvering for them as it's another currency. You can check if average is correct manually

**Comment by Barny-6** [comment]
I think there's still some work to do on this. 

Working on it manually, I split the UK / SA salaries as they aren't comparable (cost of living etc.). With the known UK salaries only I got these results:

Glasgow | £28,114
London | £33,978
North West | £31,730
West Midlands | £30,289
Total | £31,939
ZA | R260,000.00 | £10,938.98

It appears there are some discrepancies with West Mids and Glasgow so worth looking in to again. Let me know if you have any questions
