### ISSUE TITLE
Claw back Udemy licenses

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#419]
Background
We have a bunch of grads who have jobs and we need to claw back those licences as per our agreement. 

I have clawed back all inactive users already. 

Acceptance criteria
- [x] Get a list of 2021 grads with jobs or dropped out
- [ ] Deactivate those users

Owner
@MattCFry

Stakeholder

Programme Team

Approver
@MattCFry

**Comment by MattCFry** [comment]
@SallyMcGrath is it normal to send an email to people who we are deactivating? Shaun says he has done this.

**Comment by SallyMcGrath** [comment]
I haven't done this, no. Everyone was already informed they would get 1 year of Udemy and anything extra is bonus time.

**Comment by SallyMcGrath** [comment]
What is the progress of this task? It's defined as Small. Is that right?

**Comment by MattCFry** [comment]
This ticket is being done in conjunction with [Add all Udemy Users into Groups](https://github.com/orgs/CodeYourFuture/projects/142/views/1?pane=issue&itemId=52251073).

I technically have started this, however, I quickly realised a bit a dependancy/ priority issue. I feel this ticket will become more straightforward task when the connected ticket is done.

I may be unaware of some admin tools to help with this. I have been prioritising the above ticket. 

I wouldn't necessarily disagree with the small rating. It's entirely possible I am overcomplicating things 😅

**Comment by SallyMcGrath** [comment]
I estimated less than 15 minutes for this task when I wrote it up for myself, including getting the list together. I think it would be a good idea to simply get it done. Getting things done is useful to CYF and our team.  Please try to do this.

There is no benefit to turn small jobs into huge ones, especially something that is so unconnected to our business goals. There's a large benefit to completing necessary tasks efficiently. 

Let's try our best as a team to get through our work simply and quickly. Please make/get a list, tick the boxes like I showed you, and move this task to done. Thanks Matt.
