### ISSUE TITLE
Pilot of Competency auto-evaluation review with trainees/graduates

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#422]
**Background**
We have defined our [competencies](https://docs.google.com/spreadsheets/d/1Hwj_KX7-gnHNVTAP98FHffpq9QUdgtPlLLuGs3Zl_Gw/edit#gid=2086356663) and used them to evaluate the staff in 2023. Now, we want to pilot it with trainees and graduates

**Acceptance criteria**
- [ ] Define the format of the pilot (location, size, how the review will be done)
- [ ] Identify participants
- [ ] Run pilot
- [ ] Create future process

**Comment by lilianabermudes** [comment]
@kfklein15 should this be connected to the new PD coach role implementation? Maybe a nice project for Lara to join us?

**Comment by kfklein15** [comment]
Yes, that probably would make sense. @LaraHuzjan , can you add this to the PD Coach pilot? We need to create this milestone and break down all tasks for it :D
