### ISSUE TITLE
Employability vs Product: trainee update (Recurrent ticket)

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#43]
**Background**
We used to have an employability/product team meeting every two weeks to discuss how the trainees/graduates are doing in products, as well as new people that should be considered 
They are [tracked on a spreadsheet](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit#gid=1683129524)

Comments on here will give us the next steps on what should be considered/discussed.

**Comment by kfklein15** [comment]
Update (s/s has been updated)
- Mahri is going to focus on a Salesforce Developer course she is doing, so she is stepping back from CYF Next
- Islam asked to step back from Class Planner, since he wants to focus on finding jobs. He'll help onboard Milad and has to finish his story.

**Comment by kfklein15** [comment]
Update (s/s has been updated)
- Craig D'Silva & Jasvir are doing the Cloud Module, so they won't be doing interview to join or working on CYF Products

if anyone else is doing the Cloud Module on my list, could you please let me know?

**Comment by kfklein15** [comment]
Dilek will also be focussing on the Cloud Module.

**Comment by kfklein15** [comment]
Jasvir is focussing on Cloud Module.
Mandeep left for his handover/starting new job.
Khesiwe Dube (trainee) is joining as a QA.

**Comment by kfklein15** [comment]
I'm running out of volunteers. :(

Update on the recent leavers
- Davood: I suggested that him to do TA, since he doesn't have time/focus on products
- Marina: will be working with Glasgow cohort, volunteering in different capacities
- Youssef: has an dry eye issue so has to use the computer less

Possible/future interviews:
- Susan (London 9): interview week 20th March
- Houssein (London 9): possible the same, waiting for tech lead to give first feedback
- Michelle (WM 4): asked to talk after Final Projects only

**Comment by kfklein15** [comment]
**Update**:
-  Biruk from WM2 has reached out to join the Product Team. I will send him Codility test.
Should I go through the list of not-engaged Asylum seekers on the grad tracker and see if they would be interested in joining too? @gbencci @Barny-6 
- Houssein and Baz have passed Codility test, so will arrange the interviews for week of 20th.

**Comment by kfklein15** [comment]
A suggestion of a [page explaining the process](https://docs.codeyourfuture.io/volunteers/joining/join-cyf-tech-products) - so it's not only on a Slack message. 

What are your thoughts, @gbencci @Barny-6 ?

**Comment by kfklein15** [comment]
FYI I have shared this page with SA, so we are piloting it.

**Comment by Barny-6** [comment]
Can do, I'm still adjusting to github projects but I don't think updates in here are working for me

**Comment by kfklein15** [comment]
once you figure out what's the best way to update you, let me know :) We can always have a monthly meeting or a monthly thread on slack. 
I will keep updating the spreadsheet too.
