### ISSUE TITLE
Revitalise Glasgow Volunteer Meetings

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#430]
**Summary:**

Volunteer meetings weren't organised in Scotland for several months. At the start of portfolio, the community found a new time for the meetings to occur. However, attendance was low, notes weren't taken, and neither the Kanban or Agenda doc were used. 

**Completion Criteria**

- [x] Discuss with volunteer community x 3 - Dara
- [x] Staff to attend volunteer meetings to discuss - Dara x 2, Karen & Halden x 1
- [x] Otter.ai to be added to the meeting to make note taking easier for volunteers
- [x] Volunteers to be asked about the agenda doc and if they wanted to change it - Dara - they were happy with the layout for now

**Goals:**
- [x] Volunteer meetings happening regularly 
- [x] Volunteers taking ownership of meetings 

Related issues: 
It might be useful to introduce the Kanban board in future. This was moved to a new ticket #678

**Comment by emcglackenr1** [comment]
Ticket was changed from focusing on the kanban to discussing the minutes and meetings in general

**Comment by emcglackenr1** [comment]
Blocker is waiting to see how this turns out -[ temporary solution based on this discussion](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707317671309099?thread_ts=1707302840.125409&cid=C029341FPH6)

**Comment by SallyMcGrath** [comment]
I've put this back on Blocked as it's not progressed and it's Past Due

I've also unassigned D-E. This is something to hand over directly to @haldenb, who may wish to handle this differently.

I don't attend volunteer meetings unless they invite me

**Comment by haldenb** [comment]
I will go to the volunteer meeting next Friday and raise this with volunteers and see what solutions they have :)

**Comment by SallyMcGrath** [comment]
@haldenb 

Please update the deadline on this ticket as it seems to be a meeting in the past, which obviously cannot be achieved with current physics.

**Comment by emcglackenr1** [comment]
I rediscovered this ticket and edited it. I've added the actions taken by myself and other staff, removed unnecessary notes, and created a new issue #678 for the Kanban.
