### ISSUE TITLE
Prepare FOSDEM script and presentation material

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#431]
I will be presenting at FOSDEM on Feb 3rd, but I would be most grateful to have the script and the material.

This is the material that Sally submitted. Sally, I'll assign this to you, but feel free to delegate it to human or virtual services.

Proposal title: Developing in Public : Open Source Tech Education

"Abstract: Code Your Future is a free programming school for refugees and other people excluded from education. All our classes are free, and our teachers are volunteers. Since 2016 we have supported over 250 people into great careers in tech. Our one-year part-time programme, the Software Development Course (SDC) and our 16 week immersive engineering programme (CYF+) are both Digital Public Goods.

https://app.digitalpublicgoods.net/a/10951 SDG4: Quality Education,SDG5: Gender Equity,SDG8: Decent Work and Economic Growth,SDG10: Reduced Inequalities

Notes: We believe in free and open source education. We do our work in public. This means we develop all our curricula in FOSS projects on GitHub. We develop the platforms to manage and visualise these curricula on GitHub too, making heavy use of the Readme and Issues APIs to mash up content from hundreds of repos to build a coherent plan.

We code, we collaborate, and we make new collaborative coders. That's what we do! Over the years we have helped many wonderful orgs collaborate and build things, but this talk is the story of how this year we began to work with two code schools outside our organisation: MigraCode Barcelona and Hack Your Future Belgium, to build a remixable, adaptable system they can really use in their own contexts.

In this 30 minute talk, we will demonstrate: - Our open source governance model - a core maintainer team that meets fortnightly to steer roadmaps based on community input - Our agile, sprint-based development process with public Kanban boards - Our code review workflow - Cross-organisation collaboration with two recent collaborators: MigraCode and HYF Belgium

By developing curricula openly, we help other nonprofits and code schools to reuse and remix our materials freely. We benefit from a worldwide community of industry experts improving our content. This open model creates sustainability and impact for our organisation and the wider domain of accessible tech education.

We want to inspire more social good projects to develop open collaboration models and discuss the challenges and benefits we have experienced in practice."

**Comment by SallyMcGrath** [comment]
@CodeYourFuture/syllabus-team here's the collaborative doc as discussed in Syllabus https://docs.google.com/document/d/1BL50OgnaZEjR-FsJs1cyabb3ZS1vWe2M9Ov3kEd-DHc/edit?usp=sharing

Have at it!
