### ISSUE TITLE
Feedback for Tender Application

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#433]
Boshra and Bahare have requested feedback on their tender application (https://github.com/CodeYourFuture/Tenders/issues/3#issuecomment-1873514449). I have responded with the non-technical feedback that they did not meet the qualified supplier criteria but I would like support on the technical side.

**Comment by Barny-6** [comment]
@SallyMcGrath would you be able to give some feedback on their bid and write it up here? https://docs.google.com/document/d/17OTl4DgdeizvRbFJpxbb5S19Ycf2aqgh5PN0W7krKws/edit 

Please let me know if you need longer than this week to do it. Thanks

**Comment by kfklein15** [comment]
Let's try any other Tech Volunteers for this, please?

**Comment by SallyMcGrath** [comment]
> @SallyMcGrath would you be able to give some feedback on their bid and write it up here? https://docs.google.com/document/d/17OTl4DgdeizvRbFJpxbb5S19Ycf2aqgh5PN0W7krKws/edit
> 
> Please let me know if you need longer than this week to do it. Thanks

I just don't have capacity at this time. I was on holiday when you asked me. Sorry!
