### ISSUE TITLE
Invite Companies to London Job Fair 22/03/2024:

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#436]
**Background**
We have a Job Fair in March

**Acceptance criteria**

**Owner**

**Stakeholder**

**Approver**

**Comment by haldenb** [comment]
- @MarianaVazquezCYF could you add a template email for everyone to send - let's get as many hiring companies to the London Job Fair as possible :P 
- @haldenb to ask volunteers to invite their companies too

**Comment by SallyMcGrath** [comment]
There's no information on this ticket, so it cannot be assigned. Can you please edit this ticket to show what action you require me to take and by what time. TY

**Comment by haldenb** [comment]
@SallyMcGrath I have un-assigned everyone, when Marianna has updated the ticket I will re-assign it :)

**Comment by kfklein15** [comment]
This ticket will be started from scratch
