### ISSUE TITLE
Review engagement with Cloud Module comms and agree next steps

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#448]
Review engagement with the comms around the Cloud Module and C&CA/CIS roles and agree next steps

Assess engagement with posts based on reactions and whether people have followed the instructions

Minimum engagement requirements
- [x] 7 responses per region
- [x] 40 responses from UK 

**Engagement requirements not met ticket updated**

- [x] Review regional numbers
- [ ] Where minimum not met (WM, NW, GLA) create a list of minimum 5 grads to target via DM/Phone to discuss module & role
- [ ] Contact those on list to complete ticket

Assess whether more direct comms is required and set up tickets fro actions

Acceptance criteria

- [ ] Numbers added to this ticket
- [ ] If required, new tickets are created

Stakeholders
@emcglackenr1 @MattCFry @haldenb 

Approver
@Barny-6

**Comment by Barny-6** [comment]
55 Responses
Eligible for role 31
Not Eligible for role 24 (of which 2 will be eligible in 3 months)

**Regional Breakdown**
London 29
North West 13
South Africa 1
Glasgow 6
West Midland 6

**Eligible** 
London 17
North West 7
West Midlands 4
Glasgow 3

**Comment by Barny-6** [comment]
I'm content with London overall @haldenb please check the names [here](https://docs.google.com/spreadsheets/d/1fJKsV7v8KS0Yg_kyvm1M36Me_3TfztsnVS2zvwSspNk/edit?resourcekey#gid=1816487402) to see if there's anyone missing you expected to be there

North West could have a few more but eligibility seems to be a blocker - will target people individually

@ShaunCYFSA Anyone more want to join from ZA? PLease check the names [here ](https://docs.google.com/spreadsheets/d/1fJKsV7v8KS0Yg_kyvm1M36Me_3TfztsnVS2zvwSspNk/edit?resourcekey#gid=1816487402)

@MattCFry  West Midlands could do with more applicants 6 is good but we can target some more. Please look at the [list of applicants](https://docs.google.com/spreadsheets/d/1fJKsV7v8KS0Yg_kyvm1M36Me_3TfztsnVS2zvwSspNk/edit?resourcekey#gid=1816487402) and make a list of 5 (minimum) more grads to target.

@emcglackenr1 Glasgow could do with more applicants. Please look at the [list of applicants](https://docs.google.com/spreadsheets/d/1fJKsV7v8KS0Yg_kyvm1M36Me_3TfztsnVS2zvwSspNk/edit?resourcekey#gid=1816487402) and make a list of 5 (minimum) more grads to target.

**Comment by emcglackenr1** [comment]
Hi Barny, please see updates on [this spreadsheet](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit#gid=197105283) regarding targeting additional applicants. I noticed you changed the notes for some rows, please let me know if you have spoken to anyone about it already.
