### ISSUE TITLE
Review applicant numbers to C&CA/CIS role and agree any further comms requirements

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#452]
Review applicant numbers to C&CA/CIS role and agree any further comms requirements

Goal is:
30 Applicants of which
At least 5 are NW
At least 4 are GLA
At least 4 are WM

**Comment by Barny-6** [comment]
Everyone who signed up for cloud and is eligible has been tagged, emailed and dm'd last check had 14 applicants. Expecting up to 20

**Comment by kfklein15** [comment]
Are these the same? https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/445
