### ISSUE TITLE
Create and share Cloud Sign up form

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#453]
Create and share a form to sign up for the Cloud Module

Acceptance criteria
- [x] Include eligible for SC clearance
- [x] Commitment to cloud module over next five weeks
- [x] Location
- [x] Or not-eligible but I still want to do cloud
- [ ] region

Approver
@Barny-6

**Comment by Barny-6** [comment]
Form is ready here - https://docs.google.com/forms/d/1F0174vQbN823oDaqIe4KKTBsp9fLo9ontrBwuqEZQQc/edit @gbencci  please review it and let me know if the entry criteria has been decided. THanks

**Comment by gbencci** [comment]
Hi Barny, some comments:
- create a drop-down of cohorts for all the main ones and other free text.
- the SC higher/lower level is unclear. Best to ask what you need to know or explain it very carefully
- maybe 6M is too much. Ask for 3M and then option for other

Make sure that you know how many people we have that are eligible and how many of those make it after the entry phase.
