### ISSUE TITLE
Set up cloud Zoom Calls

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#456]
- make zoom links for each cloud module Saturday classes
- send links in [#cloud-module-class3](https://codeyourfuture.slack.com/archives/C06EGMX7K35)
- make sure the person hosting that class 
      1. has the host key,
       2. has tested it and knows how it works

**Comment by MattCFry** [comment]
Is this done or an ongoing thing?

**Comment by haldenb** [comment]
We went with a different solution - give log in to vols and remove ourselves from unnecessary processes, I'll close the ticket.
