### ISSUE TITLE
Review new training and development policy

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#459]
Claire has written a new [training and development policy](https://docs.google.com/document/d/1VcADNNECGcJXHWN93pGxJf2z9_NGxtoeVgIIbI2c0Eo/edit#heading=h.7k2761o461uu) as part of the implementation of the new employee benefits.

Criteria for success
- [x] draft new policy
- [x] internal review ( @lilianabermudes )
- [x] review by @gbencci 
- [ ] share with team

**Comment by ClaireBickley** [comment]
@lilianabermudes Germán has reviewed this now and left some comments (thank you G) are you able to give this another quick review please and check the changes I made based on G's feedback.

**Comment by lilianabermudes** [comment]
Done @ClaireBickley

**Comment by ClaireBickley** [comment]
thanks @gbencci and @lilianabermudes for the reviews. Let me know when you are happy for me to share with the team and we can close this ticket 😄

**Comment by lilianabermudes** [comment]
I was thinking of having the whole list with the new benefits with an implementation status for each one before we share. So the team knows what's coming, and which policies we have for each one (let me know if it's clear, I am happy to talk about)

**Comment by ClaireBickley** [comment]
OK I think we can close this one for now and I'll create a new ticket to develop an implementation plan.
