### ISSUE TITLE
Merge London 9 and 10 

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#466]
### Background

- London 9 and 10 started as one class that was then split due to huge size
- Now the number of trainees has reduced it makes sense to re-unite them

What is needed
- Archive London Class 9 and London 9 volunteers 
- Build a team of London volunteers
- Do slack training with trainees to keep channels clean

### Acceptance criteria

Cloud module finished

### Owner

@halden

### Stakeholder

@halden

### Approver

@halden

**Comment by SallyMcGrath** [comment]
stale
