### ISSUE TITLE
UI/UX Design Tech Products Test

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#467]
**Background**
We usually accept UI/UX Designers to the Tech Products team, but we have now had a case in which we are unsure if this person is ready to work with us. To avoid this scenario, I would like to have a UI/UX Designer exercise to filter people's knowledge and ensure they know what we expect them to know in this [role](https://docs.codeyourfuture.io/volunteers/teams-1/cyf-products-final-projects/roles/ui-ux-designer).

**Acceptance criteria**

**Owner**
@alecmccrindle 

**Stakeholders**
@kfklein15 

**Approver**
@alecmccrindle

**Comment by alecmccrindle** [comment]
Hi @kfklein15 - excellent point. The Deloitte funded design project Anderson is working on may be able to help with this issue. 

In that project we are likely to connect designers with folks doing their portfolios - and probably need standards for that too. 

I've added this into next Community Experience sprint to discuss.
