### ISSUE TITLE
WM5 - Community Rubric Work

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#468]
### Background

[Issues and actions with WM5 cohort](https://docs.google.com/document/d/1LJ2x6wJkcuV4YUVwqSLIe4n7MqSr79T96B_yg8gN0HI/edit?tab=t.0#heading=h.le857b972wjo)
We discussed having a "team agreement" meeting using the Rubrics.

### Acceptance criteria

- Are Rubrics approved?
- Define format of the meeting
- Define date for the meeting

### Owner

@kfklein15

### Stakeholder

@Dedekind561 

### Approver

@MarianaVazquezCYF

**Comment by kfklein15** [comment]
### Proposal 1 ###
**Prep**

1. Pre-read of the Rubrics
2. All participants should fill in an anonymous form on where they think they are for each Rubric

**Day-Plan**

1. Show the results
2. Give everyone 10 minutes to go through them
3. Separate small groups per rubric (randomly OR per personal preference? TBC)
4. Each group to work on how we can get from X to Y
5. Each group to create 3 actions
6. Play it back to the larger group
7. Vote on actions so we have 1 action per rubric

**Comment by MarianaVazquezCYF** [comment]
- Rubrics will be approved by the London board - @lilianabermudes could you please help us with this?
- Format of the meeting, in person! I will book a meeting with you Karen, to brainstorm ideas
- Date: February 17th

**Comment by kfklein15** [comment]
Sorry, the date will be 17th! I ended up booking Glasgow for the 10th.

**Comment by MarianaVazquezCYF** [comment]
Works perfect! I will be on holidays from the 9th, so I will leave our meeting booked ok?

**Comment by MarianaVazquezCYF** [comment]
Process to approve rubrics:
a) First - Review: done
b) Second - Understand how the implementation will work (Lili had already mentioned in one of the meetings that the next step should be a short presentation to us about the implementation - how this is going to work in practical terms?. Meeting booked ! 
c) Third - Stakeholders and approvers (us) and owner (Mariana) are all on the same page and approve. We might have some feedback on the implementation (normal)

**Comment by kfklein15** [comment]
**Prep** 
Rubric will not have been finalised
- Share the rubric as it is for them to understand 
- Send us your reflection on this form (what your questions, what you like, what you do not believe you could achieve within WM5 and why)
- Post-its + pens

**Workshop**
- 5 min intro of the exercise + create 4 groups (one for each rubric category - Programme, Community Activities, Community retention and ownership, Partnerships)
- 5 min discussing which level is WM5 for this category and it's sub-categories? (i.e. Meets Expectations)
- 10 min agreeing on what actions should be taken by our cohort to take us to the next level? (for example, from Meet Expectations to Exceeds Expectations
- 2 min presentation of actions to the wider group per category + 1 min feedback (15 min)

**Comment by MarianaVazquezCYF** [comment]
this is the new rubric to use in WM: https://docs.google.com/spreadsheets/d/1ycUYjkc1E68yS0tILouPL5Nf_KTxEBLgAoqiV_jvi50/edit#gid=275458106

Is the same one but I have deleted safe physical space, CYF Summit, I deleted them because its not their response to organise a summit or to find a space for class. On the same note, I deleted partnerships. 

And this is the prep form where they will give their opinion to the rubric and do a self assessment ! https://docs.google.com/forms/d/1RvfG3-7AwaIqgOFDP8-HOYr9G0GUa8BJws7u4iP7GZ0/edit

**Comment by kfklein15** [comment]
Thank you, @MarianaVazquezCYF

**Comment by kfklein15** [comment]
Posted on WM5-general tagging lead volunteers from Tech and PD to agree on the date of 17th.

**Comment by kfklein15** [comment]
All sent. Just need to plan my Birmingham travel.

**Comment by lilianabermudes** [comment]
@haldenb will also go to go to Birmingham soon; it would be amazing to combine this trip (if possible) :) . Also, it is important that Halden gets familiar with the rubrics.

**Comment by haldenb** [comment]
Im going on Saturday :D

Had a lil look and left some comments. I don't wanna storm in halfway through a process so will leave it at that:

If I am using the rubrics how much can I edit them? Here I find the lack of measurement difficult words like 'most' 'sporadic' I could we switch to numbers/ ranges?

Also, the word Graduate only appears twice. Is there a better measure of a thriving community than that it recreates itself?  Is there a better sign that the community is succeeding than grads returning?

Maybe we could have a call to discuss these points and someone could catch me up, I can see a lot of work has gone into this <3

**Comment by kfklein15** [comment]
Hey Halden,
The workshop is on this Saturday. I have agreed to run it for Mariana, per comments on this ticket.

Answering your points above:

- Please don't edit the rubric - comment on it, so we can discuss any change suggestions.
- My suggestion is book in some time with Mariana when she is back. She'll be the best person to run you through it.
