### ISSUE TITLE
Get Anderson's contract finalised 

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#473]
### Background

- [x] Update the contract
- [x] Get it signed
- [x] Share invoice template 
- [x] Ensure he can get paid 

### Acceptance criteria

Signed contract back from Anderson

### Owner

@alecmccrindle

### Stakeholder

@liliana

### Approver

@alecmccrindle

**Comment by kfklein15** [comment]
@alecmccrindle , this is showing as in progress, but it doesn't have an iteration. Should it be in this current iteration?
