### ISSUE TITLE
Planning to share our projects externally

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#475]
- [x] Retrieve collection of projects from coversation with Sally
- [x] Work on design/sketch with Anderson
- [x] Ideas for social media content - with schedule. With Barny
- [x] Make ticket for next sprint

**Comment by alecmccrindle** [comment]
Try give this task to Anderson and volunteers.

**Comment by alecmccrindle** [comment]
Got the CYF projects

- Rainbird/ CYF Blocks (it might be two projects here)
- CYF*Berkeli (video)
- NW5 - pro-boo with NGO (Kunji?)
- Dashboard
- Glasgow Avaloq/ Bike For refugees
- South Africa (choose one project)

**Comment by kfklein15** [comment]
Should this become a milestone and each project have it's own ticket (or tickets)?

**Comment by alecmccrindle** [comment]
Yes, good thinking. Will make it a milestone.
