### ISSUE TITLE
Twilio/Technical Flash Consulting

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#48]
**Background**
Twilio will be doing a Technical Flash Consulting for charities, including CYF, where they will look into some of our problems and suggest some actions/designs/solutions.

**Main contacts**
Christina Harris <charris@commonimpact.org>
Lucy Hawkes <luhawkes@twilio.com>
Matt Whalen <mwhalen@commonimpact.org>

**Proposed projects they will look into**
[Code Your Future Data Integration.pptx.pdf](https://github.com/CodeYourFuture/CYF-Staff-Tickets/files/10545265/Code.Your.Future.Data.Integration.pptx.pdf)
[Code Your Future User Segmentation in CRM_.pptx.pdf](https://github.com/CodeYourFuture/CYF-Staff-Tickets/files/10545266/Code.Your.Future.User.Segmentation.in.CRM_.pptx.pdf)

**Event dates/times**
- March 17th: 9-12:30pm EST / 2-5:30pm GMT (3.5 hours) (1.5 hours for nonprofits since they can leave at 10:30 EST while volunteers begin developing recommendations)
- March 24th: 9-11:00am EST / 2-4:00pm GMT (2 hours)

**Comment by kfklein15** [comment]
**Update**
- Have sent a correction about our DB being Mongo
- Asked if they want to see our mapping of CRM or if they want to start from scratch
- Asked what kind of support is needed on the 14th March, since I won't be here.

**Comment by kfklein15** [comment]
@lilianabermudes @gbencci I talked to Christina and they will most likely only focus on the CRM project (is where they have a better match of volunteer's skills). 

1. Are you both ok in doing the briefing on the 17th March? What information do you need from me?
2. Should we check if Marco can be part of it? This could give a lot of input for CYF Next.
3. What kind of documentation do we want to share with them? I thought about the [Data mapping](https://docs.google.com/spreadsheets/d/1GywwW3BXOpEUZiwePCqRqQCl_FzYVTz052kx1FN9egE/edit#gid=652622236) we've done. And maybe set them up in staging so they can see how our Dashboard works?
4. They might need someone supporting them from a technical perspective (instead of them setting themselves up). Any suggestion who we should talk to about this?

**Comment by gbencci** [comment]
Hi @kfklein15 
1. No problem with the briefing, I can be there, don't think I need anything specific
2. That would work, but then I would concentrate the briefing in CYF Next and for them to review the work we have done so far
3. That sounds good. There is nothing private in staging, so it works well
4. Well, if we go for a cyf next, then someone from that team, like a dev is doing really well for example. Otherwise I could only think of Mohsen or Jon

**Comment by kfklein15** [comment]
@gbencci I don't think we can change the briefing from CRM to CYF Next - although I always believe they are exact same thing!

 So to their e-mail:
**1. Who should I invite other than you?** Mohsen hasn't been involved for years now, so not sure he would be the ideal person. I can ask Jon or we could maybe chose one of our devs (knowing that they won't have all the answers)? We have Youseef and Saadia on our team right now.

**2. Provide Common Impact with background materials for your volunteers by EOD Tuesday 2/21**
I thought about sending:
- the [mapping](https://docs.google.com/spreadsheets/d/1GywwW3BXOpEUZiwePCqRqQCl_FzYVTz052kx1FN9egE/edit#gid=1930388278) we've done
- ask for the volunteers to sign-up to staging Dashboard
- ask for the volunteers Github ID and add them to the team so they can read our wiki page OR send them PDFs of it 

The dates are following: 
**Nonprofit Orientation: March 6th**. > I can go, but I won't be here on the 17th. What do you prefer to do?
Discovery & Design: March 17th, 2023, from 9am-12:30pm EST or 1-4:30pm UK 
Delivery: March 24th, 2023, from 9am-11pm EST or 1-3pm UK

**Comment by kfklein15** [comment]
Reply was sent yesterday. Waiting for Saadia and Youssef to confirm if they are ok with participating as support people.

**Comment by gbencci** [comment]
Update: Saadia and I guided the team. They asked lots of questions, so I think we can get this one as job done.
