### ISSUE TITLE
Organise Filming for Friday 16th Feb

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#483]
### Background

We're filming some interviews in London - alumni and volunteers. Need to get 5-6 folks to agree to be filmed on Friday 2nd at Cititec.

### Acceptance criteria

- [ ] Finalise potential list of interviewees
- [ ] Contact enough interviewees for 5-6 people
- [ ] Update with Ralph (filming people)
- [ ] Ensure you have all the equipment ready

### Owner

@alecmccrindle

### Stakeholder

@MarianaVazquezCYF

### Approver

@alecmccrindle

**Comment by kfklein15** [comment]
We talked about this, so should this be in progress?
