### ISSUE TITLE
[Ralph] Editing the London interviews

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#484]
### Background

Ralph going to edit our videos

### Acceptance criteria

Edited videos we can put on YT

### Owner

@alecmccrindle 

### Stakeholder

@MarianaVazquezCYF 

### Approver

@alecmccrindle

**Comment by alecmccrindle** [comment]
Emailed them, moving this to next sprint

**Comment by alecmccrindle** [comment]
Closing as I made another ticket
