### ISSUE TITLE
Meeting with alec to plan the content for social media 

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#486]
### Background

Our social media content is to align with our outreach goals! 

### Acceptance criteria

- [x] Have a plan for our social media calendar
- [x] Have actions for designs

### Owner

@mariana

### Stakeholder

@alec

### Approver

@alec

**Comment by kfklein15** [comment]
Fantastic ticket! :)

Suggestion for title:
From: Meeting with alec to plan the content for social media
To: Plan the content for social media

Also would add 1 acceptance criteria: raise tickets for the following sprints.
