### ISSUE TITLE
Invite companies to participate in the London Job Fair Mar24 stage 1 

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#488]
### Background

We are doing a Job Fair in London in Mar23, and we need your help to invite the companies you know so that we can have a diverse and interesting range of possible partners.
We need to have at least 6 companies confirmed.

This is a spin-off of ticket #481 

### Acceptance criteria

- Use this template to send to your contacts
- Update this spreadsheet with who you invited
- ?
- Invite must be sent by 6th Feb (Mon)

### Owner

Mariana

### Stakeholder

Karen, Barny, Halden, German, Alec

### Approver

Mariana

**Comment by haldenb** [comment]
Hello, maybe I am broken, I cannot find the template or spreadsheet?

**Comment by kfklein15** [comment]
Thanks. I moved it back to the Backlog, to avoid confusion. This ticket will be ready after Mariana's Friday meeting with everyone.

On a different note, you were only notified because you created the ticket. If you are requested to work on something, people must tag you OR assign it to you. So in this case, you are not being requested to work on it - yet :D

**Comment by MarianaVazquezCYF** [comment]
I am consuded, I moved it to ready to be worked on because it will be done this week and its part of this sprtint? otherwise we could have moved it from backlog to done? 

and yes no actions for you Halden, the one I assigned you its for the next sprint!

**Comment by kfklein15** [comment]
It can only be ready to be worked on when you have all the tickets with the clear description. It can still stay in this sprint (since it is has a dependency with your other ticket), but if it is ready I would assume I should be able to just start working on it - which isn't the case.
