### ISSUE TITLE
Content for LinkedIn

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#49]

**Comment by MarianaVazquezCYF** [comment]
Hey team, what are you working on this week or in the upcoming weeks that is relevant for LinkedIn? (are you invited to a conference, are you going to launch a new book?, did you create open-source content? did you do a collaboration with an organisation? did you/are you going to have a relevant event?  etc...

**Comment by gbencci** [comment]
@MarianaVazquezCYF this is my contribution to this ticket: https://qconlondon.com/speakers/germanbencci

**Comment by MarianaVazquezCYF** [comment]
Amazing!
