### ISSUE TITLE
Organise food for London Job Fair

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#491]
**Background**
During the Job Fair we will be offering some basic food and drinks

**Acceptance criteria**
- Breakfast (croissants and fruit, coffee and tea, milk/oat milk)
- Lunch (soft drinks, pizza) (KFK will check CostCo)
      - Pizza needs to have vegetarian, vegan and normal options
- Food must be enough for 70 people
- Bethan is the contact to support with this

**Comment by MarianaVazquezCYF** [comment]
Hello @kfklein15 let me know if you have investigated about Cosco please!

**Comment by kfklein15** [comment]
Forgot to update on this, sorry. Costco doesn't deliver. Neither does Sainsbury's, but we can order from Sainsbuy's and pick it-up from a nearby shop. If you want me to take a look and make a suggestion so you can approve it, let me know. BUT I only found sandwiches, fruit and dessert, not pastries for breakfast.

**Comment by MarianaVazquezCYF** [comment]
thanks Karen, my only concern is these will be the normal plain meal deal expensive sandwiches?
