### ISSUE TITLE
[Anderson] Templates designs

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#493]
[Here is the Figma file](https://www.figma.com/file/0niiYqGBfCUxfizyKbgJnV/CYF-Marketing-material?type=design&node-id=2750%3A2&mode=design&t=jyQxg1W4YTtMCovZ-1).

**Comment by MarianaVazquezCYF** [comment]
Hello @alecmccrindle, these are the designs that I need that Anderson could design! We have some templates in canvas and would love to have more! 

- [ ] Templates for diplomas, volunteers and tech leaders
- [ ] 1 template for eventbtite and meet up ! 
- [ ] Template for when speakers comes to our events ***
- [ ] 1 template for announcements ***
- [ ] 1 template for a carrucel of announcements
- [ ] 3- 5 different templates for social media *** 
- [ ] 1 template for kudos to a person
- [ ] 1 template for announcement of winners or something
- [ ] 2 templates for looking for volunteers
- [ ] 2 templates for events of the month ***

**Comment by alecmccrindle** [comment]
Hi @MarianaVazquezCYF - that is a long list! Which are the priorities please?

Also, we will need real example copy for each template. I will leave Anderson to add any further comments.

**Comment by kfklein15** [comment]
@alecmccrindle , raise one ticket for each priority template (asteriscs) and close this one, please.

**Comment by alecmccrindle** [comment]
Hopefully split this up by Friday 1st March

**Comment by alecmccrindle** [comment]
I've made all the tickets!
