### ISSUE TITLE
Banners and Posters for Dev World

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#495]
Need to be ready by 27th February

-After the meeting with Alec, we agreed on the following for the dew conference:
[ ] 

- [x] 1 poster that says: we expend our money in trainee expenses, not in stands . this poster should be delivered to our Amsterdam Hotel, location tbc the booth size is 3x3mts
- [x] 1 banner for tech leaders! it could be the same that we had? @alecmccrindle 
- [ ] 1 banner for CYF+ a call to action to look for more partners

**Comment by MarianaVazquezCYF** [comment]
Hello @alecmccrindle so far we just need 2 more banners: 1 poster, and 1 poster for CYF+  we could also pick this up when I come back from holidays, depending on the amount of days it could take them to print!

**Comment by alecmccrindle** [comment]
Hi Mariana, I've made the expenses poster. 

Who is the target for the CYF+ poster? What are we looking for, sponsorship? What should the poster communicate in simple terms? What should the read think, feel and do after seeing it?

**Comment by MarianaVazquezCYF** [comment]
target: tech leaders or leaders in tech! the reader should feel that he/she would like to go to our booth to discover more about what we do! its great is linked to the video, however, in the middle of a conference they are not going to see online content, better to have a 1:1 talk with us!

**Comment by MarianaVazquezCYF** [comment]
Hello @alecmccrindle could you please send the print to this address: 
ibis budget Amsterdam City South

Prof J H Bavincklaan 11183 AT AMSTELVEEN - Netherlands

In addition, if we don't have enough t-shirts at cititec, should we order them directly in Amsterdam? let me know!
