### ISSUE TITLE
Invite companies to participate in the London Job Fair Mar24 stage 2

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#496]
### Background

This stage is from 
Phase 2 - 16 February to 1 March: Goal confirm 4 companies, However lets start doing this right now as on this stage we need to confirm 4 companies! 

https://docs.google.com/document/d/14kq1KoR4XbYMtQkl566xAo-T3sL5vsCudOOiVE0eM8Q/edit

### Acceptance criteria

- [x] Follow up with the CYF Staff team about invites - Halden and Alec
- [x] Make a channel to ask people to help in the CYF- Festival 
- [x] Confirm the invitation with our partner company - Alec
- [x] Follow up with volunteers - Halden 
- [x] Ask trainees to help us invite companies to the job fair - Halden

### Owner

@mariana

### Stakeholder

@alec @german @karen @halden

### Approver

@mariana

**Comment by MarianaVazquezCYF** [comment]
@haldenb @alecmccrindle during this sprint I will be on holidays; therefore, could you please follow up with this ticket? we can have a meeting before I go on holidays to catch up about our progress with invites!

**Comment by SallyMcGrath** [comment]
@haldenb 

If you have completed your tasks on this ticket please check the task list boxes and _move_ this ticket to Done on our board.

When the other people assigned have completed their parts, they can _Close_ the ticket

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , please raise the individual tickets of the leftover tasks, and close this one. Thank you.
