### ISSUE TITLE
Update brochure job fair 

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#498]
-  @gbencci  to take a general look at the [brochure,] https://docs.google.com/presentation/d/1DoIhk_wNu8iQkW13mqx1AXxHPlDT4-kJbAdYP7N86iY/edit#slide=id.gb71e9e03ad_0_141 we still have Caros email, we need to put yours. In addition, please check if you are happy with the messaging . You can edit this copy
- @haldenb  could you please help us to update the projects that will be presented? is slide 11: https://docs.google.com/presentation/d/1DoIhk_wNu8iQkW13mqx1AXxHPlDT4-kJbAdYP7N86iY/edit#slide=id.g26df2751f71_0_160
- I am not too sure about slide 12: https://docs.google.com/presentation/d/1DoIhk_wNu8iQkW13mqx1AXxHPlDT4-kJbAdYP7N86iY/edit#slide=id.g1221fe987bd_0_218, what do you think @gbencci ?
- Slide 15, are we sure these are the companies where our grads work? @gbencci

**Comment by gbencci** [comment]
done
