### ISSUE TITLE
Zambia Project

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#50]
Project doc is here https://docs.google.com/document/d/1onf_ibdjK1jndnXiu1kgbxAcwNZtUz_BETArR05fdMM/edit

**Comment by ClaireBickley** [comment]
I've reviewed MOU and left some comments

**Comment by ClaireBickley** [comment]
MOU finalised, with LREL for feedback

**Comment by gbencci** [comment]
I think we can close this ticket
