### ISSUE TITLE
Catch up Scotland community coordinator

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#500]

**Comment by MarianaVazquezCYF** [comment]
On thursday I will catch up with a scotland volunteer who would like to be a Coco and I will tell her to start organising an event!

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , can you add what was the outcome of this meeting, which even they will start organising (link the event ticket, if there is one). and then close this ticket, please?
