### ISSUE TITLE
events for international womens day Scotland

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#501]

**Comment by MarianaVazquezCYF** [comment]
- [ ] Have a meeting with Morga on February 8th , Cococ volunteer in Scotland to check who is it going for the IWM day event
- [ ] Follow up with any actions from that meeting

**Comment by kfklein15** [comment]
Duplicated with https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/628
