### ISSUE TITLE
Define Duolingo documentation to implement this in Fundamentals

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#509]
### Background
We want to use Duolingo for the English test in ITD and Fundamentals.
For Fundamentals, they need to pass the Duolingo English Test to be accepted into the Software Developer Course (SDC)

### Acceptance criteria
- Create content for Fundamentals using learnings of #507 
- To pass Fundamentals must pass as B2 to be allowed to join Software Developer Course
- Evidence document needed to be able to do this test
- Approve it
- Update Coursework/Prep for Fundamentals

### Owner

@kfklein15

### Stakeholder

Trainees and Graduates

### Approver

Sally

**Comment by kfklein15** [comment]
Screenshots have been saved [here](https://drive.google.com/file/d/1jGckz1kr6XikdCelfjtoy4rRMNdkBmRr/view?usp=drive_link).

**Keynotes from KFK**

Must download the Duolingo Desktop app before doing the test. The app has access to read your screen, record screen and microphone.
Duolingo Dekstop app only works for Windows or Mac: https://testcenter.zendesk.com/hc/en-us/articles/5297715242125-What-devices-and-operating-systems-can-I-use-to-take-the-Duolingo-English-Test-
Must have ID/passport in hand
Must be in a silent location by yourself
Test is quite difficult

**Comment by kfklein15** [comment]
Could the ID be optional?

**Comment by kfklein15** [comment]
Sent Duolingo a message about IDs to understand this: https://mail.google.com/mail/u/0/#sent/KtbxLxgVVfNggtVTDlZMrShTnGbDPcFlxq

**Comment by kfklein15** [comment]
**Accommodation needs**

To submit an accommodation request, follow these steps:

1. Log in to your Duolingo English Test account at [englishtest.duolingo.com](http://englishtest.duolingo.com/). If you do not yet have an account, you may create one at https://englishtest.duolingo.com/register.

2. Once you have logged in, please click this link: https://englishtest.duolingo.com/accommodations

3. Complete the form to request an accommodation. Please note you must enter something in the "Please specify condition" text field when you check the box next to a reason for accommodation.

4. If you have any documentation to support your accommodation request, attach it using the "Choose File" button.

5. Click "Submit Request."

Once they have submitted their request, a supervisor will send a reply to the email address associated with their Duolingo English Test within three business days.

**Comment by kfklein15** [comment]
Asked Sally her opinion on Slack: https://codeyourfuture.slack.com/archives/C05KCLBLG48/p1712569445898629

**Comment by kfklein15** [comment]
**Reply from Duolingo about ID**
A solution would be to provide un-proctored tests that won't be shareable with anyone else but your own Institution, if your use case will just be internal. Proctored coupons could be arranged for your test takers that can meet the IDs requirements.
However we would like to make emphasis on the necessity for test takers to have an ID or any form of documentation that's available for them. These IDs wouldn't need to follow our regular standards (not expired, not damaged, only government, etc) but it would be our preference if possible that an ID is presented during the test.

**Duolingo Test - ID**
@SallyMcGrath , do we know how many of our trainees/applicants would NOT have a valid ID (passport, doc from home office) and would, therefore, have a problem taking our test? Duolingo asked for this number.
I know we don't collect this ID information. Looking at Global Trainees we had 53% SDC AS/Refugees in 2023, but that doesn't mean they don't have IDs.
I am thinking of leaving the ID mandatory and then we pilot it with WM and NW as graduation criteria and see how many problems we have.

I will also see if we can do a process of, when raised that people cannot take the test, we give them this internal test. I just didn't want everyone to miss out on the opportunity of having a decent diploma about their English level.

**Comment by SallyMcGrath** [comment]
Oh yes, I went on such a spelunking trip here! 😂  Here are some of the things I considered:

The key question is what sort of ID is required. It says not their regular ID but what does it mean? Library card? Railcard? 

Asylum seekers have a special biometric Home Office id. Can they use that? (Banks don't accept it; banks want utility bills and doctors letters, which often people don't have).

There's a programme here called [citizencard](https://www.citizencard.com/what-is-a-citizencard) which has [an NGO deal](https://www.citizencard.com/not-for-profit). However it is [a referee system](https://support.citizencard.com/kb/articles/referee-confirming-against-original-documents-route-1). We could be referees, but it's a big ball of admin to throw in front of an English test. On the other hand, it does meet our criteria of "useful on its own terms".  It's not clear how they handle non citizens.  I would actually ask if they would accept library cards. The reason being it is a net positive to all applicants to [get a library card](https://www.gov.uk/join-library), whether they join us at CYF or not. You have to take ID to the librarian to get one, but they accept a wide range of proofs and we wouldn't have to do it ourselves then.

What do you think?

**Comment by SallyMcGrath** [comment]
> do we know how many of our trainees/applicants would NOT have a valid ID (passport, doc from home office) and would, therefore, have a problem taking our test? Duolingo asked for this number.

We don't know. We know it's always some - a minority. But we also don't know the people we lose through asking for this kind of documentation. We know that WM has the lowest number of R/AS/FM trainees and is also the most regulated region, but we don't know if these things are connected.

**Comment by kfklein15** [comment]
Thanks, Sally. Great input as usual. I'll go back to Duolingo asking this.

**Comment by kfklein15** [comment]
Double checking my understanding with the Duolingo team:
1. Every new applicant/trainee will get a voucher from us (CodeYourFuture) to do the test.
2. If they do not have the necessary ID, we'll contact you (Duolingo English Test Support) and you'll generate a "no ID needed" voucher, which we'll send the trainees.

**Comment by kfklein15** [comment]
Reply from them:
1. What we are hoping to do given this ID concern is provide two types of coupons, 
- one set would be for students who wish to have their results shared with other institutions
- the other is for the case you would like to use it for internal purposes, hence no need to have it shared otherwise then we can create an ID leniency for those applicants.
2. If it is a case you have an applicant who would like to take the test and have it shared with other institutions however they do not have any of the accepted IDs as mentioned in the previous email then you can reach out to us and we can assist in a case by case basis.

I have asked for the split for scenario 1. Of the 500 vouchers, what would the split be? I think most of our trainees will want to be able to share their results.

**Comment by kfklein15** [comment]
Ok,the split can be whatever we want. 
@SallyMcGrath , do you have any strong opinion? I was going to propose 450 vouchers to be shared, 50 to not be shared.

**Comment by SallyMcGrath** [comment]
Yes sounds reasonable

**Comment by kfklein15** [comment]
I have created the Coursework on Week 3 of Fundamentals for this test. 
https://github.com/kfklein15/KFK-Test-Coursework-Planner/issues/111
