### ISSUE TITLE
Catch up with Cisco (fundraising and sheffield chapter)

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#511]
On January 30 we will have a catch up with Shaun who is helping us to fundraise money for CYF! I will add as part of the tech leaders strategy because even though he is not a tech leader, he is a leader in tech! and the objectives are fundraising! 

In addition, Shaun lives in Sheffield and he wants to help us with space!

**Comment by kfklein15** [comment]
What is is that we want to catch up about?
What's the goal of this ticket? It shouldn't be just a meeting, but you have an outcome of that meeting you expect. What is that?
