### ISSUE TITLE
Collaborate with Code Division - Jan 2024

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#512]
Continue collaboration with Frank from Code Division, who we share an office with at Princes House / Clutha Trust in Glasgow

Notes from the last meeting are shared in a doc with Frank and German

Frank requested that the collaborative doc be on OneDrive rather than Google, so it is not on the CYF drive yet.

Completion criteria - Meeting Notes
- [x] Tell Germán and Barny about the doc 
- [x] Intro Frank to Strathclyde regarding the youth group interested in coding ([conversation with Strathclyde](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1703872651837729))

**Blocked - moved to new issue** 
- [ ] Wait for Frank to add the updates he planned to (including adding more notes and additional contacts)

**Comment by SallyMcGrath** [comment]
Query, do you mean Code Clan or Code Division? 

I think Code Clan went very publicly bust 6 months ago so would like to know more if it's them.

**Comment by emcglackenr1** [comment]
Update: Moved to backlog while I wait for Frank to update doc

**Comment by SallyMcGrath** [comment]
@emcglackenr1 do you mean Code Clan?

**Comment by emcglackenr1** [comment]
Hi Sally, no I meant Code Division. Updated
