### ISSUE TITLE
Order equipment for dev world conference

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#513]
- [ ] We need to order a screen https://audiovision.nl/en/rentals/projection-screen-211x122cm-roll-up/ @alecmccrindle 
- [ ] We need to check if we have a projector at the office @MarianaVazquezCYF 
- [x] We need to order chairs and table @MarianaVazquezCYF https://service.rai.nl/INTERSHOP/web/BOS/RAI-raievents-Site/en_US/devworld/EUR/ViewStandardCatalog-Browse?CatalogID=RAIMasterCatalog&CategoryName=RAIMasterCatalog

**Comment by kfklein15** [comment]
You are both assigned. Who is actually doing it and who is approving it (cost, for example)?

**Comment by alecmccrindle** [comment]
I don't think we're going to order the screen now?

**Comment by MarianaVazquezCYF** [comment]
no screen, not projector! just the table and that is done! I will close this ticket
