### ISSUE TITLE
Award entries

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#514]
### Background

We would like to create an AI prompt to enter awards. 
And test it with the UFI award entry. 

[Prompt advice here](https://www.thecatalyst.org.uk/resource-articles/how-to-use-chatgpt-to-help-your-charity-meet-its-goals).

### Acceptance criteria

- [x] Review UFI award criteria
- [x] Write and test prompt
- [x] Enter UFI award

### Owner

@alecmccrindle 

### Stakeholder

@MarianaVazquezCYF 

### Approver

@gbencci

**Comment by kfklein15** [comment]
@alecmccrindle , can the title be a bit more specific? Are we talking about an award (then add the name of it)? Or if it is about an AI prompt maybe add that as a title - and then what things should be considered in the acceptance criteria?
