### ISSUE TITLE
Laptop for Ender (WM)

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#516]
### Background

Ender has been volunteering with us in person and in Tech Products since 2023. He is struggling with his computer on the Tech Products side. As per [Slack](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1706273002411249) conversation, we can provide him with a laptop.

### Acceptance criteria
- [x] Identify a computer that he can have
- [x] Set up computer on new laptop loan system
- [x] Get Ender to request a laptop through LLsystem
- [x] Contact Ender and agree how/when to pick it up

### Owner

@MattCFry 

### Stakeholder

Ender

### Approver

N/A

**Comment by MattCFry** [comment]
All laptops in Matt's possession are set up on the new system and created location of 'Matthew's House'. 

Ender has been sent the initial form to fill out and begin the process.

**Comment by MattCFry** [comment]
Ender has signed the contract and we have agreed to do handoff at this Saturday's class (Feb 3rd 2024)
