### ISSUE TITLE
Change to Docs

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#52]

**Comment by lilianabermudes** [comment]
- Remove 
https://docs.codeyourfuture.io/organisation/history
https://docs.codeyourfuture.io/organisation/working-principles

- Add updated links

- Add pages:
Required governance pages should link to our website:
https://docs.codeyourfuture.io/organisation/agreements-and-rules/anti-bribery-and-anti-corruption-policy

**Comment by lilianabermudes** [comment]
@alecmccrindle, I'm following up on this.

The idea was to remove the history from the Docs to make the Docs shorter. But maybe we would need it on the website.  Could it be under Press?

**Comment by kfklein15** [comment]
Just leaving a comment to say I use CYF Docs actively for products and intend to do so for PD too :)

**Comment by lilianabermudes** [comment]
That's fine - we're only discussing the Governance part @kfklein15
