### ISSUE TITLE
Add YT videos to blogs

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#521]
### Background

We have video interviews that we can add to blogs, add them!

### Acceptance criteria

- [x] Create list
- [x] Check previous social media posts for copy to accompany videos
- [x] Add to blogs - making new ones or updating existing ones

### Owner

@alecmccrindle

### Stakeholder

@alecmccrindle

### Approver

@alecmccrindle

**Comment by SallyMcGrath** [comment]
closed as stale
