### ISSUE TITLE
Team priorities and Goals Q1 / H1

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#527]
### Background

We have created v01 goals for Q1, we need to share them for approval. 
In relation to H1 priorities, we need to ensure we're aligned with the org. 

### Acceptance criteria

- [x] Share [goals](https://docs.google.com/document/d/1TjFV8nXIZGWB3jDc2bZoDUs4CTPTrFc-6Nv3OkJm2Ws/edit#heading=h.oy0hv04qai63)
- [x] Update goals on goals doc 

### Owner

@alecmccrindle

### Stakeholder

@lilianabermudes, @MarianaVazquezCYF

### Approver

@gbencci

**Comment by alecmccrindle** [comment]
[Have written updates](https://docs.google.com/document/d/1TjFV8nXIZGWB3jDc2bZoDUs4CTPTrFc-6Nv3OkJm2Ws/edit), will discuss with everyone.

**Comment by alecmccrindle** [comment]
I've updated after our recent discussions. Will work on prioritising this week and make a new ticket.

- Annual Summit
- Job fair for every cohort in every region
- Monthly meetings in every region 
- Senior leaders monthly visit
- Fundraising

**Comment by lilianabermudes** [comment]
Hi Alec,

What exactly should I review? You said you would create a new ticket, so should I wait?

**Comment by alecmccrindle** [comment]
Hi @lilianabermudes - in retrospect, I should have added you to the new ticket, not to this one. 

I've discussed the next steps with Mariana and Karen and I'll make the new ticket with actions for this sprint by tomorrow eop.

**Comment by alecmccrindle** [comment]
Discussion on how to approach these priorities happened in Slack and in meetings, instead of a ticket. We decided to do short and medium term planning in meeting at Cititec on the 21st March.

Following the short and medium term planning, we will have longer strategy and prioritisation sessions with Karen's help.
