### ISSUE TITLE
PD Syllabus Strategy and Learning objectives [Lara]

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#53]
**Overview**
1. Redefine PD purpose/mission (what are the goals and what is the success criteria)
2. Define approach for PD delivery
3. Redefine how PD and Tech Edu work together (more integrated syllabus)
4. Build a global syllabus PD team = a global PD community content adaptation (rebuild PD content if needed WITH the team)
5. Redefine PD buddy system, including the purpose of the PD buddy role
6. Develop and evaluate CYF bot soft skills milestones (currently piloting in LDN8)

- [ ] PD rules: 4h homework / 1.5h class / objective must be per class  / 1 piece of coursework should be key (ONLY one)

**Comment by kfklein15** [comment]
I need to consider how I will break this down into smaller tickets (if needed)

**Comment by gbencci** [comment]
What I'd like to cover to start with:

- Examples of sessions we've had in the past with role playing and mini-performances
- Other areas we might need to cover to give our trainees holistic powers
- Define the key building blocks of PD throughout the program in modules, mimicking the tech syllabus
- Find a way in which we can implement the rubrics to the whole community

**Comment by kfklein15** [comment]
Link to [Miro board](https://miro.com/app/board/uXjVPsoyaYc=/?share_link_id=904794367201)

**Comment by kfklein15** [comment]
1. Redefine PD purpose/mission (what are the goals and what is the success criteria) - [2022 Document](https://docs.google.com/document/d/1Udr7hjb6gDaJvH1ad1uuzEz3Rjzz1cZOmUImm0Xkh7U/edit)
2. Define approach for PD delivery - [Roles document](https://docs.google.com/presentation/d/1wsbBUMBlZs5bKQrpufE0h4ZoqAXXyK0Rr7YXzW5lHlc/edit#slide=id.g12faadf4818_1_1) (PD trainers/buddies) / refer to organisation if needed **(70% trainees are fine, how to support the 30%)**
3. Redefine how PD and Tech Edu work together (more integrated syllabus) - [Mapping](https://docs.google.com/spreadsheets/d/1S0h66lDGXwc1RiuufJDzB5R-YFrr2qNMIq5xxai_hxA/edit#gid=1083171479)
4. Build a global syllabus PD team = a global PD community content adaptation (rebuild PD content if needed WITH the team) - **Irene/Matt/Alfonso, Monday meetings**
5. Redefine PD buddy system, including the purpose of the PD buddy role > WM Test 1 PD buddy for 5 trainees (go through the coursework with the trainees + check-in), most challenges 1-2- Candy for 6 weeks
6. Develop and evaluate CYF bot soft skills milestones (currently piloting in LDN8) > Mentor Bot - adding rubric to it

**Comment by kfklein15** [comment]
Possible Global Team Supporters:
- SA - Lizelle Wakefield (or refer someone?)
- Employability input - Mark E.
- Glasgow - ?
- NW - ?

**Comment by kfklein15** [comment]
https://twitter.com/SahilBloom/status/1626949157998002176

**Comment by kfklein15** [comment]
Talking to Claire today we also talked about: how to use Calendar (viewing someone else's availability, for example).

**Comment by kfklein15** [comment]
[NW PD Retro](https://metroretro.io/board/LBH5316DHCSZ)

**Comment by kfklein15** [comment]
Spreadsheet with all [Learning objectives](https://docs.google.com/spreadsheets/d/1bTWa9PTG9p5Q0q5Ux8i5Fxt9YrGKJ_gIKoeKNEurXP4/edit#gid=0)

**Comment by kfklein15** [comment]
[Roadmap](https://docs.google.com/spreadsheets/d/1bTWa9PTG9p5Q0q5Ux8i5Fxt9YrGKJ_gIKoeKNEurXP4/edit#gid=1165389937) being worked on.

I will close this ticket since we are now going into the implementation phase. We'll open smaller/specific tickets with the following steps if needed (i.e. with a tactical approach).
