### ISSUE TITLE
Help find new trustee

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#532]
### Background

We need a new trustee, I'm going to ask a friend to help us find one

### Acceptance criteria

- [ ] Check with Lili this sprint on brief
- [ ] Share brief with Traci / network

### Owner
@alecmccrindle

### Stakeholder
@alecmccrindle

### Approver
@alecmccrindle

**Comment by gbencci** [comment]
Hi Alec, @lilianabermudes  is already working on this as a ticket. Once the JD is live, then you can ask your friends for it. But you can start telling them anyway.

**Comment by alecmccrindle** [comment]
Thanks, updated the ticket :)
