### ISSUE TITLE
Research PO BOX for CYF

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#534]
**Background**
We will not be able to rely on Cititec's office anymore, so we need a new central address to receive CYF's mail.

**Acceptance criteria**
- Check PO BOX possibilities
- Confirm costs/ requirements

Stakeholders
@lilianabermudes 

Approver
@gbencci

**Comment by ClaireBickley** [comment]
The process seems straight forward and we can set it all up online. There are 2 options:
- PO Box collect - post is delivered to a delivery office, somebody needs to go and collect it.
- £39.60/month DD or £192 for 6 months, or £330 for 12 months
- PO Box devlier - post is forwarded on to another address of our choosing
- £39.60/month DD or £219 for 6 months, £396 for 12 months
- [Link](https://www.royalmail.com/po-box)

Next steps @lilianabermudes @gbencci :
- decide which option we want and for how long
- decide on an address to give (it needs one for the registration)
- set up and pay

**Comment by gbencci** [comment]
Please choose the most flexible option and easiest for people. That is goes directly to their address

**Comment by lilianabermudes** [comment]
Questions:
- Who's "people"? 
- We're only talking about CYF main mail, I assume, the ones coming to London?

**Comment by ClaireBickley** [comment]
yes, if we want the option for it to be forwarded to another address, whose address should it be? We can only choose one address to forward to, not multiple.

**Comment by lilianabermudes** [comment]
I don't mind if it is sent to my address, but we have to bear in mind that I live in a rented flat in a building, so other people can grab the mail by mistake, etc. Not super common, but there's this risk.

If we think that's okay, I'm fine with it as long as I know what kind of mailing I'd be getting :)

**Comment by ClaireBickley** [comment]
likewise, I don't mind it being my address (not in shared building)
I think most things we get in the post are going to be Ops/Finance related so it makes sense for it be one of our team

**Comment by lilianabermudes** [comment]
Okay, probably best to be at my address - otherwise we'll need to change again when you go on leave :D

121 Hornsey Lane, London 
Flat 9
N6 5NP

**Comment by ClaireBickley** [comment]
yes, of course - do we want to do the monthly option or something more long term?
Do you think we could use this for people to post laptops back to us?

**Comment by lilianabermudes** [comment]
Good point, I think for the storage of laptops we'll need something else.

I'd suggest we do the PO Box for 6 months to see how it will work.

**Comment by ClaireBickley** [comment]
sounds good - although I've tried setting it up and we still need a registered address for the org. So we can use a PO Box but still need some form of address. It is asking for the address of the business when I try to set it up.
[Requirements for address](https://www.gov.uk/limited-company-formation/company-address#:~:text=You%20can%20use%20a%20PO%20Box%2C%20but%20you%20must%20still%20include%20a%20physical%20address%20and%20postcode.)

**Comment by lilianabermudes** [comment]
Does it need to be the same address? (I've read, but I'm still not sure).

**Comment by ClaireBickley** [comment]
yeah so we need a registered address for the organisation - the PO Box will just be where post arrives.

**Comment by gbencci** [comment]
maybe try somewhere else? I googled it and got this: https://www.charityconnect.co.uk/post/virtual-office-address/7028

**Comment by ClaireBickley** [comment]
Done some googling and looks like we need a registered office address, potentially with a virtual office option or a mailbox rental. Putting some links I found here, will look into them further. Lots of them are Birmingham but I'll look at London, just the location settings brought these up in the search.
[https://www.mbe.co.uk/birmingham/mailbox/registered-company-address](https://www.mbe.co.uk/birmingham/mailbox/registered-company-address)
[https://birminghamvirtualoffice.co.uk/registered-address/](https://birminghamvirtualoffice.co.uk/registered-address/)
[https://www.ukpostbox.com/address/business-address-service](https://www.ukpostbox.com/address/business-address-service)
[https://www.registeredaddress.co.uk/officeservices](https://www.registeredaddress.co.uk/officeservices)

**Comment by lilianabermudes** [comment]
Hi Claire, thought about it after seeing the emails about the office in London. We can pick it up again by the end of the week/ or when possible.

**Comment by ClaireBickley** [comment]
Yes - let me sort BreatheHR this week and then I can get back to this.

**Comment by ClaireBickley** [comment]
closed - virtual office set up
