### ISSUE TITLE
Too many slack channels in London

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#536]
### Background

There are too many slack channels. It is annoying. People miss things.

We need to archive them.

### Acceptance criteria

- let community know you will be archiving channels - specifically separate class/ volunteer channels - ask for other unused channels
- archive and condense 
- Write post and update canvas informing community of changes
- stay sane 

### Owner

@halden

### Stakeholder

@halden

### Approver

@halden

**Comment by MattCFry** [comment]
Remember to do the ticket refinement (right-hand side) before moving to ready ❤

**Comment by haldenb** [comment]
Thanks, hows that?

**Comment by SallyMcGrath** [comment]
How could volunteers do this? Who else in London can archive channels? 

https://slack.com/intl/en-gb/help/articles/213185307-Archive-or-delete-a-channel

**Comment by MattCFry** [comment]
It looks good, Halden 😄 . Would you like to refine for the other boards this ticket is on? Unfortunately, labels and such do not translate.
