### ISSUE TITLE
Make a canvas for active cohorts

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#537]
### Background

As we look to make better utilisation of canva cohorts, we should have one which provides expectations, rules, community guidance and motivations for trainees. This canva would be useful if this was usable both during and after the SDC. 

### Acceptance criteria

- [ ] Canva should include baseline information about how trainees operate during their time at CYF
- [ ] It should encourage community action and interaction
- [ ] Communicates the core values of CYF
- [ ] Links to curriculum
- [ ] Easily implementable in all global cohorts

Upon completion
- [ ] Shared in Prom channel, explained and feedback requested

### Owner

@

### Stakeholder

Proms / Community Team / Programme Team

**Comment by MattCFry** [comment]
Would be really cool to leave some room for the community to own it and make edits to it.

**Comment by emcglackenr1** [comment]
Merged with issue [#587](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/587)
