### ISSUE TITLE
Individual donors

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#54]
- [ ] Update Paypal design @alecmccrindle

**Comment by MarianaVazquezCYF** [comment]
- [ ] One sheet on individual donations? [Alec McCrindle]

- [ ] Gen video for folks to share - what does CYF do [Alec McCrindle]

- [ ] Sally on Github [Mariana Vázquez]

- [ ] Staff folks post about individual donations campaign [Alec McCrindle] and [Mariana Vázquez]

- [ ] PR agency - charities in tech (later [Alec McCrindle]
- [ ] Volunteer Newsletters no go for now

- [ ] German TED talk [Mariana Vázquez](we need a biography) 

- [ ] Obama leadership programme [Mariana Vázquez]

- [ ] Invite donors to attend the class [Mariana Vázquez](

WOM

- [ ] Create the material about donations / Speak to volunteers about the opportunities to donate/fundraise/connect us with their company [Mariana Vázquez]once we’ve made the material 

Events

- [ ] Women’s Day, Diversity, Volunteer month, Mental Health (volunteering makes you happy) and - fundraising events, eg. spinning, etc [Mariana Vázquez]
(we are just finishing the details with the venue and @alecmccrindle I was thinking we can also "sell" some special t-shirts for the event! can we do a special design please? :D 

- [ ] Ask our volunteers to do their own fun events [Mariana Vázquez]

Website
What needs to change? 
Other
Merchandising (later)
CYF shop (black shirt is only ever earned)

**Comment by alecmccrindle** [comment]
- [ ] Mariana to check with Germán about tshirt costs
- [ ] Alec to find a way to get them ordered online

**Comment by SallyMcGrath** [comment]
This ancient ticket is not assigned to any board. If it is is completed, please close it. To close a ticket you press the Close button.
