### ISSUE TITLE
Review and archive old West Mid Slack channels

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#540]
### Background

We are now in our 5th cohort and WM has begun its 4th year. It's time we have a sizable cleanup of slack. 

I am fine keeping larger cohort channels or still active channels. 

### Acceptance criteria

- [ ] Search through slack using key terms like 'wm , 'west mids' or 'west midlands' 
- [ ] Close any channels which are inactive
- [ ] Spare any large cohort main channels 

### Owner

?

### Stakeholder

WM community

### Approver

?

**Comment by MattCFry** [comment]
A great aim for this would be for community members to do this and have a mindset of when channels are no longer of use.

Halden made a good post, which Dara shared to Scotland.

**Comment by kfklein15** [comment]
Done today
