### ISSUE TITLE
Create Github Issue Form for Slack Posts

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#547]
**Summary:**
Creating an issue form template for drafting my Slack posts. Storing for now on my own Github repo and project board rather than CYF to test. This way it's less messy. No private data to be added there since it is a non-CYF repo and private board. 
I am still working on the question prompts.

Completion criteria:

- [x] Set up other project board
- [ ] Set up form (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [ ] Create questions
- [ ] Test the system - use old Slack posts if possible to gather more information
- [ ] Search for Udemy or similar information on making engaging Slack posts
- [ ] Ask the community for feedback on some posts 

Review process and it's impact on: 
- [ ] Own workflow - did this feel like an improvement?
- [ ] Effectiveness of communications - was the purpose clear to those who read it?
- [ ] Effectiveness of communications - was there interaction with it?
- [ ] [add other criteria here]
- [ ] Discuss process and impact with team 

Example might be:

**- Title:** 
Post about community event

**- Content:** 
[Draft + Emojis + tags ]

**- Has this post been done before? And are there drafts you can use to save time?**
 This particular event no, but other events such as [link] and [link] can be used for inspiration. The email also had all required info about the event. 

**- Why am I posting this?** 
To Communicate Information about an event that may be of interest

**- Does it have to be me that posts this?** 
At the moment, yes, because only I have access to the Scotland email address the information was sent to. It would be better if this was automated somehow, or if someone in the community did it.

**- If yes, how could I hand this to the community?** 
Could this be a tender? Where there is somewhere anyone in the community can post an event? e.g. could have a form where the information is copy-pasted and then submitted onto an interface?
Could there be an ''interesting events'' Scotland calendar that was separate to the other Scotland calendar? (hand to CoCos)
Could this then automatically post onto Scotland-events? Would this kill interaction with the channel 🤔 

**- Could this be automated?** 
If there is a volunteer email address, it could be signed up to events instead. Information could be pulled from there and places elsewhere?

**- Who is this for?** 
All Scotland Community. 

**- Additional information / background** 
This is an event from an organisation that community members have shown interest in in the past. 

Purpose of this task:

- Questions to prompt myself to consider why I am posting and what it will achieve
- Distance from Slack - on a different platform so more time to consider
- Plan posts ahead of time
- Review interaction with the post and why there was a response or not
e.g. previous insights with posts using a poll via emojis get more responses if the options are already there, rather than if responders have to go find them. 
Volunteers also adopted this method: https://codeyourfuture.slack.com/archives/C02NSEF31JT/p1700165348088859

**Comment by SallyMcGrath** [comment]
I'm going to remove the deadline from this and throw it in the Backlog. It's not a priority and it's past due.

**Comment by haldenb** [comment]
Hey is there anything I could do to help with this ticket? :)
