### ISSUE TITLE
Events for IWD WM

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#550]
We want events in all the region for international women day! 

- [ ] Find a volunteer or partner with an organisation to co-host an event! In the case of WM , contact women in tech WM

**Comment by MattCFry** [comment]
I think it would be really cool if we approached Aston uni with this. They've done tech events before. I think they even did something for Birmingham tech week last year

**Comment by MarianaVazquezCYF** [comment]
oh greeeat idea Matt!!! do you have some contacts or how to approach them?

**Comment by MattCFry** [comment]
So we have a contact. Her name is Eleanor Barkham. It's not 100% clear what her job title is, but she was the one who managed the relationship between us and Aston and helped us get a contract signed by the legal department at Aston.

Tony B is our WM5 cohort founder and has helped with the relationship.

I think you should approach Tony, ask who he thinks is a good idea to contact and go from there.

**Comment by MarianaVazquezCYF** [comment]
Great thanks Matt!

**Comment by MarianaVazquezCYF** [comment]
Update: Mariana to ask Laura, to organise an on fridays we do demos as a special event for international women day!

**Comment by MarianaVazquezCYF** [comment]
We will not move forward with this regional event!
