### ISSUE TITLE
Design a new onboarding process

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#551]
### Background

- at CYF we do not lecture - we avoid slides
      - the first thing new volunteers see is a list of slides
- we then create a bottle neck once they get into our slack (how do they know what team to join etc - Proms message...)
- volunteers get lost along the way 
- the communities themselves do not welcome new volunteers 
- volunteers end up being picked up by regional teams - lost opportunity to facilitate inter regional teams

### Acceptance criteria

- create new welcome session that reflects values and ways of working - https://docs.google.com/presentation/d/1zCpKwq2IWPk_LXkgr47OOlBclen-jj06ePjIfLixTrU/edit#slide=id.g15d7afd85d9_0_7

- empower TRAINEES in each region oversee CYF-Volunteers and welcome new vols (make them aware that volunteer welcoming, informing and engagement is their responsibility) 

Definition of done:
- volunteers post meaningful hello messages in CYF-Volunteers (including region, key skills, tech stack, what they want to do)
- trainees reply meaningful response and answer vol questions (eg. I can see you you are a backend developer, we are studying node from next week please join (regional volunteer channel) and (regional class channel) for more information.
- volunteers volunteer where they are welcomed by trainees

The dream:
- this becomes self-reproducing, the CYF-vols channel becomes a bank of success, new volunteers scroll up to see posts that work when they enter and copy them
- volunteers work asynchronously supporting all regions (setting up evening calls etc as in the cloud module 3)

### Owner

@halden

### Stakeholder

@dara

### Approver

@halden

**Comment by MarianaVazquezCYF** [comment]
Hello Halden, could you please make a proposal? Love the idea of trainees being empowered ! This is a project we were working with @kfklein15 with a external company that were going to help us with some authomatisation! https://www.figma.com/file/975vA8tvfN8RCPXGS39tSB/Volunteer-onboarding-process?type=whiteboard&node-id=6-316&t=Di9UZCv1CgKe8x0e-0
