### ISSUE TITLE
Add all Udemy Users into Groups

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#552]
### Background

We need to manage licences in Udemy. Thus far, the system is organising trainees into cohort groups and other users into groups like staff.

Several users do not belong to any group. In the long run, this will make licence management difficult.  

### Acceptance criteria

- [x] All active cohorts have a group 
- [x] It is established how adding trainees to non-cohort groups is managed
- [x] All Staff users belong to the staff group
- [x] All trainees belong to a group for their cohort

### Owner

@mattcfry

### Stakeholder

@CodeYourFuture/programme-managers, Programme Team

### Approver

@mattcfry

**Comment by MattCFry** [comment]
I've made two slack threads to address this. 

- [Part 1](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707306567411489) - Remaining users, what group do they belong to?
- [Part 2](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707306877885059) - What groups are necessary?

@CodeYourFuture/programme-managers, can you review these when you get a chance? Thank you

**Comment by MattCFry** [comment]
This ticket is being done in conjunction with [Clawing Back Udemy Licenses](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/419)

**Comment by SallyMcGrath** [comment]
I think the Laptop Loan work is much more important than this task. What do you think?

**Comment by MattCFry** [comment]
Sure. Udemy is an okay place where I can leave things be.

With the laptop loan system I am not 100% sure if it's in a position to role out widespread yet. I think we need to get staff onboarded first and get regional inventories up to date. 

I'll brainstorm next steps and tickets today.

**Comment by SallyMcGrath** [comment]
I think it's pretty simple, tbh!

Ill make you some tickets.

**Comment by SallyMcGrath** [comment]
Ok I made you the tickets and assigned them to this milestone

https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/20
