### ISSUE TITLE
Checkin on GLA6 Cloud

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#554]
Unsure how Glasgow-6 course completers doing cloud is going.
Course completers expressed concern about knowing how to work on the Cloud module, and finding it difficult. Ideally we would have a Glasgow based, very involved Cloud volunteer, but we don't. They expressed finding it difficult because London have contact with so many more volunteers in person. 
The issues could either be just because the module is hard, or could be a facilitation issue we can solve with volunteers.

**Observations Class Saturday 3rd of Feb**
- Glasgow volunteers support them on the day, but they didn't join London10 support remotely. 
- They were not in one study group, it was two individuals working together and one working on their own. (This may have been partly because one individual was further ahead, and also working on another project for portfolio)
- As far as I know, no Glasgow volunteers are committed to volunteering for cloud, so they don't have the in-depth knowledge of the module. They will help if asked directly on the day. 

**Other observations / concerns**
There is no visible tracking system of how GLA6 in particular are doing and engagement is hard to track without a Scotland volunteer keeping an eye on it. e.g. 
- When I wrote this issue, only one member of GLA6 had added their name to [this spreadsheet ](https://docs.google.com/spreadsheets/d/12E2lItp_8Qe9eLUfzVh-leeDcfZOFh-ATj6jDd_5i38/edit#gid=0)and responded to [this poll ](https://codeyourfuture.slack.com/archives/C06EGMX7K35/p1707035388951999)
- Some Glasgow course completers are not engaging online as much as London

Completion Criteria 
- [x] Ask Cloud trainees 
- [x] Ask volunteers - Scotland

If the feedback from trainees is there is a facilitation issue:
- [x] Put to trainees to ask Cloud volunteers and other trainees on course via Slack 
- [x] Put to volunteer who responded to ask Cloud volunteers

**Comment by emcglackenr1** [comment]
Current activity - waiting for responses from GLA6 trainees and volunteers
Outcome: All trainees bar one have responded with feedback on the module / explanation on if they want to apply for the role or not. 

[Volunteer responded,](https://codeyourfuture.slack.com/archives/C02NSEF31JT/p1707230758148479) I replied, [asked for feedback on my response ](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707405809018959)
Awaiting further action from volunteers on #scotland-volunteers or [#cloud-module-volunteers](https://codeyourfuture.slack.com/archives/C05KRNW8D25)

**Comment by emcglackenr1** [comment]
Will review at class 9th Feb 2024

**Comment by SallyMcGrath** [comment]
@emcglackenr1 how did this go? Can this ticket progress to Done?

**Comment by emcglackenr1** [comment]
Yes this is done
