### ISSUE TITLE
Upload WM5 JS3 Exit Codility Results

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#555]
### Background

WM5 has completed this Codility. Here is [them discussing their results](https://codeyourfuture.slack.com/archives/C05UPN70GCC/p1707147374511879). 

Matt has been having difficulty. Here is [tech ed tools](https://codeyourfuture.openclass.ai/classes/tech-ed-tools) to help. Matt has shared tracker with @CodeYourFuture/programme-managers.

### Acceptance criteria

- [ ] The tracker produces the desired results with 'Get Codility' function. 
- [ ] Any external versions of the results sheet is deleted from all drives, emails and machines. 

### Owner

?

### Stakeholder

@CodeYourFuture/programme-managers

### Approver

@mattcfry

**Comment by haldenb** [comment]
What is the desired result? :)

**Comment by haldenb** [comment]
What is the desired result? :)

**Comment by MattCFry** [comment]
Maybe I should have used better wording. According to the script, once the function is run, the trainee performance points change by the following.
 * 1 for not taking the test
 * 2 for taking it
 * 3 for getting any score
 
 This isn't the case when I run it. [See this thread.](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707237831320219).

I guess it should be 'intended result'?

**Comment by SallyMcGrath** [comment]
Your trainee tracker was not in alphabetical order, so your Codility function could never work.
