### ISSUE TITLE
Import Laptops into new system WM

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#557]
From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#556  

### Background

We have a new laptop loan system. We have an existing messy spreadsheet that still needs some information pulling from before we can archive it. Break this down into regions and spend up to 3 hours a week on it. 

### Acceptance criteria

1. Our laptop airtable lists all the laptops we have an existing record of
2. Our laptop airtable lists the state (perished, loaned, etc) of each laptop
3. Our laptop airtable lists the location of each laptop

### Owner

n/a this system doesn't work for our team

### Stakeholder

@SallyMcGrath

### Approver

@ClaireBickley

**Comment by MattCFry** [comment]
The first thing I decided to do was verify our current records. Claire worked with me to consolidate the WM laptop inventory and decide who should contact about their laptop record. 

I will mail merge these people to understand the status of their laptop possession and if it needs to be returned. After this, it should be a straightforward entry to the new system.

For the record, I will class the Birmingham storage as global. I will enter that separately into the new system.
