### ISSUE TITLE
Import Laptops into new system GLA

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#559]
From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#558  

From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#557  

From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#556  

### Background

We have a new laptop loan system. We have an existing messy spreadsheet that still needs some information pulling from before we can archive it. Break this down into regions and spend up to 3 hours a week on it. 

### Acceptance criteria

1. Our laptop airtable lists all the laptops we have an existing record of
2. Our laptop airtable lists the state (perished, loaned, etc) of each laptop
3. Our laptop airtable lists the location of each laptop

### Owner

n/a this system doesn't work for our team

### Stakeholder

@SallyMcGrath

### Approver

@ClaireBickley

**Comment by MattCFry** [comment]
I am just waiting for the final verification of GLA 6 records, and then I can finish uploading.

**Comment by SallyMcGrath** [comment]
Dependency on #571

**Comment by MattCFry** [comment]
The only laptops not added are the ones considered AWOL and we are not confident we will ever see again. If circumstances change they can be added on at a later date.
