### ISSUE TITLE
Import Laptops into new system GLOBAL/REMOTE

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#560]
From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#559  

From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#558  

From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#557  

From CYF-Staff-Tickets created by [SallyMcGrath](https://github.com/SallyMcGrath): CodeYourFuture/CYF-Staff-Tickets#556  

### Background

We have a new laptop loan system. We have an existing messy spreadsheet that still needs some information pulling from before we can archive it. Break this down into regions and spend up to 3 hours a week on it. 

### Acceptance criteria

1. Our laptop airtable lists all the laptops we have an existing record of
2. Our laptop airtable lists the state (perished, loaned, etc) of each laptop
3. Our laptop airtable lists the location of each laptop

### Owner

n/a this system doesn't work for our team

### Stakeholder

@SallyMcGrath

### Approver

@ClaireBickley

**Comment by emcglackenr1** [comment]
Potential task for this issue and the individual regional ones.

- No longer necessary: 
- Convert laptop inventory into same format/layout as Airtable inventory for easier import. 
Unsure if this should be completed by each PROM or @MattCFry

**Comment by SallyMcGrath** [comment]
I just don't think we have so many laptops that we need to bother adding extra steps like an extra data input process.

It's really just a case of sitting down and typing them in. It's not gonna take more than a couple of hours. We don't have ten thousand laptops.

Matt can take charge of this. It's not a huge job.
