### ISSUE TITLE
Review Laptop Loan Data Import and mothball old system

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#561]
### Background

We have built a new laptop loan system. We are importing our old data and once this is done we need to clear up the old system so nobody keeps on using it. 

### Acceptance criteria

- [x] #556 
- [x] #557 
- [x] #558 
- [x] #559 
- [x] #560 

### Owner

n/a this system doesn't work for our team

### Stakeholder

@SallyMcGrath

### Approver

@ClaireBickley

**Comment by MattCFry** [comment]
The imports should be complete. I've marked in yellow on the spreadsheet laptops where we need to know where they are or are AWOL. 

I could ask either Dara, Shaun or Halden to review. That would create a dependency on onboarding them to Airtable.

**Comment by MattCFry** [comment]
@SallyMcGrath, the review and this milestone is complete.

I've added [ARCHIVED] the[ Laptop Inventory UK](https://docs.google.com/spreadsheets/d/1QeZmhAKSD8k4lyIpWrZvZM3voWKf9rnSpI0WpcJIDLg/edit#gid=2072559628).

Apart from communicating a note on the daily, are there any other steps for this changeover?
