### ISSUE TITLE
Invite companies for the Festival of Diverse Talent LDN10

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#562]
Hello German, I have tagged you in this document. https://docs.google.com/spreadsheets/d/1THxEqrJw-OaJZK6Q919cGPRmFtFNx2VgLhZY_Hy0NfA/edit#gid=0, where there are some companies that I think you could invite! These are companies I know we have had some conversations. Please also add more companies ! 

Thank you!

**Comment by gbencci** [comment]
Thanks! Updated!
