### ISSUE TITLE
Reaching out to GLA6 FP Volunteers

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#563]
**Summary:**
Portfolio 2 is starting soon in Glasgow. It would be great if some of the FP volunteers could return for Portfolio 2 to support with projects. Final Projects went quite well in Glasgow. There were some amazing volunteers involved. It would be great to get them back and to understand why they haven't returned.

**Desired outcome**
- Lets work on this together! I would think at least 2 FP volunteers do some variation of: coming to a class planning meeting, coming in person to class, posting / commenting on Slack, provide remote support etc.
- Ideally, we would have one volunteer active either in class or during the week that could support with each Portfolio project so the outcome was successful.

**Potential discussion points:**
- How has this worked in other regions? Have FP volunteers remained for Portfolio? If not, were steps taken to encourage them to return for it?

**Comment by emcglackenr1** [comment]
Hey! @haldenb Can you explain why this is 'in review?'

**Comment by haldenb** [comment]
My thoughts:
- let's move towards only having one group of volunteers - they can be called CYF volunteers (they can do more than one task and do not have artificial end dates) for channels lets have 1 channel in each region for volunteers maybe Glasgow volunteers? This seems super complex and like the complexity is causing the blocker?
- Can the trainees from their FP group invite them to the PF module? I think one message in the trainee channel can achieve this - "Do you want more volunteers in PF module? Have you ivited volunteers from the SDC and Launch projects?" Reply [insert emoji] if you have

In London I do not chase up volunteers outside of messages in group channels

When trainees say they would like more volunteers I ask what they are doing to get them, whether they have messaged volunteers inviting them to a class.

**Comment by emcglackenr1** [comment]
Hi Haldan, 

I'm not sure what you mean by this being super complex. The notes were perhaps too complex, but the task isn't. It's just reaching out to a group of formerly very active volunteers. I understand not reaching out in London where there are so many volunteers, but I would think it has value in other regions? I'm unsure.

- I like the idea of asking trainees to contact them. 🎉 
- I also think your solution of one post sounds good. 👍 

I maybe overdid it with the amount of info I put on this and made it confusing. The task is just reaching out to former FP volunteers, so I described ways you could get that list. 
I referencing old slack user groups because it meant you could easily tag them in a post. I agree that the plan is to merge them into one group (currently scotland-volunteers). 
During FPs they were a separate group because of how FP ran. The user groups aren't used anymore, it was just a way to direct you to names. I also offered to list them elsewhere. 

We can of course also archive channels too. I think that relates well to #591 where I mention using your advice about Slack.

I've simplified the ticket above and put in backlog because you are away.

**Comment by SallyMcGrath** [comment]
Let's put a due date on this ticket please - when is the Portfolio module starting?

**Comment by emcglackenr1** [comment]
Unfortunately, Portfolio 2 started last weekend. I still think there is value in reaching out to these volunteers somehow.

**Comment by emcglackenr1** [comment]
Turned into a new ticket #721
