### ISSUE TITLE
Update laptop inventory Scotland with volunteer notes

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#569]
Relates to #567 

Completion criteria
- [x] Volunteer to check laptop inventory in storage at Princes House
- [x] Dara to add findings/updates to the laptop inventory (because the volunteer didn't have access to the laptop inventory)
- [x] Let Matt know when above are complete because of #571 

Relates to issue: #589 
Completed tasks relating to 589 have been moved to that issue from here

**Comment by SallyMcGrath** [comment]
This seems to be past its deadline. I'm raising the Priority and promoting to Ready

**Comment by emcglackenr1** [comment]
Hi Sally, I've updated this and split into two tickets. It should have been two in the first place. Moving this part to done as it was completed this sprint.
