### ISSUE TITLE
GLA6 Meeting More Grads

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#570]
**Background**
It would beneficial for GLA6 to meet more grads from other regions. We don't have many active grads in the region. How can we address this?

**Why should we do this?**
- In general, this has been shown to be beneficial across regions. 
- Course completers have expressed wanting to meet other grads in the past (see below)

**Request to Meet Grads from a Non-Tech Background**
Following @Barny-6 's discussion with GLA6 about employability and portfolio, 3 course completers expressed to Dara/volunteers that they want to meet more employed grads who had no tech experience before CYF.

**Steps taken:**
Dara posted first on [the PROM channel,](https://codeyourfuture.slack.com/archives/C029341FPH6/p1705769880350939) and then in [this open channel.](https://codeyourfuture.slack.com/archives/C011T8UHVV0/p1705916011076469)

There was a response from grads from other regions, which was great! However, the GLA6 course completers didn't respond. It feels like this ties into #591 - Slack Engagement Issues and [this milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/26). 

If this ticket is worked on before Slack engagement improves, options for how to facilitate this will be impacted.

**Completion Criteria** 
- [x] Discuss with volunteers at volunteer meeting (1st March) - Dara
- [ ] Barny and Dara /volunteers to discuss other ways to facilitate this, considering the lack of engagement on Slack
- [ ] TBD

**Related Milestone **
Because course completers expressed this would help reassure them before applying for jobs, this also potentially relates to https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/29

**Comment by haldenb** [comment]
What do you mean by meet grads? Has this come from the community? What did they say they wanted? **Can they ask for it in a public channel?** Do we need to do anything here at all?

Ask them to:
- Post in public channel #cyf-volunteers would probably work 
- They can tag me and whoever organises the agenda for Saturdays so they can agree a time on a Saturday
- I will tag grads I know

**Comment by emcglackenr1** [comment]
I have updated the summary above to answer your questions 👍

**Comment by haldenb** [comment]
I don't understand this ticket what needs to be done?

**Comment by Barny-6** [comment]
Agree with Halden. I'm unsure what the action is - is it to find speakers who are Glasgow alumni?

**Comment by emcglackenr1** [comment]
I want to discuss what the actions would be, that's why it's not in ready yet. Since intro'ing them on Slack didn't work, I think we should take another step. I have added two actions, please add more if you think of any that would help.

**Comment by Barny-6** [comment]
Okay, I see. I am also talking to Morgan on Slack is that part of this ticket?

**Comment by emcglackenr1** [comment]
Unless Morgan is a grad, or is a volunteer who is going to introduce trainees to grads, then I don't think so?

**Comment by haldenb** [comment]
Morgan McClure? Looks like Morgan is setting up events? That would be a great place to introduce/ get grads back involved

**Comment by emcglackenr1** [comment]
I've invited previous GLA grads to the community event based on this ticket https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/800

It would be good to facilitate this another way as well, for example, a remote chat the grads + course completers can organise, or sharing recorded interview(s) of successful grad who didn't have a tech background
