### ISSUE TITLE
Verify LDN Laptop Inventory

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#572]
### Background

We need to enter all of our records into the new system as part of [this milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/20) before we can roll it out for global usage.

Many global records need verifying before entering the new system as usable records.

### Acceptance criteria

- [x] (Halden) Identified those on their laptop inventory who should be contacted.
- [ ] (Matt or Halden) Cohort and Email Identified.
- [ ] (Matt) The people identified should be contacted via mail merge.

A week after the mail merge for a region has been sent, the work in that region can be considered complete on #567. 

### Owner

@mattcfry

### Stakeholder

@haldenb 

### Approver

@MattCFry

**Comment by haldenb** [comment]
Hey Matt 'what does Cohort and Email Identified' mean?

**Comment by MattCFry** [comment]
Just that we figure out the cohort of everyone on the list (not critical) and pull the email from global trainees.

I've started the mail merge spreadsheet. I'll share it with you (not here if it will have sensitive emails). 

This task isn't a priority for me so don't feel like we need to worry about it today.

**Comment by haldenb** [comment]
I have added the ones I know from the top of my head

**Comment by MattCFry** [comment]
I've shared the mail merge sheet with you. I won't work on this for a while, but if you find yourself with spare time, then feel free :). Again, it's not urgent at all.
