### ISSUE TITLE
Verify NW Laptop Inventory

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#573]
### Background

We need to enter all of our records into the new system as part of [this milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/20) before we can roll it out for global usage.

Many global records need verifying before entering the new system as usable records.

### Acceptance criteria

- [x] (Barny) Identified those on their laptop inventory who should be contacted.
- [x] (Matt or Barny) Cohort and Email Identified.
- [ ] (Matt) The people identified should be contacted via mail merge.

A week after the mail merge for a region has been sent, the work in that region can be considered complete on #567. 

### Owner

@mattcfry

### Stakeholder

@Barny-6 

### Approver

@MattCFry

**Comment by Barny-6** [comment]
[Updated on Slack](https://codeyourfuture.slack.com/archives/C066XTVBN65/p1707922543467909)

**Comment by Barny-6** [comment]
@MattCFry is this now complete? Can we close it?

**Comment by MattCFry** [comment]
Last thing before we do. The Manchester page on the UK inventory has some coloured lines. I can tell red means broken, lost or stolen. What does green and orange mean?

**Comment by MattCFry** [comment]
Also, there are multiple records where we don't seem to know where they are. What I've said to Dara Emma is any laptops considered AWOL can be ignored for the purpose of these tickets, however, they should be dealt with separately.

**Comment by MattCFry** [comment]
I've found some things that could be more consistent, from the inventory spreadsheet to activity in the new system. If we don't know the status of something, I think it should be known.

**Comment by SallyMcGrath** [comment]
Let's try to focus here on the GOAL of this task.

We want to close down this inadequate sheet and move to our database as quickly and simply as possible.

We just need to know what we have in stock and what we have loaned out. That's it. Anything we don't know, you can add to a list of mysteries. 

Let's focus on the goal and get the task done. 💪

**Comment by MattCFry** [comment]
The spreadsheet isn't a complete source of truth in any region so some investigating needs to happen before we can "know" anything. 

Anything that can't be clarified in a reasonable time frame can go on to this list of mysteries.

Most of the NW inventory is on there now but we’ve already established inaccuracies by doing this investigating.

**Comment by SallyMcGrath** [comment]
I really need you to listen to what I'm saying, Matt. 

The organisation needs this task to be completed and ready before cohorts open again. I need you to complete this task now please. 

If you have a list of unsolved questions, that is useful, but they must not hold up the completion of this task. You must address those separately later, because this task needs to be completed.  Thank you.
