### ISSUE TITLE
Reach out to engaged grads

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#574]
### Background

Classes run best when Grads are involved. How do we engender a community where grads come back?

- Get  list of engaged grads in each region - host collective discussion
- Share goals of getting more grads engaged - why it is so important
- Ask what has led them to get more involved and what do they get out of it 
- See if they can bring more grads in 

Mostly listen, don't talk too much.

### Acceptance criteria

2x Grads come to class in each region

### Owner

@halden

### Stakeholder

@emcglackenr1 

### Approver

@halden

**Comment by dara** [comment]
Wrong @dara

**Comment by dara** [comment]
Awesome, thanks for the update!

**Comment by emcglackenr1** [comment]
It would be good to have a meeting or share related docs about this. I had a recent chat with @Barny-6 about course completers / grads and his work in that area.
Can you share the info or book a meeting with me? :)
