### ISSUE TITLE
Laptop Loan Comms and Docs 

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#585]
### Background

The laptop loan docs need to be updated
https://docs.codeyourfuture.io/trainees/support/request-a-laptop is going to the old form and https://cyf-signposts.netlify.app/topics/equipment/
is going to the docs too.

Could instead they go to the new system.

### Acceptance criteria

- [x] Trainees needing a laptop can go to signposts and find the link they need
- [x] They probably don't need an extra step of the docs so that page could be archived or redirected to signposts

### Owner

n/a this system doesn't work for our team

### Stakeholder

@ClaireBickley

### Approver

@SallyMcGrath

**Comment by SallyMcGrath** [comment]
@MattCFry here's the ticket

**Comment by ClaireBickley** [comment]
@MattCFry if you need access to signposts Sally can help with this - I don't think you have access to Gitbook, which we use for updating docs so I'll sort that now for you.

**Comment by MattCFry** [comment]
Hi @ClaireBickley. I can make an edit merge request or a straight-up merge (I think). I'm just figuring out how this redirection works. I'll take on signposts in a bit.

**Comment by MattCFry** [comment]
I've done[ a PR](https://github.com/CodeYourFuture/CYF-Signposts/pull/3) to update the laptops loan signposts info. (I have not done a PR in aeons so go easy on me XD).

I have updated CYF docs ['Support Section'](https://docs.codeyourfuture.io/trainees/support) to link to signposts. The old page has been updated but moved to archived pages.

**Comment by SallyMcGrath** [comment]
BTW there's a CMS at https://signposts.codeyourfuture.io/admin you can use -- you already have an account with your work email

**Comment by SallyMcGrath** [comment]
Looks great, @MattCFry ! Everything sorted. Thanks for picking this up! 🚀
