### ISSUE TITLE
Trainee Canvas

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#587]
### Background

We have been making canvases in our Slack Channels as part of our goal to calm down Slack, clarify docs, and reduce our chaos.

Here's an example of a class canvas that belongs to one context: https://codeyourfuture.slack.com/canvas/C05RPC3T4JH

Here's an example of a volunteer team canvas  that is embedded in many places : https://codeyourfuture.slack.com/docs/T2H71EFLK/F065ASFF743

I think we need a trainee team canvas that can be embedded on many channels. It should be:

- short
- simple
- well targeted
- visible
- updated

What could it contain? I think signposts, community safety, the cohorts dashboard, and the curriculum need to be on there. What else? One person set up a rough draft and give everyone edit powers. Then mob on it for 10 minutes and get it embedded. This could be a nice demoable task.

### Acceptance criteria

- [x] The short and simple canvas contains at least the key links I identified - @emcglackenr1 [Trainee canvas ](https://codeyourfuture.slack.com/docs/T2H71EFLK/F06RX77S0JX)
- [x] The language is clear and simple (use Hemingway to help you) - @emcglackenr1 
- [x] Signposts, safeguarding, and the curriculum are included - @emcglackenr1 
- [x] The canvas can be edited by trainees and volunteers - @emcglackenr1 
- [x] The canvas is embedded on high traffic trainee channels - @emcglackenr1 
- [x] Request feedback from team and ability to edit canvas - @emcglackenr1 
 

### Owner

n/a this system doesn't work for our team

### Stakeholder

@ClaireBickley

### Approver

@SallyMcGrath

Examples: 
https://codeyourfuture.slack.com/canvas/C0515NZ6TQW

**Comment by MattCFry** [comment]
This seem similar to #537. Do both tickets need to exist? What are the differences?

Sidenote: the laptop loan form would be useful to add.

**Comment by emcglackenr1** [comment]
- [ ] @MattCFry to add anything from his version that seems relevant

**Comment by MattCFry** [comment]
I would just be duplicating what's written in #537. Could we not just have both for now?

**Comment by emcglackenr1** [comment]
**Notes from Matt's ticket: #537 

Background**
As we look to make better utilisation of canva cohorts, we should have one which provides expectations, rules, community guidance and motivations for trainees. This canva would be useful if this was usable both during and after the SDC.

**Acceptance criteria**

-  Canva should include baseline information about how trainees operate during their time at CYF
-  It should encourage community action and interaction
-  Communicates the core values of CYF
-  Links to curriculum
-  Easily implementable in all global cohorts

**Upon completion**
 Shared in Prom channel, explained and feedback requested

**Comment by emcglackenr1** [comment]
Halden suggested adding this to the canvas 'You can ask for help from regional and remote volunteers on anything you need here [#cyf-volunteers](https://codeyourfuture.slack.com/archives/CTD17PH0D) '

**Comment by emcglackenr1** [comment]
Blocked part - [signposting component ](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1710429602045949)
Rest is in progress

**Comment by SallyMcGrath** [comment]
I can't see any action to take or what your blocker is? Just link to the signposting website.

**Comment by emcglackenr1** [comment]
Sorry the blocked part was I was asked to hold off on sharing signposting. That's been clarified on Slack, so it is no longer blocked.

**Comment by emcglackenr1** [comment]
Instructions suggested link to class dashboard in the Canvas. If the link is in the general global trainee canvas, then it can't be customised to each region. 

Options:
1. Copy pasting from the template allows trainees to edit it to suit their region. On the other hand, Canvases are no longer linked to one template. If one Canvas is changed then others aren't. 

2. Have some text outside of the canvas container that is separate from the global trainee canvas. This text can be updated even if the trainee one is not. This also means that several canvases can be in one region, an example of how this looks is visible on #za2-graduates

Option 1
![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/64873698/8923035f-ac81-4551-93ab-e6af364d2d11)


Option 2 
![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/64873698/5869227e-76e6-4e89-9adf-d21a75fdcba8)

**Comment by emcglackenr1** [comment]
Added without dashboard line into channels: 
NW #north-west  #nw5-entire-cohort
WM #westmidlands  #wm5-general #wm4
GLA #glasgow-class-6-devs  #scotland 
LDN #london  #london-classes

Didn't add to #nw6-general as it's in other NW channels and NW6 have a good canvas they seem to be building themselves.
Was unsure about adding to ZA @ShaunCYFSA because some of the resources / links might not be global. What do you think?

Added dashboard line to SD cohorts outside of trainee key links Canvas for now. 
I only did this for WM5 because NW6 have it on their Canvas already

Line used outside of Canvas:

**:gauge-chart: Class Dashboard** 
If you have a class dashboard, please copy paste the link here 👉  [link]
