### ISSUE TITLE
Work on Increasing Slack Engagement - GLA6 / Scotland

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#591]
There is very low engagement on Slack since we returned after winter break. 
For example: [Karen's post about her visit](https://codeyourfuture.slack.com/archives/C044M02QTM5/p1707233493619019)

What can we do to increase engagement?

- [x] Ask community in person - they said it was helpful but they don't like checking it.
- [x] [Posting on Slack ](https://codeyourfuture.slack.com/archives/C044M02QTM5/p1708174494379139) to ask Community 
- Background on this post - trainees left early because there was no volunteer, but there was one and no one communicated openly on the Slack channels, so the volunteer and trainee group didn't find each other.
- Maybe the impact of this confusion will help encourage Slack participation in future

- [x] Ask staff what worked in other regions 
- [Discussion 1 - Actions speak louder than words ](https://codeyourfuture.slack.com/archives/C029341FPH6/p1708175107103039)
- Met with Haldan, [made a plan](https://docs.google.com/document/d/1LuewFqh7BfuMXqzkZ6oxVei840WGxgWF7BAVdIUGzPg/edit)

Plan based on discussion and meeting with Haldan
- [x] Discuss with volunteers - [planned for volunteer meeting 23rd Feb](https://docs.google.com/document/d/1jWlN-PnLdDI_O6IzkC170SObCIuC9kSfxnpcveNzACE/edit)
- [x] Volunteers to discuss with class - Feb 24th

**Comment by haldenb** [comment]
My thoughts:

Slack is a tool you cannot organise without:
- let it fail
- draw attention to why it failed
- allow learning 
- don't try to encourage it

Also be an example of best practice. 

I replied more content in slack

**Comment by emcglackenr1** [comment]
Waiting for volunteer meeting to see how the discussion goes

Related: following volunteer meeting volunteer Jack [posted on #glasgow-6-devs to ask trainees if they are attending ](https://codeyourfuture.slack.com/archives/C044M02QTM5/p1708694934406309)

**Comment by emcglackenr1** [comment]
These tasks are completed, the goal of increasing Slack engagement from both volunteers and trainees has not been reached. @haldenb and I will continue to work with community and monitor.

**Comment by haldenb** [comment]
Great work :) 

This will be a little-by-little change, it will take time
