### ISSUE TITLE
Review Tech Ed roles offered to companis

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#592]
### Background

We share these roles with companies, so it's time to review if they still make sense, if they exist, and if we want to keep them all. We will also share them with Capgemini. https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.gfd85783a87_0_23.

### Acceptance criteria

- [x] Sally/ Tech Ed to review slide 5
- [x] Lili to make any amendments need

### Owner

@liliana

### Stakeholder

@sally

### Approver

@sally

**Comment by SallyMcGrath** [comment]
Can you give a deadline or due date for this @lilianabermudes ? I'm adding it to the curriculum planning board

**Comment by SallyMcGrath** [comment]
This looks good to me, but @illicitonion and @40thieves what do you think? Could this also support some of the work Leila (can't see her GH handle) has been doing on code review? Do you have any improvements or requirements?

**Comment by lilianabermudes** [comment]
Hi Sally, and team,

A good one would be the end of this month, so we start March with an updated version: **29/02**.

**Comment by SallyMcGrath** [comment]
I made some minor changes. If nobody else pitches in before the deadline it's good to go as is

**Comment by lilianabermudes** [comment]
Fab, thanks!
