### ISSUE TITLE
West Midlands Intro (New Roles Transition)

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#593]
- Get an overview of what the situation is in WM4, 5 and 6 

**Dara**
- [x] Dara - met Matt on 15th Feb
- [x] Overview of WM4 - Dara
- [x] Overview of WM5 - Dara
- [x] Meet WM5 - Dara
- [x] Overview of WM6  - Dara

**- Halden**
Unsure of the actions you took, please add them here

**Documents**
- [ ] Identify what documents are needed - Matt - [no because it relates to this ticket](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/597)
- [x] Provide access to documents and channels needed for each - Matt

**Determine Next Steps**
- [x] Meeting to discuss / prioritise (Dara, Matt, Halden, Shaun) - March 13th

Introductory Plan / future actions

- @Barny (and maybe Dara) will work with WM4 (e.g. #594 )
- Dara, Halden, Matt, Mitch, (and everyone else, where relevant) will work with WM5 as they’re an active cohort
- Matt will discuss with the volunteer about WM6 joining for co-working [#772](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/772) and then hand this over 
- Halden - to put volunteers in touch with WM4 grads or point them towards #cyf-volunteers

**Comment by MattCFry** [comment]
Hi @emcglackenr1. Please see [this milestone](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/22). Consider if you still need this ticket. 😄

**Comment by haldenb** [comment]
@MattCFry what documents and channels do I need access to? Can you share them?

**Comment by haldenb** [comment]
I would break this into more tickets:
- have 1 ticket on meeting the community - maybe with a deadline of this quarter 
- then have another ticket on me and Dara meeting to strategise/ prioritise (this could only be done once we have met the community anyway?)

What do ya'll think?

**Comment by MattCFry** [comment]
@haldenb I'm not sure to be honest.

If you guys look through the milestone I linked then that might be sufficient? Lemme know what you guys think :D

**Comment by haldenb** [comment]
I am not sure what ' Halden and Dara meet to strategise/prioritise' means?

**Comment by emcglackenr1** [comment]
@haldenb - when we started the new roles we discussed collaborating / strategise because our roles are closely related. So, it's good to have an idea of who would do what, and combine our skills / knowledge / experience. 
That action was to have a meeting to discuss what we knew so far about WM, and create actions / discuss how we would support the region. It was listed as following discussions with Matt. It also now relates to #703 , because I have since visited WM. 

I think it would still be good to have at least a short meeting about it, rather than working separately. 

I created this 3 weeks ago, so, if you prefer, we can archive this ticket and you can create one that you think makes more sense?

**Comment by MattCFry** [comment]
Hey Dara, can you review the milestone I made and let me know what else you need? 

What you're proposing feels very similar to #598

**Comment by emcglackenr1** [comment]
We said we would break #598 down into smaller issues, this is a smaller issue. This issue(593) was created first, but I edited the description after seeing 598 to make it suitable. I made it smaller so it's achievable in two weeks. I think this is small enough to be it's own issue, which can be done over the course of a 2 week sprint and helps us progress with [West Midlands Programme Delivery Integration](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/22)

It's purpose is just to get an intro / understanding of the different cohorts so we can take actions / divide work. These are the tasks I though would be a good start. 

If you would prefer this is expressed/organised in a different way, please edit the ticket or create new ones and archive this.

**Comment by emcglackenr1** [comment]
We had a meeting where we discussed how to divide the work, so I'm closing this

**Comment by emcglackenr1** [comment]
@MattCFry did you share the relevant docs with me?
