### ISSUE TITLE
West Midlands Graduates

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#594]
### Background

- There were only a few unemployed WM grads from before Matt joined. 
- WM4 Graduated in March 2023. Marta was their PROM, who left in Jan 2023. 
- Nirmeet interacted with grads and had some findings (there's a doc that exists somewhere). 
- Matt has been the primary contact and driving force behind them, especially with little to no volunteer support. 

### Acceptance criteria

- [x] Dara and Matt meet to discuss grads (Course completers) @emcglackenr1 and @MattCFry 
- [x] Discussion of key pain points for the grads.
- [x] Next steps actions decided and logged - Dara and Barny - discussed on 07/03/2024, Barny said he would continue to work with them and I created a ticket based on the info from that meeting to collaborate on https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/699

### Owner

@emcglackenr1

### Stakeholder

 @MattCFry 

### Approver

@emcglackenr1

**Comment by emcglackenr1** [comment]
I don't entirely understand what express and understand means in this context

**Comment by MattCFry** [comment]
Same as the others :) shall we wait until we start working on this to get specifics down?

**Comment by emcglackenr1** [comment]
I think it would be good to have more clarification, so we know what sprint this should belong to. I think it would be good to start working on it asap. Maybe this Sprint or next?

Can you expand on what you mean about '[grad tracker](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit#gid=638041181) in a useable place'? Is it that the information is out of date on some tabs?

**Comment by MattCFry** [comment]
This is part of you and Halden being able to do your jobs within WM. The sprint is dependent on you two. I wouldn't leave this until Sheffield starts.

I have not caught up with alot of grass for a while. Particularly, the disengaged ones

**Comment by haldenb** [comment]
I'm going to un-assign myself from this 

It seems like reaching out to Grads may be Dara, once they have agreed on their goals and got something in motion (a PF module), I can start organising volunteers around it

**Comment by MattCFry** [comment]
Which doc do you need? You have access to the [global grad tracker](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit?usp=sharing)

**Comment by emcglackenr1** [comment]
I was referencing the ticket before it was edited I think. A document was mentioned and I didn't know if I had the information needed. I'll edit to remove that part of the task.

**Comment by emcglackenr1** [comment]
@Barny-6 in our meeting earlier in March you said you were happy to work with grads
