### ISSUE TITLE
West Midlands 5

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#595]
### Background

- Nirmeet was their PROM until early HTML/CCS (I think?)
- Typical range of performance ranges.
- Started at 19 people from fundamentals and now only 13 remain.
- Great class space.
- Typically good volunteer turnout, has fluctuated recently downwards. 
- Volunteers making productive use of their time in class is a development point. 

### Acceptance criteria

- [ ] Prog Delivery Team discuss all individuals and go through the trainee tracker.
- [ ] Discussion of key pain points for the cohort.
- [ ] Next steps actions decided and logged.

### Owner

@emcglackenr1

### Stakeholder

@MattCFry

### Approver

@Dedekind561

**Comment by MattCFry** [comment]
Karen's Community Health Workshop Post 

"My main perceptions of this visit:
1. The trainees act as if they were competitors, not a community.
2. There is a clear separation of "good trainees" and "not-so-good trainees" - a physical separation. In the first group, I saw many people with backgrounds in tech, engineering, etc., which makes it easier for them to learn.
3. The volunteers give more support to the "good trainees" and just go to the not-so-good ones if they ask for help.
4. The flipped classroom is working better from what Mitch told me, but I don't think we are there yet.

Next steps/questions:
- Actions that were created must be actually actioned in the coming weeks.
- How to remove the competition between groups."

@emcglackenr1 made a [slack post](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1708787059467149) inviting discussion on this.

**Comment by emcglackenr1** [comment]
What does Express mean in the title?

**Comment by MattCFry** [comment]
Explain facts and provide my subjective experiences.

**Comment by emcglackenr1** [comment]
If you aren't free to talk today, can we change the sprint and deadline?

**Comment by MattCFry** [comment]
Of course. I didn't know we were working on this now
