### ISSUE TITLE
Ensure Dara and Halden have Access to all necessary Docs and Resources

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#597]
### Background

For [West Midlands Programme Delivery Integration](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/22) to happen Dara and Halden need to have access to everything they need.

### Acceptance criteria

- [ ] Dara and Halden must express everything they need access to.
- [ ] Matt will give them access to whatever he can.
- [ ] Anything Matt can't give access to, the trio finds help from other staff.

### Owner

@emcglackenr1 and @haldenb

### Stakeholder

@MattCFry

### Approver

@emcglackenr1 and @haldenb

**Comment by emcglackenr1** [comment]
Does this include WM Planning channel?

**Comment by MattCFry** [comment]
I think we need to ask that question on slack. The conversation will get lost in this thread.

**Comment by SallyMcGrath** [comment]
Book a 15 minute call for 2 weeks time.
Make a doc and attach it to the call.
Collaborate on the document to ask and answer all questions beforehand.
If you do this well, you will be able to cancel the call.

**Comment by MattCFry** [comment]
I've moved 1 or 2 niche things to shared drives. Everything else has either been public access or existing staff access, so I don't need to make changes. I'm going to close this. 

If anyone thinks of anything  and can't find it then ask :)
