### ISSUE TITLE
Additional Strategizing and Prioritisation for WM

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#598]
### Background

Much work and understanding is taking place in '[West Midlands Programme Delivery Integration](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/22)'. I think it's best to get your head around it and figure out the property of tasks. 

### Acceptance criteria

- [ ] Dara and Halden agree they have sufficient information/understanding to begin strategizing and prioritising.
- [ ] Produce some tickets belonging to a milestone for this work.
- [ ] Identify dependencies of every piece of work.
- [ ] Express a prioritisation of order to tackle to this by the Programme Delivery Team. 

### Owner

@emcglackenr1 and @haldenb

### Stakeholder

@MattCFry

### Approver

@emcglackenr1 and @haldenb

**Comment by MattCFry** [comment]
You guys can ask me questions as you go. The important thing is to start.

**Comment by emcglackenr1** [comment]
This relates to ticket #593

**Comment by emcglackenr1** [comment]
How do we progress with this ticket? @haldenb @MattCFry

**Comment by MattCFry** [comment]
I don't think this is the ticket to start with. I think we should conclude with this ticket.

Can we move this to the backlog and go with some of the expressing tickets?
