### ISSUE TITLE
Review PD and Product volunteering Opportunities

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#599]
### Background

We share these roles with companies, so it's time to review if they still make sense - if they exist, and if we want to keep them all. We will also share them with Capgemini. https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.gfd85783a87_0_23.

### Acceptance criteria

- [x] Karen to review slides 6 and 7, by 29/02
- [ ] Lili to make any updates needed

### Owner

@liliana

### Stakeholder

@karen

### Approver

@liliana

**Comment by kfklein15** [comment]
Hi @lilianabermudes , I would only remove the process one on slide 7. We had some people interested but this never really moved forward.
Should I remove it from the slide directly and also from the spreadsheet?
Thanks

**Comment by lilianabermudes** [comment]
Hi Karen, yes, please remove from both if you can :) thank you!!

**Comment by kfklein15** [comment]
Done toady on the spreadsheet and the presentation. Sorry for the delay on this.
