### ISSUE TITLE
Dara to take over as Product Owner for Signposting Website

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#600]
As part of my new role, Sally asked that I become the product owner for https://signposts.codeyourfuture.io/ and take over that job from @ClaireBickley 

- [x] Meet Sally to discuss 27-02

**Comment by SallyMcGrath** [comment]
I think this might belong to a milestone, which is your role transition milestone. Could you make one and set a date for it @emcglackenr1 ?

**Comment by emcglackenr1** [comment]
Sure! I had created a Signposting website one but that's perhaps too small an aspect for a milestone. 
Will make the new one now.
