### ISSUE TITLE
When do we graduate in Global Trainees?

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#602]
### Background

We have very clear graduation criteria for trainees - this is fine and doesn't need reviewing. However, we often need to share number of graduates with partners (e.g. Capgemini) and we need to understand how many people completed the course for monitoring. We don't want different course completion dates within the same cohort, so need a consistent approach. Suggestions include (some of these are crossovers but could technically be on different days):
- Demo Day
- Internal Demo Day
- External Job Fair
- End of Portfolio
- End of Employability Module

### Acceptance criteria

This is for the purposes of reporting and monitoring and only for use in Global Trainees etc.
- [x] Decide on what date should be used on Global Trainees for cohorts (GLA6 onwards).
- [x] Decide if any changes to terminology are needed in Global Trainees (e.g. course completers)
- [x] Update Global Trainees

### Owner

@lilianabermudes @clairebickley

### Stakeholder

@SallyMcGrath @kfklein15

### Approver

@gbencci

**Comment by kfklein15** [comment]
Adding the [Slack link discussed previously](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1703086082828289)

When does the SDC journey officially end? When does “product” start? Where do we consider trainees as grads? [We need this on data records]
We’ve told people that they graduate when they finish the Employability Module, so those people we've said that to, that is what will happen!
NW5 + WM4 + ZA2- are graduates (have certificates) :white_tick:
LDN 9/10 + GLA6 - Portfolio with 2 projects = graduates (will have to get a certificate)
NW6 + WM5 - The Launch + [Portfolio goals ](https://module-graduates.codeyourfuture.io/how-does-this-work/portfolio-goals)= graduate
Future cohorts - same as above

**Comment by ClaireBickley** [comment]
thanks Karen, does this mean people within the same cohort could have different "graduation" dates?

**Comment by kfklein15** [comment]
Yes, I understand that this could be the case.

**Comment by ClaireBickley** [comment]
Thanks Karen. @lilianabermudes I will ask Bethan if this will work for her.
