### ISSUE TITLE
Test New Expenses Form

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#603]
### Background

Claire has created a new expenses form, this covers all UK regions. When implemented, it should make life easier for Leanda and Matt as they only need to review one form, not multiple. The new form needs some test claims adding so Claire can see if the back-end formulas still work.

### Acceptance criteria

- [x] Matt to add some [test claims](https://forms.gle/TCiYScxByBenPJiz8), probably 2-3 from each region, info can be made up, don't worry about the receipt upload
- [ ] Claire to review formulas in the spreadsheet, test if they work in Xero and Wise
- [ ] Review with Leanda
- [ ] Update links in various places
- [ ] community start using the new form

### Owner

@MattCFry

### Stakeholder

@ClaireBickley

### Approver

Leanda

**Comment by SallyMcGrath** [comment]
> -The reimbursement can take up to 3-4 weeks. 
> Please don't contact me regarding reimbursements before this time has elapsed.

Suggest rephrasing this

**Comment by MattCFry** [comment]
I have made about 7 fake test claims. Hope this is sufficient :)
