### ISSUE TITLE
Examining the current trainee withdrawal form process

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#605]
**Examining the current trainee withdrawal form process**

**Background:**
The trainee withdrawal form is sent to trainees who drop out. It's worth evaluating this process, since the data is not used. As well as that, not every drop out fills out the form.

**Questions to consider**
- Is the data from the form used?
- Are we monitoring or actioning it?
- How can interaction / usage be increased?
- What is the value of this process?
- What are the constraints and regulatory requirements? 

**Further information/discussion:** 
- [Discussion that prompted this issue ](https://codeyourfuture.slack.com/archives/C029341FPH6/p1707919143730019)
- [Previous discussion about the value of it](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1681286406811149)
- [Early usage / introducton 1](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1589187955015400?thread_ts=1589183987.006800&cid=G6H0HAY10)
- [Early usage / introduction 2](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1606825277018500)

**Resources / Docs**
[Form](https://docs.google.com/forms/d/1O53ct-h6KANDyc9oOfLk7JCjAdtY-bJYYPPzXn_WhbA/edit)
[Spreadsheet of responses](https://docs.google.com/spreadsheets/d/19qn5CEzL8-nzQuhsKFyLQUEBHkZ61AbtZKyz1UJLz1Q/edit#gid=2072979637)
[Letter to trainee](https://docs.google.com/document/d/1ha5_bIugMEJI8n5XPUeoJwKEEMA46hx6nj3vuw69JG0/edit?usp=drive_link)
[Global Trainees (for summaries)](https://docs.google.com/spreadsheets/d/1sE277UuUIqQHKdDxy8zl-VwBmz4MgBnpAHcZYpc0kZA/edit?usp=drive_link)

**Completion Criteria:**
- [ ] Gather all information together (break down into smaller steps)
- [ ] Examine results 
- [ ] Prepare presentation to discuss with other staff (might become a new ticket)

**Comment by SallyMcGrath** [comment]
⭐ Great - have added a point supporting our topic on Complexity, recalling that:

 _Instead of asking what is the process ask, 'what is the goal?'  and 'what is the law?'_
