### ISSUE TITLE
Review new Access Needs form

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#608]
### Background

This piece of work was extracted from the old Personal Circumstances form. This access needs form reduces the risk of trainees sharing unwarranted medical information and reframes the questions more clearly towards what they may need to access learning. @gbencci this is also the  piece you wanted to improve our data on our disability support - it's a twofer. 

I have grouped the questions under three categories: Facilities (places), Communication (blind, deaf, neurodivergent etc), and Assistants (used to be called Attendants or Companions in old money). I think I covered all our most common bases and our statutory obligations but please @ClaireBickley review and check! 🙏 

https://forms.gle/6mC4Z63yQti8Pwwq8

The questions in the PC form are replaced simply by _Do you have an access need?_

### Acceptance criteria

- [x] The form is simple, clear, and covers most circumstances
- [x] The form is in the right place in the Drive 
- [x] The Signposts link is clear and simple https://cyf-signposts.netlify.app/topics/accessibility/
- [x] #612

### Owner

Claire

### Stakeholder

Dara-Emma

### Approver

Sally

**Comment by ClaireBickley** [comment]
this looks good - I changed Guide dog to assistance dog to cover Hearing Dogs etc.

I really like the categorisation you've gone with here, very clear.

On equipment (Communications) do we need to be clearer or give examples? Maybe not, I'm assuming whoever needs the equipment will be OK with the wording, I'm more thinking about people who don't yet know quite what they need.

Also, do we need an explainer at the top that trainees do not qualify for Access to Work with CYF but we'll do our best to support them?

**Comment by SallyMcGrath** [comment]
Thanks for the edits. Don't load in extra information on a form, it is obscuring not clarifying.

Put Access to Work info in Signposts

**Comment by ClaireBickley** [comment]
Cool, I've added AtW to Signposts
