### ISSUE TITLE
Update airtable credit card before next billing period

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#609]
### Background

I have removed myself from the [CYF airtable](https://airtable.com/) so we don't get double charged.  I tranferred all the referral credits to the CYF workspace, made laptops the owner, and kicked myself out. 

Please now sign in with the laptops google account and add a CYF card and remove mine. (I don't have a CYF card or I would have done this.)

### Acceptance criteria

- [x] The CYF card is on the billing
- [x] The charity 50% discount is also applied (check email)

### Owner

@ClaireBickley

### Stakeholder

@MattFry

### Approver

@SallyMcGrath

**Comment by ClaireBickley** [comment]
I will add mine today

**Comment by ClaireBickley** [comment]
OK added my card, but haven't received an email about the discount.

**Comment by SallyMcGrath** [comment]
I forwarded it again to you Claire

**Comment by ClaireBickley** [comment]
yep, got it - sorry thought it would be a new one to expect. All good!
