### ISSUE TITLE
London PF module 2 

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#610]
### Background

London will do a PF module: 

### Acceptance criteria

- message to London classes
- message to London Volunteers
- Find module leads (preferably trainees)
- Set Launch Criteria

### Owner

@halden

### Stakeholder

@Barny-6 

### Approver

@CodeYourFuture/cyf-programme-team

**Comment by SallyMcGrath** [comment]
This looks a lot like delivery. Could Ellie lead this? 

The launch criteria is published on the website here https://curriculum.codeyourfuture.io/portfolio/prep/

**Comment by kfklein15** [comment]
I don't think "message to London classes" should be our job. We should only find volunteers and they should do the class/trainee tasks.

**Comment by SallyMcGrath** [comment]
This clearly isn't in progress as @haldenb is on leave.

**Comment by Barny-6** [comment]
@haldenb can you close this if it's done, thanks
