### ISSUE TITLE
EXL - March cohort assignment review

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#615]
### Background

As part of our CSR contract with EXL, they have volunteers who will be reviewing the assignments for the DLP for 5 cohorts.
March volunteers are: 
Marking week: 15th March - 22nd March: Rowan McGrath & Neha Maheshwari
Marking week: 22nd March - 29th March: Ian Wall 
Marking week: 29th March - 5th April: Shivendra Singh & Scott Gordon Walker

### Acceptance criteria

- [x] Email volunteers a reminder that the course is starting. Send on 8th March
- [ ] Email volunteers the link to the consolidated marking sheet to mark entry assessments and the first at-home assignment. Send on 15th March with reminder that we will need the feedback by the 22nd March
- [ ] Send feedback to trainees on 22nd March
- [ ] Email volunteers the link to the consolidated marking sheet to mark second at-home assignment. Send on 22nd March with reminder that we will need the feedback by the 29th March.
- [ ] Send feedback to trainees on 29th March
- [ ] Email volunteers the link to the consolidated marking sheet to mark exit assessment and third at-home assignment. Send on 29nd March with reminder that we will need the feedback by the 5th of April.
- [ ] Send feedback to trainees on 5th April.

### Owner

Amy

### Stakeholder

EXL: Muskan

### Approver

Amy

**Comment by SallyMcGrath** [comment]
long past
