### ISSUE TITLE
Deveron tasks this sprint

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#617]
Creating all tickets for Deveron

**Comment by alecmccrindle** [comment]
Handed this over to Anderson for now.

**Comment by alecmccrindle** [comment]
My jobs for this sprint

- [x] Desktop styling review
- [ ] Mobile styling review

**Comment by alecmccrindle** [comment]
Mobile styling not complete, move to next sprint

**Comment by kfklein15** [comment]
Create new ticket with Mobile styling review
