### ISSUE TITLE
Start DLP Glasgow Volunteer Recruitment

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#618]
**Summary:**
Recruit volunteers for DLP Glasgow. Low priority, because Amy has higher priority projects, and a motivated volunteer lead is needed to kickstart anything. 

**Completion Criteria**

- [ ] Dara to discuss with Haldan about volunteer outreach. (might be related to another ticket that doesn't exist at the time this was written)
- [ ] Could set up an online event and see what they think of it as a group.  (possibly around a month from when this was written, e.g. 19th of March). Time to advertise.
-  If no one attends/ we don't get the volunteers we need leave it until someone expresses interest in GLA, or 6 months or so has passed 

**Possible Actions**
Could I talk to Shaun about how he set up DLP to be run by volunteers successfully in SA.

Related to #541

**Comment by haldenb** [comment]
I have removed myself and assigned Mariana as  Mariana does outreach, and help with volunteers already in CYF :)
