### ISSUE TITLE
Review Volunteer Reach Out Process

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#631]
**Summary:**
Is it worth reaching out to formerly active volunteers in regions that have less volunteers?
Volunteers who used to work with CYF might be better than bringing in new volunteers who have no experience with CYF, and have no demonstrated involvement yet. 

Relates to discussion on #563 

**Completion Criteria** 
- [ ] Discuss and determine if process needed 
- [ ] TBD

**Comment by MattCFry** [comment]
I think it always has value. Trying to involve volunteers which have some experience with the org is never a bad thing. 

I've experienced some volunteers adjusting to changes in the org over recent times (I.e. flipped classroom, use of public channels vs DMs). I don't think these difficulties are sufficient to not want volunteers back in the fold. 

We will have to contend with the reason why they disengaged in the first place. A lot of WM volunteers cited increase in workload, however, I sometimes feel that it was just a cover for difficulties in integration.

Not to go off topic but a big theme that I want to discuss with our team is the idea of volunteers feeling like they have a 'stake in the game'. I think it plays a big factor in volunteer experience and and retention.

**Comment by MattCFry** [comment]
For a process, could you not just do a mail merge? Once you get responses you can start getting personal and move away from a blanket response?

**Comment by emcglackenr1** [comment]
A mail merge would be perfect for this. This ticket is to discuss if we think it is necessary to reach out to volunteers in regions who don't have many, e.g. Glasgow

**Comment by MattCFry** [comment]
Ah okay. Yes, I think it's a decent idea. 

There is never really a bad time to do it.

**Comment by haldenb** [comment]
Sending an email is good :) 

We also want to encourage community ownership. It is best when trainees get in contact with volunteers to invite them back. This removes us from processes is and is more effective. 

Does this happen in regions that struggle with volunteers?

**Comment by MattCFry** [comment]
This does not happen in WM. However, we had our first example of trainees going to cyf-volunteers to ask for support (which is amazing!). I think this will need to be something we keep encouraging to have a culture change.

In terms of this ticket
- I think we can all agree that it would be best if the community did this. 
- If we (meaning staff) do any volunteer engagement it should be on an infrequent basis. Especially if people are not on slack often and would require emailing, for example. I think personalised mail merge is fine. How often should we do this?
