### ISSUE TITLE
Data Talent - Tue 12 Mar 2024

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#633]
**Summary:**
Data Talent is Scotland’s premiere in-person showcase bringing together fresh talent from across Scotland with organisations in the public, private and third sector actively recruiting for a variety of roles in the field of data science and AI.

For more information see here: https://www.tickettailor.com/events/datafest/1047109

Frank from Code Division wants to collaborate on this with us. He can get trainees, volunteers or staff discounted tickets through Code Division if we want to attend. 
Frank asked that a staff member and some trainees attend. 

**Completion Criteria**
- [ ] Someone to discuss with Frank
- [ ] Ask community
- [ ] Secure tickets

**Comment by emcglackenr1** [comment]
[Related actions](https://codeyourfuture.slack.com/archives/C04B5106M6U/p1709831926892189)

**Comment by gbencci** [comment]
Hi! We normally don't pay for tickets and get them for free from organisers. This is more of Outreach area (@MarianaVazquezCYF ) of event attendance, but that's our general guideline.

There are lots of paid events all over, so we would need to know why this matters.

**Comment by emcglackenr1** [comment]
From speaking to Frank, there is going to be recruiters there interested in meeting graduates from organisations like CD and CYF, so it would have been a good potential employment opportunity. We also could have gotten CD tickets for only £10 each, so I thought that would have been reasonable. I've booked a call with you @MarianaVazquezCYF to discuss

**Comment by emcglackenr1** [comment]
Event date has passed.
