### ISSUE TITLE
JP Morgan and Code Division Discussions

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#634]
**Summary:**
Frank from Code Division is speaking to JP Morgan about potential collaboration, and hiring more Code Division and CYF grads. [More details in this document](https://onedrive.live.com/edit?id=E1D749A20126FF01!206780&resid=E1D749A20126FF01!206780&ithint=file%2cdocx&authkey=!ANs0QME_Txdps00&wdo=2&cid=e1d749a20126ff01)

Dara handed this over to Germán so it can be discussed with Frank. Frank has been asked to introduce Germán via email.

**Some details**
Apprenticeships very popular in Scotland, JP Morgan have hired many apprentices. 
Frank talking to JP Morgan about how hiring refugees is more practical than the cost of hiring so many apprentices.

- [ ]  Frank to introduce via email to Germán / or work with Germán - deadline set for Mar 15th or else you should follow up

**Completion Criteria:**
TBD - add more actions when more information is known

**Comment by Barny-6** [comment]
looks like this is @gbencci 's ticket so I'm unassinging myself. Add me back if there are actions for me.

**Comment by emcglackenr1** [comment]
Hi @Barny-6 this relates to employability which is why I added you. I think @gbencci mentioned working with you and Frank from CD on this. I have added some of the notes from the collaborative doc to the ticket so you can see it. But you would have to discuss with Frank and @gbencci about actions and whether there is something you can help with on this.

**Comment by emcglackenr1** [comment]
Ticket placed in 'in-review' as we are waiting for Frank to intro Germán

**Comment by gbencci** [comment]
Thanks, @emcglackenr1 . Yes, please ask Frank for an email intro to JP Morgan person. And yes Barny, it relates to employability, so it'd be great if you could be involved.
