### ISSUE TITLE
Cyber / Data Showcase Event with Oracle, Scotland IS and Code Division

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#635]
Summary:

Code Division have been speaking to Oracle about a Cyber Showcase event in which CYF and CD could do a presentation on their organisation and invite trainees / grads to show projects. This would present the chance for trainees / grads to network and there would be potential recruitment opportunities. Frank: 'Cyber, web, whatever projects people want to deliver. Could even be final projects.'

More information in [this document for now](https://onedrive.live.com/edit?id=E1D749A20126FF01!206780&resid=E1D749A20126FF01!206780&ithint=file%2cdocx&authkey=!ANs0QME_Txdps00&wdo=2&cid=e1d749a20126ff01)

Would be best to plan around Feb / March. Could bring a group of trainees from both CD and CYF together to discuss what they want to present.

Could potentially use oracle [building in Linlithgow ](https://www.oracle.com/assets/map-oracle-linlithgow-316342-en-gb.pdf) or Scotland IS might be able to provide a facility 

Looking at May as a possible date.

Frank: 'Opportunity to do presentations and showcase things – you want people to interact with these companies. All you’re trying to showcase is these people are great. There will be companies there. We can just ask the community what they want to showcase. Then ask the companies: How can you help? '

Completion Criteria:

- [ ] Collaborate with Frank
- [ ] Ask community in both Scotland and other regions if they want to contribute
- [ ] Secure venue with Frank
Etc. 
(Please edit as necessary)

**Comment by Barny-6** [comment]
Hi, this doesn't look like a ticket for me right now. Let me know if there are actions for me/ assign me back in

**Comment by MarianaVazquezCYF** [comment]
Hello @emcglackenr1 where is my action here? because yes this is 100% a priority !

**Comment by emcglackenr1** [comment]
Hi Mariana, I'm not sure. I just created this ticket to hand it over and for you both to develop together. Most of the information I have about it is in[ this doc ](https://onedrive.live.com/edit?id=E1D749A20126FF01!206780&resid=E1D749A20126FF01!206780&ithint=file%2cdocx&authkey=!ANs0QME_Txdps00&wdo=2&cid=e1d749a20126ff01), but I could also intro you to Frank so you can discuss it further.

I added you @Barny-6 for the same reason, it is to do with employability and is a great opportunity because there would be recruiters there.
