### ISSUE TITLE
CB: Events Tech diversity

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#64]

**Comment by MarianaVazquezCYF** [comment]
Hey @AliciaE08 @martaesn @haldenb @ShaunCYFSA @caromelendezl  can you please help me to identify in your regions what are the main events in this first half of the year where we need to be present ? :D

**Comment by SallyMcGrath** [comment]
@MarianaVazquezCYF  is this ticket obsolete now?

**Comment by SallyMcGrath** [comment]
closed due to non engagement
