### ISSUE TITLE
Update Eligibility and Suitability communication

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#640]
### Background

We repeatedly get the feedback that the way we describe suitability and eligibility on our website is confusing and in some cases misleading. 

We have worked up some new language that expresses our criteria more accurately.

Please update the website and marketing materials

# Should I apply to Code Your Future?

## Eligibility

Are you over 18?
Do you live within 90 minutes of a CYF city?
Are you on a low income?
And do you want to change your life with a career in tech?

## Suitability

And have you experienced **one** or more of the following:

- [ ] Refuge/Asylum
- [ ] Forced Migration
- [ ] Disability
- [ ] Prison
- [ ] Long term unemployment
- [ ] Homelessness
- [ ] Single parenthood
- [ ] Social care
- [ ] Poverty

Then you are welcome at Code Your Future.

### Acceptance criteria

The website is updated

### Owner

Alec

### Stakeholder

Mariana

### Approver

@SallyMcGrath

**Comment by alecmccrindle** [comment]
This is very helpful, thank you. 

I will make the update on [ITD](https://codeyourfuture.io/itc/) and [the regional pages](https://codeyourfuture.io/itc-ldn/). 

**Questions @SallyMcGrath**

- Did you intend to keep the Suitability checkboxes on the ITC sign-up page? I like the check box, to be clear.   
- Do we need to keep the work Suitability if they need to have Eligibility + one Suitability?
- Can we change the main language on the CYF home page to reflect this? That also leads to confusion if they don't identify as disadvantaged? eg. Free training for adults on low-income, etc.

**Comment by alecmccrindle** [comment]
Hi @SallyMcGrath - I'll work on this ticket the week I'm back from holiday - the week of the 2nd April.

The update to /itc will take a few minutes. The update to the regional pages will take a few hours. I realise I didn't assign the ticket to you so you may not have seen my questions above. Thanks in advance to your replies. 

I think the FP change is probably another ticket, but perhaps you can have a think for now?

**Comment by SallyMcGrath** [comment]
> Did you intend to keep the Suitability checkboxes on the ITC sign-up page? I like the check box, to be clear.

Sure!

> Do we need to keep the work Suitability if they need to have Eligibility + one Suitability?

I don't understand this question, sorry. Can you give me an example of what you mean?

> Can we change the main language on the CYF home page to reflect this? That also leads to confusion if they don't identify as disadvantaged? eg. Free training for adults on low-income, etc.

If we can change disadvantaged, let's do this. I know in our surveys trainees and grads often say they don't love the term.

_Training for refugees and people on low incomes._  

(Instead of the identity "low income people", switch it round to the circumstance "people on low incomes"?)

**Comment by alecmccrindle** [comment]
Thanks for the reply.

Example of excluding Suitability in the copy: 

----

To be eligible for CYF, you must meet all four of the following criteria:

- [ ] Are you over 18?
- [ ] Do you live within 90 minutes of a CYF city?
- [ ] Are you on a low income?
- [ ] And do you want to change your life with a career in tech?

And have experienced one or more of the following: 

- [ ]  Refuge/Asylum
- [ ]  Forced Migration
- [ ]  Disability
- [ ]  Long term unemployment
- [ ]  Homelessness
- [ ]  Prison
- [ ]  Single parenthood
- [ ]  Social care
- [ ]  Poverty

Then you are welcome at Code Your Future.

----

**Comment by SallyMcGrath** [comment]
Sure - we use the term a lot in later comms but if you don't want it there, I am ok with you removing it

**Comment by SallyMcGrath** [comment]
Hi there - this seems a long way past its deadline. Is there something holding it up?

**Comment by alecmccrindle** [comment]
Hi @SallyMcGrath - I haven't been able to find the 2-4 hours to update the mailchimp part. It's a priority for this week and apologies for the delay in response.

**Comment by alecmccrindle** [comment]
I've completed and tested this ticket
The new pre-registration forms are live and collecting data. 

I'm going to make two new tickets
1. Discuss moving the check box requirement from the [current pre-registration](https://codeyourfuture.io/itc-ct/) page to the ITD signup.
2.  Update the home page copy - to check if anyone minds.
