### ISSUE TITLE
Share this with each region

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#642]
### Background

We create bottle necks when we welcome new volunteers. Can the community do it better?

### Acceptance criteria

- share this with each CYF region - https://codeyourfuture.slack.com/archives/CTD17PH0D/p1708370883281139
- trainees and volunteers welcome new volunteers without staff 

### Owner

n/a

### Stakeholder

@CodeYourFuture/programme-managers 

### Approver

@lilianabermudes

**Comment by lilianabermudes** [comment]
Hi Halden,

Three comments/questions: 
1. What exactly do you want to share in each region?
2. I don't need to be on this ticket. I recommend that the Community Experience team be the approver. Mariana can be a stakeholder, and Alec can be the approver.
3. If we're making changes to the onboarding, I suggest that teams update the onboarding guide (having in mind that: if we all leave CYF tomorrow, new people would be able to pick up this task/process)
