### ISSUE TITLE
Do you homework

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#643]
### Background

Prioritise tasks from the role transition Jamboard - https://jamboard.google.com/d/1q7AD9kyGmigWPl7dHmlU6wGhQ1pcq88_Gcnbg8u41T0/viewer?f=0

### Acceptance criteria

New responsibilities are:
- prioritised 
- most urgent are time boxed

### Owner

@halden

### Stakeholder

Prom delivery team

### Approver

@SallyMcGrath

**Comment by SallyMcGrath** [comment]
This seems so delayed as to have become obsolete
