### ISSUE TITLE
Understand ITD and Fundamentals

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#644]
### Background

As we think about launching Sheffield, we should begin to familiarise ourselves with the ITD/ fundamentals processes 

### Acceptance criteria

- read this https://docs.google.com/document/d/1KuWZUrL8C7sqyPq5VDiS1TplkFjbF9RHzJrM-0sHOGU/edit
- book a meeting with someone who has done ITD/ Fundamentals (@Barny-6?) to work our pain points/ get advice 

### Owner

@halden

### Stakeholder

@emcglackenr1 @MattCFry 

### Approver

@halden

**Comment by MattCFry** [comment]
[Relevant thread](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1709024582512059) from Mitch

**Comment by Barny-6** [comment]
I last did ITD/Fundamentals 3 years ago. I'm not sure I would be of much use here but happy to talk if you think I'd be of asssitance
