### ISSUE TITLE
Canvas CYF volunteers

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#654]
### Background

All new volunteers are sent to CYF volunteers. Its the first thing they see in our slack, it sets the tone

### Acceptance criteria

Canva with 
- team/ class channels 
- google calendar 
- class-planner
- staff are not used as figureheads/ bottlenecks

### Owner

@halden

### Stakeholder

@MarianaVazquezCYF 

### Approver

@halden

**Comment by MattCFry** [comment]
Here is the[ canva for WM Vol channel](https://codeyourfuture.slack.com/canvas/C051HHYUAJ2). Hope it helps :)
