### ISSUE TITLE
Community Guidelines for Whatsapp

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#657]
### Background

We have moved comms with trainees' largely to whatsapp as we have found it a more effective medium of communicating with them. This involves DMs as well as groups and a community.
To have the correct safeguarding measures in place we are looking to add community guidelines to WhatsApp

### Acceptance criteria

- [x] Using the Slack guidelines write a draft of WhatsApp community guidelines. Cross reference with https://docs.google.com/document/d/1yAHXNuLt98wZToK-_gqKh0lOvTIGN4IcAwNByXFPpak/edit#heading=h.uzhs2tadkmrx
- [x] have this reviewed by Alec, Claire and German
- [x] make any necessary amendments
- [x] sign off draft for adding to the channel
- [x] Create a CYF docs page to link to

### Owner

Amy

### Stakeholder

Alec Claire German

### Approver

Claire

**Comment by AmyCYF** [comment]
@ClaireBickley  @alecmccrindle using your feedback from Slack I have put together the following draft for the Whatsapp community guidelines: https://docs.google.com/document/d/1fLfQwN_siz31lEFktZVh-5kI0_si8YXU5r0xZd_KGHY/edit

Do you think we should put this on the website somewhere so we can link to it rather than pasting this whole thing in Whatsapp?

**Comment by alecmccrindle** [comment]
Hi @AmyCYF - the WhatsApp guidelines look good to start with. I assume you learnt from other orgs and checked the legal obligations?

**Comment by AmyCYF** [comment]
@alecmccrindle we are aligned to the best practices outlined here: https://faq.whatsapp.com/361005896189245/?locale=en_US as well as the community guidelines outlined here: https://www.whatsapp.com/communities/learning/settingupyourcommunity

I have added a consent/ opt-in to WhatsApp comms on our sign up form. 

However from a Safeguarding perspective I will need to rely on your expertise.

**Comment by ClaireBickley** [comment]
thanks Amy, I've left a couple of comments the main thing I think is to follow the code of conduct and our values & working principles. I think it could be worth letting people know where to find things like our safeguarding policy and complaints process, what do you think?

Do you cover these topics in your first session? We have resources already that could work for this

I agree, hosting these online and linking to them is good - I would suggest the CYF Docs is a good space for this.

**Comment by AmyCYF** [comment]
@ClaireBickley I added some amendments based on your changes. 
Regarding putting this on CYF Docs-  would you be able to guide me on how to do that?

We do not cover this in the sessions, I can create another ticket about this though so we do not add top much to this task.

**Comment by ClaireBickley** [comment]
sure thing - shall we have a call next week and I can talk you through it?

**Comment by AmyCYF** [comment]
@alecmccrindle @ClaireBickley please let me know if you are happy for me to proceed with the updated version of the document? If so I will mark is as ready to go and will add it to WhatsApp once we set up the CYF docs link.

**Comment by ClaireBickley** [comment]
I'm happy! Will add you to Gitbook now (we use this for Docs)

**Comment by AmyCYF** [comment]
@ClaireBickley I have created the Gitbook doc and marked you to review it - thanks for you help with this!

**Comment by ClaireBickley** [comment]
looks good :) https://docs.codeyourfuture.io/trainees/digital-literacy-program/whatsapp-community-guidelines
