### ISSUE TITLE
Onboard new volunteers on dashboard

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#658]
### Background

https://dashboard.codeyourfuture.io/volunteers

This is a weekly task. Book this task into your calendar and clear the backlog every week. If you are away, hand this task to another person so the backlog doesn't build up. 

You can break this down into smaller by region  tickets to help you get through it. At the moment, according to the org needs:

## Prioritise

- [ ] Manchester ☄️ 
- [ ] Remote  🪨  (onboard them to North West to do Code Review)
- [ ] Sheffield 🪨 
- [ ] Birmingham 🔨 

### Acceptance criteria

Every NEW volunteer on the dashboard has been contacted
Every Sent Welcome Invite volunteer has been contacted again

### Owner

@haldenb

### Stakeholder

Mariana

### Approver

Sally

**Comment by haldenb** [comment]
I am onboarding all volunteers together as I want to break down the belonging to regions, so there is no need for regional tickets. 

I am asking for feedback in each session and with new volunteers, if it is raised as an issue that people would like a more specific introduction to regions, I will separate them :)
