### ISSUE TITLE
slacks

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#66]
**West Midlands:** TechMids and MidlandsJS. I need to ask if they can add you

**Comment by MarianaVazquezCYF** [comment]
Hey @AliciaE08 @haldenb @ShaunCYFSA @caromelendezl  can you please help me to identify in your regions what are the slack channels of your region? 

This is a good way to identify where we can have potential volunteers :)

**Comment by ShaunCYFSA** [comment]
Hi @MarianaVazquezCYF - The active Slack Channels in ZA are:
**For Volunteers:**
pd-capetown
cyfza-community-coordinator
southafrica
za2-sdc-eduteam

**For Trainees:**
#sdc-za-class2

**For both Trainee and Volunteers:**
southafrica-photos

**Comment by AliciaE08** [comment]
@MarianaVazquezCYF  I've added you to most of the channels where active conversations take place

**For **Volunteers**
north-west-volunteers
north-west-education
north-west-personal development 
nw5-buddies 
north-west-saturdays
nw-digitalskills-manchester

**For Trainees**
nw5-entire-cohort
nw5-leeds
nw5-manchester
nw5-pathways

**For Alum**
north-west-alum

**For Everyone**
north-west

**For Specific Activities**
north-west-outdoors
north-west picnic
