### ISSUE TITLE
Bug: Childcare form on docs is not accepting new responses

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#660]
### Background

https://docs.codeyourfuture.io/organisation/agreements-and-rules/student-agreement/student-expenses-policy/childcare-expenses-form
<img width="1446" alt="Screenshot 2024-02-29 at 08 02 54" src="https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/42203406/d3117c6a-44cc-4cea-815f-d105a1754614">

### Acceptance criteria

This page either has a functional form or a link to a functional form

### Owner

n/a

### Stakeholder

Claire

### Approver

Claire

**Comment by emcglackenr1** [comment]
Form: https://docs.google.com/forms/d/1D1vujTcfKnyRfDXYK6N4LvVEFmuVt7ndCO9GRG41XLw/edit#responses

Related post asking if there is a new process: https://codeyourfuture.slack.com/archives/C029341FPH6/p1709733055422989

**Comment by emcglackenr1** [comment]
@ClaireBickley - I've assigned you and marked as done to close the ticket.
