### ISSUE TITLE
Communicate Improvements in Tech Industry to GLA6 Grads

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#661]
**Communicate Improvements in Tech Industry to GLA6 Grads**

Is there something we can share with GLA6 to increase confidence in their employability potential and the industry?
Potential Actions:
- Communicate improvements in the industry (e.g. [the graph @Barny-6 posted recently] (https://codeyourfuture.slack.com/archives/G0143AEFSBF/p1708362580436799)) 
- Highlight grads gaining employment in other regions to GLA6
- Communicate qualities employers have said they really appreciate about CYF grads (e.g. collaboration ability in comparison to grads from other courses)

**Other options:**
**Speaker / New Volunteer?**
- Volunteers in Glasgow have spoken to them, but it might be good to get someone external to speak to them

**Grads**
- This relates to #570 

Completion Criteria:
- [x] Speak to volunteers {volunteer meeting 1st March) - Dara
- [x] Barny supplied information to volunteers to share with course completers

**Volunteer actions**
- [x] Move actions to volunteer board and agenda - Dara

**Comment by Barny-6** [comment]
I message the volunteers on Friday, is this done now?

**Comment by emcglackenr1** [comment]
I've edited now, I think it's done from a staff perspective
