### ISSUE TITLE
DLP Sessions including Safeguarding and complaints

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#662]
### Background

@ClaireBickley mentioned it would be worth letting people know where to find things like our safeguarding policy and complaints process,

Do you cover these topics in your first session? We have resources already that could work for this

### Acceptance criteria

- [x] @ClaireBickley link the resources we have for this
- [x] Meeting with Alec and Sally
- [x] Add these resources to the first session of the DLP

### Owner

Amy

### Stakeholder

Claire

### Approver

Claire

**Comment by ClaireBickley** [comment]
these are the [slides](https://docs.google.com/presentation/d/1o58dBm8lEdA2Iz8zABnsv6aFDjkXJp8XoUC9tuO1ER0/) we use - this is from Fundamentals Week 1

**Comment by AmyCYF** [comment]
Meeting with Alec and Sally: 

Agenda: 
- discuss integrating the Safeguarding and complaints elements to the DLP first session [Code of Conduct - Induction](https://www.google.com/url?q=https://docs.google.com/presentation/d/1o58dBm8lEdA2Iz8zABnsv6aFDjkXJp8XoUC9tuO1ER0/edit&sa=D&source=calendar&ust=1709983221303148&usg=AOvVaw3gACmWCnjsYCtHrp5qFH4z) (Alec to advise as Safeguarding lead)
- Address the fact that we do not have a trainee agreement with the DLP trainees. (Sally to advise based on SDC experience)
- discuss potential updates to onboarding to include these elements (Amy to lead as the DLP program manager)

Working document: 
https://docs.google.com/document/d/1VFBdOXxIlc57IA0xibDy-6zV-YW38Cmxh-BAabnX6Mc/edit

**Comment by AmyCYF** [comment]
Updates made to the week 1 slides: https://docs.google.com/presentation/d/1eROA0X3bEapjckdLmck3jVqYbZ_2ANSo7I7KRaS4OsY/edit#slide=id.g29389de9e42_0_159

Onboarding the vols leading the session on Saturday on Thursday
