### ISSUE TITLE
Work on collaborative document before Messaging Meeting

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#664]
### Background

See calendar invite Tuesday, 5 March⋅09:00 – 09:15 / 1400 - 14:15 As we work through our transition to a delivery team model, let's sort out how we take care of emails
https://docs.google.com/document/d/1_GkHk6uwioDr_p6SiJFOK6U0IrzrA-vsDWkTlrRHNSA/edit?usp=sharing

In this 15 minute session we will as a group set up our gmails to:

1. Store and use template messaging
2. Send personalised emails with mail merge
3. Subscribe to collaborative inboxes
4. Send mail from a google group

We are all doing parts of this, let's get everyone on the same page and reduce our workload with efficient professional practices. 

Before this call, use the notes section to ask questions, share expertise, and work through setup in your own time

### Acceptance criteria

- [x] You have read the meeting notes
- [x] You have added any team email groups that are missing
- [x] You have added the prom team to the email groups listed
- [x] You have tried to set up the listed email groups as collaborative inboxes and made note of any blockers
- [x] You have tried to set up your gmail to send from the groups you will use a lot and made note of any blockers
- [x] You have tried to send a test message using document email draft and mail merge and made note of any blockers

Do not spend hours on this.  Just note your blockers and move on. If you already know all this, set up a (free) mail merge client like YAMM https://talarian.io/ and try more complex personalisations.

### Owner

n/a this system doesn't work for our team

### Stakeholder

delivery team

### Approver

@SallyMcGrath

**Comment by MattCFry** [comment]
Question: Does 'document email draft' mean using the 'Preview in Email' button on the templates? That sends the doc content to Gmail as an email draft.

Google isn't being super helpful in this one.

**Comment by SallyMcGrath** [comment]
> Question: Does 'document email draft' mean using the 'Preview in Email' button on the templates? That sends the doc content to Gmail as an email draft.
> 
> Google isn't being super helpful in this one.

Yes - email draft from docs rather than from gmail templates. Gmail templates aren't shared - they belong to an account, so we should use the docs feature "email draft" instead

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/42203406/1fa21ace-83ed-40eb-8877-1273b87d90f8)
