### ISSUE TITLE
Clean up old laptop docs

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#665]
### Background

The old laptop system is still linked on our docs and this means we are running two systems at the same time. We need the old system to be removed, so all new requests go to the new system.

### Acceptance criteria

- [x] All docs about the old system are removed: https://docs.codeyourfuture.io/leaders/joining-the-course/laptops/requesting-a-laptop-or-support
- [x] Wipe the page and replace with a link to the new system
- [x] Then move the page to the archived folder, so links decay gracefully
- [x] Archive the form and turn off (turn it so it doesn't accept responses) https://docs.google.com/forms/d/1zcuZR3OXBn6B-PGBwTmtzJ69dc6uymOK-q5N7DJ1-gw/edit

### Owner

n/a this system doesn't work for our team

### Stakeholder

Claire

### Approver

Sally

**Comment by MattCFry** [comment]
@SallyMcGrath This should now be complete. Can you please review and close if you are happy with it :D

**Comment by SallyMcGrath** [comment]
There doesn't seem to be a link to the new system on this page. To me, it looks blank, and there's another link at the bottom to another page and that has a form link but nothing to signposts? Am I looking at the wrong thing? Can you link/explain the work you have done?

**Comment by MattCFry** [comment]
So "Wipe the page and replace with a link to the new system" suggested to me 'get rid of the page contents and replace with a link' found on [this page](https://docs.codeyourfuture.io/leaders/joining-the-course/laptops) (where that page used to live). And that is what I've done.

The link at the bottom just shows the adjacent pages in the archived section. I'm assuming that's a GitBook thing.

Judging by your reaction, I assume this was not your intention. Does [this draft](https://app.gitbook.com/o/-LcSabThbCRVBSHYbXg4/s/-MLT3gO-UutAs-bJiUtk/~/changes/615/leaders/joining-the-course/laptops/requesting-a-laptop-or-support) look more to your liking?

**Comment by SallyMcGrath** [comment]
So, think through with me what the user experience is and what we are trying to do here, instead of thinking of my liking, think of the user. 

A user is trying to get a laptop or help someone else get one. They follow a link to this page, which we know they will do because there are links all over the place. They have landed on this page. What does the user do next? How are we helping, informing, or guiding this user to their goal? We want as few steps, as simple steps, and no missing stairs. A missing stair is like, a dead link, a blank page, no way to continue. 

I feel like if I was trying to get a laptop and I didn't know how to do it, I would be lost in a maze. Don't you?

**Comment by MattCFry** [comment]
Okay. I've merged the draft as it does give guidance on this and does not leave a blank page. It still lives on archived pages. [Live page](https://docs.codeyourfuture.io/archive/archived-pages/requesting-a-laptop-or-support)
