### ISSUE TITLE
Create createria for attendees from more regions to present their demos at the job fair 

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#670]
**Criteria to apply for demo**
- Graduates or trainees without a job
- 1 demo per region - except London (4 or 5 demos)
- Team project, represented by at least 1 person (but all members can come)
- We'll pay expenses for the trainees/graduates

**Criteria to select the demo**
- Ideally to be a product different from what is already planned for London 10
- Prioritise WM, NW and Glasgow
     - WM: Portfolio Module (Chioma, Chiddima, Kavita, John G, X)
     - NW: Portfolio Module (Levi and Leila Faez > confirm if they worked together?)
     - Glasgow: Portfolio Module - Spotify Briefing (Mandy, Christina, X?) [repeat]
     - Milad / Haroon: team work? (Church product?)

**Comment by kfklein15** [comment]
Done, and new ticket for invites created: https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/705
