### ISSUE TITLE
Signposting Issues on Mobile

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#674]
**Summary** 
Drop down menu didn't work on mobile. Find out what / in what instance. Turn into actions to fix it.

**Background**

When visiting West Midlands Dara tried to go through it on mobile with a tech ed volunteer and the drop down didn't work on either of our mobiles. It worked fine on my laptop. This was on 03/03/2024 at around 6pm.

Is the problem just Mozilla? 
- [x] Ask volunteer what browser they use
- [ ] On 12/03/2024 add additional actions depending on if/how volunteer responds. 

**Checking on Chrome Dev Tools it seems to work fine:** See image below

![Image](https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/64873698/56d26b8f-74d8-4ee0-8c92-8f714c967e56)

**Comment by SallyMcGrath** [comment]
No, the answer is to encourage the volunteer to open a ticket directly on the repo. Don't create an extra step or bottleneck, connect the person directly.

https://github.com/CodeYourFuture/CYF-Signposts/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by emcglackenr1** [comment]
Thanks for feedback 😊
I did ask them to but it looks like they didn't do one. Thanks for feedback though and I'll note for next time that I shouldn't create an issue as well as asking them
