### ISSUE TITLE
Build cohorts calendar 2024 for Capgemini

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#675]
### Background

We need to send them the 2024 calendar with estimated dates for new cohorts in each region. @Claire and I can work on the calendar, but I want to agree on the requirements first with you.

### Acceptance criteria

- [ ] Agree on the premises for suggested dates:
- [ ] 1. Look at the requirements - are you still happy with [the suggested employment rates](https://docs.google.com/document/d/1KuWZUrL8C7sqyPq5VDiS1TplkFjbF9RHzJrM-0sHOGU/edit#heading=h.kdxzky7gbqs6)?
- [ ] 2. Are there any other requirements to launch ITD, such as cohort founders?

### Owner

@Liliana

### Stakeholder

@claire @sally @karen

### Approver

@german

**Comment by kfklein15** [comment]
I think we have finalised this, correct?

**Comment by lilianabermudes** [comment]
No, not yet. In progress...

**Comment by lilianabermudes** [comment]
But also, it would be great to get answers to those questions :)

**Comment by kfklein15** [comment]
1. I am happy with the employment rates. If the market picks up like crazy, maybe we want to review them in 6 months time. But looking at the numbers in other cohorts, I think we should keep them this way.
2. The Programme team is working on the [Cohort Launch tasks](https://github.com/orgs/CodeYourFuture/projects/110/views/4?sliceBy%5Bvalue%5D=0+-+Community+Setup+) (WIP) that has all the set-up tasks that MUST be done to start a new cohort. Maybe we can, once we finished, link this board to this doc?

**Comment by lilianabermudes** [comment]
That's great to know, thanks!

**Comment by kfklein15** [comment]
Who else do we need to give us input on this task? I love closing a ticket :D

**Comment by lilianabermudes** [comment]
Let's close it (for now); this will be heavily reopened - believe me!
