### ISSUE TITLE
Collecting Alumni Retention & Progress Data

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#679]
**Context**
We want more details on where our alumni work and how long they worked there. See https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/607 for more details

**Acceptance Criteria**
- [ ] A % figure on the number of grads with a retention of over 2 years
- [ ] A figure average retention in the first role
- [x] Data on where >75% of our alumni have worked

**Owner**
@MattCFry 

**Stakeholders**
@Barny-6 @MattCFry 

**Approver**
@Barny-6

**Comment by MattCFry** [comment]
Retention Measuring: Claire will add new columns to global trainees. Barny will work with her on this. 

Automate the retention period between the job start date and the end date.

**Comment by MattCFry** [comment]
Promotions, within the same company, should be counted as a 2nd role.

**Comment by MattCFry** [comment]
@Barny-6 could you provide a rough priority of groups to focus time on? Using the groups on Global Trainees.

Additionally, what groups do we not need info from?

**Comment by MattCFry** [comment]
Another question. I found [this survey](https://docs.google.com/forms/d/1BWoqDi7LCI5YLJ54SOFjp16WU8Do9jjhHhiG2XPV9B4/edit). Is this something we can send out again through mail merge?

Update 20/3/24: I've changed that survey, which might make it a bit more useful to us. @Barny-6 can you give me your thoughts?

**Comment by MattCFry** [comment]
Taken this ticket and align with Barny to do regular tasks towards this
