### ISSUE TITLE
Ask people to organise the after party

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#686]
**Background**
We would like to have an after-party when the Job Fair finishes, but need to identify volunteers that can help us. Below are the A/C for the Party format.

**Task**
- [ ] Find 2 volunteers to organise this

**Acceptance criteria for the party**
- After-party from 3.30-7pm
- Focus is on networking, so people should be together in one place as much as possible
- Keep the budget close to zero (or very low)
- Drinks shouldn't be too expensive so the community can afford them

**Comment by MarianaVazquezCYF** [comment]
@haldenb how are we doing with this? :D

**Comment by haldenb** [comment]
I am a little confused what needs organising?

I have booked the big chill for after just waiting for confirmation 

Do we want activities? Networking - with who? Are we inviting the companies to the party?

**Comment by MarianaVazquezCYF** [comment]
great! thats it honestly ! how would that work? people will buy the drinks?

and when you have the info, could you please post it on the channels so people can get excited please? and yes companies are welcome to join us!
