### ISSUE TITLE
Volunteer Policy Review

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#691]
### Background

Make volunteers aware of CYF policies:
- expenses https://docs.codeyourfuture.io/trainees/support/trainee-expenses
- code of conduct https://codeyourfuture.io/about/code-of-conduct/#:~:text=At%20CYF%2C%20we%20want%20a,or%20harassment%20in%20our%20community.
- Volunteer expenses policy https://docs.codeyourfuture.io/volunteers/volunteer-expenses

### Acceptance criteria

- Met with regional teams to discuss
- Pinned both in Canva of regional channels
- trainees authorise expenses correctly
- code of conduct procedure followed

### Owner

@halden

### Stakeholder

@halden @alec @MattCFry 

### Approver

@lilianabermudes

**Comment by MattCFry** [comment]
Wrong Matt XD
