### ISSUE TITLE
Onboarding Delivery Team to Airtable - Halden

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#692]
### Background

The new laptop loan system is in a position to be launched for global use. We need to get all the relevant delivery team onto airtable. 

### Acceptance criteria

Read/watch through the following. Add all questions to the Q&A doc
- [x] [Guidelines for staff](https://docs.google.com/document/d/1MWbVARMdF6rnb3I9JHA8T682wm7tiyQ1K-ZUSHNkjRA/edit#heading=h.ctwgnu3t1c9c) (Ignore the part about QR codes for now)
- [x] [Training Video](https://drive.google.com/file/d/1DfK3HBwM9fKsY-86r5NVcAqZQZ0cEBwc/view?usp=sharing)
- [ ] [Staff Guide](https://drive.google.com/drive/u/0/folders/13gb3AgjUppR3TugFbbBRITIrjftzAZNG)
- [ ] [Q&A](https://docs.google.com/document/d/1vDq_2mIJC3c4ZS90DUD_dWhUjljRRrk_fwOtbGzt-a0/edit)

Once completed 
- [x] Add yourself to #laptop-loans on Slack.
- [x] Book a 15-minute meeting with Matt.
- [ ] Find Airtable on Bitwarden and come prepared with it.

### Owner

@haldenb 

### Stakeholder

@MattCFry 

### Approver

@haldenb

**Comment by ClaireBickley** [comment]
Hi Matt - do I need to be in the 15 minute calls? What will the calls cover?

**Comment by MattCFry** [comment]
Ah, since we are not logging in through the Google account then we don't need to do verification. Right?

I remembered we said before but that's changed now

**Comment by MattCFry** [comment]
Feel free to rebook when you're better @haldenb :)

**Comment by MattCFry** [comment]
Im going to close this as we will do something slightly different
