### ISSUE TITLE
Email Strategy

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#694]
**Summary**
Following the discussion on DT Template messaging, mail merge, group inboxes (05/03/2024), we discussed consolidating regional inboxes into program delivery inboxes for better communication and efficiency.

**Completion Criteria** 
- [ ] Halden to set up volunteer email
- [x] Dara to set up trainee email - yes but not linked yet, see discussion below
- [ ] More actions TBD 

- [ ] Feedback to Sally about the consolidation plan

**Comment by haldenb** [comment]
The volunteer/ trainee email is only worth setting up if we can get regional emails to forward to the Proramme delivery group.

So I wold suggest making that a ticket, if it is not possible to do the first step steps 3 and 4 won't help us

**Comment by emcglackenr1** [comment]
Hi @haldenb , do you want to set that up as a ticket and link it? It sounds like you have a good understanding of what that ticket would look like. :) 
As I mentioned here, [I was unwell when we had this meeting](https://codeyourfuture.slack.com/archives/C029341FPH6/p1709809788558269), so I'm not entirely clear on the details. It would be helpful if someone who wasn't unwell during the meeting could create the issue.
