### ISSUE TITLE
Write strategy to speak at events with Barnys comments

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#696]
**Background**
Speaker events suggestions from Barny.

**Acceptance criteria**
- Review the below and add them to the current strategy/guidelines
    -  Asking the community to speak at regional meet-ups and attend and network 
    - Providing workshops and skills about this 
    - Asking just to ask for a 3-minute intro when they attend the event
    - If they want to speak at an event, they can talk about what they are doing at Code your future and about our open-source syllabus and our incredible demos! 
    - They will gain a CYF t-shirt, personal marketing about their volunteer experience, gain more soft skills, 
    - On this strategy, also put the German strategy to talk about more significant events! 
- Approve the final document: @alecmccrindle 

stakeholfder:
@Barny-6

**Comment by MarianaVazquezCYF** [comment]
This ticket is parked as we need to establish the priorities of what we will work on

**Comment by alecmccrindle** [comment]
Addin my notes from chat with Barny. 

Speaking at local events - alumin and volunteers

staff speaking at events
find the names of local event organisers - be really targeted in how we know them
ask people who we think would do a great job
popular topics - lightnigh talks + or do a talk (community learning, flipped classroom, soft skills, etc.).
International events

Need a strategy - better network strategy - follow up with G
UPDATE

Add this to Priorities
