### ISSUE TITLE
Policy update  - Volunteer Agreement

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/CYF-Staff-Tickets#7]
https://docs.google.com/document/d/1U8fOZchdaSgbJZER6GB_NnSDletSunpnhkOxu2OpfH0/edit

**Comment by ClaireBickley** [comment]
Working draft is here https://docs.google.com/document/d/1I0H0qc_IMRSA10ORDEo7oHDH9KP-QEu5m7ZI9I8aII8/edit

Further discussion to be had with Alec and Liliana.

**Comment by ClaireBickley** [comment]
new version complete, being reviewed by Traver Smith LLP

**Comment by kfklein15** [comment]
Is this still in review, @ClaireBickley ?
