### ISSUE TITLE
DLP Impact report

### ISSUE THREAD

**Issue by ShaunCYFSA** [CodeYourFuture/CYF-Staff-Tickets#702]
Background
Create an impact report to show the benefits of providing smartphone skills to communities.
Use the report as part of a funding proposal

Acceptance criteria
Review this [document ](https://docs.google.com/document/d/11dvyDq7U9oVyquCrwpsRtPHEX4PMOlp1/edit)to ensure that it covers the basis of a good impact report.

Owner
@shaun

Stakeholder
Germán, Lana Franks

Approver
Shaun, Lana Franks

**Comment by ShaunCYFSA** [comment]
Currently updating graphs as per suggest from @gbencci 
Awaiting feedback from Beth Uriel Trainees

**Comment by gbencci** [comment]
thank you! review done!

**Comment by ShaunCYFSA** [comment]
Thanks. @gbencci 
Data graph options added to the Impact form.
I am awaiting feedback from trainees.

**Comment by gbencci** [comment]
thanks @ShaunCYFSA. If possible, please ask Lili for review as she has a very good eye for strong narrative.

**Comment by ShaunCYFSA** [comment]
1 applicant has provided feedback.
@lilianabermudes - Could you provide your thoughts on this [document](URL), please?

**Comment by lilianabermudes** [comment]
Hi Shaun, I've left some comments and editing suggestions. Let me know if you need more help.

How long this report should be?

**Comment by ShaunCYFSA** [comment]
@lilianabermudes - Thank you very much for the comments.
The report does not need to exceed 1 1/2 - 2 pages.
