### ISSUE TITLE
Providing observations / notes from WM visit

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#703]
_**Summary**_ 
Following my visit to #663 I have written up some notes / observations
I wanted to get feedback on it before I shared it 

- [x] [Ask](https://codeyourfuture.slack.com/archives/C029341FPH6/p1709642716780619)
- [x] Share notes[ - shared](https://codeyourfuture.slack.com/archives/C029341FPH6/p1709916704198269?thread_ts=1709642716.780619&cid=C029341FPH6)

**Comment by haldenb** [comment]
Where are the notes? :)

**Comment by emcglackenr1** [comment]
Hey, the[ notes are posted now. ](https://codeyourfuture.slack.com/archives/C029341FPH6/p1709916704198269?thread_ts=1709642716.780619&cid=C029341FPH6)I was just getting feedback on them first because they were long.
