### ISSUE TITLE
Add ticket to update marketing material 1400% stat

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#713]
**Background**
We need to update the 1400% stat since it is misleading

**Acceptance criteria**
- Define which is going to be the new stat
- Update the Decks, Flyers and Presentations

**Comment by alecmccrindle** [comment]
I've used the 800 hours stat, but can use another instead. Need to share with team.

**Comment by alecmccrindle** [comment]
Changed it to 5.5x lower attrition rate.
