### ISSUE TITLE
Make a plan to Promote Portfolios on Linkedin

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#715]
**Background**
We want to support our course completers to find jobs, so we want to promote their portfolios

**Acceptance criteria**
- Understand the criteria for a good portfolio
- Identifying the 5 good portfolios
- Raise sprint to create the content

**Comment by alecmccrindle** [comment]
Had a chat with Barny on this.

Getting 5 good portfolios is a bigger challenge as it's subjective. 

Idea:

Gamify which portfolios to promote with volunteers (how do we organise this, and it is the best idea)

5(?) winners will get shared on socials

Everyone gets a couple of bullet points of feedback (who can do this)

Moving to next sprint.

**Comment by alecmccrindle** [comment]
@kfklein15 to add a list of portfolios that look good enough to share?

**Comment by alecmccrindle** [comment]
@kfklein15 - a prompt on this. Not a priority though.

**Comment by kfklein15** [comment]
@alecmccrindle , do you have the link the Sally or Barny had with all the portfolio links? I cannot find it :(

**Comment by kfklein15** [comment]
Barny sent me the link: https://codeyourfuture.slack.com/archives/C01TKCAHYN4/p1707920653696869

**Comment by kfklein15** [comment]
**Understand the criteria for a good portfolio**
- The volunteers have put together this document: https://docs.google.com/document/d/1rUyO6MAHYreENCOqQIW3MJDiRtc0K0Bz2jLj_b3Bzcc/edit
- These are the main criteria for a good portfolio:
       - Example of your work: add projects that work, have simple but good usability and be responsive. These should have links to your GitHub (with a decent ReadMe file) and the app. 
       - About me: tell people who you are, what you know (i.e. tech stack) and other experiences that can make you stand out. Don't forget a sample CV.
       - Your goals: make sure it is clear what your next challenge would look like and the type of work that inspires you.
       - A way to get in contact: e-mail, LinkdIn, contact form. You can do whatever you want, as long as it works and people can contact you.
      

**Identifying the 5 good portfolios**
@alecmccrindle , I choose more than 5. :D 
- https://olenareukova.netlify.app/#home - London
- https://levicharles.vercel.app/#services - Sheffild
- https://leilafaez-portfolio.vercel.app/ - North West
- https://olha-danylevska-pink-portfolio.netlify.app/#main - London
- https://portfolio-alexjora.netlify.app/ - South Africa
- https://bediomuri.netlify.app/ - London
- https://portfolio-ebrahim-beiatiasl.netlify.app/ - London
- https://kamportfoliomain.netlify.app/ - North West
I could not find a good one from Birmingham. And have too many form London :(

**Comment by alecmccrindle** [comment]
[Wrote the first version of Olena's promotion](https://docs.google.com/document/d/1x-zE1-1O4opar4-TYV-hySAutr-biozSz3WxIgH39Vo/edit), made a template in InDesign to make high-quality PDFs.

Waiting for feedback from Barny and Sally, but plan to share asap.

**Comment by alecmccrindle** [comment]
[Next sprint ticket here](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/1075)
