### ISSUE TITLE
[Anderson] Design template for Eventbrite and meet up

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#726]
## Background
In canva we have different images that we use for events, however, the images look repetitive and ugly! in addition, because of the lack of a template, some volunteers design everything that they want and this doesn’t follow the cyf design guidelines. Therefore, we have asked Anderson to help us design templates 

## Acceptance criteria

- [ 
- [ ] Anderson to created editable template in Google Slides or Canva for events 

### Owner
@MarianaVazquezCYF 

### Stakeholder
@alecmccrindle / Anderson

### Approver
@alecmccrindle

**Comment by SallyMcGrath** [comment]
stale
