### ISSUE TITLE
Review Trustee Application Process

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#735]
We need agree and approve the suggested process to move on with the role promotion externally.

https://docs.google.com/document/d/1QZJWkkLBD3JomW9aHaKdw_zBMcRI_fPKsvc5g9oBCnw/edit#heading=h.l5y6nsw3gfog

**Comment by gbencci** [comment]
@lilianabermudes are there any specific questions or areas you want me to go over? If you and Claire are both in agreement and there are no other areas of concern, we can send it over to trustees. 

At the moment, the main problem is we don't have candidates for the alumnit trustee role (or only one interested).

**Comment by lilianabermudes** [comment]
@gbencci we only wanted to know if you were okay with the questions/process.

Would you like to share it with the trustees before we start really promoting it? Or can we start sending emails to the alumni group with this process? Just unsure about the situation with trustees atm.

**Comment by gbencci** [comment]
yes @lilianabermudes, please go ahead and send it to the alumni group. There is no need to wait for trustees approval to have a pool of candidates. This will take a while

**Comment by lilianabermudes** [comment]
Okay, thanks!

@ClaireBickley I've put in my list to draft email + send email to the alumni group on Monday. Let's give them a couple of days.

My second communication will be following up with some alumni we think would be a good fit
