### ISSUE TITLE
Ask alumni for new stories

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#741]
## Background
We need some new stories for our website and to share with partners, volunteers and applicants. We haven't written any new stories for several months, so worth contacting those who found jobs recently. 

## Acceptance criteria

- [x] Update alumni interview form
- [x] Emails / Slacks to folks on t[his list](https://docs.google.com/document/d/1L8j9gFbx5EGTuxi7Zip0m20bYfl1W6LOOF6pWrREY-4/edit)
- [x] Follow up with folks already asked
- [ ] Make tickets for stories

### Owner
@alecmccrindle 

### Stakeholder
@MarianaVazquezCYF 

### Approver
@alecmccrindle

**Comment by alecmccrindle** [comment]
Older stories too

**Comment by ellie** [comment]
You probably didn't mean me :) Your org looks cool though!

**Comment by alecmccrindle** [comment]
Haha, thanks @ellie - I will be careful when copy and pasting slack names in future. 

I just reviewed your website - you would be a great CYF volunteer / speaker / friend. [Our website](https://codeyourfuture.io/), our (open-source) [curriculum](https://curriculum.codeyourfuture.io/). Do get in touch. 

EDIT: or just ask questions here!

**Comment by alecmccrindle** [comment]
Asked a few folks, will make tickets once they share their stories. Closing this ticket.
