### ISSUE TITLE
List of examples of misplaces Slack messages

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#75]
- Help the community talk to each other by creating open communication practices
- Avoid using lock channels for information that should be public
- Example, coursework is only fixed in the class
- Encourage usage of module channels

Action
Create a list of examples and practices for Slackk communication approach to get the community to work together.

What is it for?
We will use this to train the team and include it in the community and use it to monitor our comm approach moving forward

**Comment by SallyMcGrath** [comment]
https://codeyourfuture.slack.com/archives/C029341FPH6/p1675263271535519

**Comment by gbencci** [comment]
Thanks @SallyMcGrath I'll take it from here

**Comment by SallyMcGrath** [comment]
Thanks

I created Slack emoji channel bots which will automatically repost messages to the right channel for these emojis:

:html: -> #cyf-module-html-css
:css: -> #cyf-module-html-css
:react: -> #cyf-module-react
:postgres: -> #cyf-module-sql
:node: => #cyf-module-node

Possible further channel bots (but we would need to upload these custom emojis)

:codewars: -> #cyf-codewars
:devops: -> #cyf-devops
:linux: -> #cyf-ask-tech-stuff
