### ISSUE TITLE
WM6 Support

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#772]
**Summary** 
West Midlands 6 are waiting to start. 
Two trainees are engaged, Halden and Matt have both spoken to them. 

**Completion Criteria**
- [x] Discuss co-working with volunteer - @MattCFry 
- [x] Communicate outcome with team and handover - @MattCFry 

**Additional Actions Depending on Outcome**
If it seems like a viable option for them to use this space, then we can communicate this to them.
If we don't get a volunteer to support with this, @haldenb could then support them by putting them in touch with a volunteer.

**Comment by MattCFry** [comment]
[Post asking for volunteer support](https://codeyourfuture.slack.com/archives/C011ZSSTFQV/p1710498656575579)

**Comment by MattCFry** [comment]
I've added 2 WM5 trainees who volunteered to arrange things with WM6. @emcglackenr1 can you confirm if this ticket is done?

**Comment by MattCFry** [comment]
I'm going to close as this seems to be done. Any new actions can go in a new ticket.
