### ISSUE TITLE
Retro for Job Fair

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#777]
## Background
We want to ensure that we continue to improve the job fair format. In addition to making the next job fair more efficient, effective and with more community involvement, we also want to let the wider team know how it went. 

We want to tell people how it went so they can contribute to future events, but also, so we can celebrate the wonderful work and community success that went into the recent job fair. 

## Acceptance criteria

- [x] Analyse and synthesise surveys (ask for any additional feedback from those who didn't get the 1st survey)
- [x] Meet to do a retro
- [x] Make a ticket to share the results with the wider org

### Owner
@alecmccrindle 

### Stakeholder
@MarianaVazquezCYF 

### Approvers
@alecmccrindle

**Comment by alecmccrindle** [comment]
@MarianaVazquezCYF  - for the Job Fair retro, I think we follow the @KFK (she, her)'s template? 

Now that you have sent the survey, is there anything else we can do to get the feedback we need to make the improvements we think are needed for the next Job Fairs? For example, I wonder if we also open the template to the attendees from CYF if they didn't get the survey? e.g. CYF staff, for example. 

We might have to make it a doc instead as the miro template may not be big enough. 

No pressure to answer this comment today!

**Comment by MarianaVazquezCYF** [comment]
this is the documet: https://docs.google.com/document/d/1TxjmYJrTs5bhRoXG_mKnbE3CwyqV6ItBbETwjDyBrZQ/edit

I didnt do a miro, just the document and I copied and pasted all the information from survey, and yes feedback will be implemented .

Did I reply to your questions ? :D

**Comment by alecmccrindle** [comment]
Great job getting the feedback @MarianaVazquezCYF!
