### ISSUE TITLE
Submit talk for Manchester tech Festival

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#779]
https://sessionize.com/manchester-tech-festival-2024/

I need the following info:
Session tittle and session description! 

Submissions end on June 7th

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , add the folder with the talks to this ticket.

**Comment by MarianaVazquezCYF** [comment]
https://drive.google.com/drive/folders/1j-58k2YS8VM82xzXMndysCwuWBjI9gy6

Thanks team! ok I will unassigned myself :)
