### ISSUE TITLE
Celebrate nomination for the WSIS Prizes 2024

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#782]
## Background
We have been nominated for a UN award. [WSIS is run by ITU.](https://www.itu.int/en/Pages/default.aspx )

Online public vote is open now so we should promote on social media and outreach. 

## Acceptance criteria

- [ ] Consider which channels to promote
- [ ] Make more tickets / take simple actions

### Owner
@alecmccrindle 

### Stakeholder
@SallyMcGrath  @MarianaVazquezCYF 

### Approver 
@alecmccrindle

**Comment by SallyMcGrath** [comment]
Just checking you know you have published this on the internet?

**Comment by alecmccrindle** [comment]
I didn't realise! Or forgot. I conflated people not being able to make tickets on our board with them not being able to see our tickets. Updated the words and will check other boards for public suitability.

**Comment by SallyMcGrath** [comment]
<img width="581" alt="Screenshot 2024-03-15 at 15 21 14" src="https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/42203406/1667fae2-ce1e-45d4-998b-640a823a4264">

It shows you which are public on the repo itself with the word PUBLIC and then on projects the world symbol shows it is public. I also added a loudspeaker on this project to make it clearer, which might help


<img width="664" alt="Screenshot 2024-03-15 at 15 21 51" src="https://github.com/CodeYourFuture/CYF-Staff-Tickets/assets/42203406/0bb2fc18-88cd-44f6-808d-3a4101e87cb5">

**Comment by SallyMcGrath** [comment]
Hey, if this is backlogged, shall I just post about it? It will take me 20-30 seconds - probably less time than writing this comment. Or have you got some big plan?

**Comment by alecmccrindle** [comment]
Haven't got to it yet @SallyMcGrath - post content will be awesome, thank you.  

@MarianaVazquezCYF can post during the week.

**Comment by MarianaVazquezCYF** [comment]
Hello team, I am working on this now!! Anderson will create an image and in the meantime, I will create a post on LinkedIn, Instagram and I will send an email to the community to vote for us!

**Comment by MarianaVazquezCYF** [comment]
this is done, I will create a new ticket for our stand during the nomination :)

**Comment by SallyMcGrath** [comment]
Thanks @MarianaVazquezCYF
