### ISSUE TITLE
building event guides/ roadmaps projects

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#789]
Create roadmaps or guides that could work for all our events events:

- [ ] - Job fair 
- [ ] - Ladies brunch
- [x] - Friday we do demos 
- [ ] - Summit 
- [ ] - Tech Confessions 

**Tasks**
- Need the ability for CoCos to manage the events/steps
- Need to show CYF Staff what is happening

**Comment by kfklein15** [comment]
Let's build something like our [Grant Board](https://github.com/orgs/CodeYourFuture/projects/154), maybe?

**Comment by MarianaVazquezCYF** [comment]
I checked it but the format does work! I will explain how I want them to look in our meeting tomorrow !

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , I started a [draft](https://github.com/orgs/CodeYourFuture/projects/173/views/1): we have a repo and a project. Now I just need you tell me which other steps are needed so we can trial it with the summit  - or the highest priority event
