### ISSUE TITLE
WTM Scotland - International Women's Day 04/03/2023

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/CYF-Staff-Tickets#79]
Saturday 4th of March from 9 am to 5:30 pm at the Sir Charles Wilson building, which is part of the University of Glasgow. 

[www.wtmscotland.com](https://www.wtmscotland.com/)

- [x]  Possibility of becoming Community/Charity Partners
- [x] In conversations to get a booth and speaker slot for CYF.
- [x] I'll update @MarianaVazquezCYF as soon as I have more info.

**Comment by MarianaVazquezCYF** [comment]
Perfect thanks Caro! what capacitity do you see to have our own event ? (it can be small)

**Comment by caromelendezl** [comment]
Update 16.02.2023

- CYF Booth - we've been asked arrive at 7:45 am to have CYF's booth set up. We can leave things the day before the event as well.
- They are currently sold out but we have some reserved for sponsors and partners.
- @MarianaVazquezCYF will be the main speaker as CYF Head of Community & Outreach (20 mins)
- Looking for a CYF Glasgow graduate to come to the stage and share their experience 

- [ ] Ask in the community for a Glasgow graduate - can any volunteer recommend one?
- [ ] Send the name of the speaker, Job title + picture
- [ ] Send our needs for the booth. Plug for 2 laptops (Volunteers sign up, leads), a table, if available a screen
- [ ] Send time for the talk - 20 mins
- [ ] Confirm we would like to be listed as partners for the conference


-

**Comment by MarianaVazquezCYF** [comment]
![Marianaphoto](https://user-images.githubusercontent.com/91734869/219738203-407a65ad-633f-4632-8ae4-8e224acef46f.jpeg)
This is my picture Caro :) btw is : Head of Community Building and Outreach :)
