### ISSUE TITLE
Download payslips

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#797]

**Comment by kfklein15** [comment]
@ClaireBickley , can you help us with this with @LeandaCYF , please?

**Comment by ClaireBickley** [comment]
this is already with Leanda - she is just swimming in audit at the moment - it's on her list definitely

**Comment by LeandaCYF** [comment]
Hi, I have saved all payslips and P60's from the MHA Sage system into a folder and sent access in the shared drive to Alec. Thanks
