### ISSUE TITLE
EXL volunteering opportunities

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#798]
### Background

EXL are looking for more volunteering opportunities. They currently have sponsored 5 DLP cohort for £10,000 and this comes with 25 volunteering opportunities.
Liliana suggested they look at the SDC.

### Acceptance criteria

- [x] Share corporate volunteering opportunities with Muskain.

### Owner

Liliana

### Stakeholder

Liliana

### Approver

Liliana

**Comment by AmyCYF** [comment]
@lilianabermudes are you happy to action this ticket?

**Comment by lilianabermudes** [comment]
@AmyCYF if you look at slide 11 (DLP info), was that the deal with them? Because if they paid 10k, I will change that number to 10K instead of 9,900 :)

https://docs.google.com/presentation/d/1RBBOWAGlKFuhM9MiKJngfgF_mMNR4KjWNsSmNL1QBuo/edit#slide=id.g259cd8596f4_0_0

**Comment by AmyCYF** [comment]
I double checked the invoice and it was £10,000 excl Tax. 
[Invoice INV-0055 (1).pdf](https://github.com/CodeYourFuture/CYF-Staff-Tickets/files/14694455/Invoice.INV-0055.1.pdf)
