### ISSUE TITLE
Meeting with the Sheffield volunteers

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#799]
### Background

We are wanting to have a DLP cohort up and running in [Sheffield](https://docs.google.com/document/d/1Pfzt1S2gQ7YHRXnyjB1FaxIFLSPaOeEZfXixwlFlm3I/edit#heading=h.jf6luv4l20kh
) by the end of April.

We need to meet with the volunteers to Discuss the following: 

- that we will be starting with the DLP before proceeding with ITD and SDC. 
- DLP volunteer roles and responsibilities
- outline next steps with tight deadline in mind

@MarianaVazquezCYF has been the point of contact with these volunteers up until this point.

### Acceptance criteria

- [x] Meeting set up with the volunteers to discuss getting a cohort running in Sheffield in April. 
- [x] CYF team to attend: @haldenb @lilianabermudes @emcglackenr1 @amy

### Owner

Mariana

### Stakeholder

Liliana, Halden

### Approver

Amy

**Comment by MarianaVazquezCYF** [comment]
Great team! I will contact the volunteers now and I will check something in your calendar to schedule a meeting with them in order to start this chapter moving!

**Comment by MarianaVazquezCYF** [comment]
`Hello team, I will also send an email to the applicants. in that region, maybe they want to volunteer and for sure, they will know people interested to attend the course! I will cc you!`

**Comment by MarianaVazquezCYF** [comment]
Updates:

[ ] Our 2 most committed applicants for th SDC are interested to be volunteers for the DL
[ ] 3/5 volunteers have replied expressing their interest in volunteering: Sean, Sulivan and maybe Tom 
[ ] Tom and Sean have replied with their contact for venues! Tom have suggested asking the company where he work for paying for our venue and in the future hosting us on their offices and Sean has introduce us to Emma from the Sheffield Tech Park who could host our sessions
