### ISSUE TITLE
Continue working on Community Event for GLA6

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#800]
**Summary**
Engagement is down, a community building event in Glasgow would be good. 
Responses to it aren't very high so far. 
e.g. 

- [post in cohort channel ](https://codeyourfuture.slack.com/archives/C044M02QTM5/p1709748847027519)
- [post in community coordinator channel](https://codeyourfuture.slack.com/archives/C04PS57LZJ4/p1709807651368579)
- On advice from Mariana, Dara contacted formerly active trainees / volunteess directly via Slack and most have said they probably can't make it

This ticket relates to [#681](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/681)

Since @alecmccrindle and @haldenb are visiting, Dara and Mariana changed the community day to their arrival week. 

**Completion Criteria**

- [x] Update timetables to remove current community day - Dara
- [x] Create a form asking the community what they want to do for the community day and when  - Mariana 
- [x] Send a deadline for people to reply to the form - Wednesday 3rd of April 
- [x] Send emails to the people in the community (trainees, grads, volunteers) asking them to fill out the form.  - @emcglackenr1 
- [x] Share on Slack - @emcglackenr1

**Comment by alecmccrindle** [comment]
Hi @emcglackenr1 - @haldenb and I were working on monthly / frequent socials. All communities.  

[Discussions and actions here](https://docs.google.com/document/d/1mT19p72KzJF0kCAYTa5IzaBqSpttDA15T2vUpYfcB0E/edit#heading=h.h39q51mqb2ve). One of the actions is @MarianaVazquezCYF to discuss combining your desire for a Glasgow community event with the start of regular meetings. 

She'll mention this in your meeting on Monday.

**Comment by alecmccrindle** [comment]
Also, I'm booked to visit Glasgow, arriving the morning 12th, departing Glasgow train station at 3pm. Maybe try to host an event on the 12th evening or 13th around class? I don't have stay for the whole event, and this timing may not work at all. In which case, I'll find something else to do :) 

@haldenb was planning to come too.

**Comment by emcglackenr1** [comment]
Updated actions after meeting with Mariana :)
Part 2 moved to another ticket. #830
