### ISSUE TITLE
DLP Documents Review - Dara

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#806]
**Summary**
Review documents for DLP Sheffield, add any questions ready for Monday meeting.
**Completion Criteria**
Review
- [x] Sheffield exploratory doc:  https://docs.google.com/document/d/1xI8MG_0zRxb3hTh64Nj-hopXCg226XDQvAkimz0LOec/edit
- [x] Miro board for DLP trainee overview:  https://miro.com/app/board/uXjVMk16md4=/
- [x] Volunteer roles:  
https://docs.google.com/document/d/1vtSMNy2e8Th7HfYTFqLTt4Ah4utR_gKPZRtJZQUUlHo/edit#heading=h.y2rw79kr4tre (this includes program manager responsibility which will be dispersed within the team so worth having a look and seeing what would fall within your remit)
- [x] Canvas on the DLP channel has links to all the course material  https://codeyourfuture.slack.com/archives/C035198HB5E

@AmyCYF can you add anything if I missed something?

**Comment by AmyCYF** [comment]
I think thats all for now :)
