### ISSUE TITLE
Tech Products Meeting

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#81]
**Background**
We used to have a weekly Product meeting. This ticket is a trial to see if we can live without it - or if we can have more specific meetings

**Product Team boards**
These boards have the backlog and sprints of each team. This means we can go through it and ask questions or challenge it on this main ticket. 
[Dashboard](https://github.com/orgs/CodeYourFuture/projects/18/views/2)
[Class Planner](https://github.com/orgs/CodeYourFuture/projects/21/views/1)
CYF Next
[Mentor Bot](https://github.com/orgs/CodeYourFuture/projects/19)

**Support with input**
Input will be requested via Daily, private messages or directly on the board tickets

**Comment by gbencci** [comment]
@kfklein15 let's try!

I see that the dashboard and class planner look very different. Is it worth working towards a single set of stages?

**Comment by kfklein15** [comment]
> @kfklein15 let's try!
> 
> I see that the dashboard and class planner look very different. Is it worth working towards a single set of stages?

@gbencci , I think every team has its peculiarities. In Class Planner, we have UI/UX designers working with the team, for example. The dashboard has two environments - one for testing and one for system integration testing.
I think giving the teams freedom to organise themselves in the best way, as long as they deliver, I wouldn't worry too much about it.

**Comment by kfklein15** [comment]
@alecmccrindle , I still need a few things on the [ITD 30 days epic](https://github.com/CodeYourFuture/tech-team/milestone/19).
1) Design for [ITD portal with countdown](https://github.com/CodeYourFuture/tech-team/issues/648)
2) E-mail to be sent on the last day before the applicant cannot send any more steps
3) Design for [ITD Portal once no step can be sent](https://github.com/CodeYourFuture/tech-team/issues/647)

Could also review the other stories to make sure you are happy with them:
1) [ITD reminder 7, 14 and 21 days](https://github.com/CodeYourFuture/tech-team/issues/649)
2) [Extension e-mail](https://github.com/CodeYourFuture/tech-team/issues/670)

**Comment by kfklein15** [comment]
@gbencci @alecmccrindle for Q2 we will focus on getting all the 30 days ITD applications right. This [presentation](https://docs.google.com/presentation/d/1Yx63x1_uoswur0ieoyieCHmCZUSzNXRTWgFXnyKDoK4/edit#slide=id.p) explains it a bit

The reason for that is, that because our delivery timeline is too long and we have a high turnover, we need to get the team to focus. And the ITD is now partly done, but still missing a lot to get to a good state that actually is a useful process for the PROMs.

This means that the volunteer work will be done later. I know it is not ideal, but having people working on everything just means we don't deliver anything with quality and actual value. 

If we get more volunteers, we can then create another block of delivery for volunteers" - I will think about how this would be broken down.

**Comment by kfklein15** [comment]
- [Dashboard Roadmap](https://docs.google.com/spreadsheets/d/1jG1j7Jw56ct1FFVYCehE3WevKfjGjVTJl3vj0UuHx7U/edit#gid=680924847) of what we are focussing on right now

I am closing this ticket since I think it is too generic, and if needed, we can open specific tickets for requests.
