### ISSUE TITLE
Sheffield DLP - Venue Confirmation

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#815]
### Background

We need to confirm the venue space we have been offered - this includes the days/  dates we can use it, times we can use it, restrictions and whether it will be a sufficient space for the program.

Venue address: Sheffield Technology Park - (Sheffield Science Park Cooper Buildings, Arundel St, Sheffield City Centre, Sheffield S1 2NS; contact: Emma) 

### Acceptance criteria

- [x] Reach out to Emma and confirm if we can go ahead with the first Sheffield DLP. (need dates)

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@MattCFry

**Comment by AmyCYF** [comment]
@MattCFry before we can set dates for the DLP, let's find out what dates/ days the space can offer us, then we can look at how we can work our DLP dates from there.

**Comment by MattCFry** [comment]
Thanks Amy.

Could you point me in the direction of Emma's contacts?

**Comment by AmyCYF** [comment]
Unfortunately not - Worth asking on this [sheet  ](https://docs.google.com/document/d/1Pfzt1S2gQ7YHRXnyjB1FaxIFLSPaOeEZfXixwlFlm3I/edit#heading=h.jf6luv4l20kh)who has the contact details.

**Comment by MattCFry** [comment]
Update: Sheffield Tech Park is not available for us. I am working on finding another with the team.
