### ISSUE TITLE
Reach out to Sheffield NGOs (3 previously identified organisations)

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#818]
### Background

Contact about new Chapter/ colaboration.

Sheffield:
 Ashiana Sheffield - [www.ashianasheffield.org](http://www.ashianasheffield.org/)
 Assist Sheffeild - [www.assistsheffield.org.uk](http://www.assistsheffield.org.uk/)
 New Roots Therapeutic Service, Sheffield & South Yorkshire - [www.refugeecouncil.org.uk/get-support/services/new-roots-therapeutic-services-sheffield-and-south-yorkshire](http://www.refugeecouncil.org.uk/get-support/services/new-roots-therapeutic-services-sheffield-and-south-yorkshire)

### Acceptance criteria

- [ y] - Email sent
- [ ] - First meeting
- [ ] - Follow up  call if no reply to email

### Owner

@halden

### Stakeholder

@emcglackenr1 

### Approver

@halden

**Comment by emcglackenr1** [comment]
Hi Halden, I am working on [this spreadsheet ](https://docs.google.com/spreadsheets/d/1ivm9ioUt9ps4KYbPNnP4hX7uUvlo6juenWLmJMruoR8/edit#gid=0)today of additional contacts. Can we work together on the spreadsheet as well?

**Comment by emcglackenr1** [comment]
I've edited this ticket a bit to make it more clear what part you are doing (so we don't accidentally do the same work - please let me know if you want to collaborate on this differently either here, via Slack or in a meeting) 

I have also closed [this ticket,](https://github.com/CodeYourFuture/DLP/issues/111#issue-2200235697) linked your other related ticket, created one for the part I am working on. Details are on [the closed ticket.](https://github.com/CodeYourFuture/DLP/issues/111#issue-2200235697)
