### ISSUE TITLE
Stand for the WSIS Prizes 2024

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#821]
WSIS Prizes 2024 Ceremony will be announcing the winners during the [WSIS+20 Forum High-Level Event](http://www.wsis.org/forum), taking place in Geneva on 27-31 May. The most voted projects in each category will be considered by the WSIS Prizes 2024 Expert Group in the selection phase, to decide on the winner. [Register](https://www.itu.int/net4/wsis/forum/2024/Home/Registration) for the event (onsite and/or virtual) and book your travels to join us in celebrating your achievement.

 

Participate and contribute to the WSIS+20 Forum High-Level Event by organizing an exhibition booth and showcasing your project, attending carefully crafted sessions covering all WSIS Action Lines and emerging technologies, discussing achievements, gaps and opportunities of WSIS and its many aspects, including the WSIS Stocktaking and WSIS Prizes, contribute to the discussions on the WSIS+20 review and the future of information and knowledge societies.

Actions:

- [x] Check with the team who would like to attend and if so decide if we will have an in person or an online stand

**Comment by MarianaVazquezCYF** [comment]
German is organising it, when can see the info on this link: https://codeyourfuture.slack.com/archives/C011T8UHVV0/p1713526295497959 . According to the post, Ana is interested in attending!

**Comment by kfklein15** [comment]
Alladin is also going.

**Comment by kfklein15** [comment]
Alec will put marketing material in one place (different tickets).
Mariana to talk to Ana and Allading to register a stand and let us know how they need help.
Mariana create a temp channel for this
