### ISSUE TITLE
Communicate Sheffield Chapter to Community

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#822]
### Background

I would like to start using our existing community to help build the Sheffield chapter (a message in #cyf-volunteers and #general to ask people if they have contacts in Sheff who can help out). 

However, we have not sent out any news on the new chapter yet.

It would be good if we sent out communications about a new chapter first. 

@MarianaVazquezCYF could you send out some communication about the new chapter to our community? 

### Acceptance criteria

Message in public channel about:
- new chapter
- why Sheffield
- how volunteers can get involved

### Owner

@halden

### Stakeholder

Sally, Marinana

### Approver

@halden

**Comment by SallyMcGrath** [comment]
Just FYI, you are messaging right now in any case as this is all public. It's ok that it's public! I'm just saying - this is all messaging.

**Comment by MarianaVazquezCYF** [comment]
Great!! am I an asignee? or a stakeholder? and if I am an asignee which are my actions?
so far from the Sheffield chapter i will connect you with the existing volunteers (if there are still involved) and with the volunteer who knows about the space!

**Comment by SallyMcGrath** [comment]
Why am I assigned to this ticket? What tasks should I complete? It's not clear to me at all.

**Comment by emcglackenr1** [comment]
Hi there, this links to the handover and the Sheffield launch, so I have added a deadline. @MarianaVazquezCYF since some of the community are trainees / graduates, I am happy to help with this also, especially since you are taking over more of the #800

**Comment by MarianaVazquezCYF** [comment]
Hey guys, Dara Emma will communicate this to the community ! I will remove the assignment to me

**Comment by haldenb** [comment]
Awesome,

I would like to get volunteer coms sent out before Easter,.Do we think we can get general Coms sent out today/ tomorrow? What can I do to help this happen?

This is what I have drafted for volunteers:

:mariodance: CYF Sheffield Chapter :cyf:

- We are getting ready to open our chapter in Sheffield 
- We have had trainees waiting for the course for a long time (they were supposed to start with NW6)
- We have space and funds 
      - We need volunteers to help us build a wonderful community
      - Please join #sheffield if you would like to be involved.
 We need:
      - People in Sheffield
      - Experienced volunteers who can help out remotely 
      - Remote volunteers who need experience with DLP and ITD to get ready for their own regions re-opening
      - Your networks: do you know anyone in Sheffield who might want to help out? Do you know any organisations that you could introduce us to in the city?

**Comment by SallyMcGrath** [comment]
You can just post this on Slack, it's fine. I think this is too much messing about for a Slack message tbh guys.
