### ISSUE TITLE
Sprint 17 - Update GT with data from #823 

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#824]
### Background

We want more details on where our alumni work and how long they worked there.
- A % figure on the number of grads with a retention of over 2 years
- A figure average retention in the first role

Dependant upon #823 

### Acceptance criteria

- [x] Update global trainees with data collected from #823 
- [x] Relay any relevant info to Barny

### Owner

@mattcfry

### Stakeholder

@Barny-6

### Approver

@mattcfry

**Comment by MattCFry** [comment]
We got 19 responses @Barny-6 :D 

How does that compare with your usual mail merge surveys?

**Comment by Barny-6** [comment]
That's great! well done Matt :D
