### ISSUE TITLE
GLA6 Communicate Plans for Community Day

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#830]
**Summary**
This ticket contains the tasks involved in finalising the details of GLA6 Community Day
Deadline TBD , but the event is fairly soon. So, the week of April 1st would probably be best. 
Relates to ticket #800 
[Summary doc](https://docs.google.com/document/d/1gjGJmCtGuMcgXD8y06XBzzFaMAkOIKRBMmXFHmm3tj8/edit)

- Potential restaurant: https://www.edarestaurant.co.uk/
- Location for classes: https://www.strath.ac.uk/whystrathclyde/campusupdate/learningteachingbuilding/
- Timetable and location for classes : https://docs.google.com/spreadsheets/d/1j_lMZkMbPhQwY_siNSfFG3DDFYufISLEWQxY38Nrckc/edit#gid=0
- Responses to community day form: https://docs.google.com/spreadsheets/d/1WHcTxuJMYVPi1qVO5N9gDIGWJOfiW7QK-E6uM4fBUhQ/edit?resourcekey#gid=1519653598

[Doc for working on this](https://docs.google.com/document/d/1gjGJmCtGuMcgXD8y06XBzzFaMAkOIKRBMmXFHmm3tj8/edit#heading=h.9yug67oqgdwn)
Spreadsheet with responses to form:
- [x] Decide and communicate the results with the community - @alecmccrindle  and @emcglackenr1 
- [x] Make arrangements / decisions based on location, feedback we have on what people want to do, etc. - @alecmccrindle 
- [x] Compile data from responses on spreadsheet - @emcglackenr1 
- [x] Create mail merge doc with responses from spreadsheet  - @emcglackenr1 
- [x] Decide and draft how to communicate the results with the community - @alecmccrindle 
- [x] Have 4 versions of a section of email / the email, one for friday only, saturday only, one for friday and sat, one for those who can't make either but did reply. Rest of email the same.  @alecmccrindle 
- [x] Use Alec's template to finish and send mail merge - @emcglackenr1

**Comment by alecmccrindle** [comment]
Notes from Glasgow update Retro:

Problems
- Cost of living has decreased time available for job hunting
- Job hunting is much harder too - and more time is needed to work on more projects and portfolios
- "I don't feel ready to apply for a job"

Publish the portfolios
- how do we do this?

**Comment by emcglackenr1** [comment]
Added myself again after discussion with Alec since you were unwell @MarianaVazquezCYF .

**Comment by alecmccrindle** [comment]
[Email to send to those who signed up for the social](https://docs.google.com/document/d/1gjGJmCtGuMcgXD8y06XBzzFaMAkOIKRBMmXFHmm3tj8/edit#heading=h.ih5qhuxel6qc)

**Comment by kfklein15** [comment]
@emcglackenr1 , this is a big ticket. Could we close it with everything done and open a new one for your tasks only? Thanks
