### ISSUE TITLE
Look into gaining access to CYF Facebook for Sheffield promotion

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#838]
**Summary**
This relates to ticket #828 
Some organisations found by the delivery team were on Facebook. I don't have access to the CYF Facebook to contact them. 

Can who does either:

- [x] Request access
- [x] Chase up if couldn't get access x 2 (deadline 8th April to get access)
- Provide access to the Programme Delivery Team
Subtasks
--- @emcglackenr1 had to create a Facebook profile to access the CYF Facebook account. This is a blank CYF professional one. So now we can progress using that. If other staff need to use it, they can either connect new accounts or use that one.
--- Asked Alec how I can join now I have the profile. ⌛ 
--- @emcglackenr1 - I'm now a community manager for the CYF page, but still can't message from it. So, have set up the account I made to look like a proper account so I can contact people from it. Hopefully it doesn't look too spammy.

**Comment by emcglackenr1** [comment]
Blocker is access to Facebook page. Remove blocker label once this is resolved.

**Comment by emcglackenr1** [comment]
@MarianaVazquezCYF -[ any updates on this?](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1711635425846469) :)

**Comment by emcglackenr1** [comment]
Update: I had to create a Facebook to access the CYF account from Alec. Created now.

**Comment by MattCFry** [comment]
@emcglackenr1 going to assign myself to this as I have access now :)
