### ISSUE TITLE
Create UXUI track v02

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#84]

**Comment by kfklein15** [comment]
Could you please add the UI/UX tracker link to this ticket? This way we can find things related to it easily :)

**Comment by alecmccrindle** [comment]
What is a UXUI tracker link?

I've started  [collecting material](https://docs.google.com/document/d/1S7SP1a9GPw2bTxIfFbixsD0SBu0YXNC7zK_fx3GEC_U/edit) and research starts next week.

**Comment by alecmccrindle** [comment]
Course close to completion. Will run a retro in a couple of months.

**Comment by alecmccrindle** [comment]
[Here is the final set of topics from the v02 UXUI programme](https://docs.google.com/document/d/1qMqxSI5TuM0ozvghyaRY6A_uuS_IYxqyw3farZ8ZDsQ/edit#heading=h.5u47kzh3eey)
