### ISSUE TITLE
Gather phone numbers for orgs that haven't replied to email

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#843]
**Background:**
Follow on from [#828](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/828)
Following the Easter break, follow up with organisations that haven't replied 
- [x] Add phone numbers of orgs - @emcglackenr1 

**Progress:**
Testing using [AI tool [](](https://app.anakin.ai/apps/1609)) to gather these faster not using CYF google account just in case tool isn't safe to connect to it.
Posted on Slack for advice on tools to use, [no reply so did manually.](https://codeyourfuture.slack.com/archives/C59R2722F/p1712155272059309)

**Comment by haldenb** [comment]
Happy to make some calls once we have numbers:


What are our asks?
- venue
- volunteers 
- trainees

**Comment by haldenb** [comment]
Should we do a pitch camp before we call? https://codeyourfuture.slack.com/archives/G6H0HAY10/p1694105522407179

**Comment by emcglackenr1** [comment]
Yes absolutely Halden, I have booked something in. This relates to #851 #864 #867 etc
