### ISSUE TITLE
Follow up Calls - Sheffield Outreach

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#845]
**Background**
Follow up with the organisations listed [here](https://docs.google.com/spreadsheets/d/1ivm9ioUt9ps4KYbPNnP4hX7uUvlo6juenWLmJMruoR8/edit#gid=0 ). 
In meeting between @AmyCYF and @emcglackenr1 they decided it was best to leave organisations some time to reply because they are likely to be off for the long weekend. 
If they haven't replied by 3rd / 4th, chase up with phonecalls. Set up as many meetings as possible. 

Before you make the call, be familiar with the pitch for DLP. e.g. [template for outreach](https://docs.google.com/document/d/1FBbmFvIdCZQO7bvB3FNypuwUZ1VqxKZ88PsEGQ0Wj1c/edit)

**Dependencies** 
- This ticket should be finished or at least started #843 
- Developing phone pitch #864 / #851 

**Completion Criteria**
- Call all organisations who haven't replied via email to the DLP outreach 
- [x] Call all organisations at least once - @emcglackenr1  and @MattCFry

**Comment by emcglackenr1** [comment]
Should we changed deadline after consideration see ticket #867 and/or [thread ](https://codeyourfuture.slack.com/archives/C029341FPH6/p1712157480313489)

**Comment by AmyCYF** [comment]
You can also use the elevator pitch I wrote with Pitch camp: https://docs.google.com/document/d/1WvnMZu8JLTrwza5IdXwMh3phZJNgAhUEIkVYiiran94/edit

The pitch is on page 6 - you will just need to amend the names and 'Ask' but we can chat about this if you need support.

**Comment by emcglackenr1** [comment]
Thanks Amy! Will add to here  #871

**Comment by emcglackenr1** [comment]
Update on phone calls: I made 14 phone calls, and didn't get through to most. Spoke to two organisations because of the phone calls. 
One meeting organised but it's not until the 17th, which is close to our start date.

It was a Friday afternoon, though, and these are community organisations / charities. 

So, I think it's worth trying again on a Monday or other weekday.

**Comment by MattCFry** [comment]
I'll take on Halden's half of the calls
