### ISSUE TITLE
Slack Post outreach to Sheffield Community for Venue support

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#848]
### Background

We need to launch Sheffield DLP ASAP but we do not have a venue to host us on Saturdays. The community may be able to help us.

### Acceptance criteria

First
- [x] Draft a post and find resources to post on Slack

Post in 
- [x] Sheffield
- [x] North West
- [x] cyf-volunteers
- [ ] westmidlands?

### Owner

@mattcfry

### Stakeholder

- @emcglackenr1 

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Made [this template](https://docs.google.com/document/d/1J5WXXY8ls96gAm0bTgLMmgx8ckzTiF_pfbGeUVDlDMQ/edit) as an adaption of other email templates. Going to make edits to better suit the purpose of mass venue outreach.

**Comment by emcglackenr1** [comment]
Collaborated on this 👍
