### ISSUE TITLE
Defining parameters for the continuation of Final Projects

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#85]
**Background**
Final Projects can be internal and external. But in both cases, they might end up becoming real products. This ticket is for us to identify what rules we need for each.

**When is a Final Project good to be deployed?**
* Tech Lead and/or PM working on the team must confirm the final project can go into production
* System has no security or GDPR issues
* Continuous deployment has been done (at least weekly deployment of working software)

**Charities/CYF**
* Interested in putting MVP in production
* Must have clarity of what is not working/not finalised (using [handover template](https://docs.google.com/document/d/1hWrWS1kyHfJnzSeTOc7mwjElSJx_xtk6Down1Bzlaos/edit))

**External Final projects**
* Charity must have a budget to hire 1, 2 or all graduates of the team
* Charity must have a budget for a tech lead (or have their own)

**Internal Final Projects**
* Needs to be sent to @kfklein15 to create a Product team

**Comment by kfklein15** [comment]
@SallyMcGrath @gbencci, what is your input for the question "When is a Final Project good to be deployed?"?
Happy with any input on anything else too!

**Comment by SallyMcGrath** [comment]
They should deploy working software every week.

**Comment by kfklein15** [comment]
@gbencci question about how would the tech support be after FP finishes.

Any project support after the final project must be paid for by the charity. So they should hire the graduates as contractors for a period of X days/weeks, how longer needed.

The most important part of this is the Tech Lead - if they don’t have someone, are they hiring one of our volunteers, or could they volunteer their tie? It’s an open question. And very important because our grads are very very junior, and could create a massive security or GDPR risk for the charity.

What are your thoughts in this?

**Comment by gbencci** [comment]
Hi @kfklein15 I would recommend in creating a simple packaging offer for the organisations.

It could look roughly like this: 

Level 3
We offer 1-2 devs for 3 months, they pay them directly, the charity is in charge of the deployment. They manage the process

Level 2
We manage the tech development. It includes 1-2 devs, TL, PM and CYF overheads. They need to pay for a security review person validate that is ready for deployment. They have to host it

Level 1
We manage the project all the way to deployment, including the security review and hosting for 1 year.

**Comment by kfklein15** [comment]
@gbencci , I created a [form](https://docs.google.com/forms/d/1k3rx8XbUY7zK5KoSkbVQ4tpW4xfdpMuSY9BtAkO3HbE/edit) with this information and some other questions I found relevant to ask. Could you please review it?

**Comment by gbencci** [comment]
@kfklein15 I can only think about asking for what budget they have available? So that we can help them plan for the right level.

**Comment by kfklein15** [comment]
Added. Put on Daily. waiting for feedback to update Syllabus

**Comment by kfklein15** [comment]
We have defined, we just cannot implement it for lack of people to run it.
