### ISSUE TITLE
Sheffield Pitch Camp

### ISSUE THREAD

**Issue by haldenb** [CodeYourFuture/CYF-Staff-Tickets#851]
### Background

https://docs.google.com/document/d/15A55kJdyN5Vz39LoRibueGrIdRak9eY5FDHTp5eJNIo/edit

https://docs.google.com/document/d/1xI8MG_0zRxb3hTh64Nj-hopXCg226XDQvAkimz0LOec/edit#heading=h.wdwht2p57ufy

Lets align our pitches this should allow us to share responsibility as we all have the same voice in Sheffeild

### Acceptance criteria

- do prep 
- find time for meeting
- live laugh love

### Owner

@halden

### Stakeholder

@emcglackenr1 

### Approver

@halden

**Comment by emcglackenr1** [comment]
Done and on other tickets. Removed myself

**Comment by dara** [comment]
Wrong @dara
