### ISSUE TITLE
Follow up and reply to contacts from first outreach email

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#859]
**Background**
This involves following up with organisations we contacted for Sheffield partnerships.

Organizations in Sheffield potentially offer volunteer or trainee opportunities for DLP (Digital Literacy Program), and need to be contacted urgently. The goal is to initiate awareness about the program within the targeted communities and establish connections with similar demographic-focused organizations in the area.

Volunteer-related tasks are assigned to @haldenb, with ongoing progress tracked in tickets under the Launching Sheffield Chapter Milestone.

This task aligns with the directives outlined in Amy's handover documentation.

**Important Resources:**

[Spreadsheet: "Partner organisations Sheffield - Trainee outreach"](https://docs.google.com/spreadsheets/d/1ivm9ioUt9ps4KYbPNnP4hX7uUvlo6juenWLmJMruoR8/edit#gid=0)
Ensure updates on contacted organizations are recorded in the spreadsheet to avoid duplicating efforts with other tickets.
**Email Template:**
([[TEMPLATE] Sheffield Outreach](https://docs.google.com/document/d/1FBbmFvIdCZQO7bvB3FNypuwUZ1VqxKZ88PsEGQ0Wj1c/edit))
[Amy handover doc](https://docs.google.com/document/d/1uCFk-eF7YEOns7kin4ssPz53MgMLrzSiw0Uqcvm0-FA/edit#heading=h.ujdedmq50jut)

**Completion Criteria:**
- Regularly check group inbox for replies, reply to these, set meetings and update spreadsheet accordingly 
- [x] 2nd April - @emcglackenr1 
- [x] 3rd April  - @emcglackenr1 
- [x] 4th April
- Then Move on to stage 2 of outreach (#845 , #865 etc.)
- [x] Assign conversations where relevant. (assigning Matt to venue related meetings in case other staff can't attend (Lili recommended two staff attend)
- [x] Delegate and share work. Turn into smaller tickets!! - @emcglackenr1 :D 

**Stakeholder:**
@AmyCYF

**Comment by MattCFry** [comment]
Hey. This ticket is really big. Im going to extract some action points for other tickets

**Comment by emcglackenr1** [comment]
Yes it definitely is. I brain dumped here. Thanks Matt. I'm going to extract smaller things too. I've scheduled time in my calendar to fix tickets I have like this today. Sorry for the confusion in the meantime.
