### ISSUE TITLE
Create new trustee JD - Volunteers

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#863]
### Background

We need to open a new role for trustees targeting volunteers.

### Acceptance criteria

- [ ] Create de JD draft
- [ ] Get approval from German
- [ ] Promote in the community

### Owner

Liliana

### Stakeholder

Claire

### Approver

german

**Comment by lilianabermudes** [comment]
- @gbencci, I made tiny adjustments to the JD, compared to the Grads one. Do you think we need other changes?
https://docs.google.com/document/d/1CmsRKtwpeXTAnBQ7OZ0piIm3q_Bs1REG0vRvTrIyMCI/edit

**Comment by gbencci** [comment]
This is done, so we can close the ticket.
