### ISSUE TITLE
Phonecall Follow-Up - Facilitate Collab, Re-priotise Time

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#864]
**Background:**
We need to make phonecalls to follow up on sheffield contacts. 
I suggest a half hour in our calendars to work together to plan for how to make the most out of these calls. 
We need a mini pitch, and we need a plan.
Relates to #851 

**Why is it this date?**
Date for Meeting: Thursday, April 4⋅12:00 – 12:30pm
We no longer have a venue! [The original plan was to secure it by the 5th. ](https://docs.google.com/document/d/1uCFk-eF7YEOns7kin4ssPz53MgMLrzSiw0Uqcvm0-FA/edit#heading=h.ujdedmq50jut)
So, let's make some calls as soon as possible.  

Dara, Halden, Matt - Doing the task is highly recommended. Using this time to co-work in a meeting is optional, can just be working simultaneously on this.
[Using the concept of mobbing](https://www.scrum.org/resources/blog/speed-your-scrum-mob-programming), lets all work on this to ensure we are on the same page. 

**Completion Criteria:**

- [x] Discuss / formulate plan, Reprioritise tasks - @MattCFry @emcglackenr1 huddle, [posted on PROM channel](https://codeyourfuture.slack.com/archives/C029341FPH6/p1712157480313489)
- [x] Create tickets relating to discussions above - @MattCFry @emcglackenr1 
- [x] update spreadsheet
- [x] **Create meeting** - @emcglackenr1 
- [x] **Create doc** - @emcglackenr1 - [doc for us to collaborate.](https://www.google.com/url?q=https://docs.google.com/document/d/1atElF_b7nX7wwwoYaV8q6_G5dNtr6ylAQnOiuUEa5Hw/edit&sa=D&source=calendar&ust=1712586926685964&usg=AOvVaw3iyHiiYeNy95F9LcPvleY0)[ including Pitch Camp Doc
](https://docs.google.com/document/d/14o5_mkoDOeMFFdOYrZhm49gfF0gayjdrbfianDkCzqk/edit)
Split into separate ticket then update below and tick the box below:
- [x] @emcglackenr1 #871 
- [x] @haldenb 

Ticket can include tasks such as:
- Contribute to Prep and review shared doc to see everyone's contributions
- Share helpful intros to DLP , DLP pitch-related content or tips for making the most out of phonecalls for partnerships
- At minimum, confirm you are comfortable with what has already been shared in the document 

**Optional input:**

- @AmyCYF and @MarianaVazquezCYF  - I invited you on the calendar. If you want to join. It would be ideal to add notes before the scheduled time so we can use them if you can't work on this ahead of time. If you can't do so, please share them asap to facilitate more effective follow up calls 
- Feel free to create your own tickets for this if you are doing so, and link them here if you prefer

**Comment by MattCFry** [comment]
@haldenb @emcglackenr1 is this ticket complete?
