### ISSUE TITLE
Venue Lead Follow up Calls - Sheffield

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#867]
**Background**
Related to #845 
Dependent on #866 and #864 

We want to reengage with organisations we have contacted but have not replied.
Close this ticket if it isn't something you think is necessary 👍🏻 

**Acceptance criteria**

- Call organisations who have not replied to [1st email follow up ](https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/828)

Owner
@MattCFry

Stakeholders
@emcglackenr1 @AmyCYF @haldenb 

Approver
@MattCFry

**Comment by emcglackenr1** [comment]
I had a thought. I think we were maybe overcomplicating things

Do myself and @haldenb  need to do a follow up phonecall this week for the other partnership orgs if:
1. You have done a follow up email today Matt 
2. Our priority is a venue first?

**Discussion points**
- Should we instead split the work of who to call this week prioritising potential venues? 

- Maybe a follow up email + call the next day is too much? 🤔 
Can you clarify what led to the decision to do the follow up email @MattCFry ? Wondering if we should put a pause on it since it happened to be blocked by technical issues. 
I think it confused things a bit to do that separately to the plan I had made with @AmyCYF and the phonecall plan myself and @haldenb made with Lili and Mariana. 
Or maybe there is no harm in doing both. 


I've assigned the three of us for now. We can discuss tomorrow (4th of April)

**Update after standup**
It's up to Matt if he wants to call organizations about venues. No particular issue with contacting people both via email and a phonecall.

**Comment by emcglackenr1** [comment]
I'll added your name beside orgs on the partnership / outreach spreadsheet that look like they're mostly venues. But lots of the other partners might turn out to be as well.

**Comment by MattCFry** [comment]
Closing as I don't think it is necessary :)
