### ISSUE TITLE
PD Buddy role redesign

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#87]
- Meeting with German and Elizabeth to discuss the main requirements

**Comment by lilianabermudes** [comment]
- Finished [first draft](https://docs.google.com/document/d/1i9qmqof0NXo8UpYf3iINXOyHQf2ZRiCQ14DFRMA4-y0/edit)

Actions
- Get feedback from selected trainees and volunteers

**Comment by lilianabermudes** [comment]
As a next step, can you please have a look at the draft, @kfklein15? 

This is part of the "PD Redesign project"

**Comment by kfklein15** [comment]
Added lots of comments, @lilianabermudes , Let me know if you prefer having a chat about them.

**Comment by lilianabermudes** [comment]
Thanks a lot, @kfklein15! I replied to most of them.

Let's also wait for German, as he has some ideas for it. 

--> The next challenging step would be to get feedback on this from trainees and current, and past buddies. We need to decide who should be invited to this exercise (after we agreed on the basics).

**Comment by lilianabermudes** [comment]
@kfklein15 this is the survey draft. Please edit it and change anything you want: https://docs.google.com/forms/d/1nsBiN7w4YRGmXqzR6MASwZkJwO28v9gWvo2SExSxnWY/edit 

@gbencci Karen and I agreed on the next steps. We're going to share a survey with the community and will invite at least one member per region to join us in a working session. If you have time, please also review the survey questions :)

**Comment by kfklein15** [comment]
@lilianabermudes 
My post suggestion:

PD Syllabus Team, we are looking into the PD Buddy role to redesign i, and your input is very valuable. Can you reply to [this survey](https://forms.gle/zSfaCYsee3Ea7KJUA) until 6th Apr? 
We will do a wider survey with the other PD volunteers too, but we want to have a first feel from this team.
Thank you for your support.

**Comment by lilianabermudes** [comment]
@kfklein15 it's good! Yes, let's do it - we might have time to implement something for LDN10 and Glasgow 6

Thank you!

**Comment by kfklein15** [comment]
@lilianabermudes , we had 4 responses:
- all of them prefer they we work now and think the PD buddy should focus on a mentor/employability perspective.
- No consensus about coursework

Shall I post it on the other PD channels so we can get more input (at least 10 different people)?

**Comment by lilianabermudes** [comment]
@kfklein15 - what is it--> " they we work now"? lol

I would say yes! Let's ask more people 

Interesting to know they think the focus should be employability - very similar to career mentors, maybe?

**Comment by kfklein15** [comment]
@lilianabermudes oooops the WAY we work now :D

I'll share it in other groups then!

**Comment by lilianabermudes** [comment]
lol - I could have guessed, but I didn't (melting emoji)

**Comment by lilianabermudes** [comment]
Hey @kfklein15 where are we at with the PD buddy role?

**Comment by lilianabermudes** [comment]
Not a problem! What would be the next steps? Let me know if I can help

**Comment by kfklein15** [comment]
I will talk to Lara tomorrow about it so she can develop the description next week.

**Comment by kfklein15** [comment]
@lilianabermudes , we now have the description of the  [PD roles](https://docs.google.com/document/d/18hbeu3jbZbWFjAjPa9h0BLEsQC3XvQ_IolJ-0gOtbMo/edit).
We tweaked/amended most of the roles, not just PD Buddy.

Should we pilot PD Buddy with WM5? 

The final information needs to be updated in:
- Onboarding presentation
- Volunteer roles spreadsheet
- CYF Docs
- ?

**Comment by kfklein15** [comment]
I have all my product stuff on CYF Docs, so was going to use it for PD too, since it is an easy way to have open content, without it being on the website since it is specific, @lilianabermudes 

Happy to do that @MarianaVazquezCYF

**Comment by kfklein15** [comment]
@lilianabermudes I updated the spreadsheet (3 tabs - global, SDC and occasional), but when doing so, many questions came up on the Doc file itself, so I tagged you. We can have a quick call to go through them if you want. 

@Barny-6 , feel free to take a look at them, too, especially the ones that overlap :)

**Comment by lilianabermudes** [comment]
- Thank you, Karen! I replied to your comments. Let me know if them make sense!

**Comment by kfklein15** [comment]
All good. I'll update CYF Docs next week. Will you do the presentation update or do you want me to?

**Comment by kfklein15** [comment]
Pd Coach has been designed and communicated last week. 
We are working on the step by step of it and reviewing documentations. But this ticket is done.
