### ISSUE TITLE
Planning Logistics of Sheffield Flyer Distribution

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#878]
### Background

We have found several places to distribute flyers. Now time to understand how we can distribute. 

### Acceptance criteria

- [x] Understand distribution options and list them in this ticket. 
- [x] Select a distribution option for each location

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Hi @AmyCYF. Could you share what distribution options are available for physical flyers? I'll make a ticket for emailing as well.

**Comment by AmyCYF** [comment]
@MattCFry I am not sure what you mean by distribution options?

**Comment by MattCFry** [comment]
Apologies. I mean ways of distributing the physical flyers in our locations. e.g. Assigning volunteers to distribute

**Comment by AmyCYF** [comment]
@MattCFry can you share your suggested approach and I will review it.

**Comment by MattCFry** [comment]
I have not devised a method myself. If memory serves me right, you said we would consider our options. Sorry if I misunderstood.

Any volunteers in the area distributing would be a great option. If these locations could display the electronic version we give them, that would also be great (but less likely).

What approach would you consider in this situation?

**Comment by AmyCYF** [comment]
You are on the right track with the utilisation of volunteers but I'd like you to have a bit more of a think about it and come back with a strategy for distribution that addresses the multiple scenarios we are likely to encounter as well as the end-to-end application of these scenarios. Keep in mind this is not going to be a very complex solution.

I'll put some time in on Monday to go through it together and we can plan to action something on Monday.
