### ISSUE TITLE
Mail Merge volunteers to ask for Support in Venue Outreach

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#883]
### Background

I did [a Slack post](https://codeyourfuture.slack.com/archives/C011T8UHVV0/p1712068313018329) that achieved the purpose. The issue is it needs more engagement. @AmyCYF suggested that we engage better with emails to volunteers. created a Slack post that achieved the purpose. However,

### Acceptance criteria

- [x] Export northwest volunteers to a mail merge spreadsheet.
- [x] Consider any other regions to do the same as above (ie WM and LDN) and add them. 
- [x] Send mail merge

### Owner

@mattcfry

### Stakeholder

@amyCYF

### Approver

@mattcfry

**Comment by MattCFry** [comment]
YAMM was out of free sends so thank goodness google works again.

**Comment by AmyCYF** [comment]
@MattCFry did you include the request for volunteers in this Comms?

**Comment by MattCFry** [comment]
Yes :D I told them to go to the Sheffield Slack channel and reach out. If people have been deactivated then we can put them through onboarding again then reinstate them.
