### ISSUE TITLE
Contacting disengaged course completers

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#884]
**Background**
This ticket is about contacting course completers who are marked as 'Working Independently' or have not been updated in a while. They should be on the [grad overview spreadsheet](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit#gid=197105283)

Before working on this, consider the current guidelines and updates regarding grads / course completers. These may have changed by then.
[Related notes/meeting ](https://docs.google.com/document/d/1ICt-Ntz-8H63pHE1rEB0a_TFlTXu41zjk_wbPguqfb4/edit?userstoinvite=sally@codeyourfuture.io&sharingaction=manageaccess&role=writer#task=vQxZ6ZYZrDA-dUW1)

**Completion Criteria:**
- [ ] Determine the current recommended reach out process based on information from @Barny-6 etc.
- [ ] Ensure there is a flowchart, process or guidance of some kind for contacting people. Even if it's as simple as 'email every 3 weeks'. This way we can try prevent people falling through the cracks and ensure time/energy isn't wasted by working inefficiently etc. This would also relate to tracking if someone is meeting their goals / requirements for Portfolio or not. e.g. [Grad overview spreadsheet discussion](https://codeyourfuture.slack.com/archives/G6H0HAY10/p1712151218762889), Updates to grad criteria and Portfolio syllabus
- [ ] Create template for reaching out or find it if it already exists by then (if this gets larger, make it a new ticket)
- [ ] Start process with each course completer that we haven't heard from in a while

**Comment by SallyMcGrath** [comment]
@kfklein15 I am assigning you to this and presume you can close it as obsolete

**Comment by kfklein15** [comment]
We' ve done this. Thanks, I'll close it now.
