### ISSUE TITLE
Deindex https://syllabus.codeyourfuture.io/overview

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#890]

**Comment by alecmccrindle** [comment]
Blocked, need to do some more stuff on this.

**Comment by alecmccrindle** [comment]
Did some research, need to hand this over to someone with access to our domain servers or who understands how to add a noindex to the syllabus platform.

**Comment by alecmccrindle** [comment]
Wrote a post, will leave it with the syllabus team. https://codeyourfuture.slack.com/archives/C012UUW69S8/p1713790267902889

**Comment by alecmccrindle** [comment]
[Added a ticket for the curriculum team](https://github.com/CodeYourFuture/curriculum/issues/706)
