### ISSUE TITLE
Create list of membership candidates

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#9]
- Run workshop with team on requirements, R&R
- Team to create a shortlist of candidates to launch the model

**Comment by gbencci** [comment]
@ClaireBickley could you please share here your list of active members that you have collected so far? The one you use for the drive review. Thanks

**Comment by ClaireBickley** [comment]
got an updated list on the tab dated 30/01/2023
https://docs.google.com/spreadsheets/d/1L-Rb5COz_u4wC1F7nla4mJYULcAeMoNaZknXbHi-Sq0/edit#gid=612525767
