### ISSUE TITLE
Volunteer experience: Google form unsubscribe and offboarding

### ISSUE THREAD

**Issue by caromelendezl** [CodeYourFuture/CYF-Staff-Tickets#91]
Creating this ticket as @ClaireBickley suggested after our chat regarding [Alicia's message on Slack](https://codeyourfuture.slack.com/archives/C029341FPH6/p1675778843223439?thread_ts=1675775089.416739&cid=C029341FPH6):

[Claire's message:](https://codeyourfuture.slack.com/archives/C029341FPH6/p1675777099657249?thread_ts=1675775089.416739&cid=C029341FPH6) 
We have our [offboarding process](https://docs.google.com/document/d/1vWCTXpdVgv_YZY_ETKd6UFNdCrgz2T96smPhYVElFKM/edit#heading=h.y1z93qfet0q3) - the question is, how do we know someone is inactive? Which is a bit difficult because someone could be inactive in a region but supporting Tech Products (for example) and you just aren't aware of it. Something that we continue to think on.

[Caro's message:](https://codeyourfuture.slack.com/archives/C029341FPH6/p1675788478760119?thread_ts=1675775089.416739&cid=C029341FPH6) 
Claire I think by using Alicia's approach it would be great to have a form included on a link at the bottom of general emails to volunteers
eg. _If you don't want to receive these emails and/or volunteer anymore click here_
That would take them to a google form and we can get feedback as part of the offboarding efforts.
I've been thinking about doing that here in Scotland, as we really want to have the people that really want to be part of our CYF community

@lilianabermudes @MarianaVazquezCYF @alecmccrindle what are your thoughts? This would be a good semi-auto-temp way to help us all clean our volunteer data. 

I think this could be solved by creating volunteers mailing list per region on Mailchimp we can add an unsubscribe link at the bottom + a "don't want to volunteer anymore" form, but I mentioned the "google form way" above because as far as I'm concerned we have the basic membership on Mailchimp so we can't add more mailing lists?

**Comment by lilianabermudes** [comment]
- I will leave it to Alec to comment on the Mailchimp part.

- The offboarding process will be connected to the membership model, which is something I have just started, 

- The form is something that we've been thinking about for a while. The challenge here is up to now was for volunteers to actually let us know when they are about to leave.

**Comment by kfklein15** [comment]
@lilianabermudes , can you tell me more about the membership model, please? We are looking into what info we need to get into the Dashboard (i.e. Slack Id, Github ID, CYF e-mail), so we can have an "offboard" button. This would take a while but it would be good to make sure we are on the same page.

**Comment by lilianabermudes** [comment]
@kfklein15 yes, I will tell you tomorrow, but we have nothing so fa - this will take a while.

**Comment by MarianaVazquezCYF** [comment]
I shared this with Caro on Friday but I spoke to Alec, and the people who are in MailChimp are people who accepted to be in our mail list which is different than the dashboard! 

we can't bring all the people from the dashboard to MailChimp for GDPR issues. However, proms can send an email to the volunteers from their regions, and they can easily reply to the message saying that they don’t want to volunteer anymore and in that moment the prom should mark them as inactive in the dashboard! (It had to be manual for the moment)

**Comment by gbencci** [comment]
@lilianabermudes can you please review and close if needed before creating a new one

**Comment by kfklein15** [comment]
@ClaireBickley , how is this going? We have a tender to identify "trainees" on Slack, which hopefully should be the first step to automate the Offboarding, but that will take a while. 

Should we try to think about something short-term with Slack? For example, given a user hasn't been active on Slack for 6 months AND isn't a trainee, Slack identifies them weekly and removes and generates a list, so we inactive them manually on Dashboard? Just something that came up on the top of my head now :D

**Comment by ClaireBickley** [comment]
I haven't thought on this for a long time - this ticket is currently assigned to Lili so I haven't given much thought beyond our big Slack clean up

**Comment by lilianabermudes** [comment]
@kfklein15 I like your idea, and wonder if it would also be a good idea :D:

- when the change happens on the dashboard "inactive" 'unavailble for now", the dashboard sends an automated email with an offboarding form

**Comment by lilianabermudes** [comment]
Hi @kfklein15 should we pick this up?

**Comment by kfklein15** [comment]
Could we pick this up in March by any chance? I'm struggling in delivering other thins right now.

**Comment by lilianabermudes** [comment]
100%

**Comment by kfklein15** [comment]
I can see we said we would pick this up in March LOL It's June almost. What do you want to do @lilianabermudes ?

**Comment by lilianabermudes** [comment]
This has expired in my brain. Can we have a quick chat (KFK, Lilia and Claire) to discuss next steps? I'll book it!

**Comment by ClaireBickley** [comment]
Halden is picking this up as a bigger piece, I spoke to him last week - maybe he should be included? He's got some good ideas, I've given him a list of active/inactive people on Slack and he's taken some steps already.

**Comment by SallyMcGrath** [comment]
I'm closing this ticket as cursed
