### ISSUE TITLE
Reach out to contacts assigned to Halden in the Sheffield doc

### ISSUE THREAD

**Issue by emcglackenr1** [CodeYourFuture/CYF-Staff-Tickets#910]
Background
Since Halden is away, and we are unsure of the status of contact with the orgs in Sheffield Outreach, I will reach out to them. 

Outreach doc: https://docs.google.com/spreadsheets/d/1ivm9ioUt9ps4KYbPNnP4hX7uUvlo6juenWLmJMruoR8/edit#gid=0

- [x] Discuss with Amy and Matt 
- [x] Contact organisations on the spreadsheet

**Comment by MattCFry** [comment]
Hi. As I am doing this I'll assign myself. Unless I misunderstood?

**Comment by emcglackenr1** [comment]
I am happy to take this on since you took on the Facebook task. I was just going to call / send follow up emails when I get through my current tasks. Let me know what you think

**Comment by MattCFry** [comment]
Yeah, I think I misunderstood the task. You take it.
