### ISSUE TITLE
Risk Assessments to be created for class venues

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#92]
Template is here, please let me know if you have any questions 😄 

https://docs.google.com/document/d/1B7xwua2YA0fX6FYKKvyuRZb5v3K4Ctl7/edit

**Comment by SallyMcGrath** [comment]
If this is a small task with a high priority, it should have a short deadline and not hang around for 6 months. 

@ClaireBickley can you either complete this or move it to the backlog. Tickets should not stay in progress longer than one sprint. TY

**Comment by ClaireBickley** [comment]
thanks Sally, this can be closed.
