### ISSUE TITLE
2023 Annual Report

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#94]
the questions we'll be asked for the 2023 annual return may be different. More info here https://www.gov.uk/government/consultations/charity-commission-revisions-to-the-annual-return-2023-25/outcome/annex-11-charity-annual-return-questions-2023-data-publication

**Comment by ClaireBickley** [comment]
It would be useful to know the usual; process for writing the annual report along with any key dates/deadlines.

The above link is around changes for the 2023 report so we may not need to worry about it yet - most of the new questions look like it should be for Hazel or the accountants to deal with.

**Comment by gbencci** [comment]
hi @ClaireBickley the best way to see that the previous draft for this. We've been using these versions to work on the next year:
https://docs.google.com/document/d/1LMi62MmxqF58Reav1YPIWJeOAiWHiM6xpqiN02VK_l4/edit#heading=h.o7zmpvswr0yz

https://docs.google.com/document/d/1hMYmWuuomjNMFLSxmGW8L5mdbBKuH1S3d5GEdo9jWNg/edit

Deadlines are defined by charity commission.

We need a narrative version done by us and a financial version that it's the one done by the accountants

**Comment by ClaireBickley** [comment]
Working draft here: https://docs.google.com/document/d/1lq-qsX5s0NVAyXbIQ1J5TBhWnrGA208d_YN4BkLWpt8/edit

- [x] Sent to Trustees to Review
- [ ] Claire to double check numbers

**Comment by lilianabermudes** [comment]
@ClaireBickley do we have any action for this year related to the report 2023? The one sent to the trustees was the 2022

**Comment by ClaireBickley** [comment]
I just realised the comment I made above is around the 2022 report *facepalm* I'll start a new ticket for 2022 report.

nothing at the moment for 2023 - it was more to draw attention to the different questions. I'll close this as there are no actions outside of the financial accounts which are in hand.
