### ISSUE TITLE
Inivte tech leaders to saturday classes part 1

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#948]
- [ ] Send an email to the NW tech leaders from this list : https://docs.google.com/spreadsheets/d/1wYuaBNCQLz3CDzD8UuMbFqX8O8OzYqiUZ-VxZqeqHBE/edit#gid=0 and invite them to join us for a portfolio Saturday or to volunteer for the networking event in NW 
- [x] Assign the new task for tech leaders investigation to manchester students!

**Comment by kfklein15** [comment]
Ask Daniel if he can help (and if he knows anyone else that can volunteer).
