### ISSUE TITLE
Annual Report Stories 2023

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#949]
We need to write the annual report for 2023, a lot of this should be centred around community stories.

We ideally need stories from a mix of trainees, volunteers and graduates from all regions.
Stories should focus on activities from Jan-Dec 2023 only.

There is a [starter doc](https://docs.google.com/document/d/1AAWqSwRoAjddH3Z0mL6WB-ZXA74v-eol-A6chH0nqXU/edit) with notes (based on 2022 report) which we can use as a framework.
@alecmccrindle has been tagged in the relevant sections for community stories

**Comment by alecmccrindle** [comment]
Hi @ClaireBickley 

We have the following alumni stories - folks who found jobs in 2023.

- Deago: story + video (LDN)
- Chandre: story drafted  (CPT) 
- Nasir Ali: Need to write it up. 1 hr (GLA - Asylum Seeker)
- Jaspreet Kaur:  need to write it up. 1hr (WM)

And the following volunteer stories from folks who volunteered in 2023:

- Zachee:  https://codeyourfuture.io/volunteer-stories/zachee/ (CPT)  
- Jon Wyatt:  https://codeyourfuture.io/volunteer-stories/jon-tech-products-for-good/ (Global / Tech Products)
- Ellie:  https://codeyourfuture.io/volunteer-stories/ellies-volunteer-story-giving-back-and-growing-as-a-mentor/ (LDN)

I'll make a ticket to write up Jaspreet and Nasir's stories. I need to do Jaspreet's anyway as she did a YT interview. 

- A

**Comment by alecmccrindle** [comment]
Added two volunteer and two trainee stories. 

https://docs.google.com/document/d/1AAWqSwRoAjddH3Z0mL6WB-ZXA74v-eol-A6chH0nqXU/edit#heading=h.misltkjbfpl0

Need to get quotes done now.

**Comment by alecmccrindle** [comment]
So we didn't ask for too many volunteer stories in 2023. May need to ask for more volunteer stories from folks we know were around at the time.

**Comment by alecmccrindle** [comment]
Added all trainee and volunteer content I think?

**Comment by alecmccrindle** [comment]
@ClaireBickley - please make a ticket for photos when you need them.

**Comment by ClaireBickley** [comment]
thanks Alec - we won't need photos for a few months I think, not until we're ready to send the annual report to the designers.

**Comment by ClaireBickley** [comment]
Just had a quick look - can I check the stories used, Deago, Chandre and Saadia for trainees; Zachee and Jon for volunteers.
Do we have a GLA story? Just so we're covering every region?
