### ISSUE TITLE
Sheffield Venue forms

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#958]
**Background**
As Matt is the ops person for the Sheffield project he will be managing the Venue tasks. The next steps for the venue booking have been sent via email

**Acceptance criteria**

- [x]  send form back to Sheffield student union
- [x] let finance know about the 50% deposit required

Owner
Matt

Stakeholder

Approver
Amy

**Comment by MattCFry** [comment]
I shared the agreement with finance/ops for their review. When they are happy we can work towards signing and deposit payment.

**Comment by AmyCYF** [comment]
@MattCFry I am not sure what the next step here? Do I need to sign the document?

**Comment by MattCFry** [comment]
Hi, yes. Did you receive my email?

**Comment by AmyCYF** [comment]
I did but I wasn't sure what 'we are good to go' entailed.

**Comment by MattCFry** [comment]
I'm happy for you to sign if you are as well. We've made Finance aware for the deposit.

**Comment by AmyCYF** [comment]
Signed and sent on to you :)
