### ISSUE TITLE
Obtain Written Confirmation from REAP

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#959]
### Background

A DLP trainee has[ submitted an expense claim without bank information](https://docs.google.com/spreadsheets/d/17gfXojDVfT0Fp41vZVhk5C87fEn3SO_0jImsDt-_UO4/edit#gid=1705492937). They have an agreement with the [REAP Charity](http://reap.org.uk/) to provide him with bank account details for expense reimbursement.

@ClaireBickley has asked for some written confirmation before we pay into this bank account.

### Acceptance criteria

- [x] @ClaireBickley share in the comments what sort of written confirmation you are looking for
- [ ] @MattCFry ensure finance have the REAP bank details 
- [x] @MattCFry Request written confirmation as per Claire's instruction
- [ ] @MattCFry ensure op/finance has the written statement from REAP

### Owner

@mattcfry 

### Stakeholder

Claire @LeandaCYF 

### Approver

Claire

**Comment by ClaireBickley** [comment]
Our policy states that we can't pay into other's bank accounts - it must go to the person making the claim. This is important for anti-money laundering etc. However, we understand it is tough for some to get bank accounts and there is an organisation trying to help. In order for us to pay this we would need to see some kind of agreement between the organisation and the individual. I imagine they would have signed something around this. Once we can verify legitimacy then it's fine to pay.

cc @AmyCYF

**Comment by MattCFry** [comment]
It looks like we are taking another route for this. I will close and make other tickets in the future if necessary
