### ISSUE TITLE
Social Media creator role

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#96]

**Comment by alecmccrindle** [comment]
- [ ] write role
- [ ] check costs for agency
- [ ] check part-time / full-time / contractor costs
- [ ] share with external expert for sense check
- [ ] present to Germán / Hazel

**Comment by alecmccrindle** [comment]
`[Role is here](https://docs.google.com/document/d/17dsIO0P6WoklBfd-P33uDfj58qSRgBS49OnOQMnzsyo/edit)`

**Comment by alecmccrindle** [comment]
@MarianaVazquezCYF - is this ticket helpful for your social media write up task?

**Comment by MarianaVazquezCYF** [comment]
- [ ] A proactive person that can manage the content made by our trainees/volunteers 
- [ ] A proactive person that can ask and guide the members of our community to create videos/reels for social media using our brand guidelines 
- [ ] A person that can interact with our online community and increase our social media presence in the different regions
