### ISSUE TITLE
Review March DLP - EXL social post

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/CYF-Staff-Tickets#965]
Background
As part of our contract to deliver 5 cohorts with EXL, we need to also post on our socials (linked in) about their support of our program.

This post has been written but needs to be reviewed: https://docs.google.com/document/d/1mUTNE6i8TyzIaw0hcTCeWEp-7AE16tYQCF_QfvciSHE/edit

Acceptance criteria
- [x] Marketing/ Community team to review

**Comment by alecmccrindle** [comment]
Done, added comments.
