### ISSUE TITLE
Marketing stats from our channels to LEDdev

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#968]
- Your social media channels and the number of followers
- Frequency of your newsletter and the audience size
- Audience demographic e.g. job title and seniority

**Comment by alecmccrindle** [comment]
Hi Mariana, 

Socials - you can see the social media followers on those channels. You can see the data within Linkedin about the audience. 
Newsletter - we have 2,656 folks in the main updates newsletter - we send that out every few months. We don't segment our newsletter by job, our audience is volunteers who work in tech, partners, referral partners, alumni and applicants and other supporters.
