### ISSUE TITLE
Create corporate volunteer cases

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#971]
### Background

Frequently companies ask us about corporate volunteering options, but they do not progress when they see the prices. We now have good experiences with Bregal Milestones and Twilio to share.

I will create the business cases, but I need some key info.

### Acceptance criteria

- [ ] Mariana and Karen sharing key info about our experience with Bregal (masterclasses) and Twilio (demos) - **hi both, please direct me to the best docs you have, and I'll put the info together** :)
- [ ] Lili writing the cases
- [ ] Cases updated on the volunteering presentation

### Owner

@liliana

### Stakeholder

Karen and Mariana

### Approver

Liliana

**Comment by kfklein15** [comment]
Hi @lilianabermudes , I only have the Twilio documents we built together, nothing different from that. The main things we worked on with good outcomes were:
- Demo: 4-5 volunteers came to different demos and asked questions/giving feedback. An external person in the demo automatically gave it extra weight and importance. Plus, our Software Engineers have a chance to get to know someone from a different company.
- Flash Consulting: we had 5-6 volunteers from Twilio working with our Product team volunteers to build small but important features. Within a week, they helped us solve a problem.
-  Mock-interview: we had 4 volunteers who did mock-interview practice with our Software Engineers. 
Let me know how else I can help you.

**Comment by haldenb** [comment]
Hello wonderful people,

I will include the Twilo things here

@MarianaVazquezCYF could you add the Bregal Milestone cases?

https://docs.google.com/presentation/d/17hYjzZKf0ZnbDrWeduimomSsBiMtaVIlC2_Fcdyxedo/edit#slide=id.g141ca3155bf_0_71
