### ISSUE TITLE
Have a Volunteer Review the risk assessment on the first day of the DLP

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#985]
### Background

In #817 we completed the [risk assessment.](https://docs.google.com/document/d/1L6estJIkaqgIvCs6JoxYi7CWPf-6YaD-/edit)

We need to have it reviewed by a volunteer on the first day of the Sheffield DLP.

### Acceptance criteria

- [x] Reach out to volunteers near the start date, asking for someone to take on this task
- [x] Confirm at least one volunteer to take this on
- [x] Answer any questions  

### Owner

@haldenb and volunteers

### Stakeholder

@amyCYF @haldenb

### Approver

@mattcfry

**Comment by MattCFry** [comment]
@haldenb hey! I hear you are planning on going on the first day. Can you organise doing this yourself or with a volunteer please.

**Comment by haldenb** [comment]
I am confused with this ticket: The endless ticket chains kill my tiny little brain.
- When do you say it? What is it? Could you add a link
- When you say this task what is this task?

Could you just post the risk assessment in #sheffield and ask someone to check it?

**Comment by MattCFry** [comment]
Hi Halden, I've added a link to the risk assessment.

We need to review and potentially update the risk assessment once we are in the venue. I wrote this before I learned you were heading out. 

The assessment needs to be signed off by a member of CYF staff as we are legally responsible for the participants (trainees + volunteers). You could either do this yourself or support a volunteer doing this :)

**Comment by haldenb** [comment]
Awesome I can do this Saturday :)

**Comment by MattCFry** [comment]
Hi @haldenb, can you confirm if the review was completed?
