### ISSUE TITLE
Amnesty International Project

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#99]
Amnesty International has been discussing with CYF how to work on a project to make survey data available safely.
They contacted us again on 13th Feb 2023, with feedback on the previous architecture and reduction of scope.
We need to review it and understand possible next steps.

**Comment by kfklein15** [comment]
@gbencci, I have read the document. Can you let me know when you have read it too so we can talk about it, please?

Internal questions for me:
1) Will we again try to talk to Max to lead on this?
2) We need someone with form/DB/API knowledge + someone with data analytics/BI knowledge. I don't think they need to be the same person.
3) Can we talk about how much of the possible budget is used for taxes, etc.?

**Comment by gbencci** [comment]
Hi @kfklein15 I started reading the document, but can't say I've been through all the technical requirements:

1. If you are happy with him, then I think we should keep him involved
2. Yes. However my big priority would be to find a security person. The DB/ BI part will be easier to find
3. I don't think we'll have much taxes to pay, as most of it will be via freelancing. Don't think we'll have anyone on payroll, unless it's needed. We should have a 10-15% fo CYF admin overhead from our own time on it.

**Comment by kfklein15** [comment]
Replied to Pepe today.
I will contact Max and see who security-wise we will need/can hire.

**Comment by gbencci** [comment]
no news from Pepe. If we don't hear back, we'll have to close this one :( Shame
