### ISSUE TITLE
CoC training before Claire goes on maternity leave

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#991]
What do we need to get done in the near future
What is the brief to the new person (based on what we can't get to / should be part of their job)

**Comment by alecmccrindle** [comment]
Shared details for the JD and time estimate. 

Other work needed before Claire heads out is [on this doc. ](https://docs.google.com/document/d/1-a4P9QPCJe7nnFo7n8OY2RDLt5pZUIW-VlQt8g10Q4k/edit).

I'm closing this ticket and need to make a new one to review SA safeguarding laws before the next ZA board meeting.
